- docs/platform/linode-beginners-guide.md
remove broken link in beginners guide
> remove broken link

- docs/email/citadel/email-with-citadel-on-debian-6-squeeze.md
- docs/email/clients/installing-squirrelmail-on-debian-7.md
- docs/email/clients/installing-squirrelmail-on-ubuntu-12-04.md
- docs/email/clients/using-fetchmail-to-retrieve-email.md
- docs/email/iredmail/installing-iredmail.md
- docs/email/mailman/manage-email-lists-with-gnu-mailman-on-debian-5-lenny.md
- docs/email/mailman/manage-email-lists-with-gnu-mailman-on-debian-6-squeeze.md
- docs/email/mailman/manage-email-lists-with-gnu-mailman-on-ubuntu-10-04-lucid.md
- docs/email/mailman/manage-email-lists-with-gnu-mailman-on-ubuntu-10-10-maverick.md
- docs/email/mailman/manage-email-lists-with-gnu-mailman-on-ubuntu-12-04-precise-pangolin.md
- docs/email/mailman/manage-email-lists-with-gnu-mailman-on-ubuntu-9-10-karmic.md
- docs/email/postfix/basic-postfix-email-gateway-on-debian-5-lenny.md
- docs/email/postfix/basic-postfix-email-gateway-on-debian-6-squeeze.md
- docs/email/postfix/basic-postfix-email-gateway-on-ubuntu-10-04-lucid.md
- docs/email/postfix/basic-postfix-email-gateway-on-ubuntu-10-10-maverick.md
- docs/email/postfix/email-with-postfix-courier-and-mysql-on-fedora-12.md
- docs/email/postfix/email-with-postfix-courier-and-mysql-on-fedora-13.md
- docs/email/postfix/email-with-postfix-dovecot-and-mysql-on-centos-5.md
- docs/email/postfix/email-with-postfix-dovecot-and-mysql.md
- docs/email/postfix/pflogsumm-for-postfix-monitoring-on-centos-6.md
- docs/email/postfix/postfix-dovecot-and-system-user-accounts-on-debian-5-lenny.md
- docs/email/postfix/troubleshooting-problems-with-postfix-dovecot-and-mysql.md
More fixes, email articles this time.
> Spelling fixes in email articles

- docs/networking/linux-static-ip-configuration.md
> Update IPv4 Static IP networking guide to comply with RFC 5737

- docs/security/ossec-ids-debian-7.md
> How to install and configure OSSEC HIDS on Debian 7

- docs/applications/game-servers/minecraft-with-spigot-ubuntu.md
> Spigot on Ubuntu

- docs/security/firewalls/protecting-your-linode-using-tcp-wrappers.md
> Protecting your Linode with TCP Wrappers

- docs/platform/package-mirrors.md
Change it to "all of our" for the sake of Frankfurt. ;-)
> Update "all six of our data centers" for Singapore.

- docs/tools-reference/custom-kernels-distros/run-a-distributionsupplied-kernel-with-pvgrub.md
Followed the instructions for Wheezy, and they worked for me on Jessie.
> Add pv-grub distro kernel instructions for Debian 8 (Jessie).

- docs/email/postfix/email-with-postfix-dovecot-and-mysql.md
master.cf should have the complete entries for submission and smtps uncommented, not just the first line.
> Fix issue 219 - TLS wrapper problem

- docs/email/postfix/email-with-postfix-dovecot-and-mysql-on-centos-7.md
REF: http://www.dovecot.org/list/dovecot/2014-May/096084.html
> Fix error in dovecot SSL configuration

- docs/security/ssl/how-to-make-a-selfsigned-ssl-certificate.md
I think this was just a typo :question:
> Should be a .crt not .pem

- docs/security/firewalls/control-network-traffic-with-firewalld.md
> Control Network Traffic With FirewallD

- docs/applications/game-servers/csgo-server-debian-ubuntu.md
> CounterStrike:Global Offensive Server 

- docs/networking/diagnostics/diagnosing-network-speed-with-iperf.md
Added a space between ',' and 'launch'.
> Fixed a typo

- docs/uptime/monitoring/monitoring-servers-with-monit.md
A guide to configuring Monit, with examples and explanations of common uses.
> First draft of guide on installing and configuring Monit

- docs/email/postfix/email-with-postfix-dovecot-and-mysql.md
This PR includes the changes in #250 as well as other small fixes.
> Postfix mysql updates

- docs/applications/game-servers/minecraft-on-debian-and-ubuntu.md
Changed server download link to point to version 1.8.8 as this is more stable.
> Update server download link

- docs/uptime/monitoring/top-htop-iotop.md
> fix typo, iptop -> iotop

- docs/networking/vpn/pritunl-vpn-ubuntu.md
The *-m* option in command *iptables* has clerical error.
> fix the error command

- docs/applications/configuration-management/vagrant-linode-environments.md
> Fix 'Install Vagrant' link

- docs/security/firewalls/configure-firewall-with-ufw.md
Sudo ufw delete allow 22 changed to HTTP 80 as stated in description above.
> Update configure-firewall-with-ufw.md 

- docs/linode-writers-guide.md
> fix spelling mistake

- docs/applications/game-servers/csgo-server-debian-ubuntu.md
- docs/networking/remote-access.md
The original fix from https://github.com/linode/docs/pull/455, with clarified copy.
> Broken link Fix

- docs/applications/game-servers/csgo-server-debian-ubuntu.md
- docs/networking/remote-access.md
This link is broken, looks like the title was changed at some point
> This link is broken

- docs/email/postfix/configure-spf-and-dkim-in-postfix-on-debian-8.md
an adjusted version of https://github.com/linode/docs/pull/392
> SPF DKIM key rotation.

- docs/platform/linode-backup-service.md
Merge conflict resolution for https://github.com/linode/docs/pull/446
> Copyedits and rename Linode Backups

- docs/tools-reference/introduction-to-linux-concepts.md
Merging @smoreface's edits with some formatting tweaks
> Merging SM's edits + tweaks

- docs/platform/index.md
- docs/platform/linode-backup-service.md
Fix Backup Service guide per https://github.com/linode/docs/pull/446. This PR does what https://github.com/linode/docs/pull/483 was intended to do, but correctly.
> Linode backup fix

- docs/websites/cms/install-wordpress-using-wp-cli-on-ubuntu-14-04.md
Looks like there was a stray "www-data" in front of this line
> Fix small error with 'wp core update' command

- docs/platform/nodebalancer/nodebalancer-reference-guide.md
Small spelling/grammar mistakes found while reviewing doc.
> Spelling mistakes

- docs/applications/ansible/getting-started-with-ansible.md
"databases" should be singular here
> Remove an extraneous "s"

- docs/websites/nginx/deploy-django-applications-using-uwsgi-and-nginx-on-ubuntu-14-04.md
Line 152.
"/etc/uwsgi/site" should be "/etc/uwsgi/sites"
> A minor typo

- docs/websites/cms/how-to-install-and-configure-wordpress.md
An update of https://github.com/linode/docs/pull/489
> Wordpress mv command

- docs/websites/cms/how-to-install-and-configure-wordpress.md
changed "cp -R" to "mv" and removed the force remove command. That's dangerous!
> removed an rm -rf command

- docs/websites/apache-tips-and-tricks/modsecurity-on-apache.md
Update of https://github.com/linode/docs/pull/507
> Include directive

- docs/platform/kvm-reference.md
i have provided a few different options not sure whichone the author was going for.
> missing word in first sentence.

- docs/websites/nginx/how-to-configure-nginx.md
This fixes a spelling mistake.
> nginix -> nginx

- docs/migrate-to-linode/migrate-from-shared-hosting-to-linode.md
@Rohaq -
I've added a disclaimer note beneath the "Before you Begin" section. There's also a few edits to fix some of the links.
> Shared hosting prereq

- docs/migrate-to-linode/migrate-from-shared-hosting-to-linode.md
Added a "make sure your site will actually run on a LAMP stack" prerequisite. Whilst I'd really hope that anyone considering migrating to a Linode would be technically minded enough to be aware of this requirement already, it's generally better to be explicit with prerequisites than not.
> Added prerequisite to migrate-from-shared-hosting-to-linode.md

- docs/websites/lamp/install-lamp-on-ubuntu-16-04.md
- docs/websites/lemp/lemp-server-on-ubuntu-16-04.md
Adjustments to @maidentaiwan's https://github.com/linode/docs/pull/534
Removed mysql_secure_installation and incorporated password change step along with some minor formatting cleanup
> duplicate of Update install-lamp-on-ubuntu-16-04.md

- docs/applications/development/git-source-control-management.md
Fix Portage --ask flag and git is now in the dev-vcs category.
> Fix Gentoo command to install Git

- docs/getting-started.md
Fix Gentoo system update command and add timezone procedures from the
Gentoo Handbook: https://wiki.gentoo.org/wiki/Handbook:AMD64
> Getting Started updates for Gentoo Linux

- docs/websites/apache/apache-web-server-on-ubuntu-14-04.md
Initially mpm_event.comf I change mpm_event.conf
> Edit script mpm_event.conf

- docs/security/securing-your-server.md
> copy edit to L224

- docs/applications/salt/install-salt.md
- docs/applications/salt/use-salt-states-to-create-lamp-stack-and-fail2ban-across-salt-minions.md
revised guide based on @ferricoxide's suggestion in https://github.com/linode/docs/issues/393
> incorporated suggestions from GH Issue #393. Tested, tweaked, reviewed.

- docs/tools-reference/tools/find-files-in-linux-using-the-command-line.md
Zero was used instead of capital letter O!
> Replace multiple instances of `-0` with correct `-O`

- docs/applications/game-servers/minecraft-on-debian-and-ubuntu.md
All links and version references updated to current as of Jan 17, 2017.
> Updated version references and links

- docs/platform/linode-backup-service.md
Asked support about this after trying to find it in this document and this is how they said to do it.
> Add how to restore into a different data center

- docs/getting-started.md
> Gentoo - note on package management with 'emaint'

- docs/websites/apache-tips-and-tricks/tuning-your-apache-server.md
Created this PR to address https://github.com/linode/docs/issues/564.
I updated all the MPM sections (not just prefork) to include the suggested information, and rewrote them to be a little more accessible. I also reformatted the section headers to be a easier to read in Markdown.
> Updated Apache MPM sections

- docs/websites/apache-tips-and-tricks/tuning-your-apache-server.md
> Revert "Updated Apache MPM sections"

- docs/websites/apache-tips-and-tricks/tuning-your-apache-server.md
Same updates as #624, plus updated restart commands per recommendation.
> Apache MPM update

- CONTRIBUTING.md
Links in the contributing markdown doc were broken
> Fixed broken link to style guide

- docs/applications/game-servers/install-steamcmd-for-a-steam-game-server.md
- docs/tools-reference/tools/find-files-in-linux-using-the-command-line.md
The "steamcmd" package is currently available in Debian Testing and Ubuntu Xenial\Yakkety.
> SteamCMD: Installation using package from repositories

- docs/tools-reference/custom-kernels-distros/custom-compiled-kernel-debian-ubuntu.md
https://kernel-handbook.alioth.debian.org/ch-common-tasks.html#s-kernel-org-package
> Update to conform to Debian Kernel Handbook

- docs/migrate-to-linode/disk-images/copying-a-disk-image-to-a-different-account.md
> xvd[ab] --> sd[ab]

- docs/platform/automating-server-builds.md
Thanks to @BGmot, fixing a link in the Automating Server Builds guide
> fixed link to knife plugin

- docs/websites/cms/install-wordpress-on-ubuntu-16-04.md
extra spacing in the apache permalinks section
> slight formatting change to markdown

- docs/tools-reference/introduction-to-linux-concepts.md
A minor typo (bur instead of but), and a word change (yet instead of but).
> A typo change in introduction-to-linux-concepts.md

- docs/networking/diagnostics/diagnosing-network-speed-with-iperf.md
You only need to be root for the installation of iperf, not for the execution of iperf.
> correct superuser note

- docs/web-servers/lamp/lamp-server-on-arch-linux.md
Updated php installation. Taken from https://wiki.archlinux.org/index.php/Apache_HTTP_Server
> Update for php 7 LAMP server

- docs/development/install-java-on-ubuntu-16-04.md
Per request, here's the first draft of a guide on installing Java on Ubuntu 16.04. I've covered both the Oracle JDK and OpenJDK versions because FOSS rules. I've tried to be liberal with warnings about licensing implications due to the recent Oracle v Google fiasco, but you guys can decide how much of that you think is necessary. 
I'm not really a Java guy, so I can't think of much else to include here as far as starting up the VM and whatnot, although I suspect that Java users will already have a good idea of how to do that once it's been installed.
I also don't have access to the dev server anymore, so my apologies if there are any gross formatting errors :)
> BOUNTY - Install Java on Ubuntu 16.04

- docs/platform/disk-images/copying-a-disk-image-over-ssh.md
Was pointing at the generic page for using Lish, which was very confusing at first.
> Update link to using Lish in rescue mode

- docs/applications/containers/what_is_docker
from @jlwallen "This is the first draft. I copied and pasted directly from my .odt file, so all formatting was (obviously) stripped out."
> First draft of What Is Docker

- docs/databases/couchdb/securely-administer-couchdb-with-an-ssh-tunnel.md
> Revert "Update and rename securely-administer-couchdb-with-an-ssh-tunnel.md t…"

- docs/platform/how-to-use-block-storage-with-your-linode.md
It's really important that people know this.
> Bring backups info into own paragraph and clarify

- docs/web-servers/apache-tips-and-tricks/tuning-your-apache-server.md
apache2buddy.pl domain is being decommissioned.
many thanks
Richard Forth
Author and maintainer - apache2buddy.pl
> updated link to apache2buddy script (by author)!

- docs/web-servers/lamp/install-lamp-on-ubuntu-16-04.md
- docs/web-servers/lamp/install-lamp-stack-on-ubuntu-16-04.md
XR #772 , #773 
Squashed commit over Keith's copyedit since it will route back to him. We will need to discuss as a team not to mix tabs and spaces in the same document.
- Removed duplicate alias.
- Updated last modified date.
- Added tasksel for quick install option.
- Added back section on Configuring Virtual Hosts.
- Removed php-pear because it does not seem to be used anywhere.
> [TECH] Lamp install on Ubuntu 16.04

- docs/networking/dns/configure-your-linode-for-reverse-dns.md
Quick merge to fix top link of google search
> Fix alias for RDNS guide

- docs/applications/cloud-storage/owncloud.md
XR #802 
See existing guide:
https://www.linode.com/docs/applications/cloud-storage/owncloud-debian-7
Changes proposed:
- SQL statements should be capitalized for best practices
- Capitalization does not matter for SQL, but matters on database names/users
- Piped curl output to `apt-key -`; original documentation uses wget
- Fixed inconsistencies with tabs/spaces
- See PR comments for additional changes requested
> [TECH] Initial tech edit - requires revisison

- docs/applications/cloud-storage/owncloud-ubuntu-1604.md
XR #802 
- Changed installation instructions to match official documentation
- Renamed file from `owncloud.md` to `owncloud-ubuntu-1604.md`
> [TECH] Second tech edit ownCloud for Ubuntu 16.04

- docs/email/postfix/troubleshooting-problems-with-postfix-dovecot-and-mysql.md
Changed var/log/mail.log to /var/log/mail.log
Sorry, this just annoyed me for some reason. Also this is my first edit for a project that is not mine - sorry if I have done something wrong.
> Simple typo on line 67 that annoyed me

- docs/applications/cloud-storage/install-seafile-with-nginx-on-ubuntu-1604.md
Reverts linode/docs#836
Needs single quotes in description
> Revert "Update install-seafile-with-nginx-on-ubuntu-1604.md"

- docs/development/create-python-virtualenv-ubuntu-1610.md
#835 
`/docs/development` is broken on the test server. Check before merging into master.
> [COPY] Python Virtual Environment

- docs/tools-reference/tools/Use-Nano-Text-Editor-Commands.md
Title & metadescription, URL, & alias adjusted. H2s' "-ing" removed throughout. Please review for accuracy.
> Update and rename using-nano.md to Use-Nano-Text-Editor-Commands.md

- docs/tools-reference/custom-kernels-distros/install-a-custom-distribution-on-a-linode.md
yep
also not sure why we're using curl in one and wget in the other but 🤷‍♂️
> fixes markdown syntax for code block in note

- docs/tools-reference/tools/synchronize-files-with-unison.md
Project no longer actively maintained.
> [DEPRECATE] Synchronize Files with Unison

- docs/email/clients/retrieve-email-using-getmail.md
- docs/email/clients/retrieving-email-using-getmail.md
Minor formatting fixes. Removed reference to Courier in favor of Dovecot.
> [UPDATE] Retrieve Email Using Getmail

- docs/applications/cloud-storage/turtl.md
XR #825 
Strongly recommend a secondary review. Rethinkdb seems to be the issue here.
Also numbering of steps might be helpful.
> [TECH] Initial Turtl Edits

- docs/quick-answers/linux/install-selinux-on-ubuntu.md
> [Update] SELINUX reboot Fix

- docs/platform/how-to-use-block-storage-with-your-linode.md
Clarified language on block storage cost per support ticket in bits: https://bits.linode.com/Linode/docs/pull/836
> [UPDATE] Block Storage with Your Linode

- docs/networking/diagnostics/diagnosing-network-issues-with-mtr.md
I've updated the WinMTR website from sourcefourge to http://winmtr.net.
> Updated WinMTR Website Link

- docs/quick-answers/linux/how-to-disable-selinux.md
- docs/security/security-patches/patching-glibc-for-the-ghost-vulnerability.md
- docs/tools-reference/custom-kernels-distros/custom-compiled-kernel-with-pvgrub-debian-ubuntu.md
- docs/tools-reference/custom-kernels-distros/install-freebsd-on-linode.md
- docs/tools-reference/custom-kernels-distros/use-the-distribution-supplied-kernel-on-centos-6-with-grub-legacy.md
- docs/tools-reference/linux-package-management.md
- docs/web-servers/apache/install-and-configure-apache-on-centos-7.md
re: https://github.com/Guaris/docsmith/issues/1
> [FIX] fixed malformed dates in meta

- docs/websites/host-a-website-with-high-availability.md
> Updated path for percona install

- docs/networking/how-to-enable-native-ipv6-on-linux.md
> Fix "Internet Protocoal" typo

- docs/networking/create-a-socks5-proxy-server-with-shadowsocks-on-ubuntu-and-centos7.md
- docs/networking/index.md
- docs/tools-reference/how-to-install-neovim-and-plugins-with-vim-plug.md
- docs/websites/ecommerce/how-to-install-prestashop-on-ubuntu-16-04.md
Third time with Andrew Lescher's LinkedIn information broken on publish. Please keep in mind for future guides
@EdwardAngert Publish once this is merged. Thanks!
> Fixed broken LinkedIn and index references

- docs/quick-answers/linux/how-to-change-selinux-modes.md
- docs/tools-reference/custom-kernels-distros/run-a-distributionsupplied-kernel-with-pvgrub.md
@EdwardAngert Please merge and publish
> More 404s from recent updates

- docs/databases/elasticsearch/Visualize-Apache-Web-Server-Logs-using-Elastic-Stack-on-Debian-8.md
- docs/databases/elasticsearch/visualize-apache-web-server-logs-using-elastic-stack-on-debian-8.md
- fixed the contributed by
- fixed the What is Elastic Stack H2
- added image alt text
> fixed some markdown on the elasticstack guide

- docs/applications/big-data/how-to-move-machine-learning-model-to-production.md
- docs/applications/configuration-management/use-laravel-forge-to-automate-web-server-creation-on-a-Linode.md
- docs/applications/containers/how-to-install-docker-and-pull-images-for-container-deployment.md
- docs/applications/project-management/how-to-create-a-private-python-package-repository.md
- docs/applications/project-management/how-to-install-and-configure-redmine-on-ubuntu-16-04.md
- docs/applications/project-management/install-farmos.md
- docs/databases/mysql/configure-master-master-mysql-database-replication.md
- docs/databases/set-up-a-cassandra-node-cluster-on-ubuntu-and-centos.md
- docs/networking/how-to-enable-native-ipv6-on-linux.md
- docs/networking/how-to-mount-nfs-shares-on-debian-8.md
- docs/networking/ssh/ssh-connections-using-putty-on-windows.md
- docs/networking/vpn/configuring-openvpn-client-devices.md
- docs/networking/vpn/set-up-a-hardened-openvpn-server.md
- docs/networking/vpn/set-up-a-streisand-gateway.md
- docs/networking/vpn/tunnel-your-internet-traffic-through-an-openvpn-server.md
- docs/quick-answers/linux/how-to-change-selinux-modes.md
- docs/security/getting-started-with-selinux.md
- docs/tools-reference/custom-kernels-distros/run-a-distribution-supplied-kernel.md
- docs/tools-reference/how-to-install-neovim-and-plugins-with-vim-plug.md
- docs/web-servers/apache/how-to-set-up-htaccess-on-apache.md
- docs/web-servers/nginx/nginx-with-pagespeed-on-ubuntu-14-04.md
- docs/websites/forums/install-and-run-askbot-on-ubuntu-16-04.md
Keeping this under control so tests don't fail.
> Remove trailing whitespaces

- docs/security/securing-your-server.md
Caution for CentOS Users about sudo access.
> Sudo access for CentOS 6 Users

- docs/quick-answers/linode-platform/add-caa-dns-records.md
Copy and SEO for CAA-record doc.
> CAA-Record QA

- archetypes/content.md
> Add content archetype

- docs/find-this-guide-on-github.md
Landing page for deprecated guides. Ready for check/publish.
> Guide no longer live

- docs/platform/how-to-build-your-infrastructure-using-Terraform-and-Linode.md
- docs/platform/longview/longview-app-for-apache.md
@GuessWhoSamFoo 
This PR is for platform section
> Fixed formatting errors in Platform Section

- docs/development/how-to-develop-and-deploy-your-applications-using-wercker.md
Hi @kcraig34  -
Just a minor typo in the Wercker guide Title.
> Minor typo in the Wercker guide Title

- docs/security/ssl/using-openssls-subjectaltname-with-multiple-site-domains.md
Renamed the file and gave a new title.
> Using OpenSSL's subjectAltName with Multiple Domains

- docs/networking/vpn/set-up-a-hardened-openvpn-server.md
https://community.openvpn.net/openvpn/wiki/Openvpn24ManPage#lbAK
> OpenVPN - Replace tls-auth with tls-crypt

- CONTRIBUTING.md
- ci/test_filename.py
Added Windows support via Chocolatey.
Instructions to fork.
Testing instructions.
XR #1132
> Add CONTRIBUTING.md

- docs/applications/configuration-management/use-salt-states-to-create-lamp-stack-and-fail2ban-across-salt-minions.md
> Fix Indentation Error on Salt States and LAMP Stack

- docs/networking/diagnostics/install-iperf-to-diagnose-network-speed-in-linux.md
XR #808 
Thanks @dastergon ...
> add openSUS zypper command to install iPerf

- ci/conftest.py
- ci/requirements.txt
- ci/test_alias.py
- ci/test_filename.py
- ci/test_whitespace.py
- ci/test_yaml.py
- ci/yaml_rules.json
- docs/applications/cloud-storage/access-google-drive-linode.md
- docs/applications/cloud-storage/how-to-install-a-turtl-server-on-ubuntu.md
- docs/applications/project-management/how-to-create-a-private-python-package-repository.md
- docs/applications/project-management/install-farmos.md
- docs/applications/project-management/setting-up-taskwarrior-on-ubuntu-16-10.md
- docs/email/using-google-apps-for-email.md
- docs/game-servers/how-to-set-up-minecraft-server-on-ubuntu-or-debian.md
- docs/game-servers/multicraft-on-debian.md
- docs/game-servers/multicraft-on-ubuntu.md
- docs/getting-started.md
- docs/platform/network-helper.md
- docs/uptime/monitoring/ossec-ids-debian-7.md
- docs/web-servers/nginx/install-nginx-pagespeed-module-on-ubuntu1604.md
- Changed filepaths to singular in conftest to avoid confusion
- Removed old commented code
- Added comment for regex
- Require pytest 3.3.0 for showing % test completion when using xdist
- Check for og metadata in yaml config
There are a few md files that are missing publishing dates/keywords.
```
____________________________________________________________ test_yaml[./docs/getting-started.md] ____________________________________________________________
md_filepath = <_io.TextIOWrapper name='./docs/getting-started.md' mode='r' encoding='UTF-8'>
@file_io
def test_yaml(md_filepath):
filestring = md_filepath.read()
reg = regex.compile(r'^---(.*?)---',flags=regex.DOTALL)
match = regex.search(reg, filestring)
if not match: pytest.skip('No YAML header')
yaml_text = match.group(1)
parsed_yaml = …
```
> Enable test_yaml - extend required Hugo headers

- docs/email/postfix/email-with-postfix-dovecot-and-mysql.md
Fixed the DNS record in the `email with postfix dovecot and mysql` guide. XR #1256
> [FIX] Fixed DNS issue in Email guide

- docs/linode-writers-formatting-guide.md
includes changes made in https://github.com/linode/docs/pull/1153 that we can't merge in without bringing a bunch of other files along for the ride
> edits to writers formatting guide

- docs/networking/remote-access.md
arping command was wrong according to the man page entry. I've changed it to what worked for me.
> Fix arping command

- docs/networking/create-a-socks5-proxy-server-with-shadowsocks-on-ubuntu-and-centos7.md
XR https://github.com/shadowsocks/shadowsocks-libev/pull/1655
Closes [DOCS-51](https://jira.linode.com/browse/DOCS-51)
> SOCKS5 updates requires c-ares dependency

- docs/platform/disk-images/copying-a-disk-image-over-ssh.md
> Add SSH compression option

- docs/development/version-control/manage-source-code-versions-with-subversion.md
@Guaris Review and merge
Tests did not pick this up for some reason.
> Subversion Apache SSL link does not exist

- docs/applications/configuration-management/configure-and-use-salt-cloud-and-cloud-maps-to-provision-systems.md
- docs/applications/configuration-management/configure-and-use-salt-cloud.md
> [NEW] Salt Cloud Guide

- docs/tools-reference/custom-kernels-distros/install-nixos-on-linode.md
NixOS has a service for integration with Linode Longview.
> Add instructions for enabling Longview agent

- docs/databases/mariadb/set-up-mariadb-clusters-with-galera-debian-and-ubuntu.md
Not sure if we should handle 10.0 even though it still is active; makes the whole document confusing to read.
> [Update] MariaDB cluster with 10.0 vs 10.1 distinction

- docs/linode-writers-formatting-guide.md
> Fix external_resources example in formatting guide

- docs/security/securing-your-server.md
> Use ss -lnp output on fresh Debian 9 install

- .travis.yml
- CONTRIBUTING.md
Upgrade to newer version in docs and for tests. Also get multihost support
> Update Hugo version to 0.31.1

- docs/applications/configuration-management/install-and-manage-mysql-databases-with-puppet-hiera-on-ubuntu-16-04.md
- docs/applications/project-management/how-to-install-and-configure-redmine-on-ubuntu-16-04.md
- docs/applications/project-management/install-farmos.md
- docs/databases/mariadb/mariadb-setup-debian.md
- docs/getting-started.md
- docs/platform/how-to-build-your-infrastructure-using-terraform-and-linode.md
- docs/quick-answers/linux/how-to-install-configure-and-run-fish.md
- docs/security/visualize-server-security-on-centos-7-with-an-elastic-stack-and-wazuh.md
- docs/tools-reference/introduction-to-linux-concepts.md
- docs/troubleshooting/troubleshooting-common-apache-issues.md
- docs/websites/cms/drush-drupal.md
- docs/websites/ecommerce/install-magento-on-centos-7.md
> Indentation and syntax fixes

- docs/applications/messaging/_index.md
- docs/development/nodejs/_index.md
- docs/development/ror/_index.md
- docs/security/ssl/_index.md
- docs/web-servers/_index.md
- docs/websites/cms/_index.md
Link preservation for crawler/SEO value?. Added aliases to appropriate sections per TVF
> Aliases for deprecated sections

- docs/security/backups/backing-up-your-data.md
- docs/security/backups/using-rdiff-backup-with-sshfs.md
- Fix typo in rsync commmand (as per Jira ticket)
- Update style to current Linode style guide requirements
- Remove references to Unison, which is no longer actively developed
> [Update] Backing up your data

- docs/applications/cloud-storage/own-your-cloud-with-nextcloud.md
- docs/applications/cloud-storage/store-and-share-your-files-with-nextcloud-centos-7.md
trying this again
still 404ing on my local, but without anything that I can find wrong with it.
@GuessWhoSamFoo , please send help
> [COPY] edits to nextcloud on centos guide

- docs/tools-reference/tools/faster-file-navigation-with-autojump.md
> [New] Autojump - Command line tool

- docs/development/version-control/manage-source-code-versions-with-subversion.md
https://github.com/linode/docs/pull/1243
> [COPY] edits to Svn guide

- docs/databases/postgresql/configure-postgresql.md
Intro para needs a better introduction to (some combo of):
- what postgres is
- what other guides we have on it
- what the coming configurations configure
> [COPY] edits and tweaks to configure postgres guide.

- docs/development/introduction-to-websockets.md
> [COPY] edits to websockets guide

- docs/platform/automating-server-builds.md
Previous Ansible module was deprecated and replaced with a rolled in module.
> Updating link to deprecated Ansible module

- docs/web-servers/lamp/lamp-on-debian-8-jessie.md
> removing parenthetical in image debian 8 lamp

- docs/quick-answers/linux/install-selinux-on-ubuntu.md
- docs/security/encryption/use-luks-for-full-disk-encryption.md
- docs/tools-reference/custom-kernels-distros/run-a-distribution-supplied-kernel-with-kvm.md
- docs/uptime/monitoring-and-maintaining-your-server.md
Since keywords in the front matter are used for searches, we need to be more explicit with defining some of them.
> Add Lassie to keyword search index

- docs/platform/meltdown_statement.md
mostly cleanup - suggestions requested for description (L5)
xr: #1382
> meltdown format and description

- docs/websites/forums/install-and-run-askbot-on-ubuntu-16-04.md
> spacing fix for terminal input

- docs/platform/billing-and-payments.md
> [Update]Billing instructions 

- docs/platform/stackscripts.md
> Fix table format in stackscripts.md

- docs/platform/meltdown_statement.md
updated with FAQ from support doc
> Meltdown update jan17

- docs/platform/meltdown_statement.md
#how-to-reboot-into-an-updated-linode-kernel from #how-to-reboot-into-an-updated-kernel
> fixed anchor link to how to reboot

- README.md
Start encouraging users new to git to make documentation contributions to better understand the workflow. Can leave open issues with the `first-timers-only` label so it's searchable.
> Add first-timers-only badge

- ci/test_filename.py
added CODE_OF_CONDUCT to test_filename
> Add Code of Conduct as exception to test_filename.py

- docs/applications/containers/deploying-microservices-with-docker.md
> [COPY] backup copy edit to microservices guide

- README.md
from: 
> We are constantly looking to __impove__ the quality of our library
to: 
> We are constantly looking to __improve__ the quality of our library
> typo: spelling error "impove" edited to "improve"

- docs/applications/containers/node-js-web-server-deployed-within-docker.md
> Re-add deleted run command

- docs/email/running-a-mail-server.md
https://github.com/linode/docs/pull/1424/
> [COPY] edits to mail server guide

- docs/CODE_OF_CONDUCT.md
> [NEW] initial commit with code of conduct

- docs/platform/meltdown_statement.md
> Changed Meltdown fix to deployed

- docs/tools-reference/tools/modify-file-permissions-with-chmod.md
> [Update] Chmod File Permissions

- docs/tools-reference/tools/modify-file-permissions-with-chmod.md
Reverts linode/docs#1434
premature merging
> Revert "[Update] Chmod File Permissions"

- docs/tools-reference/tools/modify-file-permissions-with-chmod.md
now with easier reference
redo of #1434, but with a copy edit this time
> [NEW] Chmod guide update

- docs/networking/dns/dns-records-an-introduction.md
ref. https://tools.ietf.org/html/rfc1035
> SOA = Start Of Authority

- docs/contribute.md
Chose to leave this file in place so format is available
when needed.
> Clear contribute.md topics list

- docs/applications/configuration-management/beginners-guide-chef.md
- docs/development/ci/automate-builds-with-jenkins-on-ubuntu.md
- docs/development/ci/how-to-develop-and-deploy-your-applications-using-wercker.md
- docs/development/frameworks/apache-tomcat-on-debian-6-squeeze.md
- docs/game-servers/garrys-mod-server-on-centos-7.md
- docs/networking/diagnostics/diagnosing-network-issues-with-mtr.md
- docs/security/advanced-ssh-server-security.md
- docs/web-servers/apache/apache-2-web-server-on-centos-5.md
- docs/web-servers/apache/apache-2-web-server-on-debian-5-lenny.md
> Grammar fixes from Vale

- docs/applications/big-data/how-to-move-machine-learning-model-to-production.md
- docs/applications/cloud-storage/how-to-install-a-turtl-server-on-ubuntu.md
- docs/applications/messaging/instant-messaging-services-with-ejabberd-on-ubuntu-8-04-hardy.md
- docs/applications/messaging/using-irssi-for-internet-relay-chat.md
- docs/development/frameworks/yesod-nginx-mysql-on-debian-7-wheezy.md
- docs/security/using-fail2ban-for-security.md
- docs/uptime/analytics/open-web-analytics-install-and-launch-on-your-server.md
> Fixes to avoid incorrect dictionary generation

- ci/vale/dictionary.txt
> Added derivatives of: Token and stopwords

- docs/development/java/install-java-8-ppa.md
- docs/development/python/install_python_miniconda.md
- docs/development/python/introduction-to-pyspark.md
PySpark API to count words via corpus from NLTK.
> [New] Introduction to PySpark

- docs/platform/linode-cli.md
The intention here is to direct some traffic to the new, beta CLI.  If
this isn't the best way to go about it, please make suggestions or just
close this PR and open a new one doing it the right way.
> Added link to beta CLI

- ci/vale/dictionary.txt
- docs/security/meltdown-and-spectre.md
Update with wording about Spectre-V2
> [Update] Meltdown Spectre doc

- docs/security/mitigations/mitigating-memcached-amplification-attacks.md
F should be lowercase according to their website.
> CloudFlare -> Cloudflare

- ci/vale/styles/Linode/Terms.yml
> Update Terms.yml to include Cloudflare

- docs/applications/project-management/jupyter-notebook-on-jekyll.md
includes alias to not-break any existing links
> fixed jupyter notebook filename and first notebook graphic

- docs/web-servers/apache-tips-and-tricks/modevasive-on-apache.md
added Test mod_evasive section with link to our [Load Testing with Siege](/docs/tools-reference/tools/load-testing-with-siege/) guide
> [COPY] refresh on mod_evasive guide

- docs/development/r/how-to-deploy-rshiny-server-on-ubuntu-and-debian.md
> Remove R installation shortguide reference

- docs/applications/cloud-storage/install-seafile-with-nginx-on-ubuntu-1604.md
- docs/applications/containers/how-to-create-a-docker-swarm-manager-and-nodes-on-linode.md
- docs/databases/elasticsearch/monitor-nginx-web-server-logs-using-filebeat-elastic-stack-centos-7.md
- docs/development/use-a-linode-for-web-development-on-remote-devices.md
- docs/security/visualize-server-security-on-centos-7-with-an-elastic-stack-and-wazuh.md
- docs/web-servers/nginx/websites-with-nginx-on-arch-linux.md
- docs/websites/cms/how-to-install-ghost-cms-on-ubuntu-16-04.md
- docs/websites/introduction-to-high-availability.md
- docs/websites/varnish/use-varnish-and-nginx-to-serve-wordpress-over-ssl-and-http-on-debian-8.md
- docs/websites/wikis/ikiwiki-on-ubuntu-12-04-precise-pangolin.md
There are definitely a ton of these especially in order documentation.
> nginx -> NGINX cleanup

- docs/development/java/how-to-deploy-spring-boot-applications-nginx-ubuntu-16-04.md
> Remove shortguide reference to JDK 8

- docs/web-servers/apache-tips-and-tricks/apache-configuration-structure.md
Updated and Copy Edited Apache configuration Structure Guide. Worked w/ Cwalsh for verification of correctness. Guide just needed a copy edit.
> [Update] Apache Configuration Structure

- docs/databases/cassandra/set-up-a-cassandra-node-cluster-on-ubuntu-and-centos.md
- docs/databases/couchdb/access-futon-over-ssh-using-putty-on-windows.md
- docs/databases/hadoop/how-to-install-and-set-up-hadoop-cluster.md
- docs/databases/hadoop/install-configure-run-spark-on-top-of-hadoop-yarn-cluster.md
- docs/databases/mongodb/build-database-clusters-with-mongodb.md
- docs/databases/mongodb/create-a-mongodb-replica-set.md
- docs/databases/mysql/create-physical-backups-of-your-mariadb-or-mysql-databases.md
- docs/databases/mysql/how-to-install-mysql-on-centos-7.md
- docs/databases/mysql/install-and-configure-mysql-workbench-on-ubuntu.md
- docs/databases/mysql/install-mysql-on-ubuntu-14-04.md
- docs/databases/mysql/install-mysql-phpmyadmin-ubuntu-14-04.md
- docs/databases/oracle/oracle-10g-express-edition-on-ubuntu-10-10-maverick.md
- docs/databases/postgresql/configure-postgresql.md
- docs/databases/postgresql/how-to-install-postgresql-on-ubuntu-16-04.md
- docs/databases/postgresql/how-to-install-postgresql-relational-databases-on-centos-7.md
- docs/databases/redis/install-and-configure-redis-on-centos-7.md
- docs/email/how-to-create-an-email-server-with-mail-in-a-box.md
- docs/email/running-a-mail-server.md
- docs/email/zimbra/zimbra-on-ubuntu-14-04.md
- docs/platform/how-to-use-block-storage-with-your-linode.md
- docs/quick-answers/linode-platform/find-your-linodes-ip-address.md
- docs/security/backups/backing-up-your-data.md
- docs/security/encryption/use-luks-for-full-disk-encryption.md
- docs/security/vulnerabilities/scanning-your-linode-for-malware.md
- docs/uptime/reboot-survival-guide.md
- docs/websites/host-a-website-with-high-availability.md
There are ton more of these. It is certainly possible to track these, but check if this has any effects on metrics before putting more resources into this.
> Update links to avoid redirects

- docs/applications/containers/deploying-microservices-with-docker.md
- docs/applications/containers/when-and-why-to-use-docker.md
- docs/applications/social-networking/dolphin.md
- docs/applications/voip/install-asterisk-on-centos-7.md
- docs/development/perl/manage-cpan-modules-with-cpan-minus.md
- docs/development/python/task-queue-celery-rabbitmq.md
- docs/development/ror/ruby-on-rails-apache-debian-8.md
- docs/development/version-control/introduction-to-version-control.md
- docs/development/version-control/manage-distributed-source-branches-with-bazaar.md
- docs/email/clients/installing-squirrelmail-on-ubuntu-12-04.md
- docs/email/clients/retrieve-email-using-getmail.md
- docs/email/postfix/email-with-postfix-dovecot-and-mysql.md
- docs/networking/remote-access.md
- docs/platform/linode-beginners-guide.md
- docs/platform/longview/longview-app-for-mysql.md
- docs/platform/upgrade-to-hourly-billing.md
- docs/tools-reference/file-transfer/transfer-files-with-winscp-on-windows.md
- docs/tools-reference/linux-system-administration-basics.md
- docs/tools-reference/tools/introduction-to-rsync.md
- docs/tools-reference/tools/schedule-tasks-with-cron.md
- docs/uptime/analytics/webalizer-on-centos-5.md
- docs/uptime/analytics/zipkin-server-configuration-using-docker-and-mysql.md
- docs/uptime/monitoring-and-maintaining-your-server.md
- docs/web-servers/apache-tips-and-tricks/managing-resources-with-apache-modalias.md
- docs/web-servers/caddy/compile-caddy-from-source.md
- docs/websites/cms/install-wordpress-using-wp-cli-on-ubuntu-14-04.md
For SEO reporting purposes XR #1593
> Remove even more 301 redirects

- docs/game-servers/left-4-dead-2-multiplayer-server-installation.md
> Update dead cfg links for L4D2 server install

- docs/websites/static-sites/how-to-choose-static-site-generator.md
makes the sentence make sense "You can add your own email form..." > "You can add create your own email form"
> fixed language flow in "You can add" section

- netlify.toml
Pending approvals and initial Oauth setup
> Add toml for Netlify preview deploy

- ci/vale/dictionary.txt
- ci/vale/styles/Linode/Terms.yml
Capitalization of URL and URI, singular and plural.
> Add URIs to dictionary

- docs/web-servers/lamp/lamp-on-ubuntu-14-04.md
Changed "hot" to "how" and deleted an unneeded comma
> minor change - corrected misspelling

- .gitignore
- _redirects
- netlify.toml
This should fix the broken assets and links for Netlify previews.
> Fix preview pathing with Netlify URL rewrite

- docs/websites/cms/how-to-install-a-webmin-control-panel-and-modules.md
Can't find this one from git blame. Weird that this alias was lost over time.
> Update webmin link from irc auto-responder

- docs/getting-started.md
- Copy edits as needed
- Comment out videos
> Move /etc/hosts/ section back into Getting Started guide

- ci/vale/styles/Linode/British.yml
- docs/game-servers/minecraft-with-bungee-cord.md
This should not raise any errors but good to start tracking
> Standardize alternative spelling of words

- docs/websites/introduction-to-high-availability.md
Not really sure the best way to disambiguate these terms - or if we want to at all.
virtual ip vs floating ip vs failover ip
Thoughts? @Jonchun @EdwardAngert
> Update floating IP to failover IP

- ci/test_whitespace.py
Closes #1657 
Correct missed cases prior to merging
> Fix false negative case for mixed whitespace test

- docs/platform/how-to-use-block-storage-with-your-linode.md
> [Update] Update  BS Locations

- docs/applications/project-management/setting-up-taskwarrior-on-ubuntu-16-10.md
- docs/platform/linode-images.md
Continue to use 4 spaces instead of tabs
> Remove mixed whitespace

- docs/tools-reference/tools/how-to-install-midnight-commander.md
seeing if we can get rid of the minify warning on the midnight commander guide build
> removed hyphen and spacing in yaml keywords

- docs/networking/set-up-an-ipv6-tunnel-on-your-linode.md
> Transfer fixes from separate PR

- docs/networking/an-overview-of-ipv6-on-linode.md
Remove false statement about link-local documentation prefix.
> IPv6 overview: remove false statement

- docs/tools-reference/tools/find-files-in-linux-using-the-command-line.md
> Remove extraneous single quote

- docs/platform/longview/longview.md
> [UPDATE] longview debug update

- ci/blueberry.py
- docs/applications/configuration-management/learn-how-to-install-ansible-and-run-playbooks.md
- docs/networking/vpn/vpn-firewall-killswitch-for-linux-and-macos-clients.md
* Edited blueberry.py to add a test for broken images.
* Fixed two examples in library that were failing the new test.
> Add test to Blueberry for broken image links

- docs/web-servers/nginx/nginx-installation-and-basic-setup.md
> Replace html with http in NGINX series part 1

- docs/applications/configuration-management/automatically-configure-servers-with-ansible-and-playbooks/index.md
> ~/.ansible to ~/ansible

- docs/getting-started/index.md
> Intro sentence to set hostname section

- docs/applications/cloud-storage/install-nextcloud-talk/index.md
> Remove spreed repo name

- docs/networking/set-up-an-ipv6-tunnel-on-your-linode/index.md
> Remove failover line and copy edit

- docs/tools-reference/custom-kernels-distros/install-a-custom-distribution-on-a-linode/index.md
"Entails" isn't really the right word here since installing a custom linux distro isn't like..a necessary consequence of what the guide is trying to accomplish, it's the actual purpose of the guide. 
Also it's not *your* KVM Linode if you don't have a KVM Linode, which is the whole point of the note. 
Also, if Xen is really 100% gone it might be worth getting rid of the "If you're currently running Xen.." bit.
> fix this wording

- docs/quick-answers/linux-essentials/why-use-linux-for-development/index.md
Just some small spelling/grammar fixes that were missed after final review/publish
> [UPDATE] Why Use Linux for Development?

- docs/networking/dns/how-to-set-up-cloudflare-with-linode/index.md
Got some feedback in #support in Slack:
https://linode.slack.com/archives/C4W7XDHFH/p1531756990000503
Added a couple paragraphs to the *Keeping Your Linode’s IP a Secret* section.
> [UPDATE] Updated Cloudflare guide with feedback from the support team

- docs/quick-answers/linux-essentials/what-is-cloud-computing/index.md
Added some keywords to the guide.
> [UPDATE] Keyword edit in cloud computing guide

- docs/platform/manager/using-the-linode-shell-lish/index.md
Small note to address the ability to scroll back in LISH.
> [UPDATE] LISH - Guide

- docs/platform/manager/dns-manager/index.md
I just wanted to clarify a few things for newbies like myself.
> Added verbiage to adding wildcards

- docs/email/running-a-mail-server/index.md
- docs/getting-started/index.md
- docs/web-servers/lemp/how-to-install-a-lemp-server-on-ubuntu-18-04/index.md
Issues:
https://github.com/linode/docs/issues/2066
https://github.com/linode/docs/issues/2063
https://github.com/linode/docs/issues/2062
> Quick fix GitHub issues.

- docs/web-servers/apache-tips-and-tricks/configure-modsecurity-on-apache/index.md
Small fix introduced via Disqus comment.
> [Fix] Command for package version

- docs/websites/cms/how-to-install-and-configure-wordpress/index.md
The sub commands like `-u www-data`  is not necessary here because we are using `chown` command for `www-data` user throughout this guide.
> Unnecessary sub commands

- docs/web-servers/nginx/serve-php-php-fpm-and-nginx/index.md
- 'within' rather than 'in' because I think it’s more clear
- remove 'of course' because it talks down to the reader who may not know
- insert missing 'to'
- clarify sudo privileges
- 'on' to more appropriate 'in'
> Minor edits

- docs/game-servers/how-to-set-up-minecraft-server-on-ubuntu-or-debian/index.md
> [Update] How to Set Up a Minecraft Server on Ubuntu or Debian

- docs/uptime/monitoring-and-maintaining-your-server-new-manager/index.md
- docs/uptime/monitoring-and-maintaining-your-server/index.md
Mentioning Linode Managed in this guide.
> [UPDATE] Monitoring and Maintaining your server

- docs/applications/cloud-storage/install-nextcloud-talk/index.md
Nothing needed changing in the guide aside from the new version number, all of the steps and screenshots are up to date. Will comment back to the Disqus user as mentioned in the Trello card with more detailed information about their particular Nextcloud Apps, which are either already updated or in the process of being updated to Nextcloud 14.
> [Update] Introduction to Nextcloud Talk

- ci/vale/dictionary.txt
- docs/applications/configuration-management/secrets-management-with-terraform/index.md
High level overview of how to secure both a `.tf` file and a `.tfstate` file.
Will be updated to include a link to the Terraform backends guide once it is written.
> [New] Secrets Management with Terraform

- docs/applications/configuration-management/test-salt-locally-with-kitchen-salt/index.md
- docs/applications/containers/deploy-a-flask-application-with-dokku/index.md
> Update Modified date.

- docs/web-servers/caddy/install-caddy-archlinux/index.md
Continued from https://github.com/linode/docs/pull/2148.
> [NEW] Install caddy on arch linux

- CONTRIBUTING.md
Updated the CONTRIBUTING.md to reflect the gitflow workflow, and also added a command to add the docs repo as an upstream remote.
> [Update] CONTRIBUTING.md to gitflow workflow

- docs/platform/tokyo2-migration/index.md
Removing the default promo code banner
> [UPDATE] Migrating from Tokyo 1 to Tokyo 2

- ci/vale/dictionary.txt
- docs/networking/linux-static-ip-configuration/index.md
Update `Linux Static IP Configuration` guide to include Netplan instructions for Ubuntu 18.04 and later (escalation DOCS-124)
> [UPDATE] Linux Static IP Configuration

- docs/networking/vpn/pritunl-vpn-ubuntu/index.md
Deprecating Pritunl VPN Server and Management Panel on Ubuntu 14.04
Resolves https://github.com/linode/docs/issues/2213
> [UPDATE] Pritunl VPN Server and Management Panel on Ubuntu 14.04

- docs/platform/billing-and-support/support-new-manager/index.md
- docs/platform/billing-and-support/support/index.md
Revising list of issues that Linode Support can help with within the Scope of Support section, per comments on DOCS-121.
> [UPDATE] Linode Support

- docs/development/nodejs/install-nodejs-nodesource/index.md
- docs/email/running-a-mail-server/index.md
- docs/networking/vpn/install-openvpn-access-server-on-linux/index.md
- docs/web-servers/caddy/compile-caddy-from-source/index.md
Updating modified by dates that were not updated upon initial pull request.
> Update modified by dates.

- docs/platform/manager/keep-your-linode-account-safe/index.md
- docs/security/linode-manager-security-controls-new-manager/index.md
*** DONE Remove IP Whitelisting section 
CLOSED: [2019-01-08 Tue 09:14]
*** DONE replace manager.linode.com -> cloud.linode.com in new guide
CLOSED: [2019-01-08 Tue 09:54]
*** DONE Rename *Linode Manager* to Classic Manager in old guide
CLOSED: [2019-01-08 Tue 09:14]
*** DONE Change Linode *Linode Manager* to *Linode Cloud Manager*
CLOSED: [2019-01-08 Tue 09:54]
> Removed IP White Listing Section

- docs/applications/configuration-management/install-and-manage-mysql-databases-with-puppet-hiera-on-ubuntu-18-04/index.md
This PR adds a deprecated tag to the 16.04 version of this guide, and creates a new 18.04 guide with instructions for how to manage MySQL databases with Puppet 6.1.0.
> [Update] Install and Manage MySQL Databases with Puppet Hiera on Ubuntu 18.04

- ci/vale/dictionary.txt
- docs/applications/configuration-management/beginners-guide-chef/index.md
PR includes general updates and clarifications throughout the guide.
> [Update] A Beginner's Guide to Chef

- docs/platform/automating-server-builds/index.md
Add links to Salt and Terraform guides. Update other third-party tool links and other misc. copy updates.
> [Update] Automating Server Builds

- docs/applications/configuration-management/creating-your-first-chef-cookbook/index.md
This updates and improves this guide by removing any steps that require a user to manually log into a node managed by Chef. Instead the knife ssh command is used from a workstation.
> [Update] Creating Your First Chef Cookbook

- ci/vale/dictionary.txt
- docs/platform/how-to-resell-linode-services/index.md
This guide is on how to resell Linode services. The guide explains what reselling means and some avenues for becoming a Linode reseller.
> [New] How to Resell Linode Services

- themes/docsmith/layouts/partials/dedicated_cpu_link.html
- themes/docsmith/layouts/partials/image_banner_alert.html
Including updates to blog link in banners for Dedicated CPU
> [Release Candidate] RC-v0.6.1

- docs/platform/how-to-choose-a-linode-plan/index.md
Fixing typo in Nanode section of How to Choose a Linode Plan.
This PR replaces https://github.com/linode/docs/pull/2314 with a new Hotfix branch from master.
> [Hotfix] v0.6.3

- docs/platform/manager/using-the-linode-shell-lish/index.md
In response to issue #2326, update  Using the Linode Shell with ED25519 fingerprints and MD5s
> [Hotfix] v0.6.5

- themes/docsmith/layouts/partials/footer.html
- themes/docsmith/layouts/partials/nav.html
- themes/docsmith/layouts/partials/promo_code.html
This only updates the links in the theme, not in any individual guide.
Creating new Hotfix to quickly resolve DOCS-162.
> [Hotfix] v0.6.6 (merge into develop)

- themes/docsmith/layouts/partials/footer.html
- themes/docsmith/layouts/partials/nav.html
- themes/docsmith/layouts/partials/promo_code.html
This only updates the links in the theme, not in any individual guide.
Creating new Hotfix to quickly resolve DOCS-162.
> [Hotfix] v0.6.6

- docs/platform/manager/using-the-linode-shell-lish/index.md
Reverting recent changes to Lish fingerprints.
> [Hotfix] v0.6.7

- docs/platform/manager/using-the-linode-shell-lish/index.md
Reverting recent changes to Lish fingerprints.
> [Hotfix] v0.6.7 (merge into develop)

- docs/getting-started-new-manager/index.md
Update two links in the guide to point to Cloud Manager versions:
- Billing and Payments
- Linode Manager Security Controls
> [Update] Getting Started Guide

- docs/platform/billing-and-support/upgrade-to-hourly-billing/index.md
Several customers have brought up that this document is not quite up to date with our most recent announcement about converting to hourly billing. This is intended to clarify some of those confusions.
> Update hourly billing document for clarity regarding impending update

- docs/getting-started/index.md
Merging changes that happened on release candidate branch back into develop:
- Reverted GIF in Getting Started guide to not show Toronto
> [Release Candidate] v0.7 (merge into develop)

- docs/platform/manager/using-the-linode-shell-lish-classic-manager/index.md
- docs/platform/manager/using-the-linode-shell-lish/index.md
* Remove straggler DSA fingerprints
> [Hotfix] v0.7.2

- docs/platform/migrate-to-linode/migrate-from-shared-hosting-to-linode/index.md
Remove deprecated tag. Update links to new cloud manager versions of guides.
> [Update] Migrate from Shared Hosting to Linode

- docs/platform/block-storage/how-to-use-block-storage-with-your-linode/index.md
- docs/platform/manager/dns-manager/index.md
* Add missing bullet points to BS guide.
* Fix anchor link in DNS manager guide.
> [Release Candidate] v0.8 (merge into develop) 

- docs/platform/billing-and-support/billing-and-payments/index.md
Added "Monthly Cap" to the billing table to make the cap more clear. Resolved CT-13.
> [Update] Billing and Payments 

- docs/getting-started/index.md
Fix spacing around "hosts file" link.
> [Fix] formatting

- docs/applications/configuration-management/import-existing-infrastructure-to-terraform/index.md
Update this guide to include importing domain records.
> [Update] Import Existing Infrastructure to Terraform

- docs/platform/nodebalancer/nodebalancer-reference-guide-classic-manager/index.md
- docs/platform/nodebalancer/nodebalancer-reference-guide/index.md
Original PR was #2337 .
Add the new Backup mode to list of available modes and provide a small description of functionality. Update both old and Cloud Manager versions of the guide.
> [Update] NodeBalancer Reference Guide

- docs/applications/media-servers/how-to-install-shoutcast-dnas-server-on-linux/index.md
- Updated package installation url in response to a Disqus comment.
> [Disqus] - How to Install A SHOUTcast DNAS Server on Linux

- docs/platform/billing-and-support/billing-and-payments/index.md
JKobos noted that "cancel account" is a frequently-searched for term, but we have no search results for it. Inserting that exact phrase into the keywords for the Billing and Payments guide, which is the guide that shows how to cancel your account.
> [Update] Billing and Payments

- docs/security/linode-manager-security-controls/index.md
* Add alias for outdated link to *Linode Cloud Manager Security Controls* guide.
> [Fix] Linode Cloud Manager Security Controls

- docs/platform/tokyo2-migration/index.md
Updating the Tokyo 2 migration guide to change the timeline listed in the guide.
> [Hotfix] v0.9.1

- docs/platform/disk-images/resizing-a-linode/index.md
> [Hotfix] v.0.9.2 (merge into develop)

- docs/platform/package-mirrors/index.md
**Don't merge until Toronto**
Update package mirrors to include Toronto: http://tor1.mirrors.linode.com
> [Update] [Toronto]Package Mirrors

- docs/getting-started/index.md
* Add Getting Started gif with Toronto DC back to guide.
* Rebased to pull in @nmelehan PR:https://github.com//pull/2366.
> [Update] [Toronto] Getting Started guide

- docs/platform/manager/using-the-linode-shell-lish-classic-manager/index.md
- docs/platform/manager/using-the-linode-shell-lish/index.md
* Add Toronto fingerprints.
* Update Classic and Cloud to link to each other.
> [Update] [Toronto] Using the Linode Shell (Lish)

- docs/platform/api/using-the-linode-cli/index.md
- Added Toronto DC to example regions response.
> [Update] [Toronto] Using the Linode CLI

- docs/platform/billing-and-support/billing-and-payments/index.md
- docs/platform/billing-and-support/upgrade-to-hourly-billing/index.md
- Removed "Prepaid Billing" section of: https://linode.com/docs/platform/billing-and-support/billing-and-payments/
- Added deprecated note to: https://linode.com/docs/platform/billing-and-support/upgrade-to-hourly-billing/
- This guide comes up in a search for prepaid and already contains a deprecated note:https://linode.com/docs/platform/billing-and-support/prepaid-billing-and-payments-legacy/
> [Update] Misc. updates to reflect prepaid EOL.

- docs/platform/one-click/deploy-mern-with-one-click-apps/index.md
- New guide for MERN One-Click App.
> [New] Deploy MERN with One-Click Apps

- docs/web-servers/nginx/how-to-configure-nginx/index.md
> [Update] How to Configure NGINX

- docs/tools-reference/tools/introduction-to-vim-customization/index.md
> Fixed issue #2445

- ci/vale/dictionary.txt
- docs/platform/billing-and-support/billing-and-payments-classic-manager/index.md
- docs/platform/billing-and-support/billing-and-payments/index.md
- docs/platform/billing-and-support/tax-information-classic-manager/index.md
- docs/platform/billing-and-support/tax-information/index.md
Includes new Tax Information guide
> [Hotfix] v0.10.1

- docs/platform/disk-images/linode-images-classic-manager/index.md
- docs/platform/disk-images/linode-images/index.md
Added raw disk and custom filesystem caveat
> [Update] Linode Images

- docs/platform/disk-images/clone-your-linode-classic-manager/index.md
- docs/platform/disk-images/clone-your-linode/index.md
> [Update] Clone Your Linode 

- docs/platform/billing-and-support/network-transfer-quota/index.md
- Add IPv6 transfer quota info.
> [Update] Network Transfer Quota

- ci/vale/dictionary.txt
- docs/applications/containers/beginners-guide-to-kubernetes/index.md
A high level overview of beginner Kubernetes concepts.
> [New] Beginners Guide to Kubernetes

- docs/platform/manager/dns-manager/index.md
Add note that active Linodes are required for domains to be served.
> [update] DNS manager

- docs/applications/containers/deploy-volumes-with-the-linode-block-storage-csi-driver/index.md
- Create a draft of the Linode Block Storage CSI guide.
> [New] Deploy Persistent Volume Claims with the Linode Block Storage CSI

- ci/vale/dictionary.txt
- docs/applications/containers/getting-started-with-kubernetes/index.md
- docs/applications/containers/how-to-deploy-nginx-on-a-kubernetes-cluster/index.md
- Draft of new guide: [New] Getting Started with Kubernetes: Use kubeadm to Deploy a Cluster on Linode.
- Deprecate guide: How to Install, Configure, and Deploy NGINX on a Kubernetes Cluster.
> [New] Getting Started with Kubernetes: Use kubeadm to Deploy a Cluster on Linode

- docs/platform/network-helper/index.md
Added newer version of Ubuntu version split to indicate which files are modified, same as arch, not as. Debian. DOCS-173
> [Update] Network Helper

- docs/networking/linux-static-ip-configuration/index.md
PR for [issue #2509](https://github.com/linode/docs/issues/2509)
> [Update] Linux Static IP Configuration - OpenSUSE net docs link broken

- docs/networking/ssh/using-sshfs-on-linux/index.md
This PR adds fixes and updates in response to a Disqus comment.
> [Update] Using SSHFS To Mount Remote Directories

- docs/platform/disk-images/linode-backup-service/index.md
- docs/platform/disk-images/restore-backup-image-short/index.md
This should be pointing to the disk resize guide, not the linode resize guide.
> [update]fix disk resize link

- docs/tools-reference/tools/modify-file-permissions-with-chmod/index.md
> [Update] Modify File Permissions with chmod

- ci/vale/dictionary.txt
- docs/applications/configuration-management/deploy-linodes-using-ansible/index.md
* Deploy and manage Linodes using Ansible and the linode_v4 module.
* Create an Ansible inventory for your Linode infrastructure using the dynamic inventory plugin for Linode.
> [New] Deploy Linodes Using Ansible and the linode_v4 Module.

- ci/requirements.txt
Fixed Twisted version for Scrapy
> [Update] Updated twisted to version 19.2

- ci/requirements.txt
> [Update] Updating twisted to 19.2.1

- docs/platform/manager/using-the-linode-shell-lish/index.md
Add Mumbai to Lish guide, remove Tokyo 1 Lish information
> [Hotfix] v0.16.4 (merge into develop)

- docs/platform/object-storage/how-to-use-object-storage/index.md
Adding a "coming soon" note to two screenshots to explain that
LKE is not available yet.
> [Update] How to Use Linode Object Storage

- docs/platform/block-storage/how-to-use-block-storage-with-your-linode-classic-manager/index.md
- docs/platform/block-storage/how-to-use-block-storage-with-your-linode/index.md
Corrected the data centers on the Block Storage guide. 
xr #2569
> [Hotfix]v0.17.1

- docs/databases/mysql/create-physical-backups-of-your-mariadb-or-mysql-databases/index.md
> [Update] Create Physical Backups of your MariaDB or MySQL Databases

- docs/applications/containers/beginners-guide-to-kubernetes/index.md
- docs/applications/containers/deploy-container-image-to-kubernetes/index.md
- docs/applications/containers/deploy-minio-on-kubernetes-using-kubespray-and-ansible/index.md
- docs/applications/containers/getting-started-with-kubernetes/index.md
- docs/applications/containers/how-to-deploy-kubernetes-on-linode-with-rancher-2-2/index.md
- docs/applications/containers/how-to-deploy-nginx-on-a-kubernetes-cluster/index.md
- docs/applications/containers/how-to-install-apps-on-kubernetes-with-helm/index.md
- docs/applications/containers/manage-a-docker-cluster-with-kubernetes/index.md
Added Kubernetes guides to their own concentration
> [Update] Added Kubernetes Concentration

- docs/networking/vpn/set-up-wireguard-vpn-on-debian/index.md
This is a rebased PR for #2503
> [New] Set Up Wireguard VPN on Debian

- docs/security/upgrading/upgrade-to-ubuntu-18-04/index.md
added note about needing to upgrade from 17.04 to 17.10 first
> [Update] How to Upgrade to Ubuntu 18.04 LTS (Bionic Beaver)

- docs/getting-started/index.md
- docs/quick-answers/linux/choosing-a-distribution/index.md
Updated to include Distro section and create a new gif to reflect changes to the manager
> [Update] Getting Started with Linode

- README.md
The link text reads: rotating list of suggested topics.
Updated the text to: Contribute to our Tutorials
> [update] the anchor text in the link

- docs/networking/an-overview-of-ipv6-on-linode/index.md
Updated the ip address as 2600:3c02::f03c:91ff:fe24:3a2f/64
> Fixed the typo in Line 6

- docs/troubleshooting/troubleshooting-basic-connection-issues/index.md
> [Update] Troubleshooting Networking 

- docs/platform/billing-and-support/tax-information-classic-manager/index.md
- docs/platform/billing-and-support/tax-information/index.md
Revising Tax Information guide with information about the Goods
and Services Tax that will be collected for Australian and Indian
customers.
> [Update] Tax Information

- docs/platform/billing-and-support/tax-information-classic-manager/index.md
- docs/platform/billing-and-support/tax-information/index.md
Fixing the start date for GST tax collection
> [Hotfix] v0.19.2

- docs/applications/containers/kubernetes/kubernetes-reference/index.md
> [Move] Kubernetes Reference guide to Kubernetes section

- README.md
Added build status and latest release badges to the readme
> Added build status and latest release badges

- docs/security/securing-your-server/index.md
Added a note that informs user of the risk of Directory Listings on Apache and the option of disabling it
> [Update] Securing Your Server

- docs/applications/configuration-management/beginners-guide-to-terraform/index.md
- docs/applications/configuration-management/create-a-nodebalancer-with-terraform/index.md
- docs/applications/configuration-management/create-terraform-module/index.md
- docs/applications/configuration-management/deploy-a-wordpress-site-using-terraform-and-linode-stackscripts/index.md
- docs/applications/configuration-management/how-to-build-your-infrastructure-using-terraform-and-linode/index.md
- docs/applications/configuration-management/import-existing-infrastructure-to-terraform/index.md
- docs/applications/configuration-management/secrets-management-with-terraform/index.md
* Update all Terraform guides to use Terraform 0.12 syntax.
> [Update] Terraform syntax update.

- ci/vale/dictionary.txt
- docs/security/securing-your-server/index.md
updated the listen on onely one protocol step and added the words to dictionary
> [Update] How to Secure Your Server

- docs/networking/vpn/install-openvpn-access-server-on-linux/index.md
updated the steps to reflect the DNS settings
> [Update] Manage OpenVPN with OpenVPN Access Server

- docs/security/firewalls/configure-firewall-with-ufw/index.md
updated the standard example IP address as per https://github.com/linode/docs/issues/2003
> [Update] How to Configure a Firewall with UFW

- ci/requirements.txt
Updated twisted requirement version
> [Update] updated twisted requirement

- ci/vale/dictionary.txt
- docs/development/introduction-to-awk/index.md
Initial commit from this PR: https://github.com/linode/docs/pull/2561
> [New] Learn the AWK Programming Language

- docs/development/introduction-to-awk/index.md
This PR contains in the change Leslie made to the RC branch that was merged into master yesterday.
> RC v0.20.0 (into develop)

- docs/development/go/install-go-on-ubuntu/index.md
> [Update] How to Install Go on Ubuntu

- docs/platform/block-storage/how-to-use-block-storage-with-your-linode/index.md
Added recommendation to unmount volumes before detaching them if the Linode is powered on.
> [Update] Added warning for hot-unplugging mounted volumes (Cloud)

- docs/security/firewalls/introduction-to-firewalld-on-centos/index.md
updated the ipaddress and the example output.
> [Update] Introduction to FirewallD on CentOS

- docs/security/using-fail2ban-for-security/index.md
* Revert commit that removed fail2ban guide.
> [Hotfix][Release Candidate]v0.21.1

- docs/applications/configuration-management/creating-your-first-chef-cookbook/index.md
> Add missing space after link

- docs/platform/disk-images/linode-backup-service/index.md
shouldn't this just be "14 days" instead of "8 - 14 days"?  I am not sure if I am missing something here.
> [update] change day length that we do not keep back ups for

- docs/quick-answers/linux-essentials/what-is-systemd/index.md
Fix typo in "what is systemd".
> [update] Fix typo in "what is systemd"

- docs/applications/configuration-management/running-ansible-playbooks/index.md
> [update] Automate Server Configuration with Ansible Playbooks

- ci/vale/dictionary.txt
- docs/platform/block-storage/block-storage-use-cases/index.md
We will want to socialize this guide with Block Storage devs to get their opinion on it.
> [New] Block Storage Use Cases

- docs/platform/api/getting-started-with-the-linode-api/index.md
- appended  " | json_pp" to all the curl commands in the guide for a better output
> [Update] Getting Started with the Linode API

- docs/applications/configuration-management/getting-started-with-ansible/index.md
updated the link text as a fix for https://github.com/linode/docs/issues/2688
updated the documentation ip address
> [Update] Getting Started With Ansible - Basic Installation and Setup

- docs/platform/how-to-choose-a-linode-plan/index.md
As a fix for the comment: https://www.linode.com/docs/platform/how-to-choose-a-linode-plan/#comment-4621159783
Added a link to Resizing a Linode guide.
> [Update] How to Choose a Linode Plan

- docs/tools-reference/tools/introduction-to-vim-customization/index.md
Fixed a typo as a fix for the issue: https://github.com/linode/docs/issues/2736
> [Update] Introduction To Vim Customization

- docs/platform/manager/using-the-linode-shell-lish/index.md
Added MD5 fingerprint for ed25519 encryption. Needed for Putty support
> [Update] Using the Linode Shell (Lish)

- docs/databases/mysql/how-to-optimize-mysql-performance-using-mysqltuner/index.md
- updated the URL of the mysqltuner script
> [Update] How to Optimize MySQL Performance Using MySQLTuner

- docs/quick-answers/linux/start-service-at-boot/index.md
Updated the guide with  Troubleshooting information as a fix for the issue: https://github.com/linode/docs/issues/2511
> [Update] Use systemd to Start a Linux Service at Boot

- docs/development/version-control/install-gitlab-on-ubuntu-18-04/index.md
- Updated the URL to the external site as a fix for https://github.com/linode/docs/issues/2753
> [Update] Install GitLab on Ubuntu 18.04

- docs/platform/linode-managed-classic-manager/index.md
* Hide the classic manager version of Linode managed
* Link to cloud version of the guide
> [Update] Linode Managed - Classic Manager

- docs/platform/linode-managed/index.md
- Guide currently instructs user to visit a nonexistent tab in Cloud Manager
- Replaced this instruction with direction to current link in Legacy Manager
- We can update this again when the link is reintroduced in a different place in future interation of Cloud Manager
> **Fixed Instruction on Where to Signup  for Managed

- docs/platform/longview/longview-app-for-mysql/index.md
Added a note as a fix for https://github.com/linode/docs/issues/2597
> [Update] Longview App for MySQL

- docs/email/running-a-mail-server/index.md
> [Update] Running A Mail Server

- docs/quick-answers/linux/how-to-use-fsck-qa/index.md
added note with link to boot to rescue and steps for verifying disk is unmounted
> [Update] How to Use fsck - Quick Answer

- docs/networking/vpn/set-up-wireguard-vpn-on-debian/index.md
- docs/networking/vpn/set-up-wireguard-vpn-on-ubuntu/index.md
added note about grub 2 for both debian and ubuntu guides - please check both
> [Update] Setup WireGuard VPN on Ubuntu (and Debian)

- docs/platform/object-storage/pricing-and-limitations/index.md
A short guide describing pricing, limitations, and transfer quotas.
> [New] Object Storage Pricing and Limitations

- docs/applications/media-servers/how-to-install-jellyfin/index.md
* Original link had been moved on the Jellyfin site.
> [Release Candidate] - v0.24 (develop)

- docs/platform/object-storage/bucket-versioning/index.md
- docs/platform/object-storage/how-to-use-object-storage/index.md
- docs/platform/object-storage/pricing-and-limitations/index.md
This hotfix includes a number of changes to our Object Storage guides.
- The billing guide has been updated to include information on prorating
- Fixed a typo in the bucket versioning guide
- Fixed the intro line in the how-to guide to reflect that Cloud can be used to upload and delete objects.
> [Hotfix] RC 0.24.1

- docs/tools-reference/custom-kernels-distros/install-nixos-on-linode/index.md
Updating this guide for NixOS's 19.09 release.
I tested it to confirm it works. Some changes had to be made regarding the usage of sudo, DHCP configurations, and longivew.
> [Update] NixOS guide for 19.09

- ci/vale/dictionary.txt
- docs/networking/an-overview-of-ipv6-on-linode/index.md
Update section on Blocks and Pools
> [Update] An Overview of IPv6 on Linode

- docs/getting-started/index.md
> [Update] Getting Started

- docs/platform/object-storage/pricing-and-limitations/index.md
Update Object Storage Pricing and Limitations guide to reflect per-cluster limits model.
> [Hotfix] v0.24.3

- docs/platform/object-storage/pricing-and-limitations/index.md
Align the copy of the Cloud Manager and the guide where applicable within the 'Pricing' section.
> [Update] Object Storage Pricing and Limitations

- docs/applications/configuration-management/deploy-linodes-using-ansible/index.md
- docs/databases/mongodb/install-mongodb-on-centos-7/index.md
- docs/databases/mongodb/install-mongodb-on-ubuntu-16-04/index.md
- docs/databases/mysql/how-to-install-mysql-on-centos-7/index.md
- docs/databases/mysql/how-to-install-mysql-on-debian-7/index.md
- docs/databases/mysql/how-to-install-mysql-on-debian-8/index.md
- docs/databases/mysql/install-mysql-on-ubuntu-14-04/index.md
- docs/databases/redis/how-to-install-a-redis-server-on-ubuntu-or-debian8/index.md
- docs/databases/redis/install-and-configure-redis-on-centos-7/index.md
- docs/game-servers/create-an-ark-survival-evolved-server-on-ubuntu-16-04/index.md
- docs/platform/billing-and-support/billing-and-payments-classic-manager/index.md
- docs/platform/disk-images/resizing-a-linode-classic-manager/index.md
- docs/platform/disk-images/resizing-a-linode/index.md
- docs/platform/how-to-choose-a-linode-plan/index.md
- docs/websites/ecommerce/install-magento-on-centos-7/index.md
- docs/websites/ecommerce/install-magento-on-ubuntu-16-04/index.md
- docs/websites/ecommerce/install-magento-on-ubuntu-18-04/index.md
- Changed https://www.linode.com/pricing#all to https://www.linode.com/pricing/
- Changed https://www.linode.com/pricing#high-memory to https://www.linode.com/pricing/high-memory
- Changed https://www.linode.com/pricing#high_memory to https://www.linode.com/pricing/high-memory
-Changed https://www.linode.com/pricing#standard to https://www.linode.com/products/standard-linodes
> [Update] Guides that contain anchor links

- docs/websites/cms/how-to-install-ghost-cms-with-docker-compose-on-ubuntu-18-04/index.md
- Updated the comment based on the suggestion on DisQus :http://disq.us/p/256ykbc
> [Update] How to Install Ghost CMS with Docker Compose on Ubuntu 18.04

- docs/development/bash/intro-bash-shell-scripting/index.md
> [Update] URL for bash scripting guide

- docs/security/vulnerabilities/scanning-your-linode-for-malware/index.md
- Spelling fix, vulnerabilities was missing an 'i'
- Conform to the new h1 standard
> [Update] Scanning for Vulnerabilities with ClamAV

- docs/email/postfix/pflogsumm-for-postfix-monitoring-on-centos-6/index.md
Added full path to each command and remove unwanted commands like cd also added wget instead of curl command.
> [update]Added full path to each command and remove unwanted commands like cd

- docs/applications/containers/kubernetes/how-to-deploy-kubernetes-on-linode-with-k8s-alpha-cli/index.md
* Add paragraph about LKE
* Link to deploy a cluster with LKE guide
* Did not include info about beta. User will learn about the private beta when they view the LKE
guide.
> [Update] How to Deploy Kubernetes on Linode with the k8s-alpha CLI

- CONTRIBUTING.md
- README.md
- Added information about working on issues.
> [Update] CONTRIBUTING.md

- docs/game-servers/minecraft-with-mcmyadmin-on-debian/index.md
This PR is to fix errant commits that appeared in https://github.com/linode/docs/pull/2742.
> [Update] Installing McMyAdmin for Minecraft on Debian

- docs/platform/object-storage/host-static-site-object-storage/index.md
* Clarify CNAME addition for custom domain
* Add note that bucket name must match domain name
* Add SSL incompatibility note for custom domain
This PR will close #2842.
> [Update] Host a Static Site using Linode Object Storage: (Optional) Next Steps Edit

- ci/vale/dictionary.txt
- docs/development/bash/an-intermediate-guide-to-bash-scripting/index.md
- docs/development/bash/bash-scripting-2/index.md
* An Intermediate guide to Bash Scripting.
* Contributed by @mactsouk
> [New] Bash scripting intermediate

- docs/development/go/learning-go-functions-loops-and-errors-a-tutorial/index.md
* A variety of copy edits
* Restructured guide to use bullets instead of big blocks of texts.
* Minor copy edits and rewording.
> [Update] - A Tutorial for Learning Go Functions, Loops, and Errors

- docs/platform/longview/longview-app-for-mysql/index.md
- docs/platform/longview/longview/index.md
Update guides based on customer feedback.
- Add note about timing to manual installation steps.
- Add firewall example
- Add additional error message to Longview MySQL guide
> [Update] Longview and Longview MySQL Guides

- docs/platform/linode-managed-classic-manager/index.md
- docs/platform/linode-managed/index.md
Fix Linode Managed link on product documentation
> [Hotfix] v0.26.2

- docs/kubernetes/deploy-and-manage-a-cluster-with-linode-kubernetes-engine-a-tutorial/index.md
- docs/kubernetes/deploy-and-manage-lke-cluster-with-api-a-tutorial/index.md
fixed symbol in command to set kubeconfig environment variable
> [Update] Create an LKE Cluster (Cloud Manager + API)

- docs/tools-reference/tools/find-files-in-linux-using-the-command-line/index.md
- updated the commands to use -7 and -3 to list all files modified in the last 7 and 3 days.
> [Update] Find Files in Linux, Using the Command Line

- docs/platform/package-mirrors/index.md
This one-commit PR adds mirror link for Mumbai and Sydney mirror data centers.
This PR will close #2893.
> [Update] Package Mirrors

- docs/platform/api/linode-cli/index.md
As per https://github.com/linode/linode-cli/issues/150 it's wasn't clear ( to me at least ) how to add an authorized_key file.
> Add example for rebuilding a host

- themes/docsmith/layouts/_default/baseof.html
- Added Weglot Javascript initializer in base template
- The placeholder key in this initializer code will be replaced
with the actual key by a weglot gulp task during production
deployment
> [Theme rebuild] Weglot integration v1

- docs/kubernetes/deploy-and-manage-a-cluster-with-linode-kubernetes-engine-a-tutorial/index.md
- docs/kubernetes/deploy-and-manage-lke-cluster-with-api-a-tutorial/index.md
Left a note in relevant LKE guides to make clear the limitations of the Beta when deploying Linodes for your cluster
> [Update] Deploy and Manage a Cluster with LKE 

- docs/platform/stackscripts/index.md
- updated the link to  StackScript Bash Library 
- fixes https://github.com/linode/docs/issues/2899
> [Update] Automate Deployment with StackScripts

- docs/applications/voip/install-asterisk-on-centos-7/index.md
- added information about enabling the service.
- fixes https://github.com/linode/docs/issues/2745
> [Update] How to Install Asterisk on CentOS 7

- docs/email/_index.md
This PR replaces $date with actual outbound connection ports restriction date (November 5th, 2019) on the description.
This will close #2988
> [Update] Email Server Guides: $date

- themes/docsmith/layouts/_default/baseof.html
- themes/docsmith/layouts/partials/community_link.html
- themes/docsmith/layouts/partials/feedback.html
- themes/docsmith/layouts/partials/mobile_feedback.html
- themes/docsmith/layouts/partials/sidebar.html
* Add button link to Delighted CES survey in theme's left sidebar.
* Includes mobile support / responsive behavior
* See related hercules PR 157
> [Theme build] Add Delighted CES survey in theme's left sidebar.

- docs/security/ssl/install-lets-encrypt-to-create-ssl-certificates/index.md
> Fix a typo

- ci/vale/dictionary.txt
- docs/development/go/go-structures/index.md
This is a new PR for https://github.com/linode/docs/pull/2793, as it looks like the upstream repo their has been deleted.
> An introduction to Go Structures (new PR)

- docs/linode-writers-formatting-guide/index.md
[Update] The Linode Writer's Formatting Guide
- Fixes:
- Makes the guide searchable in Algolia
- Switches the link to the contribute page to match the new
Write For Linode program page
> [Hotfix] v0.29.1

- docs/platform/object-storage/host-static-site-object-storage/index.md
fixed url returned in info command
> [Update] Host a Static Site with Linode Object Storage 

- docs/applications/containers/how-to-deploy-the-elastic-stack-on-kubernetes/index.md
- docs/kubernetes-shortguide-definitions/k8s-alpha-deprecation-shortguide/index.md
- docs/kubernetes/beginners-guide-to-kubernetes-part-5-conclusion/index.md
- docs/kubernetes/deploy-container-image-to-kubernetes/index.md
- docs/kubernetes/deploy-nodebalancers-with-linode-ccm/index.md
- docs/kubernetes/deploy-volumes-with-the-linode-block-storage-csi-driver/index.md
- docs/kubernetes/getting-started-with-kubernetes/index.md
- docs/kubernetes/how-to-deploy-istio-with-kubernetes/index.md
- docs/kubernetes/how-to-deploy-kubernetes-on-linode-with-k8s-alpha-cli/index.md
Added k8s-alpha deprecation shortguide and implemented it in guides that benefit from a deprecation notice
> k8s-Alpha deprecation notice

- docs/applications/containers/when-and-why-to-use-docker/index.md
Replaced `dockerhub.net` with `hub.docker.com`
> [Update] When and Why to Use Docker

- docs/security/linode-manager-security-controls/index.md
- updated the link to configure security events notifications
> [Update] Linode Cloud Manager Security Controls

- docs/platform/object-storage/bucket-versioning/index.md
Added awi s3api command for deleting objects
> [Update] Object Storage Bucket Versioning

- docs/applications/remote-desktop/remote-desktop-using-apache-guacamole-on-docker/index.md
- Added the Before you begin section
- Removed the ' ' in the docker run command
- Added a note about the default browser
- Moved the VNC Server on a Linode section before Guacamole in Browser because you need to open the browser on the VNC server
> [Update] Virtual Cloud Desktop Using Apache Guacamole

- docs/platform/object-storage/how-to-use-object-storage-acls-and-bucket-policies/index.md
added subdirectory, deny, and showed combined rules
> [Update] Object Storage ACLs and Bucket Policies

- README.md
- docs/databases/mysql/install-and-configure-mysql-workbench-on-ubuntu/index.md
- Updated the Before you begin section based on the comments in https://github.com/linode/docs/issues/2783
> [Update] Install and Configure MySQL Workbench on Ubuntu 16.04

- docs/platform/manager/a-classic-to-cloud-manager-overview-guide/index.md
- themes/docsmith/layouts/partials/contribute_footer.html
Add the link to the new contributor program
> Hotfix v.0.30.2

- themes/docsmith/layouts/_default/baseof.html
> [Hotfix] v0.30.3

- ci/vale/styles/Linode/Terms.yml
- docs/applications/containers/how-to-deploy-the-elastic-stack-on-kubernetes/index.md
- docs/kubernetes/deploy-minio-on-kubernetes-using-kubespray-and-ansible/index.md
- docs/kubernetes/deploy-volumes-with-the-linode-block-storage-csi-driver/index.md
- docs/kubernetes/getting-started-with-kubernetes/index.md
- docs/kubernetes/how-to-deploy-istio-with-kubernetes/index.md
- docs/kubernetes/how-to-deploy-kubernetes-on-linode-with-rancher-2-x/index.md
- docs/kubernetes/how-to-deploy-nginx-on-a-kubernetes-cluster/index.md
- docs/kubernetes/how-to-install-apps-on-kubernetes-with-helm-2/index.md
- docs/kubernetes/manage-a-docker-cluster-with-kubernetes/index.md
- docs/kubernetes/troubleshooting-kubernetes/index.md
Added the following terms to the file for consistency:Kubeadm: kubeadm
Kubectl: kubectl
Kubelet: kubelet
kubernetes: Kubernetes
Kube Controller Manager: kube-controller-Manager
Kube Proxy: kube-proxy
Kube Scheduler: kube-scheduler
pod: Pod
> [Update] Terms.yml

- themes/docsmith/layouts/_default/baseof.html
Spanish language users will now be alerted to the progress of the docs spanish language translations when toggling the docs site to Spanish. The project is currently in progress and not all translations have been verified by professional translators.
See sister hercules PR for more details.
> [Theme] Add note for Spanish language users.

- docs/platform/object-storage/bucket-versioning/index.md
- docs/platform/object-storage/host-static-site-object-storage/index.md
- docs/platform/object-storage/how-to-manage-objects-with-lifecycle-policies/index.md
- docs/platform/object-storage/how-to-use-object-storage-acls-and-bucket-policies/index.md
- docs/platform/object-storage/how-to-use-object-storage/index.md
- docs/platform/object-storage/object-storage-cancellation-shortguide/index.md
- docs/platform/object-storage/object-storage-use-cases/index.md
- docs/platform/object-storage/pricing-and-limitations/index.md
added object storage cancellation notice shortguide to all obj storage guides
> [Update] Object Storage Cancellation Notice Shortguide

- docs/platform/manager/using-the-linode-shell-lish/index.md
added connection info for Sydney
> [Update] Using the Lish Shell

- docs/applications/media-servers/how-to-install-jellyfin/index.md
Updated to ensure the Linux Gamer is properly listed as the contributor
> [Update] How to Install Jellyfin on Linux

- docs/quick-answers/linode-platform/resize-a-linode-disk/index.md
Extra explanation/description here
> [Update] Resize a Linode Disk

- docs/platform/billing-and-support/manage-billing-in-cloud-manager/index.md
- docs/quick-answers/linode-platform/cancel-your-account-shortguide/index.md
- docs/quick-answers/linode-platform/how-to-cancel-your-account/index.md
added shortguide for cancel account section for new guide and billing page
> [New] How to Cancel Account

- docs/platform/object-storage/how-to-access-objects-with-linode-object-storage/index.md
> [New] Accessing Objects with Linode Object Storage

- docs/development/go/go-structures/index.md
- updated the output in Pointers and Structs and Functions section
- fixed the typo in json.go file in Structs and JSON section
- fixes https://github.com/linode/docs/issues/3083
> [Update] A Tutorial for Learning Structs in Go

- docs/platform/billing-and-support/how-linode-billing-works/index.md
added copy with info about refunds
> [Update] Billing and Payments Guide

- docs/platform/billing-and-support/linode-beginners-guide/index.md
> [Update] Linode Beginner's Guide

- docs/platform/nodebalancer/getting-started-with-nodebalancers/index.md
> [Update] Getting Started with NodeBalancers

- docs/platform/block-storage/how-to-use-block-storage-with-your-linode/index.md
Added instructions for transferring a volume to a new Linode
> [Update] How to Use Block Storage With Your Linode

- docs/databases/cassandra/how-to-install-apache-cassandra/_index.md
- docs/databases/cassandra/how-to-install-apache-cassandra/centos/index.md
- docs/databases/cassandra/how-to-install-apache-cassandra/debian/index.md
- docs/databases/cassandra/how-to-install-apache-cassandra/ubuntu/index.md
* Add How to Install Cassandra, Ubuntu, Debian, and CentOS
> [New] How to Install Cassandra (Debian, Ubuntu, CentOS)

- docs/databases/mysql/how-to-create-and-use-mysql-stored-procedures/index.md
Greetings,
This is my initial guide on how to create and use MySQL database triggers.
Hoping for the best.
Best wishes,
Francis Ndungu
> Initial draft of how to create and use mysql stored procedures

- docs/databases/mysql/how_to_work_with_triggers_in_mysql_database/index.md
Greetings,
kindly review my guide on MySQL Database Triggers
> Initial draft of mysql database triggers

- docs/platform/object-storage/bucket-versioning/index.md
- docs/platform/object-storage/host-static-site-object-storage/index.md
- docs/platform/object-storage/how-to-access-objects-with-linode-object-storage/index.md
- docs/platform/object-storage/how-to-manage-objects-with-lifecycle-policies/index.md
- docs/platform/object-storage/how-to-use-object-storage-acls-and-bucket-policies/index.md
- docs/platform/object-storage/how-to-use-object-storage/index.md
- docs/platform/object-storage/object-storage-cluster-shortguide/index.md
- docs/platform/object-storage/object-storage-ga-shortguide/index.md
- docs/platform/object-storage/object-storage-use-cases/index.md
- docs/platform/object-storage/pricing-and-limitations/index.md
Added shortguide for ga note and applied to all - these all had the same or similar note at the top.
Added Frankfurt region to How to Use Object Storage guide.
> [Hotfix] v0.33.1 (Object Storage Guides)

- docs/kubernetes/beginners-guide-to-kubernetes-part-1-introduction/index.md
- docs/kubernetes/beginners-guide-to-kubernetes-part-2-master-nodes-control-plane/index.md
- docs/kubernetes/beginners-guide-to-kubernetes-part-3-objects/index.md
- docs/kubernetes/beginners-guide-to-kubernetes-part-4-controllers/index.md
- docs/kubernetes/beginners-guide-to-kubernetes-part-5-conclusion/index.md
- docs/kubernetes/beginners-guide-to-kubernetes/index.md
- docs/kubernetes/kubernetes-reference/index.md
Link to latest version of the docs
v1.13 isn't offered on Linode anymore
> Update Links to Kubernetes API References

- docs/platform/manager/remote-access/index.md
added keywords: "add additional ipv4 address", "add ip address", "add additional ip address"
so that this doc will show up in the cloud manager support search for adding an IP address
> [Update] Remote Access

- docs/platform/manager/using-the-linode-shell-lish/index.md
Corrected incorrect fingerprint listings for sydney and mumbai
> Correct Fingerprints in sydney and mumbai

- docs/websites/cms/wp-cli/_index.md
- docs/websites/cms/wp-cli/how-to-install-wordpress-using-wp-cli-on-centos-7/index.md
- docs/websites/cms/wp-cli/how-to-install-wordpress-using-wp-cli-on-centos-8/index.md
- docs/websites/cms/wp-cli/how-to-install-wordpress-using-wp-cli-on-debian-10/index.md
- docs/websites/cms/wp-cli/how-to-install-wordpress-using-wp-cli-on-ubuntu-18-04/index.md
- docs/websites/cms/wp-cli/how-to-install-wordprress-using-wp-cli-on-debian-9/index.md
Final edits. Continued from 
https://github.com/linode/docs/pull/3144
> [NEW] Install WordPress Using WP-CLI On [X]

- docs/platform/billing-and-support/how-linode-billing-works/index.md
added note about prepaid/overpayment refunds
> [Update] How Linode Billing Works

- docs/platform/disk-images/linode-images/index.md
The max image size has been increased from 2GB to 6GB
> Update maximum image size

- docs/quick-answers/linode-platform/cancel-your-account-shortguide/index.md
- Fixed the typo as suggested in https://github.com/linode/docs/issues/3162
> [update] Cancelling Your Account

- docs/platform/one-click/how-to-deploy-flask-with-one-click-apps/index.md
* Fixed a small typo I missed when drafting and added a better description and og_description while I was here.
> [Update] Flask One-Click: Fix small typo

- docs/platform/one-click/deploy-mysql-with-one-click-apps/index.md
- Created a new guide for MySQL/MariaDB one-click app.
PS: I have retained the links to external docs to MySQL docs
> [New] MySQL one-click

- docs/platform/one-click/deploy-mean-with-one-click-apps/index.md
- docs/platform/one-click/deploy-mysql-with-one-click-apps/index.md
- docs/platform/one-click/deploy-postresql-with-one-click-apps/index.md
Created one click guides for:
- PosgreSQL
- MEAN
> MEAN and PostgreSQL oneclick guides [1k]

- ci/vale/dictionary.txt
- docs/development/go/go-data-types/index.md
> [New] Go Data Types

- docs/email/running-a-mail-server/index.md
this is no longer a required confirmation. we provide this information in the form of a statement now.
> Removing the CAN-SPAM confirmation

- docs/kubernetes/beginners-guide-to-kubernetes-part-4-controllers/index.md
- reordered sections
- added note in replicaset
- updated language in deployment to come before replicaset
> [Update] Beginners Guide to Kubernetes Part 4

- docs/security/securing-your-server/index.md
Move steps 3-4 of adding Limited user to clarify the steps are OS agnostic and should be completed regardless of Linux distribution.
> Update securing-your-server, index.md

- docs/platform/api/linode-cli/index.md
Added LKE and Object storage cli commands
Reordered the list to reflect the API page order
> [Update] Using the Linode CLI

- themes/docsmith/layouts/partials/footer.html
Theme rebuild: Updating footer links
> [Hotfix] v0.35.1

- ci/vale/dictionary.txt
- docs/kubernetes/deploy-and-manage-a-cluster-with-linode-kubernetes-engine-a-tutorial/index.md
- docs/kubernetes/deploy-and-manage-lke-cluster-with-api-a-tutorial/index.md
- docs/kubernetes/how-to-deploy-a-static-site-on-linode-kubernetes-engine/index.md
- docs/kubernetes/lke-network-firewall-information-shortguide/index.md
Add information about networking and firewalls for LKE cluster nodes.
> [Update] LKE Guides

- docs/web-servers/lemp/how-to-install-the-lemp-stack-on-centos-8/index.md
-Added a note about selinux boolean for httpd scripts as mentioned in https://github.com/linode/docs/issues/3252
> [Update] Installing the LEMP Stack on CentOS 8

- ci/requirements.txt
https://github.com/advisories/GHSA-h96w-mmrf-2h6v
https://github.com/advisories/GHSA-p5xh-vx83-mxcj
> Updated Twisted to 20.3.0, per GitHub security advisories

- docs/kubernetes/deploy-and-manage-lke-cluster-with-api-a-tutorial/index.md
* remove v4beta from API endpoints
* Update version field to k8s_version
* New sections: add and delete tags
> [Update] Deploying and Managing a Cluster with Linode Kubernetes Engine and the Linode API

- docs/development/python/create-a-python-virtualenv-on-centos-8/index.md
- docs/development/python/create-a-python-virtualenv-on-debian-10/index.md
- docs/development/python/create-a-python-virtualenv-on-ubuntu-18-04/index.md
- Added new guides for centos 8, debian 10, and ubuntu 18.04
> [New] How to create a Python Virtual Environment on Linode (1k)

- docs/applications/configuration-management/automate-a-static-site-deployment-with-salt/index.md
- docs/applications/configuration-management/beginners-guide-to-salt/index.md
- docs/applications/configuration-management/configure-and-use-salt-cloud-and-cloud-maps-to-provision-systems/index.md
- docs/applications/configuration-management/configure-and-use-salt-ssh/index.md
- docs/applications/configuration-management/configure-apache-with-salt-stack/index.md
- docs/applications/configuration-management/create-a-salt-execution-module/index.md
- docs/applications/configuration-management/getting-started-with-salt-basic-installation-and-setup/index.md
- docs/applications/configuration-management/introduction-to-jinja-templates-for-salt/index.md
- docs/applications/configuration-management/monitoring-salt-minions-with-beacons/index.md
- docs/applications/configuration-management/salt-command-line-reference/index.md
- docs/applications/configuration-management/secrets-management-with-salt/index.md
- docs/applications/configuration-management/test-salt-locally-with-kitchen-salt/index.md
- docs/applications/configuration-management/use-and-modify-official-saltstack-formulas/index.md
- docs/applications/configuration-management/use-salt-states-to-configure-a-lamp-stack-on-a-minion/index.md
- docs/applications/configuration-management/use-salt-states-to-create-lamp-stack-and-fail2ban-across-salt-minions/index.md
- docs/applications/media-servers/install-plex-media-server-with-salt/index.md
- removed Salt20 promo code from Salt guides
> [Update] Salt guides

- docs/platform/one-click/deploying-wordpress-with-one-click-apps/index.md
- updated the distro to Debian 10
- Added the following fields:
- MySQL Root Password
- WordPress Database Password
- Updated the fields:
- Wordpress Address (URL)
- Site Address (URL)
> [Update]  How to Deploy WordPress with One-Click Apps

- docs/tools-reference/custom-kernels-distros/install-nixos-on-linode/index.md
show exactly how to do this config
> give example for forceInstall

- docs/kubernetes/how-to-deploy-kubernetes-on-linode-with-rancher-2-x/index.md
added read write clarification to api key prereq
> [Update] How to Deploy Kubernetes on Linode with Rancher 2.x

- ci/vale/dictionary.txt
- docs/development/nodejs/how-to-install-nodejs-and-nginx-on-centos-8/index.md
- docs/development/nodejs/how-to-install-nodejs-and-nginx-on-debian-10/index.md
- docs/development/nodejs/how-to-install-nodejs-and-nginx-on-ubuntu-18-04/index.md
- added new guides for Debian 10, Ubuntu 18.04, and Cent OS 8
> [New] How to Install Node.js and NGINX  ( 1 k )

- docs/troubleshooting/troubleshooting-web-servers-databases-other-services/index.md
Fixing indentation of the Troubleshoot Databases section
> [Update] Troubleshooting Web Servers, Databases, and Other Services

- docs/security/securing-your-server/index.md
- docs/tools-reference/linux-users-and-groups/index.md
Clarified what sudo is and how it can be enabled, added section on whitelisting commands
> [Update] Linux Users and Groups

- docs/kubernetes/how-to-deploy-kubernetes-on-linode-with-rancher-2-x/index.md
-Updated with note on network helper reliance
> [Update] How to Deploy Kubernetes on Linode with Rancher

- docs/development/java/install-openjdk-on-centos-8/index.md
- docs/development/java/install-openjdk-on-debian-10/index.md
- docs/development/java/install-openjdk-on-ubuntu-18-04/index.md
- docs/development/java/install-openjdk-on-ubuntu-20-04/index.md
- Created new guides for centos8, debian 10, and ubuntu 18.04
> [New] Installing Java Development Kit 11 (1k)

- docs/kubernetes/how-to-deploy-kubernetes-on-linode-with-rancher-2-x/index.md
- Removed out of date note on separating control/worker nodes in production
> [Update] How to Deploy Kubernetes on Linode with Rancher 2.3

- docs/kubernetes/how-to-deploy-an-lke-cluster-using-terraform/index.md
- docs/kubernetes/how-to-deploy-kubernetes-on-linode-with-rancher-2-x/index.md
* [New] Deploying a Linode Kubernetes Engine Cluster Using Terraform
* [Update] How to Deploy Kubernetes on Linode with Rancher 2.3
> [Hotfix] v0.38.1 

- docs/kubernetes/how-to-deploy-an-lke-cluster-using-terraform/index.md
[Update] Deploying a Linode Kubernetes Engine Cluster Using Terraform:
* Further clarify base64 note
* Add note: output values can supress their output with sensitive argument
* Add spacing between required and description (variables.tf)
> [Hotfix] v0.38.2

- docs/web-servers/nginx/how-to-install-nginx-centos-8/index.md
Replaced YUM with DNF as CentOS 8 is using DNF as a default package manager. Added "sudo ls -dZ /var/www/example.com" to check whether SELinux Context are added to the directory or not. Modified the command "sudo firewall-cmd --zone=public --permanent --add-service={http,https}" which is used to add the given services to firewall using single command this saves time. Added command "sudo firewall-cmd --list-all" to check the list of services and ports which are added to firewall.
> Minor Modifications and added some commands

- docs/development/go/using-cobra/index.md
> Minor formatting correction.

- docs/platform/api/linode-cli/index.md
After running into errors using just `pip`, I edited this to show `pip3`, which worked.
> update pip installation command

- docs/platform/object-storage/how-to-use-object-storage/index.md
Found 2 more examples of commands using `pip` instead of `pip3`
> updating pip commands for pip3

- docs/platform/object-storage/how-to-use-object-storage/index.md
Added instructions related to creating a new CLI access key
> [Update] How to Use Object Storage

- docs/platform/manager/dns-manager/index.md
I found these instructions confusing. I wanted a subdomain, so I followed the instructions under the *Subdomain* heading.
Unfortunately, it's actually a Sub-Subdomain section. I deleted the record I created and added the correct entry. I added the instructions here since it wasn't explicit.
> Actual subdomains section, update subsubdomains

- docs/quick-answers/websites/certbot-shortguide-centos/index.md
- docs/quick-answers/websites/certbot-shortguide-debian/index.md
- docs/quick-answers/websites/certbot-shortguide-ubuntu/index.md
- docs/quick-answers/websites/certbot/_index.md
- docs/quick-answers/websites/certbot/certbot-on-centos-8/index.md
- docs/quick-answers/websites/certbot/certbot-on-debian-10/index.md
- docs/quick-answers/websites/certbot/certbot-on-ubuntu-18-04/index.md
- added new guides for centos8, debian 10, and ubuntu 18.04
> [New] Secure HTTP Traffic with Certbot 1k

- docs/platform/object-storage/how-to-use-object-storage/index.md
Since classic manager isn't accessible for customers anyway, figured that part wasn't needed.
> removed reference to Classic Manager

- docs/web-servers/lamp/how-to-install-a-lamp-stack-on-debian-10/index.md
- docs/web-servers/lamp/how-to-install-a-lamp-stack-on-ubuntu-18-04/index.md
> [Update] How to Install a LAMP Stack on Ubuntu 18.04

- docs/platform/billing-and-support/how-linode-billing-works/index.md
Updated the Refunds section to clarify refund requests based on MSA
> Updated Refunds section

- docs/platform/manager/dns-manager/index.md
Instead of conveying a time, I simply re-wrote to "a few minutes," which is still much shorter than the previous time of 30 minutes.
> Update DNS Manager guide with new DNS times

- docs/platform/disk-images/linode-images/index.md
Sorry for the duplicate PR hopefully this one works better.
> Updated images per account from 5 to 3

- docs/platform/linode-gpu/getting-started-with-gpu/index.md
> [Update] Getting Started with GPU

- docs/platform/disk-images/linode-backup-service/index.md
> [Update] The Linode Backup Service

- docs/platform/dedicated-cpu/dedicated-cpu-use-cases/index.md
Updated "standard" to "shared"
> [Update] Dedicated CPU Use Cases

- docs/platform/billing-and-support/how-linode-billing-works/index.md
- docs/platform/one-click/deploying-minecraft-with-one-click-apps/index.md
Deploy Minecraft with One-Click Apps guide had Minecraft v1.13 listed, but after testing it's currently installing v1.16.1
> Updated Minecraft version in Deploy from OCA guide

- docs/platform/manager/accounts-and-passwords/index.md
More detailed explanation on user permissions/general fixes
> [UPDATE] Accounts And Passwords

- docs/platform/one-click/how-to-deploy-nextcloud-with-one-click-apps/index.md
* Add note about deployment time
> [Update] Deploying Nextcloud on Linode with One-Click Apps

- docs/platform/object-storage/object-storage-cluster-shortguide/index.md
> [Update] Object Storage Cluster Shortguide

- docs/development/python/flask-and-gunicorn-on-ubuntu/index.md
- rephrased to avoid, your and possessive words.
- replaced root with 'example_user'
- updated the command to install Gunicorn
- validated that the command `pip3 install -r flask_app/requirements.txt` does not need a sudo . Attached the file for reference.
> [Update] Deploying a Flask Application on Ubuntu

- docs/platform/manager/dns-manager/index.md
- docs/platform/manager/troubleshooting-dns/index.md
> [New] Troubleshooting DNS Records

- docs/platform/object-storage/pricing-and-limitations/index.md
Creating a new branch to test  if merging is possible.
> [Update] Add Singapore to OBJ Pricing and Limitations

- themes/docsmith/layouts/partials/footer.html
- themes/docsmith/layouts/partials/header.html
> Theme rebuild: header/footer link name updates.

- docs/platform/disk-images/disk-images-and-configuration-profiles/index.md
- docs/platform/disk-images/resizing-a-linode/index.md
DOCS-323
- Add note on Auto Disk Resize limitations to *Resizing a Linode*.
- Update note on resizing disks in *Disks and Configuration Profiles*.
> [Update] Resizing a Linode; Disks and Configuration Profiles

- docs/platform/object-storage/how-to-use-object-storage-acls-and-bucket-policies/index.md
FIxed wording to better reflect Deny Policy, acknowledged condition that can lead to manager/user being locked out of accessing user's buckets
> [Update] Enacting Access Control Lists (ACLs) and Bucket Policies

- docs/platform/billing-and-support/support/index.md
updated the link to the support
> [Update] rephrased the sentence to support

- docs/kubernetes/deploy-and-manage-lke-cluster-with-api-a-tutorial/index.md
updated curl for node pool recycle
> [Update] Deploy and Manage LKE Cluster with API

- docs/kubernetes/getting-started-with-load-balancing-on-a-lke-cluster/index.md
- docs/kubernetes/how-to-configure-load-balancing-with-tls-encryption-on-a-kubernetes-cluster/index.md
- docs/platform/nodebalancer/getting-started-with-nodebalancers/index.md
- docs/platform/nodebalancer/nodebalancer-ssl-configuration/index.md
- docs/platform/nodebalancer/what-are-nodebalancers/index.md
* Add note about current ProxyProtocol support.
> [Update] Linode NodeBalancer guides + LKE load balancing guides

- docs/kubernetes/how-to-deploy-nginx-ingress-on-linode-kubernetes-engine/index.md
* Add note about proxy protocol support in NGINX Ingress guide
> [Update] Deploying NGINX Ingress on Linode Kubernetes Engine

- docs/platform/nodebalancer/configure-nodebalancer-shortguide/index.md
- docs/platform/nodebalancer/nodebalancer-ssl-configuration/index.md
- added note about port matching on configure shortguide
- updated ssl guide with appropriate fields and made less confusing
> [Update] NodeBalancer SSL Configuration + Getting Started with NodeBalancers

- themes/docsmith/layouts/partials/header.html
Remove rogue search link and theme rebuild
> [Hotfix] v0.46.1

- README.md
- ci/vale/dictionary.txt
updated readme with hugo version
> [Update] Readme

- docs/platform/disk-images/linode-backup-service/index.md
removed pricing tables, added link to pricing page
> [Update] Linode Backup Service

- docs/platform/object-storage/server-side-encryption/index.md
This guide teaches you how to secure your Linode Object Storage data with server-side encryption using an example script written in Python.
> [New] Using Server-Side Encryption with Linode Object Storage

- docs/security/vulnerabilities/scanning-your-linode-for-malware/index.md
Updated the steps to account for the following changes:
Update Finnix no longer requires manual GPG key setup
ClamAV install now comes with a daemon that automatically runs freshclam
New Finnix no longer creates /media/sda or populates /etc/fstab
> Updated steps for new Finnix

- docs/kubernetes/deploy-volumes-with-the-linode-block-storage-csi-driver/index.md
- docs/kubernetes/how-to-install-the-linode-block-storage-csi-driver/index.md
split guide into two, added note about secret also deployed with lke and terraform
> [Update] Deploy Volumes with Linode Block Storage CSI Driver

- docs/platform/one-click/deploying-cs-go-with-one-click-apps/index.md
https://deploy-preview-3496--nostalgic-ptolemy-b01ab8.netlify.app/platform/one-click/deploying-cs-go-with-one-click-apps/
- Add header "Connect with the CS:GO Client" under "Getting Started after Deployment".
- Relocate instructions on enabling developer console.
- Add instructions on connecting if setting server password.
> [Update] Deploying CS:GO with One-Click Apps

- docs/platform/disk-images/linode-images/index.md
The correct number of images per account is 3
> Update images per account to 3, not 5

- themes/docsmith/layouts/partials/footer.html
- themes/docsmith/layouts/partials/header.html
* Theme build: Header and footer link updates.
> [Hotfix] 0.47.1

- docs/platform/manager/dns-manager/index.md
This reverts commit ca95953db0c7b8b71ff91e5cd798496bd6b9ab51.
> Revert "Testing a git thing (#3568)"

- ci/yaml_rules.json
- docs/databases/mariadb/how-to-install-mariadb-on-centos-7/index.md
- docs/databases/mariadb/how-to-install-mariadb-on-centos-8/index.md
- docs/databases/mariadb/how-to-install-mariadb-on-debian-10/index.md
- docs/databases/mariadb/how-to-install-mariadb-on-debian-9/index.md
- docs/databases/mariadb/how-to-install-mariadb-on-ubuntu-18-04/index.md
Add frontmatter for distribution switcher
> [Update] How to Install Mariadb guides

- docs/platform/billing-and-support/how-linode-billing-works/index.md
- docs/platform/how-to-choose-a-linode-plan/index.md
updated billing and how to choose a plan pages with support suggestions
> [Update] How Billing Works and Choose Linode Plan

- docs/platform/object-storage/how-to-use-object-storage/index.md
Current information on Limited Access Keys
> [Update] How to Use Object Storage 

- docs/platform/cloud-firewall/getting-started-with-cloud-firewall/index.md
* Add note about Cloud Firewall Beta sign up
> [Update] A Tutorial for Adding and Configuring Linode Cloud Firewall

- docs/game-servers/create-an-ark-survival-evolved-server-on-ubuntu-16-04/index.md
- docs/game-servers/deploy-just-cause-2-multiplayer-server-on-ubuntu/index.md
- docs/game-servers/garrys-mod-server-on-centos-7/index.md
- docs/game-servers/how-to-set-up-minecraft-server-on-ubuntu-or-debian/index.md
- docs/game-servers/install-a-half-life-2-deathmatch-dedicated-server-on-debian-or-ubuntu/index.md
- docs/game-servers/install-black-mesa-on-debian-or-ubuntu/index.md
- docs/game-servers/install-dont-starve-together-game-server-on-ubuntu/index.md
- docs/game-servers/launch-a-counter-strike-global-offensive-server-on-ubuntu-14-04/index.md
- docs/game-servers/launch-a-counter-strike-global-offensive-server-on-ubuntu-18-04/index.md
- docs/game-servers/left-4-dead-2-multiplayer-server-installation/index.md
- docs/game-servers/minecraft-on-linode-with-ubuntu-12-04/index.md
- docs/game-servers/minecraft-with-bungee-cord/index.md
- docs/game-servers/minecraft-with-mcmyadmin-on-debian/index.md
- docs/game-servers/minecraft-with-spigot-ubuntu/index.md
- docs/game-servers/multicraft-on-debian/index.md
- docs/game-servers/multicraft-on-ubuntu/index.md
- docs/game-servers/pocketmine-server-on-debian-7/index.md
- docs/game-servers/team-fortress2-on-debian-and-ubuntu/index.md
> [Update] Tags for Game Servers

- docs/troubleshooting/disaster-recovery-guide/index.md
- docs/troubleshooting/rescue-and-rebuild/index.md
- docs/troubleshooting/troubleshooting-basic-connection-issues/index.md
- docs/troubleshooting/troubleshooting-common-apache-issues/index.md
- docs/troubleshooting/troubleshooting-memory-and-networking-issues/index.md
- docs/troubleshooting/troubleshooting-ssh/index.md
- docs/troubleshooting/troubleshooting-web-servers-databases-other-services/index.md
- docs/troubleshooting/troubleshooting/index.md
> [Update] Tags for Troubleshooting 

- docs/databases/mysql/how-to-install-mysql-on-debian-8/index.md
fix for https://github.com/linode/docs/issues/3454
> [Update] added a note about mysql-server package

- docs/uptime/best-practices/reboot-survival-guide/index.md
> [Update] Reboot Survival Guide

- docs/platform/manager/manually-enable-elastic-ip-on-your-linode/index.md
* Reorder configuration value table
> [Update] Manually Enable Elastic IP on your Linode

- docs/platform/disk-images/resizing-a-linode/index.md
added section on moving to a smaller plan, eliminated some future tense
> [Update] Resizing a Linode

- docs/platform/manager/manually-enable-elastic-ip-on-your-linode/index.md
* [Update] Manually Enable Elastic IP on your Linode
* Update network interfaces command to prevent broken SSH pipe.
> Hotfix v0.50.1

- docs/platform/one-click/deploying-wordpress-with-one-click-apps/index.md
adding new fields and wording for dns changes
> [Update] WordPress OCA

- ci/vale/dictionary.txt
- docs/platform/one-click/one-click-add-domain-shortguide/index.md
- products/tools/one-click-app-marketplace/_index.md
- products/tools/one-click-app-marketplace/developers/_index.md
- products/tools/one-click-app-marketplace/guides/_index.md
- products/tools/one-click-app-marketplace/guides/one-click-access-app/index.md
- products/tools/one-click-app-marketplace/guides/one-click-add-domain-name/index.md
- products/tools/one-click-app-marketplace/guides/one-click-deploy-app/index.md
- products/tools/one-click-app-marketplace/resources/_index.md
* OG PR: https://github.com/linode/docs/pull/3641
> [Update] Product Docs for One-Click Apps Marketplace

- products/tools/monitoring/_index.md
- products/tools/monitoring/developers/_index.md
- products/tools/monitoring/guides/_index.md
- products/tools/monitoring/guides/monitoring-cloud-graphs/index.md
- products/tools/monitoring/guides/monitoring-configure-watchdog/index.md
- products/tools/monitoring/guides/monitoring-email-alerts/index.md
- products/tools/monitoring/guides/monitoring-third-party-tools/index.md
- products/tools/monitoring/resources/_index.md
* OG PR: https://github.com/linode/docs/pull/3640
* Rebased on feature branch + cherry picks
> [Update] Product Docs Monitoring 

- ci/vale/dictionary.txt
- products/tools/cloud-manager/_index.md
- products/tools/cloud-manager/developers/_index.md
- products/tools/cloud-manager/guides/_index.md
- products/tools/cloud-manager/guides/cloud-api-keys/index.md
- products/tools/cloud-manager/guides/cloud-billing/index.md
- products/tools/cloud-manager/guides/cloud-block-storage/index.md
- products/tools/cloud-manager/guides/cloud-create-linode/index.md
- products/tools/cloud-manager/guides/cloud-credits/index.md
- products/tools/cloud-manager/guides/cloud-delete-ip/index.md
- products/tools/cloud-manager/guides/cloud-domains/index.md
- products/tools/cloud-manager/guides/cloud-email-notifications/index.md
- products/tools/cloud-manager/guides/cloud-find-disks/index.md
- products/tools/cloud-manager/guides/cloud-images/index.md
- products/tools/cloud-manager/guides/cloud-invoices/index.md
- products/tools/cloud-manager/guides/cloud-kubernetes/index.md
- products/tools/cloud-manager/guides/cloud-longview/index.md
- products/tools/cloud-manager/guides/cloud-marketplace/index.md
- products/tools/cloud-manager/guides/cloud-nodebalancers/index.md
- products/tools/cloud-manager/guides/cloud-oauth/index.md
- products/tools/cloud-manager/guides/cloud-object-storage/index.md
- products/tools/cloud-manager/guides/cloud-reboot-linode/index.md
- products/tools/cloud-manager/guides/cloud-stackscripts/index.md
- products/tools/cloud-manager/resources/_index.md
* OG PR: https://github.com/linode/docs/pull/3638
* Rebased on top of latest feature branch changes + cherry-pick
> [Update] Product Docs Cloud Manager 

- ci/vale/dictionary.txt
- products/tools/linode-api/_index.md
- products/tools/linode-api/developers/_index.md
- products/tools/linode-api/get-started/_index.md
- products/tools/linode-api/guides/_index.md
- products/tools/linode-api/guides/authenticate-requests/index.md
- products/tools/linode-api/guides/build-final-query/index.md
- products/tools/linode-api/guides/get-access-token/index.md
- products/tools/linode-api/guides/get-config-parameters/index.md
- products/tools/linode-api/resources/_index.md
* OG PR: https://github.com/linode/docs/pull/3632
* Rebased on top of feature branch latest + cherry picking
> [Update] Product Docs Linode API

- docs/platform/one-click/deploy-phpmyadmin-with-one-click-apps/index.md
- docs/platform/one-click/deploy-plex-with-one-click-apps/index.md
- docs/platform/one-click/deploying-wordpress-with-one-click-apps/index.md
- docs/platform/one-click/how-to-deploy-azuracast-with-one-click-apps/index.md
- docs/platform/one-click/how-to-deploy-jitsi-with-one-click-apps/index.md
- docs/platform/one-click/how-to-deploy-virtualmin-with-one-click-apps/index.md
- docs/platform/one-click/how-to-deploy-webmin-with-one-click-apps/index.md
> Rc v0.51.0

- docs/platform/one-click/how-to-deploy-percona-monitoring-management-with-one-click-apps/index.md
Hotfix:
- removes the `hostname` field from the Percona PMM One-Click.
- Adds `admin password`
- removes Ubuntu as distro option
- removes no longer necessary step 8
> [Hotfix] 0.51.1

- docs/game-servers/how-to-set-up-minecraft-server-on-ubuntu-or-debian/index.md
- docs/game-servers/launch-a-counter-strike-global-offensive-server-on-ubuntu-14-04/index.md
- docs/game-servers/launch-a-counter-strike-global-offensive-server-on-ubuntu-18-04/index.md
- docs/game-servers/minecraft-on-linode-with-ubuntu-12-04/index.md
- docs/game-servers/multicraft-on-debian/index.md
- docs/game-servers/multicraft-on-ubuntu/index.md
> [Update] Distros for Games

- docs/networking/dns/provide-authoritative-dns-services-with-nsd-on-debian-5-lenny/index.md
- docs/networking/dns/provide-authoritative-dns-services-with-nsd-on-debian-6-squeeze/index.md
- docs/networking/dns/provide-authoritative-dns-services-with-nsd-on-fedora-13/index.md
- docs/networking/dns/provide-authoritative-dns-services-with-nsd-on-fedora-14/index.md
- docs/networking/dns/provide-authoritative-dns-services-with-nsd-on-ubuntu-10-04-lucid/index.md
- docs/networking/dns/provide-authoritative-dns-services-with-nsd-on-ubuntu-10-10-maverick/index.md
- docs/networking/dns/provide-authoritative-dns-services-with-nsd-on-ubuntu-11-04-natty/index.md
- docs/networking/dns/provide-authoritative-dns-services-with-nsd-on-ubuntu-12-04/index.md
- docs/networking/dns/provide-authoritative-dns-services-with-nsd-on-ubuntu-9-10-karmic/index.md
- docs/networking/dns/use-unbound-for-local-dns-resolution-on-debian-5-lenny/index.md
- docs/networking/dns/use-unbound-for-local-dns-resolution-on-debian-6-squeeze/index.md
- docs/networking/dns/use-unbound-for-local-dns-resolution-on-fedora-13/index.md
- docs/networking/dns/use-unbound-for-local-dns-resolution-on-fedora-14/index.md
- docs/networking/dns/use-unbound-for-local-dns-resolution-on-fedora-15/index.md
- docs/networking/dns/use-unbound-for-local-dns-resolution-on-ubuntu-10-04-lts-lucid/index.md
- docs/networking/dns/use-unbound-for-local-dns-resolution-on-ubuntu-10-10-maverick/index.md
- docs/networking/dns/use-unbound-for-local-dns-resolution-on-ubuntu-11-04-natty/index.md
- docs/networking/dns/use-unbound-for-local-dns-resolution-on-ubuntu-12-04-lts-precise-pangolin/index.md
- docs/networking/dns/use-unbound-for-local-dns-resolution-on-ubuntu-9-10-karmic/index.md
- docs/networking/vpn/secure-communications-with-openvpn-on-centos-6/index.md
- docs/networking/vpn/secure-communications-with-openvpn-on-debian-5-lenny/index.md
- docs/networking/vpn/secure-communications-with-openvpn-on-debian-6-squeeze/index.md
- docs/networking/vpn/secure-communications-with-openvpn-on-ubuntu-10-04-lucid/index.md
- docs/networking/vpn/secure-communications-with-openvpn-on-ubuntu-10-10-maverick/index.md
- docs/networking/vpn/secure-communications-with-openvpn-on-ubuntu-12-04-precise-and-debian-7/index.md
- docs/networking/vpn/secure-communications-with-openvpn-on-ubuntu-9-10-karmic/index.md
- docs/networking/vpn/set-up-wireguard-vpn-on-debian/index.md
- docs/networking/vpn/set-up-wireguard-vpn-on-ubuntu/index.md
added distros for networking guides
> [Update] Distros for Networking

- docs/platform/longview/what-is-the-linode-longview-app-for-apache/index.md
- docs/platform/longview/what-is-the-linode-longview-app-for-mysql/index.md
- docs/platform/longview/what-is-the-linode-longview-app-for-nginx/index.md
added distro to platform guides
> [Update] Distros for Platform

- docs/quick-answers/linux/how-to-install-selinux-on-debian-10/index.md
- docs/quick-answers/linux/how-to-install-selinux-on-ubuntu-18-04/index.md
- docs/quick-answers/websites/how-to-install-certbot-on-centos-8/index.md
- docs/quick-answers/websites/how-to-install-certbot-on-debian-10/index.md
- docs/quick-answers/websites/how-to-install-certbot-on-ubuntu-18-04/index.md
add distro to quick answer guides
> [Update] Distros for Quick Answers

- docs/tools-reference/custom-kernels-distros/custom-compiled-kernel-centos-7/index.md
- docs/tools-reference/custom-kernels-distros/custom-compiled-kernel-debian-ubuntu/index.md
- docs/tools-reference/custom-kernels-distros/custom-compiled-kernel-with-pvgrub-centos-7/index.md
- docs/tools-reference/custom-kernels-distros/custom-compiled-kernel-with-pvgrub-debian-ubuntu/index.md
- docs/tools-reference/custom-kernels-distros/custom-compiled-kernel-with-pvgrub-on-arch/index.md
- docs/tools-reference/custom-kernels-distros/install-alpine-linux-on-your-linode/index.md
- docs/tools-reference/custom-kernels-distros/install-coreos-on-your-linode/index.md
- docs/tools-reference/custom-kernels-distros/install-freebsd-on-linode/index.md
- docs/tools-reference/custom-kernels-distros/install-nixos-on-linode/index.md
added distro relations for tools and references guides
> [Update] Distros for Tools and References

- ci/vale/dictionary.txt
- docs/security/vulnerabilities/scanning-your-linode-for-malware/index.md
@leslitagordita 
Added additional section with instructions for running the new ClamAV script in Finnix
> Updated for Automated ClamAV scanning in Finnix

- docs/networking/dns/use-dig-to-perform-manual-dns-queries/index.md
- docs/platform/manager/dns-manager-add-domain-shortguide/index.md
- docs/websites/cms/cpanel/set-up-dns-services-on-cpanel/index.md
> [Release Candidate] v0.52.2

- config.toml
Corresponds with https://github.com/bep/linodedocs/pull/8
> Set promo code in site config

- docs/networking/dns/use-dig-to-perform-manual-dns-queries/index.md
- docs/platform/manager/dns-manager-add-domain-shortguide/index.md
- docs/websites/cms/cpanel/set-up-dns-services-on-cpanel/index.md
> [Update] Add Domain Shortguide

- docs/_index.md
- docs/guides/_index.md
- docs/products/_index.md
* Completely removed the /docs welcome text 
* Add guides and product docs welcome text
> Welcome text updates

- _vendor/github.com/linode/linode-api-docs/v4/openapi.yaml
- _vendor/modules.txt
- docs/guides/security/basics/how-to-use-fail2ban-for-ssh-brute-force-protection/index.md
- go.mod
- go.sum
Rebuild vendor to point to latest API release tag 4.78.3
> API release 4.78.3

- _vendor/github.com/bep/linodedocs/assets/js/main/search/search.js
- _vendor/github.com/bep/linodedocs/layouts/index.html
- _vendor/github.com/bep/linodedocs/layouts/partials/sections/content/promo_code.html
- _vendor/modules.txt
- config.toml
- docs/guides/platform/api/_index.md
- go.mod
- go.sum
Theme updates:
- Empty webinars link fix
- Set promo_code_amount in config.toml
Guide updates:
- docs/guides/platform/api/ section page
> [Hotfix] v1.0.1

- _vendor/github.com/bep/linodedocs/assets/js/main/main.js
- _vendor/github.com/bep/linodedocs/layouts/partials/sections/content/products/title-byline.html
- _vendor/github.com/linode/linode-website-partials/footer.html
- _vendor/github.com/linode/linode-website-partials/header.html
- _vendor/modules.txt
- go.mod
- go.sum
* Turbolinks fix for css styling and weglot lang switcher
* Updates to header links
* Fix product docs guide sections
> Theme changes for Oct 28 2020

- _vendor/github.com/bep/linodedocs/assets/js/main/search/filters.js
- _vendor/github.com/bep/linodedocs/layouts/_default/_markup/render-image.html
- _vendor/github.com/bep/linodedocs/layouts/partials/sections/after-body-start.html
- _vendor/github.com/bep/linodedocs/layouts/partials/sections/content/marquee-img.html
- _vendor/github.com/bep/linodedocs/package.json
- _vendor/modules.txt
- go.mod
- go.sum
Theme updates:
- Disable CloudFlare Rocket Loader for breadcrumbs
- Fix an issue where the featured image is displayed twice on a
guide
- Fix an issue where clicking on a tag on a guide would have no
effect
> Theme updates

- docs/guides/platform/vlan/how-to-create-a-private-network-with-linode-vlans-api/index.md
* VLAN API guide recreate PR for new docs UI
* Edits to link to product documentation, most recent changes to the API endpoints, and marketing landing page.
> [New] Creating a Private Network Using Linode APIv4 and Linode VLAN

- netlify.toml
> Fix Netlify preview builds

- docs/guides/platform/cloud-firewall/add-new-cloud-firewall-rules-shortguide/index.md
This is to remove extra edit section from add cloud firewall shortguide.
> [Hotfix] v1.6.2

- docs/guides/platform/billing-and-support/how-linode-billing-works/index.md
- docs/guides/platform/billing-and-support/manage-billing-in-cloud-manager/index.md
Adds address requirement where relevant
> [Update] Billing and Support

- _vendor/github.com/linode/linode-api-docs/v4/openapi.yaml
- _vendor/modules.txt
- go.mod
- go.sum
Update API reference to v4.80.0
> Release 1.7.0 

- docs/guides/quick-answers/linux/how-to-add-linux-alias-command-in-bashrc-file/index.md
> [New] How to Add the Linux alias Command in the .bashrc File

- _vendor/github.com/bep/linodedocs/layouts/_default/single.html
- _vendor/github.com/bep/linodedocs/layouts/content/list.html
- _vendor/github.com/bep/linodedocs/layouts/partials/sections/content/products/title-byline.html
- _vendor/github.com/bep/linodedocs/layouts/partials/sections/content/title-byline.html
- _vendor/github.com/bep/linodedocs/layouts/products/list.html
- _vendor/github.com/bep/linodedocs/layouts/products/single.html
- _vendor/github.com/linode/linode-website-partials/footer.css
- _vendor/github.com/linode/linode-website-partials/footer.html
- _vendor/github.com/linode/linode-website-partials/header.css
- _vendor/github.com/linode/linode-website-partials/header.html
- _vendor/modules.txt
- go.mod
- go.sum
Includes:
* header/footer updates (image optimizations, update menu options, remove unneeded comments and vendor prefixes)
* Only show one date (published or modified date) in article head
* Add original publish date at the bottom of a page.
> Update docs theme

- docs/guides/troubleshooting/rescue-and-rebuild/index.md
- Copy edits
- fixes:
the fstab update note and chroot instructions
> Update [Rescue and Build]

- docs/guides/platform/disk-images/copying-a-disk-image-over-ssh/index.md
Clarification on copying/download language and process
> [Update] Copy a Disk Over SSH

- docs/guides/platform/manager/using-the-linode-shell-lish/index.md
Updated 3pa note to appropriate section
> [Update] Using the Linode Shell Lish

- docs/guides/platform/object-storage/host-static-site-object-storage/index.md
Removing unnecessary note on SSL
> [Update] Host a Static Site Using Linode's Object Storage

- docs/guides/tools-reference/custom-kernels-distros/install-a-custom-distribution-on-a-linode/index.md
- Removed the note about Xen Linode
- Fixes https://github.com/linode/docs/issues/3781
> [Update] Install a Custom Distribution on a Linode

- docs/products/networking/_index.md
- docs/products/networking/ddos-protection/_index.md
- docs/products/networking/ddos-protection/resources/index.md
- docs/products/networking/dns-manager/_index.md
- docs/products/networking/dns-manager/developers/index.md
- docs/products/networking/dns-manager/get-started/index.md
- docs/products/networking/dns-manager/guides/_index.md
- docs/products/networking/dns-manager/guides/add-dns-records/index.md
- docs/products/networking/dns-manager/guides/add-domains/index.md
- docs/products/networking/dns-manager/guides/edit-dns-records/index.md
- docs/products/networking/dns-manager/guides/remove-domains/index.md
- docs/products/networking/dns-manager/guides/transfer-domain-zones/index.md
- docs/products/networking/dns-manager/resources/index.md
- docs/products/networking/nodebalancers/_index.md
- docs/products/networking/nodebalancers/developers/index.md
- docs/products/networking/nodebalancers/get-started/index.md
- docs/products/networking/nodebalancers/guides/_index.md
- docs/products/networking/nodebalancers/guides/configure/index.md
- docs/products/networking/nodebalancers/resources/index.md
* Prod docs networking descriptions
* OG PR: https://github.com/linode/docs/pull/3715
> Networking prod docs update

- docs/guides/kubernetes/how-to-deploy-nginx-ingress-on-linode-kubernetes-engine/index.md
- updated the location of the chart for helm and the related output
> [update]How to Deploy NGINX Ingress on Linode Kubernetes Engine

- _vendor/github.com/linode/linode-api-docs/v4/openapi.yaml
- _vendor/modules.txt
- go.mod
- go.sum
Update API reference to API spec v4.81.0
> Release v1.10.0 for API v4.81.0

- docs/guides/applications/media-servers/how-to-install-jellyfin/index.md
- docs/guides/email/iredmail/install-iredmail-on-ubuntu/index.md
- docs/guides/platform/disk-images/copying-a-disk-image-over-ssh/index.md
- docs/guides/platform/linode-gpu/getting-started-with-gpu/index.md
- docs/guides/platform/marketplace/deploy-mern-with-marketplace-apps/index.md
> [Update] Link Fixes in multiple guides

- docs/guides/platform/migrate-to-linode/best-practices-when-migrating-to-linode/index.md
> [Update] Best Practices When Migrating to Linode

- docs/products/networking/cloud-firewall/_index.md
> Cloud Firewall Tor Avail

- docs/guides/quick-answers/websites/secure-http-traffic-certbot/index.md
- docs/guides/security/ssl/how-to-make-a-selfsigned-ssl-certificate/index.md
- docs/guides/security/ssl/install-lets-encrypt-to-create-ssl-certificates/index.md
changed deprecated link to certbot guide for ubuntu
> [Update] Lets Encrypt and SSL guides - deprecated links

- docs/guides/applications/configuration-management/terraform/how-to-build-your-infrastructure-using-terraform-and-linode/index.md
- docs/guides/applications/configuration-management/terraform/import-existing-infrastructure-to-terraform/index.md
- docs/guides/kubernetes/deploy-and-manage-lke-cluster-with-api-a-tutorial/index.md
- docs/guides/kubernetes/getting-started-with-kubernetes/index.md
- docs/guides/kubernetes/how-to-deploy-a-static-site-on-linode-kubernetes-engine/index.md
- docs/guides/networking/diagnostics/lsof/index.md
- docs/guides/networking/diagnostics/ss/index.md
- docs/guides/platform/object-storage/host-static-site-object-storage/index.md
- removed &nbsp; in output
- updated links
- removed future tense
> [Update] Formatting Output Column Fixes

- docs/guides/kubernetes/how-to-install-the-linode-block-storage-csi-driver/index.md
updated links and removed future tense
> [Update] How to Install the Linode Block Storage CSI Driver

- docs/guides/platform/marketplace/how-to-deploy-jitsi-with-marketplace-apps/index.md
> [Update] Jitsi Marketplace App

- docs/guides/websites/cms/cpanel/set-up-dns-services-on-cpanel/index.md
> [Update] Setup DNS on cPanel

- _vendor/github.com/linode/linode-api-docs/v4/openapi.yaml
- _vendor/modules.txt
- go.mod
- go.sum
Publish docs for API release 4.82.0
> [Release Candidate] v1.12.0

- docs/guides/platform/manager/dns-manager-add-domain-shortguide/index.md
AXFR Update, official IP deprecation and note
> [Release Candidate] v1.12.1

- docs/guides/tools-reference/tools/find-files-in-linux-using-the-command-line/index.md
* SEO updates for How to Find Files in Linux Using the Command Line.
> [Hotfix] 1.12.4

- docs/guides/platform/marketplace/deploy-wireguard-with-marketplace-apps/index.md
- docs/products/tools/marketplace-one-click-apps/guides/_index.md
Wireguard OCA is healess and not indexed.
> Hotfix 1.12.6

- docs/guides/email/email-services/postfix-smtp-debian7/index.md
- docs/guides/websites/hosting/secure-website-lets-encrypt-acme-sh/index.md
* Update to add FAQs (submitted originally in the following PR: https://github.com/linode/docs/pull/3867
> [Update] Configure Postfix to Send Email Using External SMTP Servers

- .github/workflows/test.yaml
- _vendor/github.com/linode/linode-api-docs/v4/openapi.yaml
- _vendor/modules.txt
- go.mod
- go.sum
* API releases 4.83.0 & 4.83.1
* Vale GHA steps update
> [Release] v1.14.0

- docs/guides/platform/marketplace/how-to-deploy-kepler-with-marketplace-apps/index.md
- added a new guide for Kepler
> [New] How to Deploy Kepler with Marketplace Apps

- archetypes/marketplace.md
Used for the creation of Marketplace app guides.
> Marketplace App Archetype

- docs/guides/applications/containers/how-to-use-dockerfiles/index.md
> [Update] How to Use Dockerfiles

- ci/vale/dictionary.txt
- docs/guides/development/concepts/what-is-unit-testing/index.md
Martin Heller's "What is unit testing" guide.
> Initial draft of guide

- docs/guides/development/nodejs/how-to-install-use-node-version-manager-nvm/index.md
Guide for NVM installation and usage guide.
> Initial draft of NVM installation and usage guide

- docs/guides/kubernetes/how-to-drain-a-node-pool-in-linode-kubernetes-engine/index.md
- docs/kubernetes/how-to-drain-a-node-pool-in-linode-kubernetes-engine/index.md
- Created a new guide based on https://trello.com/c/i1SEi0KN/47-how-to-drain-a-node-pool-in-lke
> [New] Draining a Node Pool in Linode Kubernetes Engine

- _vendor/github.com/bep/linodedocs/assets/js/main/sections/home/home.js
- _vendor/modules.txt
- go.mod
- go.sum
Theme update
This theme update puts in place a short-term fix for a home screen
bug. Previously, the home screen was showing a blank body on
mobile. We identified some code related to touch-swiping behavior
of the carousels on mobile as the culprit.
That code is now commented out, so the home page appears on mobile.
However, the carousels cannot be swiped left/right until the issue
is investigated further.
> [Hotfix] v1.20.1

- docs/guides/networking/linode-network/linux-static-ip-configuration/index.md
- docs/guides/platform/marketplace/deploying-plesk-with-marketplace-apps/index.md
- docs/guides/platform/nodebalancer/nodebalancer-ssl-configuration/index.md
- Linux Static IP Configuration
- Deploy Plesk with Marketplace Apps
- Nodebalancer SSL Configuration
> Docs Patches Feb 16 2021

- docs/guides/kubernetes/troubleshooting-kubernetes/index.md
Provide realistic solutions to resource contention, clean up wording
> [Update] Troubleshooting Kubernetes

- docs/guides/quick-answers/websites/certbot-shortguide-ubuntu/index.md
- docs/guides/web-servers/nginx/use-nginx-reverse-proxy/index.md
New PR to address [conflicts](https://github.com/linode/docs/pull/3981)
> [Update] Use NGINX as a Reverse Proxy

- _vendor/github.com/linode/linode-api-docs/v4/openapi.yaml
- _vendor/modules.txt
- go.mod
- go.sum
Update API reference to API spec v4.85.0
> [Release] v1.25.0

- docs/guides/applications/big-data/introduction-to-machine-learning-training-and-inference/index.md
- docs/guides/applications/big-data/ml-cloud/index.md
Initial draft of guide for Andy Patrizio's "machine learning in the cloud"
> Machine learning in the cloud

- docs/guides/quick-answers/linux/how-to-use-echo/index.md
- docs/quick-answers/linux/how-to-use-echo/index.md
Signed-off-by: Rajakavitha1 <krajakavitha@gmail.com>
- created a the echo command guide
> [New] How to Use Echo

- _vendor/github.com/linode/linode-api-docs/v4/openapi.yaml
- _vendor/modules.txt
- go.mod
- go.sum
Update API reference to API spec v4.86.1
> [Release] 1.29.0

- docs/guides/platform/marketplace/deploy-cyberpanel-with-marketplace-apps/index.md
Fixes information on supported distros
> [Update] Deploy Cyberpanel with Marketplace Apps

- _vendor/github.com/linode/linode-docs-theme/assets/js/main/index.js
- _vendor/github.com/linode/linode-docs-theme/assets/js/main/navigation/breadcrumbs.js
- _vendor/github.com/linode/linode-docs-theme/assets/js/main/navigation/explorer.js
- _vendor/github.com/linode/linode-docs-theme/assets/js/main/search/filters.js
- _vendor/github.com/linode/linode-docs-theme/assets/js/main/search/input.js
- _vendor/github.com/linode/linode-docs-theme/assets/js/main/search/search.js
- _vendor/github.com/linode/linode-docs-theme/assets/js/main/sections/home/home.js
- _vendor/github.com/linode/linode-docs-theme/assets/js/main/sections/sections/list.js
- _vendor/github.com/linode/linode-docs-theme/config.toml
- _vendor/github.com/linode/linode-docs-theme/layouts/index.html
- _vendor/github.com/linode/linode-docs-theme/layouts/partials/funcs/get-author-link.html
- _vendor/github.com/linode/linode-docs-theme/layouts/partials/sections/content/products/title-byline.html
- _vendor/github.com/linode/linode-docs-theme/layouts/partials/sections/content/title-byline.html
- _vendor/github.com/linode/linode-docs-theme/layouts/partials/sections/head-src.html
- _vendor/github.com/linode/linode-docs-theme/layouts/partials/sections/head.html
- _vendor/github.com/linode/linode-docs-theme/layouts/partials/sections/search/input.html
- _vendor/github.com/linode/linode-docs-theme/layouts/partials/sections/search/panel.html
- _vendor/github.com/linode/linode-docs-theme/layouts/sections/list.html
- _vendor/modules.txt
- go.mod
- go.sum
Theme updates:
- Optionally link author byline using the contributor link front matter
- Add breadcrumbs to search panel
- Avoid updating breadcrumbs when location changes
- Fix search panel opening on focus when it should not
- Fix singular + plural versions of items in Products, Marketplace and Blog
- Move search configuration to the theme repo
- Allow on-page h1 title to differ from title used in title tag
> [Hotfix] v1.30.2

- docs/guides/networking/linode-network/linux-static-ip-configuration/index.md
`/etc/resolve.conf`  --> `/etc/resolv.conf`
> Fix little typo

- _vendor/github.com/linode/linode-api-docs/v4/openapi.yaml
- _vendor/modules.txt
- go.mod
- go.sum
Update API reference to API spec v4.87.0
> [Release] 1.32.0

- docs/products/storage/object-storage/get-started/index.md
- Added a note about using AbortIncompleteMultipartUpload policy.
> [Update] Object Storage - Get Started
