linode/docs

- docs/websites/lemp/lemp-server-on-ubuntu-12-04-precise-pangolin.md
The suggested nginx.conf should point to the unix socket that php5-fpm is already configured to be listening on.
> Correct php5-fpm listening socket

- docs/networking/linux-static-ip-configuration.md
We should not be using aliases anymore. After ifconfig was deprecated and iproute2 took precedence, aliases became a thing of the past. 
As per Debian: "The newer ip utility does not use the same concept of aliases or virtual interfaces." 
Using aliases doesn't break the configuration, but it's probably not the best practice. It's best not to use them.
> Removed aliases for Debian and CentOS as per iproute2

- docs/security/full-disk-encryption.md
Only Arch Linux uses the `cryptdevice` parameter to dynamically specify where the encrypted disk resides. In Debian this is done statically through `update-initramfs`.
> Remove cryptdevice parameter

- docs/contribute.md
Certain links under **Completed Topics** are old and redirect to their new location.
> Update links of "Completed Topics"

- docs/websites/apache/running-fastcgi-php-fpm-on-debian-7-with-apache.md
The two external links under **More Information** appear in a single line. Formatted them as an unordered list.
> Place external links in a list

- docs/websites/apache/running-fastcgi-php-fpm-on-debian-7-with-apache.md
The words **LAMP stacks** links to a screenshot instead of the list of LAMP guides.
> Fix "LAMP stacks" link

- docs/networking/ssh/setting-up-an-ssh-tunnel-with-your-linode-for-safe-browsing.md
- docs/platform/accounts-and-passwords.md
Some links in these [two](https://www.linode.com/docs/networking/ssh/setting-up-an-ssh-tunnel-with-your-linode-for-safe-browsing) [articles](https://www.linode.com/docs/platform/accounts-and-passwords) redirect to their new pages and the link to the **Getting Started** page is broken.
> Change old links

- docs/tools-reference/search-and-filter-text-with-grep.md
Otherwise (as it is now) the pipe ("|") is not shown. This will fix that.
> Change format so ls command is valid in search and filter guide

- docs/networking/using-the-linode-shell-lish.md
The LISH shell isn't screen, so don't use the screen detach sequence to
exit it; instead, use the EOF sequence.
> Fix LISH logout procedure

- docs/applications/development/developing-git-github.md
- docs/networking/native-ipv6-networking.md
We shouldn't be using ifconfig (deprecated). We also should be removing ip addr add from this, because the changes won't be saved permanently unless they're in the /etc/network/interfaces file (or similar, depending on distribution).
I've kept the second IPv6 address add section, but removed the first because it's unnecessary to have the same information twice in the same documentation. 
While ArchLinux uses systemd-networkd now, there's a lot of people still using netctl, so I believe that we'll be okay keeping netctl in there, but will likely add systemd-networkd as well shortly. This change is more of a "pushing it out there because adding IPv6 by ip addr add is a bad idea" kind of change. 
Additionally, I've added information about IPv6 forwarding. While I don't want to add …
> Make changes to IPv6 pool to add forwarding information

- docs/websites/cms/drush-drupal.md
- docs/websites/cms/managing-web-content-with-drupal-7.md
- docs/websites/cms/managing-web-content-with-drupal-8-beta.md
Very minor changes:
- changed Github to GitHub
- specified Drupal version in a subtile of the Drupal 7 doc
- changed the titles of both "Managing Web Content with Drupal *" guides to "Installing Drupal *"
- changed the formatting of the word beta
> Drupal scrub

- docs/tools-reference/linux-system-administration-basics.md
Looks weird otherwise, and a lot of it was on one line. Fixed that.
> Fix syntax and format in Linux Systems Administration Basics doc

- docs/websites/lamp/lamp-server-on-ubuntu-14-04.md
LAMP Server Ubuntu 14.04 incorrectly referred to mpm_prefork_module as
mpm_preform_module. This fixes that.
> Fixed typo "preform" vs "prefork"

- docs/websites/lamp/lamp-server-on-arch-linux.md
only comment out pm_event_module will fail to start httpd.service, and give `httpd: Configuration error: No MPM Loaded.`, need replace with mpm_prefork_module
> need to replace mpm_event_module with mpm_prefork_module

- docs/tools-reference/custom-kernels-distros/run-a-distributionsupplied-kernel-with-pvgrub.md
Line 511: When I used  'yum install kernel-x86_64'   the debug version of the kernel was installed.  I changed the hyphen to a dot and the correct non-debug version was installed.  Assuming same for other entries.
> change '-' to '.' in CentOS6 kernel install cmd

- docs/websites/nginx/startssl-wth-latest-nginx-debian-7.md
Disables export ciphers to protect against a [Logjam attack](https://weakdh.org/).
> Disables Export Ciphers

- docs/email/postfix/email-with-postfix-dovecot-and-mysql-on-centos-7.md
Alias database loop error caused by repeated domains in BOTH mydestination and virtual_alias/virtual_mailbox_domains
REF: http://serverfault.com/questions/491601/postfix-do-not-list-domain-example-com-in-both-mydestination-and-virtual-alias
> Fix alias database loop error

- docs/email/postfix/email-with-postfix-dovecot-and-mysql-on-centos-7.md
The format for the location of the SSL cert and key file entries has changed in Dovecot's config file.  I'm not sure which version the change took place in but I'm running version 2.2.10 on Cent OS 7 and had to use the format specified in my change (or Dovecot would fail to respond to pop3 connections).  This is a great guide, thanks.  This was the only "gotcha" I ran into so I wanted to contribute the update.
> Updated SSL cert and key config line entries

- docs/getting-started.md
Using backticks in the name of the zone file is a syntax error
> Change backticks to single quotes in timedatectl command

- docs/databases/mysql/how-to-install-mysql-on-ubuntu-14-04.md
Fixed the error: "You have an error in your SQL syntax;" in the example create user command.
> Fix syntax error in 'create user' command

- docs/security/ssl/how-to-make-a-selfsigned-ssl-certificate.md
As it currently stands the instructions tell you to create certificates and then chmod some unrelated files that probably don't exist.  I changed the chmod command to relate to the files generates, and added some text to explain that example.com should be replaced with the domain in question in both commands.
> Fixing an error and providing explanatory text

- docs/networking/linux-static-ip-configuration.md
Small typo, but makes a big difference. Without the correct suffix here, network no-workie.
> Corrected typo in CENTOS 7 static networking config example

- docs/security/securing-your-server.md
It appears only accepting ICMP traffic matching `-m state --state NEW` stops all incoming connections – I could not even ping the machine with `ping6`. My knowledge of this area is quite weak, but the suggestion on IRC was that Conntrack does not track state, so --state NEW would not match.
This was using Debian 8.2 with the newest Kernel (4.4.0-x86_64-linode63)
> Fix apparent mistake in IPv6 firewall rules

- docs/applications/game-servers/install-steamcmd-for-a-steam-game-server.md
SteamCMD automatically uses the "Steam" folder for its files (logs, workshop items, etc.). Using another folder to extract files in results in duplicate files and unneeded occupied space.
It's better to keep only one folder, for space and order reasons.
I also changed the user home folder in the installation log to match the suggested user name.
> [SteamCMD] Changed installation folder to the standard one

- docs/applications/game-servers/left-4-dead-2-multiplayer-server-installation.md
Changed SteamCMD installation folder to the standard one.
Fixed the steps order.
> [Left 4 Dead 2] Fixed folders and steps order

- docs/platform/longview/longview-app-for-apache.md
The guide does not clearly explain the common troubleshooting scenario wherein an overzealous Apache virtual host configuration can block the ability for Longview Apache to work. I added this in.
> Added a troubleshooting scenario for a bad virtualhost config

- docs/email/postfix/configure-spf-and-dkim-in-postfix-on-debian-8.md
Expand step 2 of rotating keys to include verifying the new key and DNS data before activating the key in Postfix.
Fix a minor naming/numbering error referring to a previous section and step.
> Spfdkim rotate testkey

- docs/networking/using-the-linode-shell-lish.md
While keysview is still a valid command, it is no longer relevant with the LISH gateways, so remove it from the guide.
> LISH: Remove keysview command

- docs/tools-reference/custom-kernels-distros/run-a-distribution-supplied-kernel-with-kvm.md
Grub doesn't look very good on Lish without the GRUB_TERMINAL=serial line as Lish acts as a serial terminal. Line 133 is just a newline trimmed at the end of the file.
> Add line to fix the appearance of Grub in Lish

- docs/security/securing-your-server.md
Fix is no longer neccesary, according to the linked article:
"Since iptables-1.6.0-1 the iptables.service and ip6tables.service refer to the network-pre.target so that the firewall is started before any network is configured. Respective manual configuration changes to achieve this for prior versions (FS#33478) can be dropped."
> Remove "pre-network.conf" tip

- docs/networking/native-ipv6-networking.md
I verified that after requesting /64 pool, the default address is no longer assigned by SLAAC in Debian Jessie. The administrator will need to statically define that address in /etc/network/interface, failing to do that will break IPv6 routing.
> default IPv6 address not assigned by SLAAC when /64 pool requested

- docs/tools-reference/linux-package-management.md
Arch Linux began switching over to .xz in 2010 because its better
https://www.archlinux.org/news/switching-to-xz-compression-for-new-packages/
> changed .gz to .xz

- docs/applications/development/install-gogs-on-debian-8-jessie.md
- docs/networking/native-ipv6-networking.md
- docs/uptime/monitoring/install-nagios-4-on-ubuntu-debian-8.md
- docs/websites/lemp/lemp-server-on-centos-7-with-fastcgi.md
- docs/websites/nginx/nginx-web-server-debian-8.md
Make all systemd configs consistant
Set highlighting to ini since it is the closest language
that has highlighting
Remove spaces between = sign and description
> Fix Systemd Config Highlighting And Spacing

- docs/security/securing-your-server.md
Somebody deserves to be drawn and quartered for this, but I can't tell who, because these problems predate this repo.  **ALWAYS** **ALWAYS** **ALWAYS** use `-v` when doing an `iptables -L`.  The rules are basically useless otherwise.  `-n` is also a good idea, because DNS resolution is slow and can be confusing.
> Fix iptables usage

- docs/platform/kvm-reference.md
@akerl @jessealter Helped me debug a problem with a Xen -> KVM migration and missing this kernel config option prevented the boot.
> CONFIG_BLK_DEV_SD is needed also

- docs/security/gpg-key-for-ssh-authentication.md
- docs/security/index.md
One of the really useful things for my Linode has been the ability to use a GPG key for SSH authentication (+YubiKey), so I made a guide for it.
A question for discussion: Should I have included the sections about GPG smartcards/YubiKeys? I consider them really important, because they're pretty much the primary reason someone would want to use this guide—but I can see other use-cases for this guide which might overtake smartcards in time.
> How to use a GPG key for SSH authentication

- docs/security/gpg-key-for-ssh-authentication.md
The "Contributed by" link at the top of the guide is a malformed link. This should fix it.
> Adds protocol to author's GitHub URL.

- docs/applications/ansible/getting-started-with-ansible.md
Ansible 2.1 reports that using bare variables is deprecated. I updated the code sample with the full variable syntax.
> Update deprecated syntax

- docs/security/using-fail2ban-for-security.md
Without an explicit line for ignoreregex, fail2ban-client reload complains.
Without a port line, fail2ban-client reload fails.
> add missing jail options

- docs/security/using-fail2ban-for-security.md
* do not create a junk file named ``1``
* make ``jail.local`` syntactically valid so that fail2ban will start
> bugfixes for fail2ban config files

- docs/databases/postgresql/securely-manage-remote-postgresql-servers-with-pgadmin-on-macos-x.md
- docs/databases/postgresql/securely-manage-remote-postgresql-servers-with-pgadmin-on-windows.md
pgAdmin 3 is no longer supported. Both guides have been updated to use their respective links to download pgAdmin 4.
I also would consider linking to the root pgAdmin `/download/` page, so the reader can decide for themselves, but that is up to all of you.  Most Windows users will probably be fine on pgAdmin 4 (minimum requirement of Windows 7), but pgAdmin 4 for macOS requires 10.10, and some may not be up to date.
I avoided updating the wording to use 4 throughout until someone else weighs in, but would be happy to update this pull request.
> update pgAdmin links

- docs/security/use-one-time-passwords-for-two-factor-authentication-with-ssh-on-centos-7.md
- docs/security/use-one-time-passwords-for-two-factor-authentication-with-ssh-on-ubuntu-16-04-and-debian-8.md
If SSH isn't using PAM, the SSH client will just disconnect
> Make SSH is using PAM

- docs/websites/cms/install-wordpress-on-ubuntu-16-04.md
Without these instructions, Jetpack installation and use of the Wordpress mobile app are not possible
> Include instructions for PHP extensions like php-xmlrpc

- docs/security/using-fail2ban-for-security.md
This may be stating the obvious, but I believe that the "action" setting
value must be enclosed in brackets, and wrapped in %s. For example:
`%(action_mw)s`
The current instructions don't make this clear, in my opinion.
> Clarified the correct format of the "action" setting.

- docs/applications/containers/how-to-install-docker-and-deploy-a-lamp-stack.md
Error (installation hangs forever) occurs on at least docker 1.11-1.12.1 and ubuntu 16.04.
> Workaround for docker installation bug

- docs/security/using-fail2ban-for-security.md
ERROR  There is no directory /var/run/fail2ban to contain the socket file /var/run/fail2ban/fail2ban.sock.
> for fixing fail2ban start up failure

- docs/applications/containers/how-to-install-docker-and-deploy-a-lamp-stack.md
- docs/applications/containers/node-js-web-server-deployed-within-docker.md
On a recent installation it was noted that while it still gives the warning regarding aufs missing it now uses OverlayFS (overlay2) as the storage driver instead of DeviceMapper.
> Docker seems to use OverlayFS(overlay2) by default now when available.

- docs/email/postfix/configure-spf-and-dkim-in-postfix-on-debian-8.md
when you follow the instructions, the text record has an incorrect hash entry as h=rsa-sha256, modifying it in the record to h=SHA56 fixes the issue.
without this fix, the `opendkim-testkey -d organictrader.com.au -s 201612` test failes with:
```
opendkim-testkey: unknown hash 'rsa-sha256'
```
> generated dkim entry incorrect syntax for sha-256

- docs/networking/dns/previewing-websites-without-dns.md
The command to flush the macOS DNS cache was not updated beyond Yosemite,
and in fact changed back to the old one in 10.10.4.
> Update macOs cache flush command

- docs/web-servers/nginx/configure-nginx-for-optimized-performance.md
It wouldn't make much sense to have higher number of connections than number of opened files (look like a typo).
> fix number of connections

- docs/security/advanced-ssh-server-security.md
Fixed a bug in the formatting that caused the file excerpt in the "Custom Rules Example" to not render properly.
> Formatting correction in Advanced SSH Security guide

- docs/security/firewalls/control-network-traffic-with-iptables.md
The `sed` command to fix the issue with `/etc/modules` file was editing the wrong file.
> Debian 8 upgrade netfilter-persistent fix

- docs/websites/cms/install-odoo-10-on-ubuntu-16-04.md
Link to http://download.gna.org/ no longer works
> Corrected url for wkhtmltopdf download

- docs/tools-reference/tools/manage-processes-with-killall-and-kill.md
See [here](https://www.linode.com/docs/tools-reference/tools/manage-processes-with-killall-and-kill) under section `Finding Running Processes`. The `htop` docs link is broken and leaks ugly text, so I've fixed this.
Thanks for the docs, they're a great resource! :tada:
> Fixed broken htop link in manage-processes-with-killall-and-kill.md

- docs/platform/how-to-use-block-storage-with-your-linode.md
In the screenshots included in the guide we write GiB but the docs say GB. This inconsistency is confusing (and inaccurate).
> Use GiB like Linode Manager does

- docs/web-servers/apache-tips-and-tricks/tuning-your-apache-server.md
As mentioned in the readme, for security reasons this new URL should be used.
> Updated URL to Apache2Buddy script

- docs/networking/ssh/using-gnu-screen-to-manage-persistent-terminal-sessions.md
- docs/web-servers/apache/apache-2-web-server-on-ubuntu-8-04-lts-hardy.md
These were never found via curl or scrapy because it still returned 200. Moreover, a symlink with the same path as an alias would still work because symlinks seem to take precedence with redirection. Removals might not be exhaustive...
> Removed circular alias references

- docs/networking/basic-nfs-configuration-on-debian-7.md
After troubleshooting this with a customer I wanted to share what needed to be done in this case to help others who might be in the same boat.
Following the Debian 7 guide, a user is left on the client with the mount command hanging indefinitely.
> Update NFS Doc to work with Debian 8

- docs/networking/set-up-an-ipv6-tunnel-on-your-linode.md
Fixes typo on the ifcfg-he-ipv6 interface setup for CentOS 7.
> Fix typo on IPV6_DEFAULTDEV

- docs/tools-reference/custom-kernels-distros/install-nixos-on-linode.md
NixOS 17.09 nicknamed "Hummingbird" was released so I went through this guide to ensure that it still worked.
Everything in the guide still worked, but running through it again I found that downloading the installer could use a touch up. I also realized there was a better way to configure grub to get only the configuration file.
These are small changes and the guide is still good, but this will make the user experience a little smoother.
> Update NixOS installation guide for NixOS 17.09

- docs/web-servers/lamp/install-lamp-stack-on-ubuntu-16-04.md
I've added a note not to put space after comma in the command of making the folders public_html and logs. Beginners like me may accidentally put space after the comma, which will cause an error in reloading Apache. With the note, reader are made aware before they bump into an error that would discourage them from continuing the configuration.
> Added Note In Creating Folder public_html and logs

- docs/networking/create-a-socks5-proxy-server-with-shadowsocks-on-ubuntu-and-centos7.md
The "nameserver" option is used inside the ss-server(shadowsocks server) to resolve hostname requested from client,
skipping it may result very slow response from the server.
For example, I got a big improve after set this option: from 3xxxms to 5xxms.
> Add "nameserver" options to config file

- docs/databases/hadoop/install-configure-run-spark-on-top-of-hadoop-yarn-cluster.md
- docs/databases/mysql/standalone-mysql-server.md
- docs/databases/postgresql/fedora-14.md
- docs/development/frameworks/symfony-on-centos-5.md
- docs/email/postfix/postfix-dovecot-and-system-user-accounts-on-debian-6-squeeze.md
- docs/email/postfix/postfix-dovecot-and-system-user-accounts-on-ubuntu-10-04-lucid.md
- docs/email/postfix/postfix-dovecot-and-system-user-accounts-on-ubuntu-10-10-maverick.md
- docs/tools-reference/custom-kernels-distros/run-a-distributionsupplied-kernel-with-pvgrub.md
- docs/tools-reference/tools/limiting-access-with-sftp-jails-on-debian-and-ubuntu.md
- docs/uptime/monitoring/deploy-munin-to-monitor-servers-on-ubuntu-12-04.md
- docs/uptime/monitoring/monitoring-resource-utilization-with-cacti-on-centos-5.md
- docs/uptime/monitoring/monitoring-resource-utilization-with-cacti-on-fedora-12.md
- docs/uptime/monitoring/monitoring-servers-with-munin-on-debian-5-lenny.md
- docs/uptime/monitoring/monitoring-servers-with-munin-on-debian-6-squeeze.md
- docs/uptime/monitoring/monitoring-servers-with-munin-on-fedora-14.md
- docs/uptime/monitoring/monitoring-servers-with-munin-on-ubuntu-8-04-hardy.md
- docs/uptime/monitoring/monitoring-servers-with-munin-on-ubuntu-9-10-karmic.md
- docs/web-servers/apache/apache-2-web-server-on-ubuntu-9-04-jaunty.md
- docs/web-servers/apache/authbased-access-control-with-apache.md
- docs/web-servers/nginx/nginx-and-phpfastcgi-on-ubuntu-9-10-karmic.md
- docs/websites/cms/installing-directadmin-on-debian-6.md
Also edited the Spark guide to match Hugo syntax.
All expired guides now use the original (master branch)
version, with the added expiryDate and (where applicable)
> Added expiryDate to truncated documents.

- docs/web-servers/caddy/install-and-configure-caddy-on-centos-7.md
Caddy is now available via the EPEL repository.  Using that package in these instructions avoids having to perform many of these setup steps manually.  This PR also removes some out of scope instructions that would have needed to be updated to work with using the Caddy package.
> change Caddy instructions to use EPEL package

- docs/networking/diagnostics/diagnosing-network-issues-with-mtr.md
The `-c` parameter is missing from these examples. `-rw50` is not valid mtr syntax.
> Fix typo in "mtr" TCP mode example.

- docs/quick-answers/linux/how-to-use-grep.md
Replaced redundant piping example with `cat`. New examples uses
`tail -f | grep`.
> [UPDATE] How to Use Grep

- docs/applications/remote-desktop/install-vnc-on-ubuntu-16-04.md
- docs/applications/remote-desktop/using-vnc-to-operate-a-desktop-on-ubuntu-12-04.md
Resolve JIRA ticket DOCS-49: https://jira.linode.com/browse/DOCS-49
Probably should expire the older one as they are duplicates.
https://linode.com/docs/applications/remote-desktop/install-vnc-on-ubuntu-16-04/
https://linode.com/docs/applications/remote-desktop/using-vnc-to-operate-a-desktop-on-ubuntu-12-04/
> VNC Server installation reference nonexistent step numbers

- ci/yaml_rules.json
- docs/contribute.md
- docs/find-this-guide-on-github.md
- docs/getting-started.md
- docs/linode-writers-formatting-guide.md
- docs/thankyou.md
- themes/docsmith/layouts/rss.xml
As part of change to Hugo templates, guides with show_on_rss_feed:
false will not be tracked on the RSS feed. This flag was applied
to special guides including formatting guide, contribute topics
list, and Github redirect page.
> Add show_on_rss_feed param to appropriate guides.

- docs/linode-writers-formatting-guide.md
I just added `/` to caution closing tag in the formatting guidelines page.
> Fix formatting guide caution closing tag example

- docs/search.md
Preserve results URL to not break internal tooling from GCSE to lunr.js
Pending update of robots.txt
> Support for GCSE results URL

- docs/tools-reference/linux-users-and-groups.md
The `chmod` command for setuid should be `u+s`, not `o+s`.
> Correct chmod command for setuid bit

- docs/applications/containers/how-to-deploy-nginx-on-a-kubernetes-cluster.md
- `--apiserver-advertise` flag to `kubeadm init` replaced with
`--apiserver-advertise-address`
- Section on `kubeadm token create` removed as it errors out
and does not seem to be necessary
- Replaced Docker installation section with shortcode (instructions
were out of date).
- Fixed indentation discrepancies.
> Kubernetes guide fixes

- docs/databases/postgresql/how-to-install-postgresql-on-ubuntu-16-04.md
> Remove duplicated word in how-to-install-postgresql-on-ubuntu-16-04.md

- docs/tools-reference/custom-kernels-distros/install-alpine-linux-on-your-linode.md
* 0f3cddb - Alpine's grsecurity kernel has changed `vmlinuz-grsec` and `initramfs-grsec` filenames to `vmlinuz-hardened` and `initramfs-hardened`. **As the guide is currently written, GRUB2 will fail to boot Alpine.**
* be60d11 - the default `/dev/sudoers` recommends using the `wheel` group. It's a built-in group in Alpine, so for the sake of simplicity, the guide can be updated to remove the extraneous step to setup a new group.
> Alpine Linux tech fixes

- docs/applications/configuration-management/learn-how-to-install-ansible-and-run-playbooks.md
- docs/uptime/analytics/zipkin-server-configuration-using-docker-and-mysql.md
Used more sensible grouping for table of content headers. Probably more instances of this scattered throughout the library.
More indentation fixes.
> Header changes and more indentation fixes

- docs/networking/dns/using-your-systems-hosts-file.md
- docs/security/firewalls/control-network-traffic-with-iptables.md
- docs/websites/cms/install-odoo-10-on-ubuntu-16-04.md
> Fix redundant wording

- docs/databases/elasticsearch/a-guide-to-elasticsearch-plugins.md
- docs/databases/elasticsearch/install_elasticsearch_centos.md
- docs/databases/elasticsearch/install_elasticsearch_debian_ubuntu.md
@Jskobos 
Copy edit to https://github.com/linode/docs/pull/1368
> [COPY] Elasticsearch plugins guides

- docs/platform/how-to-use-block-storage-with-your-linode.md
- docs/tools-reference/custom-kernels-distros/install-alpine-linux-on-your-linode.md
> [update] Block storage update

- docs/platform/how-to-use-block-storage-with-your-linode.md
"Block Storage Volume" is capitalized and volume should be capitalized when referring to a unit of block storage.
"Data center" is two words.
Use GB instead of GiB
10 GB minimum and 10,000 GB maximum per Volume
Deleted extraneous notes.
> [Update] Block Storage Deployment Changes

- docs/uptime/monitoring/install-icinga2-monitoring-on-debian-9.md
- docs/uptime/monitoring/monitor-remote-hosts-with-icinga.md
The official spelling of the project name is 'Icinga 2'. This PR updates the Icinga 2 installation guide to replace 'Icinga2' with 'Icinga 2'.
> Replace 'Icinga2' with 'Icinga 2'

- docs/security/ssl/create-a-self-signed-tls-certificate.md
- docs/security/ssl/obtain-a-commercially-signed-tls-certificate.md
- docs/tools-reference/tools/manipulate-lists-with-sort-and-uniq.md
- docs/web-servers/nginx/enable-tls-on-nginx-for-https-connections.md
- docs/web-servers/nginx/nginx-installation-and-basic-setup.md
- docs/web-servers/nginx/slightly-more-advanced-configurations-for-nginx.md
https://github.com/linode/docs/pull/1402/
> [COPY] Reorganize nginx

- docs/applications/big-data/how-to-install-and-configure-a-redis-cluster-on-ubuntu-1604.md
- docs/applications/cloud-storage/access-google-drive-linode.md
- docs/applications/containers/how-to-install-docker-and-pull-images-for-container-deployment.md
- docs/applications/remote-desktop/remote-desktop-using-apache-guacamole-on-docker.md
- docs/databases/mysql/how-to-install-mysql-on-centos-6.md
- docs/databases/mysql/how-to-install-mysql-on-debian-7.md
- docs/email/postfix/configure-postfix-to-send-mail-using-gmail-and-google-apps-on-debian-or-ubuntu.md
- docs/quick-answers/linux/how-to-install-configure-and-run-fish.md
- docs/security/getting-started-with-selinux.md
- docs/web-servers/apache-tips-and-tricks/rulebased-access-control-for-apache.md
- docs/web-servers/apache/apache-web-server-debian-8.md
- docs/web-servers/apache/apache-web-server-on-ubuntu-14-04.md
- docs/web-servers/apache/install-and-configure-apache-on-centos-7.md
- docs/websites/ecommerce/how-to-install-prestashop-on-ubuntu-16-04.md
> Update image alt tags and meta descriptions

- docs/security/getting-started-with-selinux.md
Minor fix to image alt tag
@jdkato Does Vale currently support scoping for specific html tags? i.e. `<img src="/docs/assets/selinux/selinux_centos.jpg" alt="Getting Started withj SELinux">`
> Fix incorrect spelling for image meta

- docs/security/authentication/how-to-use-yubikey-for-two-factor-ssh-authentication.md
Previously two versions of the YubiKey authentication file
were used; `/etc/ssh/yubikeys` has been replaced with
`/etc/ssh/authorized_yubikeys` for consistency.
In addition, a reference to rebooting the Linode was replaced
with a command to review the sshd.service.
Minor copy edits also made.
> Fix file path and minor copy fixes

- docs/networking/linux-static-ip-configuration.md
Per comments on Jira ticket DOCS-74
> Explicitly use eth0 for IPV6 on Centos

- docs/applications/media-servers/install-plex-media-server-on-centos-7.md
This solves #1574. Mistakenly typed 'Ubuntu' replaced with 'CentOS'.
> Corrected 'Ubuntu' to 'CentOS' on Plex

- ci/vale/dictionary.txt
- ci/vale/styles/Linode/Terms.yml
- docs/databases/redis/redis-on-ubuntu-10-04-lucid.md
- docs/databases/redis/redis-on-ubuntu-12-04-precise-pangolin.md
- docs/email/postfix/email-with-postfix-dovecot-and-mariadb-on-centos-7.md
- docs/email/postfix/email-with-postfix-dovecot-and-mysql-on-centos-5.md
- docs/email/postfix/email-with-postfix-dovecot-and-mysql-on-centos-6.md
- docs/networking/diagnostics/install-ntopng-for-network-monitoring-on-debian8.md
- docs/networking/nfs/how-to-mount-nfs-shares-on-debian-9.md
- docs/platform/automating-server-builds.md
- docs/platform/linode-backup-service.md
- docs/security/encrypt-data-disk-with-dm-crypt.md
- docs/security/getting-started-with-selinux.md
- docs/security/visualize-server-security-on-centos-7-with-an-elastic-stack-and-wazuh.md
- docs/tools-reference/linux-system-administration-basics.md
- docs/uptime/analytics/google-analytics-for-websites.md
- docs/uptime/analytics/google-analytics-on-wordpress.md
- docs/uptime/monitoring/top-htop-iotop.md
- docs/uptime/reboot-survival-guide.md
- docs/web-servers/apache-tips-and-tricks/tuning-your-apache-server.md
- docs/websites/cms/install-wordpress-using-wp-cli-on-ubuntu-14-04.md
* Removed duplicates
* Remove words with no impact
* Added back ticks to `bgrewriteaof` with single usage
* Instances of incorrectly spelled words from initial commit (`diplays`, `snapsnot`, `iptabes`)
* Establish `everytime` as two words
> Dictionary clean up

- docs/quick-answers/linux/how-to-use-wget.md
Seems like there are still more mixed indentation cases that are not being picked up. Adding a looping wget for speed testing.
> Fix speed test with wget to include multiple trials

- docs/tools-reference/custom-kernels-distros/install-nixos-on-linode.md
NixOS just had their 18.03 release and I went through this guide confirming that everything still works.
I didn't run into any issues, so the content is still fine I would just like to bump the modified date and version mentioned inside so people know this is maintained.
> Update NixOS guide for 18.03

- .travis.yml
Updates Hugo version used in Travis builds to 0.40.2, which provides better support for the .GetPage.Content method we use in our content shortcode.
> Update Hugo version to .40.2 in Travis

- docs/platform/api/getting-started-with-the-linode-api.md
Fix an issue where the Authorization header was incorrectly called Authentication.
> Authentication header => Authorization header in API Getting Started guide

- docs/development/python/introduction-to-pyspark.md
- docs/development/r/how-to-deploy-rshiny-server-on-ubuntu-and-debian.md
Should be fixed since #1728 
Cleaning up old copy/paste workarounds.
> Reuse content shortcode for pyspark and R shiny

- docs/applications/project-management/how-to-install-and-configure-redmine-on-ubuntu-16-04.md
Some users won't notice the path, since it isn't highlighted. Granted, users should read before copy-pasting but when we're catering to new people, that's one less question to deal with.
> Use tilde expansion for installation guides

- docs/platform/how-to-use-block-storage-with-your-linode.md
Addresses DOCS-86 and DOCS-90 in JIRA.
When a BS Volume is resized through the Manager, a series of instructions for expanding the filesystem to fit the new size is displayed. These have been added to the guide.
> Add post-resize mounting instructions for Block Storage Volumes

- docs/security/backups/backing-up-your-data.md
This fixes a small typo (`past` -> `paste`) in the  "backing up your data" doc
> fix small typo in "backing up your data" doc

- docs/platform/billing-and-payments.md
- docs/platform/linode-backup-service.md
Fixed the backups pricing for the 24GB and 300GB high-mem tiers to match what's listed on [linode.com/backups](https://linode.com/backups)
> Fixed backups pricing for 24GB and 300GB high-mem plans

- docs/security/meltdown-and-spectre.md
Linode has just completed the latest round of host reboots which patches Spectre v1 and v2
> Update Meltdown/Spectre doc

- archetypes/content.md
This updates the date formatting string so that it does not generate an error when creating a new doc.
https://discourse.gohugo.io/t/specify-date-format-in-archetype/9015/4
Error:
```
~/.../Linode/docs $ hugo new content/troubleshooting/troubleshooting-failing-ssh-connections.md
ERROR 2018/06/01 08:47:51 Unable to find archetypes directory for theme "docsmith" at "/Users/sjacobs/Code/github/Linode/docs/themes/docsmith/archetypes"
Error: Failed to process archetype file "/Users/sjacobs/Code/github/Linode/docs/archetypes/content.md": template: content:8:19: executing "content" at <.Date.Format>: can't evaluate field Format in type $
tring
```
> fix date formatting in content archetype

- themes/docsmith/layouts/index.html
Removed banner from index.html. Kept spectre_alert.html to be reused in the future when a banner is needed.  Open for discussion.
> Remove spectre banner

- docs/networking/using-the-linode-shell-lish/index.md
When users connect to Lish the SHA256 fingerprints are presented and will be useful to those who want to check.
> Add ECDSA SHA256 fingerprints for the datacenters

- docs/websites/cms/how-to-speed-up-a-wordpress-website/index.md
The Speed Up WordPress guide was not appearing in websites/cms or in the search results, and we think this was because the publish date in the front matter was in the future when this guide was originally pushed to master
> Moved publish and modify date back by one day

- docs/web-servers/lamp/lamp-on-centos-7/index.md
I added a section about FirewallD when reviewing this PR:
https://github.com/linode/docs/pull/1863
I then merged that PR into master. Afterwards, I realized that the FirewallD change I made only included instructions for the runtime firewall ruleset, and not the permanent ruleset. Updating that with this new PR.
> Fixed: adding HTTP to FirewallD's permanent ruleset

- ci/requirements.txt
Added version requirement for Twisted, which is used by Scrapy.  Twisted released update on July 14th, which broke our docs404.py test.
> Add twisted version req

- docs/tools-reference/custom-kernels-distros/install-nixos-on-linode/index.md
`filesystems` results in an error, whereas `fileSystems` works fine.
> Changed filesystems to fileSystems

- docs/security/encryption/use-luks-for-full-disk-encryption/index.md
The official docs recommend a 300mb installer size.
(https://www.debian.org/CD/netinst/)
> Use recommended installer size

- docs/web-servers/lamp/install-lamp-stack-on-ubuntu-18-04/index.md
- docs/websites/cms/install-wordpress-using-wp-cli-on-ubuntu-18-04/index.md
Update draft finished. I'm not really happy with the original title ('Install WordPress Using WP-CLI on Ubuntu 18.04'). Any better ideas?
> [UPDATE] Install WordPress Using WP-CLI on Ubuntu 18.04

- docs/development/java/install-java-on-ubuntu-18-04/index.md
Updated Java installation guide for Ubuntu 16.04 to Ubuntu 18.04.
- Used Java version 10.0.2 and OpenJDK 11
> [NEW] Install Java on Ubuntu 18.04

- docs/applications/containers/how-to-create-a-docker-swarm-manager-and-nodes-on-linode/index.md
It must be `worker`. Otherwise we get a different result from screenshot.
> [Fix] Fixed token retrieval command

- docs/applications/configuration-management/how-to-build-your-infrastructure-using-terraform-and-linode/index.md
Updates 'Create an API Key' step to link to the [Get an Access Token](https://www.linode.com/docs/platform/api/getting-started-with-the-linode-api/#get-an-access-token) section of the [Getting started with the Linode API](https://www.linode.com/docs/platform/api/getting-started-with-the-linode-api) guide (rather than the deprecated [API Key](https://www.linode.com/docs/platform/api/api-key/) guide).
> [UPDATE] How to build your infrastructure using Terraform & Linode

- ci/vale/dictionary.txt
- docs/quick-answers/linux/how-to-navigate-less-shortguide/index.md
- docs/quick-answers/linux/how-to-use-journalctl/index.md
- docs/quick-answers/linux/how-to-use-less/index.md
Two new guides:
- How to Use Journalctl
- How to Use Less
One new shortguide:
how-to-navigate-less-shortguide
Shortguide is a table of the keyboard commands used to navigate `less`. Table is embedded in the Journalctl and Less guides
> [NEW] How to Use Journalctl, How to Use Less

- docs/applications/configuration-management/configure-and-use-salt-cloud-and-cloud-maps-to-provision-systems/index.md
The config examples should be two spaces instead of a tab and `driver` in `/etc/salt/cloud.providers.d/linode.conf` is intended too far and will cause a block mapping error for salt-cloud commands:
```
a block mapping
in "/etc/salt/cloud.providers.d/linode.conf", line 2, column 5
expected <block end>, but found '<block mapping start>'
in "/etc/salt/cloud.providers.d/linode.conf", line 4, column 7
[ERROR   ] Error parsing configuration file: /etc/salt/cloud.providers.d/linode.conf - while parsing a block mapping
in "/etc/salt/cloud.providers.d/linode.conf", line 2, column 5
expected <block end>, but found '<block mapping start>'
in "/etc/salt/cloud.providers.d/linode.conf", line 4, column 7
[ERROR   ] Profile test_profile is not defined
```
> Fix YAML spacing in Salt-Cloud doc

- docs/getting-started/index.md
As per the website https://tools.ietf.org/html/rfc5737 pointed out in #2003, there are standard IP addresses that should be used when providing example IP addresses in documentation.
> The blocks 192.0.2.0/24 (TEST-NET-1), 198.51.100.0/24 (TEST-NET-2),
>    and 203.0.113.0/24 (TEST-NET-3) are provided for use in
>    documentation."
> #2003 Documentation isn't using standard example IP addresses

- docs/security/ssl/obtain-a-commercially-signed-tls-certificate/index.md
Changed the LetsEncrypt link from pointing to the LetsEncrypt homepage, to pointing to Linode's guide on Let's Encrypt instead
> changed LetsEncrypt link to point to Linode's guide

- docs/security/ssl/obtain-a-commercially-signed-tls-certificate/index.md
> Revert "changed LetsEncrypt link to point to Linode's guide"

- docs/applications/configuration-management/configure-and-use-salt-cloud-and-cloud-maps-to-provision-systems/index.md
[UPDATE] salt cloud v3 API note and curl test
[UPDATE] salt cloud use size Nanode 1GB not Linode 1024
[UPDATE] salt cloud modified date
> [UPDATE] salt cloud v3 API note and size names

- docs/security/securing-your-server/index.md
sshd should be used instead of ssh in centos (I don't know about other distros
> sshd service restart - error

- docs/applications/containers/deploy-a-flask-application-with-dokku/index.md
Instructed reader that CentOS 7 is supported experimentally and that they should checkout the official documentation.
> [Update] Deploy a Flask Application with Dokku

- docs/tools-reference/custom-kernels-distros/install-nixos-on-linode/index.md
Updating this guide for NixOS's 18.09 release. I tested it to confirm it still works and try to reproduce the `copyKernels` issue mentioned in #1688.
I didn't run into any issues, so the content is still fine I would just like to bump the modified date and version mentioned inside so people know this is maintained.
> Update NixOS guide for 18.09

- docs/applications/configuration-management/configure-apache-with-salt-stack/index.md
This guide demonstrates how to configure Apache with Salt on Ubuntu 18.04, CentOS 7 and Debian 9.
> [New] Configure Apache with SaltStack

- docs/databases/postgresql/how-to-back-up-your-postgresql-database/index.md
Fixing Postgres command. the `-1` does not exist.
> [Fix] Postgres command

- ci/yaml_rules.json
- docs/platform/update-kernel/index.md
- docs/quick-answers/linux-essentials/what-is-systemd/index.md
- docs/security/meltdown-and-spectre/index.md
This PR adds new `promo_code` and `promo_code_amount` YAML tags to the ci tests `yaml_rules.json`. It also updates any existing guides to use `promo_default` instead of `promo`.
This PR corresponds to hercules PR: https://github.com/linode/hercules/pull/107
Automated replacement of `promo` YAML tags was done with this python script: [rename.py](https://gist.github.com/leslitagordita/b3bd580fd2751298d827f6ae38bc64d2)
> Custom promo code

- docs/applications/configuration-management/test-kitchen-shortguide/index.md
A small shortguide that reads: 
To try this guide out locally, read the [Test Salt States Locally with KitchenSalt](/docs/applications/configuration-management/test-salt-locally-with-kitchen-salt/) guide and create a local testing environment.
> [New] KitchenSalt Shortguide

- themes/docsmith/layouts/_default/single.html
This theme rebuild PR corresponds to https://github.com/linode/hercules/pull/109.
When testing this theme rebuild: 
- View /docs/security/meltdown-and-spectre/ - observe that no promo code or share button appear.
- Update any guide's front matter with the following YAML: promo_code_default: false, promo_code: 'SALT50' and promo_code_amount: '50'. Observe that a promo banner appears with the defined text.
- View any guide to ensure that default promo code 10 banner appears as expected.
> Rebuild theme for promo fix

- docs/platform/longview/longview/index.md
The API key is not shown at the welcome screen on the longview page. This closes out Docs-146 in Jira.
> [UPDATE] LongView Guide

- docs/platform/block-storage/how-to-use-block-storage-with-your-linode-new-manager/index.md
Responding to issue 2139. If you detach a blockstorage volume without removing this line from your config file your Linode will not boot.
> [Update] How to Use Block Storage with your Linode

- docs/applications/configuration-management/create-terraform-module/index.md
Created after rebasing commits from https://github.com/linode/docs/pull/2160
Original comments from that PR:
> This guide walks you through the steps to create a Linode StackScripts module that provides a reusable Terraform configuration that deploys a Linode instance from a StackScript you will create.
> [NEW] Create a Terraform Module

- ci/vale/dictionary.txt
- docs/applications/configuration-management/introduction-to-hcl/index.md
Created after rebasing commits from https://github.com/linode/docs/pull/2158
Original comments from that PR:
> Provide an introduction to some commonly used HCL terminology.
> [NEW] Introduction to HashiCorp Configuration Language (HCL)

- docs/databases/mysql/configure-master-master-mysql-database-replication/index.md
This is a small update that brings support for Ubuntu 18.04 and Debian 9.
> [Update] Configure Master-Master MySQL Database Replication

- ci/yaml_rules.json
- docs/concentrations/_index.md
- docs/concentrations/scientific-computing-and-big-data/_index.md
- docs/concentrations/scripting-automation-and-build-tools/_index.md
- docs/concentrations/web-applications/_index.md
- docs/development/clojure-deployment-with-immutant-and-wildfly-on-ubuntu-14-04/index.md
- docs/development/frameworks/apache-tomcat-on-ubuntu-16-04/index.md
- docs/development/frameworks/yesod-nginx-mysql-on-debian-7-wheezy/index.md
- docs/development/go/getting-started-with-go-packages/index.md
- docs/development/java/how-to-deploy-spring-boot-applications-nginx-ubuntu-16-04/index.md
- docs/development/java/java-development-wildfly-centos-7/index.md
- docs/development/javascript/deploy-a-react-app-on-linode/index.md
- docs/development/julia/why-learn-julia/index.md
- docs/development/nodejs/how-to-install-nodejs-and-nginx-on-debian/index.md
- docs/development/nodejs/use-nightmarejs-to-automate-headless-browsing/index.md
- docs/development/python/introduction-to-pyspark/index.md
- docs/development/python/string-manipulation-python-3/index.md
- docs/development/python/task-queue-celery-rabbitmq/index.md
- docs/development/python/use-scrapy-to-extract-data-from-html-tags/index.md
- docs/development/r/how-to-deploy-rshiny-server-on-ubuntu-and-debian/index.md
- docs/development/r/how-to-deploy-rstudio-server-using-an-nginx-reverse-proxy/index.md
- docs/development/r/how-to-install-r-on-ubuntu-and-debian/index.md
- docs/development/ror/ruby-on-rails-apache-debian-8/index.md
- docs/development/ror/ruby-on-rails-apache-debian/index.md
- docs/development/ror/ruby-on-rails-nginx-debian/index.md
- docs/development/ror/ruby-on-rails-with-nginx-on-debian-7-wheezy/index.md
- docs/development/ror/use-unicorn-and-nginx-on-ubuntu-14-04/index.md
Per the [Development Housekeeping doc](https://docs.google.com/spreadsheets/d/1YK_caIoi3IZ6gYdlccT71LtfpH8dIAkLldIW2Yg7Iko/edit#gid=1022191634), I applied the concentrations taxonomy to the designated guides.
A way to test this would be to pull down the [Hercules PR that introduces these taxonomies](https://github.com/linode/hercules/pull/108) and navigate to `/docs/concentrations` and compare the listed taxonomy terms to the housekeeping doc.
> Apply Concentrations Taxonomy

- docs/web-servers/nginx/how-to-configure-nginx/index.md
https://github.com/linode/docs/issues/2181
> How to Configure NGINX, fix numbering issue.

- docs/applications/configuration-management/import-existing-infrastructure-to-terraform/index.md
This guide goes over the steps necessary to import existing Linodes, Domains, Volumes and NodeBalancers to Terraform.
This PR rebases [original PR 2137](https://github.com/linode/docs/pull/2137) submitted by @andystevensname to pull in latest changes from the `develop` branch.
> [New] Terraform infra import

- docs/security/ssl/install-lets-encrypt-to-create-ssl-certificates/index.md
This update changes the note that said that Let's Encrypt doesn't support wildcard certificates to reflect that they now do support them.
This is in response to issue #1932.
> [Update] Install Let's Encrypt to Create SSL Certificates

- docs/applications/configuration-management/how-to-build-your-infrastructure-using-terraform-and-linode/index.md
Added note about Homebrew at the top of the installation section for anyone using macOS. This is in response to [issue 2135](https://github.com/linode/docs/issues/2135).
> [Update] Use Terraform to Provision Linode Environments

- docs/development/nodejs/install-nodejs-nodesource/index.md
NPM is no longer installed alongside Node.js, so it was added to to the install list. This is in response to issue #1979.
> [Update] Install Node.js Shortguide

- docs/web-servers/caddy/compile-caddy-from-source/index.md
This PR was created from original PR https://github.com/linode/docs/pull/2161 submitted by @theel0ja. It corrects the directory path to build Caddy from source and adds a step to view your Go installation's `$GOPATH`.
> [Update] How To Build Caddy From Source

- docs/platform/longview/longview-app-for-apache/index.md
Update Apache access control syntax to version 2.4 and other small copy edits.
> [Update] Longview App for Apache

- docs/security/ssl/install-lets-encrypt-to-create-ssl-certificates/index.md
This PR deprecates the guide and links to the Certbot guide.
> [Update] Deprecate Let's Encrypt guide.

- docs/applications/configuration-management/automate-a-static-site-deployment-with-salt/index.md
- docs/applications/configuration-management/beginners-guide-to-salt/index.md
- docs/applications/configuration-management/configure-and-use-salt-cloud-and-cloud-maps-to-provision-systems/index.md
- docs/applications/configuration-management/configure-and-use-salt-ssh/index.md
- docs/applications/configuration-management/configure-apache-with-salt-stack/index.md
- docs/applications/configuration-management/create-a-salt-execution-module/index.md
- docs/applications/configuration-management/getting-started-with-salt-basic-installation-and-setup/index.md
- docs/applications/configuration-management/introduction-to-jinja-templates-for-salt/index.md
- docs/applications/configuration-management/monitoring-salt-minions-with-beacons/index.md
- docs/applications/configuration-management/salt-command-line-reference/index.md
- docs/applications/configuration-management/secrets-management-with-salt/index.md
- docs/applications/configuration-management/test-salt-locally-with-kitchen-salt/index.md
- docs/applications/configuration-management/use-and-modify-official-saltstack-formulas/index.md
- docs/applications/configuration-management/use-salt-states-to-configure-a-lamp-stack-on-a-minion/index.md
- docs/applications/configuration-management/use-salt-states-to-create-lamp-stack-and-fail2ban-across-salt-minions/index.md
- docs/applications/media-servers/install-plex-media-server-with-salt/index.md
Applying the $50 'Salt50' promo code to all Salt guides. 16 Salt guides were found and modified:
```
docs git:(develop) find docs | grep index.md | egrep -i salt
docs/applications/media-servers/install-plex-media-server-with-salt/index.md
docs/applications/configuration-management/introduction-to-jinja-templates-for-salt/index.md
docs/applications/configuration-management/test-salt-locally-with-kitchen-salt/index.md
docs/applications/configuration-management/monitoring-salt-minions-with-beacons/index.md
docs/applications/configuration-management/configure-apache-with-salt-stack/index.md
docs/applications/configuration-management/automate-a-static-site-deployment-with-salt/index.md
docs/applications/configuration-management/configure-and-use-salt-ssh/index.md …
```
> Apply Salt50 promo code to Salt guides

- docs/platform/tokyo2-migration/index.md
When the migrations from Tokyo 1 to Tokyo 2 are scheduled, Linode will also reserve Tokyo 2 IP addresses for users' Tokyo 1 Linodes in advance of the migrations. These reserved IPs will be communicated to users in a support ticket to help them in planning their migrations. This guide update includes an explanation of this feature and how to take advantage of it.
As an added wrinkle, the dashboard for Tokyo 1 Linodes will show an early migration button *before* the official migration schedule is generated and sent to users, and users will be able to use this button to migrate to Tokyo 2. If a user migrates with this button before the migration schedule is set, then they will not have a Tokyo 2 IP reserved in advance for them; the reserved IPs are only provided when the migration schedule …
> [UPDATE] Migrating from Tokyo 1 to Tokyo 2

- docs/networking/an-overview-of-ipv6-on-linode/index.md
Replacing a [broken link](http://www.ipv6ve.info/project-definition/ipv6-subnet-cheat-sheet-and-ipv6-cheat-sheet-reference) to an 'IPv6 cheat sheet' in the More Information section.
Resolves #2208
> [UPDATE] An Overview of IPv6 on Linode

- docs/web-servers/lamp/lamp-on-debian-8-jessie/index.md
We received a request in DOCS-151 to update this guide to use a newer version of PHP than PHP5, which is EOL'd:
http://php.net/supported-versions.php
This update installs PHP 7.3 via the sury.org repository.
> [UPDATE] LAMP on Debian 8 (Jessie)

- docs/web-servers/apache-tips-and-tricks/configure-modsecurity-on-apache/index.md
This is in regards to issue #2121 
Split the Ubuntu/Debian install section into two separate sections as Ubuntu has the Modsecurity package named differently. Checked against Ubuntu 18.04 and Debian 9.
> [Update] How to Configure ModSecurity on Apache

- docs/platform/block-storage/boot-from-block-storage-volume/index.md
Update to make it more clear about appropriate sizing of the Block Storage Volume, and a callout of the Rescue and Rebuild guide section on booting into Rescue Mode.
This is in regards to issue #1962.
> [Update] Boot a Linode from a Block Storage Volume

- docs/applications/configuration-management/automate-a-static-site-deployment-with-salt/index.md
- docs/applications/configuration-management/beginners-guide-to-salt/index.md
- docs/applications/configuration-management/configure-and-use-salt-cloud-and-cloud-maps-to-provision-systems/index.md
- docs/applications/configuration-management/configure-and-use-salt-ssh/index.md
- docs/applications/configuration-management/configure-apache-with-salt-stack/index.md
- docs/applications/configuration-management/create-a-salt-execution-module/index.md
- docs/applications/configuration-management/getting-started-with-salt-basic-installation-and-setup/index.md
- docs/applications/configuration-management/introduction-to-jinja-templates-for-salt/index.md
- docs/applications/configuration-management/monitoring-salt-minions-with-beacons/index.md
- docs/applications/configuration-management/salt-command-line-reference/index.md
- docs/applications/configuration-management/secrets-management-with-salt/index.md
- docs/applications/configuration-management/test-salt-locally-with-kitchen-salt/index.md
- docs/applications/configuration-management/use-and-modify-official-saltstack-formulas/index.md
- docs/applications/configuration-management/use-salt-states-to-configure-a-lamp-stack-on-a-minion/index.md
- docs/applications/configuration-management/use-salt-states-to-create-lamp-stack-and-fail2ban-across-salt-minions/index.md
- docs/applications/media-servers/install-plex-media-server-with-salt/index.md
Guide updates for second half of December and first half of January. This release includes fixes for several GitHub issues and internal requests.
> [RELEASE CANDIDATE] RC-0.4.2

- docs/databases/mysql/how-to-optimize-mysql-performance-using-mysqltuner/index.md
This PR updates the installation steps for the MySQLTuner script and adds minor copy changes.
> [Update] How to Optimize MySQL Performance Using MySQLTuner

- docs/databases/mysql/how-to-optimize-mysql-performance-using-mysqltuner/index.md
- docs/platform/manager/keep-your-linode-account-safe/index.md
- docs/security/linode-manager-security-controls-new-manager/index.md
Making a release to incorporate changes for DOCS-152.
> [Release Candidate] v0.4.3

- docs/tools-reference/custom-kernels-distros/install-freebsd-on-linode/index.md
- Adds language to clarify that the installation _must_ be completed with Glish
- Updates the link to point to the latest FreeBSD release (12.0, which works perfectly with the rest of this doc)
> Updates to the FreeBSD guide

- docs/platform/disk-images/disk-images-and-configuration-profiles/index.md
Numbering was off in some sections due to images not being indented. Changed to automatic markdown numbering while I was there.
> [Fix] Disks and Configuration Profiles

- docs/web-servers/nginx/build-nginx-with-pagespeed-from-source/index.md
Added two notes related to compiling from source. PageSpeed still needs to be compiled from source. There is still no support yet to install the dynamic module using a package manager on an existing NGINX installation.
> [Update] Build NGINX with PageSpeed From Source

- docs/applications/configuration-management/install-a-chef-server-workstation-on-ubuntu-18-04/index.md
This guide has been updated with new Chef commands, installation steps, and clarifications to existing steps. A copy edit was also applied. Original PR was https://github.com/linode/docs/pull/2254. This one was submitted to rebase on develop.
> [Update] Install a Chef Server Workstation on Ubuntu 18.04

- ci/vale/dictionary.txt
- docs/applications/containers/how-to-deploy-nginx-on-a-kubernetes-cluster/index.md
- docs/applications/containers/manage-a-docker-cluster-with-kubernetes/index.md
This update adds iptables information to the How to Install, Configure, and Deploy NGINX on a Kubernetes Cluster guide. I have also added notes to let users know that K8s Linode CLI is
available.
This PR fills the gap of not having any mention of iptables in our Kubernetes guides. In an upcoming sprint we will be adding new information related to K8s Linode CLI, Linode Kubernetes Terraform module, CSI and CCM, and general Kubernetes best practices and guidance on topics, like iptables.
> [Update] How to Install, Configure, and Deploy NGINX on a Kubernetes Cluster

- docs/networking/dns/common-dns-configurations/index.md
- docs/networking/dns/using-your-systems-hosts-file/index.md
- docs/platform/disk-images/disk-images-and-configuration-profiles/index.md
- docs/platform/disk-images/linode-backup-service/index.md
- docs/platform/disk-images/resizing-a-linode/index.md
Added new keywords based on feedback from Algolia.
> Added Keywords based on Algolia

- docs/applications/configuration-management/automatically-configure-servers-with-ansible-and-playbooks/index.md
This guide erroneously mentioned installing Apache, when it instructs the user to install NGINX. Both mentions of Apache were changed to NGINX.
> [Update] Automatically Configure Servers with Ansible and Playbooks

- docs/email/postfix/postfix-smtp-debian7/index.md
This guide was written for Debian 7, but it was tested and works on Debian 9. Mentions of Debian 7 were removed from the guide, the date was updated, and a small mention of needing to install mailutils to use the mail command.
> [Update] Configure Postfix to Send Mail Using an External SMTP Server

- docs/databases/postgresql/how-to-back-up-your-postgresql-database/index.md
> Remove Note about flag in Postgres guide.

- docs/networking/vpn/set-up-a-hardened-openvpn-server/index.md
This PR adds a note about network interface names.
> [Fix] Set up a Hardened OpenVPN Server on Debian 9

- docs/game-servers/how-to-set-up-minecraft-server-on-ubuntu-or-debian/index.md
Updated guide to denote that it works with Debian 9 and Ubuntu 18.04. Also changed a mention of Minecraft 1.12 to 1.13.
> [Update] How to Set Up a Minecraft Server on Ubuntu or Debian

- docs/applications/voip/install-asterisk-on-centos-7/index.md
Commented out section on DAHDI and updated Asterisk from 16.0.0 to 16.1.1
> [UPDATE] How to Install Asterisk on CentOS 7

- config.toml
RSS limit has been increased to 30 entries. Corresponding Hercules PR: https://github.com/linode/hercules/pull/123
> Increase RSS limit: theme rebuild

- docs/networking/diagnostics/diagnosing-network-issues-with-mtr/index.md
TCP MTR tests should be used sparingly, corrected language indicating they're reliable when they are in fact not. Also expanded flags in this section to their long-form for easier grokking.
> Clarifying Advanced MTR TCP section

- docs/platform/manager/using-the-linode-shell-lish/index.md
Fingerprints for Lish boxes are being updated, and Systems has requested a fast update to the
Using the Linode Shell (Lish) guide. This Hotfix merges those changes into master.
> [Hotfix] v0.6.4

- docs/platform/manager/using-the-linode-shell-lish/index.md
Fingerprints for Lish boxes are being updated, and Systems has requested a fast update to the 
Using the Linode Shell (Lish) guide. This Hotfix merges those changes into develop.
> [Hotfix] v0.6.4 (merge into develop)

- docs/applications/remote-desktop/run-graphic-software-on-your-linode-with-xforwarding-on-ubuntu-12-04/index.md
`$ hugo server -D`
`Building sites … ERROR 2019/02/18 16:13:04 Alias "applications/remote-desktop./running-graphic-software-on-your-linode-with-xforwarding-on-ubuntu-12-04" contains component with a trailing space or period, proble matic on Windows`
`Total in 565 ms`
`Error: Error building site: Cannot create "applications/remote-desktop./running-graphic-software-on-your-linode-with-xforwarding-on-ubuntu-12-04": Windows filename restriction`
> [Fix] Remove period from alias

- ci/vale/dictionary.txt
- docs/applications/configuration-management/create-a-nodebalancer-with-terraform/index.md
- docs/getting-started-new-manager/index.md
- docs/platform/api/getting-started-with-the-linode-api-new-manager/index.md
- docs/platform/billing-and-support/billing-and-payments-new-manager/index.md
- docs/platform/billing-and-support/support-new-manager/index.md
- docs/platform/block-storage/how-to-use-block-storage-with-your-linode-new-manager/index.md
- docs/platform/disk-images/linode-backup-service-new-manager/index.md
- docs/platform/disk-images/linode-images-new-manager/index.md
- docs/platform/manager/accounts-and-passwords-new-manager/index.md
- docs/platform/manager/dns-manager-new-manager/index.md
- docs/platform/network-helper-new-manager/index.md
- docs/platform/nodebalancer/getting-started-with-nodebalancers-new-manager/index.md
- docs/platform/nodebalancer/nodebalancer-reference-guide-new-manager/index.md
- docs/platform/stackscripts-new-manager/index.md
- docs/quick-answers/linode-platform/reset-the-root-password-on-your-linode-new-manager/index.md
- docs/quick-answers/linode-platform/resize-a-linode-disk-new-manager/index.md
- docs/security/linode-manager-security-controls-new-manager/index.md
- docs/uptime/monitoring-and-maintaining-your-server-new-manager/index.md
Update 15 Cloud Manager guides to incorporate the style guide changes we have made.
```
find ~/Documents/linode/docs/docs -type d -name "*new-manager" -print
/Users/astevens/Documents/linode/docs/docs/quick-answers/linode-platform/reset-the-root-password-on-your-linode-new-manager
/Users/astevens/Documents/linode/docs/docs/quick-answers/linode-platform/resize-a-linode-disk-new-manager
/Users/astevens/Documents/linode/docs/docs/security/linode-manager-security-controls-new-manager
/Users/astevens/Documents/linode/docs/docs/platform/block-storage/how-to-use-block-storage-with-your-linode-new-manager
/Users/astevens/Documents/linode/docs/docs/platform/manager/dns-manager-new-manager
/Users/astevens/Documents/linode/docs/docs/platform/manager/accounts-and-passwords-new-manager …
```
> [Update] Update Cloud Manager Guides to Reflect Style Guide Changes

- docs/applications/project-management/how-to-create-a-private-python-package-repository/index.md
Added missing commas resulting in a syntax error when executing `setup.py`.
Article - https://www.linode.com/docs/applications/project-management/how-to-create-a-private-python-package-repository/
> [How to Create a Private Python Package Repository] setup.py Syntax Fix

- docs/platform/one-click/deploying-drupal-with-one-click-apps/index.md
Some extra updated to the drupal one-click guide:
- Updated table of Linode instance configuration options. Will also be updating all other open one-click PRs accordingly,.
- Updated Getting Started after Deployment section
- Other copy edits
> [Update] Deploy Drupal with One-Click Apps

- docs/platform/api/using-the-linode-cli/index.md
We don't really refer to it as "beta Linode Manager" anywhere else, so edited for consistency.
> Cloud Manager isn't really in Beta anymore

- docs/tools-reference/custom-kernels-distros/install-nixos-on-linode/index.md
Updating this guide for NixOS's 19.03 release. I tested it to confirm it still works and that the guide's direction are still valid using the shiny new Linode Manager (which looks really nice and is a joy to use).
I didn't run into any issues as most of the direction on how to do things in the Linode Manager were hyperlinked to other guides that have been updated. So the content is still fine I would just like to bump the modified date and version mentioned inside so people know this is maintained.
> Update NixOS guide for 19.03

- docs/getting-started/index.md
The text removed is redundant with the following step, which has a more complete description of setting the root password.
> Remove redundant step about setting password

- docs/platform/block-storage/how-to-use-block-storage-with-your-linode/index.md
https://jira.linode.com/browse/DOCS-171
> Added e2fsck -f step

- docs/platform/api/getting-started-with-the-linode-api-classic-manager/index.md
- docs/platform/api/getting-started-with-the-linode-api/index.md
Update Cloud and Classic versions of the guide to correct links to the API documentation.
> [Update] Getting Started with the Linode API

- docs/web-servers/lemp/how-to-install-a-lemp-server-on-ubuntu-18-04/index.md
A Disqus comment suggested we bold the mention of substituting index.html for index.php for WordPress installs to make it more apparent.
> [Update] How to Install a LEMP Server on Ubuntu 18.04

- docs/security/upgrading/upgrade-to-ubuntu-18-04/index.md
Removed `-d` flag from `do-release-upgrade` command and explanation.
> [Update] How to Upgrade to Ubuntu 18.04 LTS

- docs/platform/block-storage/how-to-use-block-storage-with-your-linode/index.md
Added note with info on optional flags for volume /etc/fstab entry
> [Update] Added note for additional /etc/fstab flags

- docs/platform/disk-images/linode-images/index.md
Added a couple words about what some of the limitations are when creating disk images so folks who are running custom deployments or partition schemes know they will have to create an image manually.
> [update] Changes to Disk Images Limitations

- docs/databases/mysql/use-mysqldump-to-back-up-mysql-or-mariadb/index.md
From a Disqus comment. Add an escape character to the cron job.
> [Update] Use mysqldump to back up mysql or mariadb

- docs/game-servers/install-steamcmd-for-a-steam-game-server/index.md
- docs/game-servers/launch-a-counter-strike-global-offensive-server-on-ubuntu-14-04/index.md
- docs/game-servers/launch-a-counter-strike-global-offensive-server-on-ubuntu-18-04/index.md
Updated these two guides:
1. Install SteamCMD for a Steam Game Server
`/docs/game-servers/install-steamcmd-for-a-steam-game-server/`
Updated in place.
1. Launch a Counter Strike: Global Offensive (CS:GO) server on Ubuntu 14.04
`/docs/game-servers/launch-a-counter-strike-global-offensive-server-on-ubuntu-14-04/`
Created a new Ubuntu 18.04 guide at `/docs/game-servers/launch-a-counter-strike-global-offensive-server-on-ubuntu-18-04/` and set a deprecated link from the old guide.
The SteamCMD guide had some incorrect firewall rules. Here's what the output from netstat was when running the CS:GO game server:
```
sudo netstat -plntu
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 …
```
> [UPDATE] SteamCMD and CSGO guides

- docs/web-servers/nginx/install-nginx-ubuntu/index.md
> [Update] Install NGINX on Ubuntu 18.04

- docs/development/version-control/introduction-to-version-control/index.md
> [Update] Introduction to Version Control

- ci/vale/dictionary.txt
- docs/applications/containers/deploy-static-site-with-kubernetes/index.md
- New guide that shows you how to package a Hugo static site in a Docker container image, host the image on Docker Hub, and deploy the container image on a Kubernetes cluster running on Linode.
> [Draft] Create and Deploy a Docker Container Image to a Kubernetes Cluster

- docs/development/java/install-java-on-ubuntu-16-04/index.md
Updating to instruct to install OpenJDK 8 instead of OracleJDK 8 which is no longer available via PPA due to licensing changes. CT-372
> [Update] Install Java for Ubuntu 16.04

- docs/applications/containers/beginners-guide-to-LXD/index.md
The `lxc` CLI command to manage LXD system containers can be run without `sudo`, and it is recommended to run without `sudo`. 
To do that, you need to add the non-root user into the `lxd` Unix group.
This patch avoids the `sudo` command with `lxc` commands, and also adds some extra explanation when you add the non-root account to the `lxd` Unix group (which then makes `sudo` superfluous).
> Suggestion: Do not use sudo with lxc commands

- docs/quick-answers/linux/start-service-at-boot/index.md
Added step to move service file to /etc/systemd/system dir
CT-378
> [Update] Use systemd to Start a Linux Service at Boot

- docs/applications/containers/install-docker-ce/index.md
Added note for Ubuntu 19.04 to pull from edge/test repo 
CT-384
> [Update] How to Deploy Microservices with Docker

- docs/applications/containers/how-to-deploy-kubernetes-on-linode-with-rancher-2-2/completed-cluster-config.yml
- docs/applications/containers/how-to-deploy-kubernetes-on-linode-with-rancher-2-2/index.md
Leaving etcd unedited in deployment YAML
> [Update] How to Deploy Kubernetes on Linode with Rancher 2.2

- docs/platform/manager/using-the-linode-shell-lish/index.md
The fingerprints were correct; this PR adds a newline to the end of the file.
> [update] Lish guide refers to Toronto as Tokyo 2 in places

- docs/platform/manager/dns-manager/index.md
this is simply to make explicit that the linode nameservers don't support dnssec and that it will break name resolution if they enable it at the registrar.
> [update] adds dnssec section

- docs/platform/manager/using-the-linode-shell-lish/index.md
> [Hotfix] v0.16.4

- docs/platform/disk-images/copying-a-disk-image-over-ssh/index.md
Adding a note that directs readers to other guides if they
prefer to do a file-level copy instead of block-level
From feedback on Disqus:
https://linode.com/docs/platform/disk-images/copying-a-disk-image-over-ssh/#comment-4508871909
> [Update] Copy a Disk Over SSH

- docs/platform/object-storage/host-static-site-object-storage/index.md
- docs/platform/object-storage/how-to-use-object-storage/index.md
Clearly state that object storage access is free.
> [update] Object storage guides

- docs/security/data-portability/download-files-from-your-linode-shortguide/index.md
> [Update] Download files from our Linode shortguide

- docs/platform/api/getting-started-with-the-linode-api/index.md
updated the link to: https://developers.linode.com/api/v4/
> Fixed a 404 for https://developers.linode.com/api/v4/introduction

- docs/databases/hadoop/how-to-install-and-set-up-hadoop-cluster/index.md
Updated guide for Hadoop 3.1.2
CT-472
> [Update] How to Install and Set Up a 3-Node Hadoop Cluster

- docs/applications/configuration-management/how-to-build-your-infrastructure-using-terraform-and-linode/index.md
- docs/applications/containers/how-to-deploy-kubernetes-on-linode-with-k8s-alpha-cli/index.md
- Terraform's Linode Provider now requires Terraform version 12.0+
> [Update ] Add note about Terraform version compatibility.

- docs/databases/mongodb/build-database-clusters-with-mongodb/index.md
- docs/databases/mongodb/create-a-mongodb-replica-set/index.md
- docs/databases/mongodb/install-mongodb-on-centos-7/index.md
- docs/databases/mongodb/install-mongodb-on-ubuntu-16-04/index.md
Fixes: https://github.com/linode/docs/issues/2581
Updated all references of MangoDB 3.2 to 4.0 and validated the commands against the official MangoDB documents.
> Updated the guides to reflect 4.0 version of MangoDB

- docs/applications/configuration-management/beginners-guide-to-terraform/index.md
- docs/applications/configuration-management/create-a-nodebalancer-with-terraform/index.md
- docs/applications/configuration-management/create-terraform-module/index.md
- docs/applications/configuration-management/deploy-a-wordpress-site-using-terraform-and-linode-stackscripts/index.md
- docs/applications/configuration-management/how-to-build-your-infrastructure-using-terraform-and-linode/index.md
- docs/applications/configuration-management/import-existing-infrastructure-to-terraform/index.md
- docs/applications/configuration-management/introduction-to-hcl/index.md
- docs/applications/configuration-management/secrets-management-with-terraform/index.md
* The Terraform Linode Provider has been updated to require Terraform version 0.12+ 
* This PR adds a note to all guides w/ general version upgrade information.
* These guides will be updated to conform with Terraform's new syntax in the near future.
> [Update] Update all Terraform guide w/ version compatibility info

- docs/platform/object-storage/how-to-use-object-storage/index.md
added CLI back in, added note about bucket label rules.
CT-617 (Add CLI back)
CT-585 (Add Bucket Label rules)
Bucket labels need to be unique within the same cluster, including buckets on other users’ Linode accounts. If the label you enter is already in use, you will have to choose a different label. Additionally, bucket labels have the following rules:
•  Cannot be formatted as IP addresses
•  Must be between 3 and 63 characters in length
•  Can only contain lower-case characters, numbers, periods, and dashes
•  Must start with a lowercase letter or number
•  Cannot contain underscores (_), end with a dash (-) or period (.), have consecutive periods (.), or use dashes (-) adjacent to periods (.)
> [Update] How to Use Linode Object Storage

- docs/security/vulnerabilities/scanning-your-linode-for-malware/index.md
Currently the GPG key from our Finnix image is outdated.  Customers can't `apt update` successfully before updating the key.  Adding this to the Doc temporarily until the Finnix image is updated with the new key.
> [Update] Scanning your Linode for Malware

- docs/platform/billing-and-support/billing-and-payments-classic-manager/index.md
- docs/platform/billing-and-support/billing-and-payments/index.md
Hey all! I've been trying to get used to git/github and I thought this would be a solid way to do it! This change just adds information about the temporary authorization hold to the "Updating Credit Card Information" section of the Classic and Cloud Billing guides:
Let me know if I should change anything :)
> Adding authorization hold information to Billing Guides

- docs/getting-started/index.md
Validated the command on a Gentoo Linode. The current command: emerge --uDN @world results in: emerge --uDN @world! '--uDN' is not a valid package atom.! Please check ebuild(5) for full details.
The command emerge -uDU --keep-going --with-bdeps=y @world llisted on The wiki https://wiki.gentoo.org/wiki/Gentoo_Cheat_Sheet#Package_upgrades works fine!
> Updated the Package upgrades command for Gentoo

- docs/getting-started/index.md
reworded "You may also want to add an entry for your Linode’s IPv6 address:" as " Add an entry for your Linode's IPv6 address. Applications requiring IPv6 will not work without this entry:"
Addresses: https://linode.com/docs/getting-started/#comment-4566207670
> [update] Getting Started - Reworded the phrase about ipV6 address

- docs/websites/cms/how-to-install-ghost-cms-on-ubuntu-16-04/index.md
I have swapped out the link to Ghost's own documentation on an Ubuntu install.  The current link is broken.  The new link is very informative and takes one exactly where one needs to go.
> Update link to prevent 404 error

- docs/applications/containers/introduction-to-docker/index.md
capitalized "Dockerfile" to be consistent with convention
> Minor Formatting

- docs/platform/block-storage/how-to-use-block-storage-with-your-linode-classic-manager/index.md
Added recommendation to unmount volumes before detaching them if the Linode is powered on.
For parity with https://github.com/linode/docs/pull/2667
> [Update] Added warning for hot-unplugging mounted volumes (Classic)

- docs/platform/network-helper/index.md
Currently is says to select settings and then select advanced from there.  However, the advanced settings must have been changed to their own tab.  Which I like as it does not bury the options so deep.  Anywho, the picture will also need to be changed so that you can see the advanced tab.
> [update] Changed to click on advanced tab rather than settings tab

- docs/networking/ssh/using-sshfs-on-linux/index.md
- Update the command to copy the public ssh key
- Update the name of the limited user to example_user to keep it consistent with https://www.linode.com/docs/security/securing-your-server/#add-a-limited-user-account
- Checked that the ip address is the standard documentation ip address
> [Updated] Using SSHFS to Mount Remote Directories

- docs/platform/one-click/deploy-mern-with-one-click-apps/index.md
Removed the reference to MERN CLI as a fix for https://github.com/linode/docs/issues/2704
> [Update] Deploy MERN with One-Click Apps

- docs/applications/configuration-management/install-a-chef-server-workstation-on-ubuntu-18-04/index.md
Other steps use `sudo` before `dpkg` to get around the superuser privileges needed. Without this you get:
```bash
vagrant@stretch:~$ dpkg -i chef-workstation_*.deb
dpkg: error: requested operation requires superuser privilege
```
> dpkg requires privileges used in other steps

- docs/platform/longview/longview/index.md
1.  I had a dupe Longview key issue but didn't get the error message shown.   Re-installing by itself doesn't seem to do anything either if the client is already up to date, so it seems one may need to first *uninstall* then re-install.  
2. I also assumed the GUID shown in the URL was the same as the Longview key, which does not seem to be the case so adding a note about this may help to clarify things.
> Clarify cloned key section

- docs/security/firewalls/configure-firewall-with-ufw/index.md
As a fix for the comment https://linode.com/docs/security/firewalls/configure-firewall-with-ufw/#comment-4621073836
The note reads: If you are running Docker, by default Docker directly manipulates iptables. Any UFW rules that you specify does not apply to Docker containers.
> [Update] How to Configure a Firewall with UFW

- docs/networking/vpn/set-up-wireguard-vpn-on-ubuntu/index.md
-updated the doc ip address
-removed the sentence that reads: Currently, WireGuard is only available on Linux. It is now available on Windows as well  ( https://www.wireguard.com/install/)
> [Updated] Set Up WireGuard VPN on Ubuntu

- docs/tools-reference/linux-users-and-groups/index.md
This PR will close #2843.
In the guide, the `sudoers` `User privilege specification` allows users listed on `sudoers` to execute privileged commands **as any users on any Linodes or machines** . Unless they are trusted, the excerpt is likely to compromise Linodes.
For the reason above, this PR add caution message.
> Add caution message for sudoers

- docs/quick-answers/websites/secure-http-traffic-certbot/index.md
The current link is dead and doesn't lead to a guide which covers DNS. This will repoint the link to a guide that specifically covers adding domains/records.
> Updates the [Add DNS Records] link

- docs/applications/messaging/install-mastodon-on-ubuntu-1604/index.md
- docs/development/version-control/how-to-unbundle-nginx-from-omnibus-gitlab-for-serving-multiple-websites/index.md
- docs/development/version-control/install-gitlab-on-ubuntu-18-04/index.md
- docs/email-warning-shortguide/index.md
- docs/email/_index.md
- docs/email/clients/install-roundcube-on-ubuntu/index.md
- docs/email/clients/install-squirrelmail-on-ubuntu-16-04-or-debian-8/index.md
- docs/email/how-to-create-an-email-server-with-mail-in-a-box/index.md
- docs/email/iredmail/install-iredmail-on-ubuntu/index.md
- docs/email/postfix/configure-postfix-to-send-mail-using-gmail-and-google-apps-on-debian-or-ubuntu/index.md
- docs/email/postfix/configure-spf-and-dkim-in-postfix-on-debian-8/index.md
- docs/email/postfix/configure-spf-and-dkim-in-postfix-on-debian-9/index.md
- docs/email/postfix/email-with-postfix-dovecot-and-mariadb-on-centos-7/index.md
- docs/email/postfix/email-with-postfix-dovecot-and-mysql-on-centos-6/index.md
- docs/email/postfix/email-with-postfix-dovecot-and-mysql/index.md
- docs/email/postfix/pflogsumm-for-postfix-monitoring-on-centos-6/index.md
- docs/email/postfix/postfix-smtp-debian7/index.md
- docs/email/postfix/troubleshooting-problems-with-postfix-dovecot-and-mysql/index.md
- docs/email/running-a-mail-server/index.md
- docs/email/zimbra/zimbra-on-ubuntu-14-04/index.md
- docs/platform/billing-and-support/linode-beginners-guide/index.md
- docs/platform/one-click/deploy-gitlab-with-one-click-apps/index.md
- docs/platform/one-click/deploying-wordpress-with-one-click-apps/index.md
- docs/platform/one-click/one-click-woocommerce/index.md
- docs/security/using-fail2ban-for-security/index.md
- docs/tools-reference/linux-system-administration-basics/index.md
- docs/uptime/logs/use-logrotate-to-manage-log-files/index.md
- docs/uptime/monitoring/install-icinga2-monitoring-on-debian-9/index.md
- docs/websites/ecommerce/how-to-install-prestashop-on-ubuntu-16-04/index.md
Added email-warning-shortguide which is a disclosure note
Added long email note to the main email guide: /docs/email/running-a-mail-server/
Updated header text on: /docs/email
Added short guide notes to additional guides:
- /docs/email/iredmail/install-iredmail-on-ubuntu/
- /docs/email/postfix/postfix-smtp-debian7/
- /docs/email/postfix/configure-postfix-to-send-mail-using-gmail-and-google-apps-on-debian-or-ubuntu/
- /docs/email/how-to-create-an-email-server-with-mail-in-a-box/
- /docs/email/postfix/email-with-postfix-dovecot-and-mysql/
- /docs/email/clients/install-squirrelmail-on-ubuntu-16-04-or-debian-8/
- /docs/email/zimbra/zimbra-on-ubuntu-14-04/
- /docs/email/postfix/email-with-postfix-dovecot-and-mariadb-on-centos-7/
- /docs/email/postfix/email-with-postfix-dovecot-and-mysql-on-cent …
> [Update] Note About Email at Linode

- docs/development/java/install-java-on-ubuntu-18-04/index.md
- Updated the instructions to install Oracle JDK11 based on information provided in https://www.linuxuprising.com/2019/06/new-oracle-java-11-installer-for-ubuntu.html
- Fixes https://github.com/linode/docs/issues/2781
> [Update] Install Oracle Java SE Development Kit 11 on Ubuntu

- docs/platform/object-storage/lifecycle-policies/index.md
The multipart upload policy had an ID that was erroneously labeled the same as the non-current version policy.
> [Update] Managing Objects with Lifecycle Policies

- themes/docsmith/layouts/_default/baseof.html
* Theme rebuild to add `| Linode` to title tag in theme's head.
* Hercules PR: https://github.com/linode/hercules/pull/150
> Add |Linode to title in theme

- docs/platform/object-storage/pricing-and-limitations/index.md
Update the Object Storage Pricing and Limitations guide to reflect the new object limits (1 million per cluster).
> [Hotfix] v0.26.1

- docs/websites/static-sites/how-to-choose-static-site-generator/index.md
I noticed some links had been changed in the documentation [How to Choose a Static Site Generator](https://www.linode.com/docs/websites/static-sites/how-to-choose-static-site-generator/)
> [Update] How to Choose a Static Site Generator

- docs/development/python/flask-and-gunicorn-on-ubuntu/index.md
Found this while working on a Stackscript, the application will still install as the Doc stands, but rebooting the Linode will result in a 502 error. This will fix that.
https://www.linode.com/docs/development/python/flask-and-gunicorn-on-ubuntu/#install-and-configure-supervisor
> [Update]Ubuntu Flask Doc: missed '-' in flask_app.conf section

- docs/platform/object-storage/bucket-versioning/index.md
- docs/platform/object-storage/host-static-site-object-storage/index.md
- docs/platform/object-storage/how-to-manage-objects-with-lifecycle-policies/index.md
- docs/platform/object-storage/how-to-use-object-storage/index.md
- docs/platform/object-storage/object-storage-use-cases/index.md
- docs/platform/object-storage/pricing-and-limitations/index.md
Added information to clarify that OBJ is billed upon activation and must be completely cancelled as a service, and caveats regarding transfer with IPv6 in the same datacenter
> [Update] IPv6/billing obj clarification

- docs/uptime/monitoring/install-icinga2-monitoring-on-debian-9/index.md
- docs/uptime/monitoring/monitor-remote-hosts-with-icinga/index.md
These guides expired/were about to expire, and causing issues for other guides when attempting to run docs404. Removed expiryDate from both of them.
> Remove expiryDate from Icinga guides

- docs/kubernetes/deploy-container-image-to-kubernetes/index.md
- Added a note about latest Hugo package for the Linux distribution
- Fixes https://github.com/linode/docs/issues/2960
> [Update]Create and Deploy a Docker Container Image to a Kubernetes Cluster

- docs/networking/dns/dns-records-an-introduction/index.md
I selected this link and found out that openspf.org has been dead since February 2019. In searching for something comparable that would serve a similar purpose, I found this page https://www.dmarcanalyzer.com/spf/how-to-create-an-spf-txt-record/. 
Though to be fair that page above belongs to a for-profit company, it may be a marketing decision if recommending a third-party tool such as this or mxtoolbox
> Replace reference in dns-records guide to openspf.org which no longer exists

- docs/development/nodejs/use-nightmarejs-to-automate-headless-browsing/index.md
This PR contains changes to `linode.js` script to workaround `TypeError: Cannot read property 'focus' of null` message.
This will close #2907.
PS: Please check this PR if the error still persists.
> [Update] Use Nightmare.js to Automate Headless Browsing

- docs/email/postfix/troubleshooting-problems-with-postfix-dovecot-and-mysql/index.md
This small PR remove backslash on `disable_plaintext_auth` option on `10-auth.conf` Dovecot conf.
This will close #2975
> [Update] Troubleshooting Problems with Postfix, Dovecot, and MySQL: Remove Backslash on Disabling Plaintext Authentication

- docs/tools-reference/linux-users-and-groups/index.md
Removing invalid link to U Wisconsin resource - no longer on that page.
> Removing stale ref to UW resource

- docs/networking/dns/dns-records-an-introduction/index.md
This PR adds note about appending trailing dot in domain names `example.com.` as opposed to `example.com`. Many folks don't know that the actual FQDN contains trailing dot.
PS: Test whether DNS records with trailing dot in domain names are actually working.
This will close #2906.
> [Update] DNS Records: An Introduction - Trailing Dot in Domain Names

- docs/platform/migrating-to-a-different-data-center/index.md
Update migration instructions to include the new Disks/Configs naming convention that replaced "Advanced".
> Update Instructions to use "Disks/Configs"

- docs/platform/manager/keep-your-linode-account-safe-classic-manager/index.md
- docs/security/linode-manager-security-controls/index.md
- removed https://www.linode.com/docs/platform/manager/keep-your-linode-account-safe-classic-manager/#force-password-expirations and https://www.linode.com/docs/security/linode-manager-security-controls/#force-password-expirations- because it is a bad security practice and it is recommend to use a password manager or other users on the account.
> [Update] How to Keep Your Linode Account Safe

- docs/platform/object-storage/host-static-site-object-storage/index.md
- docs/platform/object-storage/how-to-manage-objects-with-lifecycle-policies/index.md
- docs/platform/object-storage/how-to-use-object-storage-acls-and-bucket-policies/index.md
- docs/platform/object-storage/how-to-use-object-storage/index.md
- docs/platform/object-storage/object-storage-cluster-shortguide/index.md
- docs/platform/object-storage/pricing-and-limitations/index.md
added cluster definition short guide
Added short guide to the following guides:
- docs/platform/object-storage/host-static-site-object-storage
- docs/platform/object-storage/how-to-manage-objects-with-lifecycle-policies
- docs/platform/object-storage/how-to-use-object-storage-acls-and-bucket-policies
- docs/platform/object-storage/how-to-use-object-storage
- docs/platform/object-storage/pricing-and-limitations
> [Update] Object Storage Cluster Definition

- docs/troubleshooting/rescue-and-rebuild/index.md
We auto-fill all of your disks now, so "more than two" is inaccurate.
> Update Rescue/Rebuild guide

- docs/kubernetes/getting-started-with-kubernetes/index.md
- added tool tips for first occurrences of Kubernetes and Linux terms
- fixed the table descriptions
- all references of pods changes to Pod
- maintained consistency in using kubeadm, kubectl, kube-scheduler, and other terms
- fixed the numbering issue in Before you begin section
> [Update]Getting Started with Kubernetes: Use kubeadm to Deploy a Cluster on Linode

- docs/networking/vpn/set-up-a-streisand-gateway/index.md
- updated the note to read as follows: Read/Write access for Linodes and IPs is sufficient to set up a Streisand gateway because you will creating a new Streisand Linode server.
- helpful for security in the event their token is compromised.
- Fixes https://github.com/linode/docs/issues/2959
> [Update] How to Set Up a Streisand Gateway

- docs/security/linode-manager-security-controls/index.md
[Update] Linode Cloud Manager Security Controls
Removing alias that is the same as the guide's directory path
Reported by Linode support:
This guide is currently redirecting to itself in an infinite loop:
https://www.linode.com/docs/security/linode-manager-security-controls/
I noticed that one of the aliases on the guide is `security/linode-manager-security-controls/`, which is the same as that guide's path. I logged into the production server and saw that Hugo had rendered a redirect page at that URL, instead of a normal page with content.
Proposed fix is to remove that alias. Some other weird things I noticed:
- The last time we touched this line in the file was ten months ago, and we didn't even add this problematic alias at that time: https://github.com/linode/docs/pull/2414/files
- …
> [Hotfix] v0.31.1

- docs/applications/voip/install-asterisk-on-centos-7/index.md
This PR add `--disable BUILD_NATIVE` flag to `make menuselect` step. This will produce generic binaries instead of architecture-optimized binaries. This may be suitable if Asterisk instance will be migrated later.
This will close #2744.
> [Update] How to Compile Asterisk on CentOS 7 - Disable Native Architecture Binaries

- docs/networking/vpn/set-up-wireguard-vpn-on-debian/index.md
- docs/networking/vpn/set-up-wireguard-vpn-on-ubuntu/index.md
- updated the private IP address of the server to 10.0.0.1 and that of the client to 10.0.0.2
- added a note about ensuring that the interface of the server and client is down when adding a peer
- Fixes https://github.com/linode/docs/issues/3074
> [Update] Set Up WireGuard VPN on Ubuntu and Debian

- docs/platform/longview/what-is-longview/index.md
CentOS 8 is not supported by Longview as mentioned in the note at the beginning of the doc. Changing the reference to CentOS 8 later in the doc to CentOS 7 to minimize customer confusion.
> Updating "What is Longview?" guide

- docs/platform/manager/what-are-the-cloud-manager-events-and-activity-feeds/index.md
> fixed typo in Events Page subheader

- ci/vale/dictionary.txt
- docs/kubernetes/deploy-and-manage-a-cluster-with-linode-kubernetes-engine-a-tutorial/index.md
While working on a new LKE guide I was working with this one and noticed the kubeconfig has changed during the beta.
Confirmed for all 3 supported versions of Kubernetes.
> [Update] How to Deploy and Manage a Cluster with LKE

- docs/platform/object-storage/how-to-use-object-storage-acls-and-bucket-policies/index.md
Added the following note:
Currently, you can create a new canonical ID, only by creating a completely new Linode account. A canonical ID is not assigned to a limited access user on an existing Linode account.
> [Update]Enacting Access Control Lists (ACLs) and Bucket Policies with Linode Object Storage

- archetypes/content.md
- archetypes/section.md
* `content.md` archetype should have `og_description` as default front matter.
> [Update] Add `og_description` to default front matter

- docs/platform/disk-images/linode-backup-service/index.md
Clarification regarding how restores work in Cloud Manager, taking up as much space as was allocated to the original disk
> [Update] The Linode Backup Service

- docs/platform/manager/accounts-and-passwords/index.md
- docs/platform/manager/what-are-the-cloud-manager-events-and-activity-feeds/index.md
added note that only unrestricted users can receive threshold notification emails on these two guides:
- /platform/manager/accounts-and-passwords
- /platform/manager/what-are-the-cloud-manager-events-and-activity-feeds
> [Update] Unrestricted Email Note

- docs/platform/manager/remote-access/index.md
IP sharing is not available in Sydney at this time.
> Updating Guide to reflect IP sharing Limitation

- docs/websites/cms/drupal/drush-drupal/_index.md
The Drush section wasnt showing up in the Drupal section page,
because show_in_lists wasnt set on the Drupal section _index.md.
This adds that frontmatter.
> [Update] Drush _index.md

- docs/kubernetes/deploy-and-manage-a-cluster-with-linode-kubernetes-engine-a-tutorial/index.md
- docs/kubernetes/deploy-and-manage-lke-cluster-with-api-a-tutorial/index.md
- docs/kubernetes/getting-started-with-kubernetes/index.md
- docs/kubernetes/how-to-deploy-a-static-site-on-linode-kubernetes-engine/index.md
- docs/kubernetes/how-to-install-apps-on-kubernetes-with-helm-3/index.md
Remove LKE Beta notice from the LKE guides:
- Deploy a Static Site on Linode Kubernetes Engine
- A Tutorial for Deploying and Managing a Cluster with Linode Kubernetes Engine and the Linode API
- A Tutorial for Deploying and Managing a Cluster with Linode Kubernetes Engine
- Getting Started with Kubernetes
- How to Install Apps on Kubernetes with Helm 3
> Remove LKE Beta notice from guides

- docs/security/securing-your-server/index.md
Fix note indentation in SSH Daemon Options section. Bad indentation was causing incorrect numbering of remaining steps in the section. A support member called out this issue.
> [Update] How to Secure Your Server

- docs/web-servers/lamp/how-to-install-a-lamp-stack-on-centos-8/index.md
- Added the instructions for enabling ports for HTTPS connections.
> [Update] How to Install a LAMP Stack on CentOS 8

- docs/platform/manager/what-are-the-cloud-manager-events-and-activity-feeds/index.md
Cloud Manager now only displays the past 90 days of event history instead of the entire account history
> Corrected info about Event History

- docs/tools-reference/linux-users-and-groups/index.md
The article says that the `chgrp` command functions in the same way as the `newgrp` command; that is, it is used to change a user's current group.
This is incorrect. `chgrp` is used to change the group ownership of an existing file, in the way that `chown` or `chmod` are used. Running the `chgrp` command as shown in the example in the article, without a file or directory argument to change the ownership of, results in an error:
$ chgrp web
chgrp: missing operand after ‘web’
Try 'chgrp --help' for more information.
The man page for `chgrp` confirms this:
```
CHGRP(1)                           User Commands                          CHGRP(1)
NAME
chgrp - change group ownership
SYNOPSIS
chgrp [OPTION]... GROUP FILE...
chgrp [OPTION]... --reference=RFILE FILE...
DESCRIPTION
Change the group of …
```
> Remove incorrect information about chgrp command

- docs/web-servers/squid/squid-http-proxy-centos-8/index.md
- docs/web-servers/squid/squid-http-proxy-debian-10/index.md
- docs/web-servers/squid/squid-http-proxy-ubuntu-18-04/index.md
- updated the ip address based on https://tools.ietf.org/html/rfc5737
- added guides for centos 8, debian 10, and ubuntu 18.04
- added port information, enable firewall info
> [New] How to Create an HTTP Proxy Using Squid  (1k)

- docs/applications/configuration-management/vagrant-linode-environments/index.md
Deprecate Vagrant guide, which relies on APIv3, which has been deprecated
> [Update] Using Vagrant to Manage Linode Environments

- docs/kubernetes/deploy-volumes-with-the-linode-block-storage-csi-driver/index.md
* Add info about `linode-block-storage-retain` PVC StorageClass and its associated behavior.
> [Update] Deploy Persistent Volume Claims with the Linode Block Storage CSI Driver

- docs/networking/dns/common-dns-configurations/index.md
Step 1 for configuring Subdomains said "Click Add an A/AAA record". Fixed typo
> Typo in Configuring Subdomains Step 1

- docs/tools-reference/linux-users-and-groups/index.md
The current documentation for "Linux Users and Groups" seems to imply that the sticky bit, when set on _files_, will prevent users other than the owner or root from deleting the file, similar to the functionality when set on _directories_.
This is not correct—historically, the sticky bit, when set on files (specifically, executables), would save the `.text` section of an executable into swap space to improve performance for commonly-used executables. I'm not sure if this still technically happens with modern Linux distributions, but even if it does, the sticky bit has no practical use given the speed of modern storage devices.
The documentation should be corrected, as as it is currently written a user might think that setting the sticky bit on a _file_ that she owns within a shared …
> Update documentation on sticky bit

- docs/platform/api/upgrade-to-linode-api-v4/index.md
* Deprecate: Upgrade to the New Linode API
* Linode API v3 has been deprecated. Guide now links to Getting Started with the Linode API (v4).
> [Update] Upgrade to the New Linode API

- docs/web-servers/lamp/how-to-install-a-lamp-stack-on-centos-8/index.md
- docs/web-servers/lamp/how-to-install-a-lamp-stack-on-debian-10/index.md
- docs/web-servers/lamp/how-to-install-a-lamp-stack-on-ubuntu-18-04/index.md
- docs/web-servers/lemp/how-to-install-the-lemp-stack-on-centos-8/index.md
- docs/web-servers/lemp/how-to-install-the-lemp-stack-on-debian-10/index.md
- docs/web-servers/lemp/how-to-install-the-lemp-stack-on-ubuntu-18-04/index.md
- Based on the comment in Disqus added a note in the Before your begin:
_If you have a registered domain name for your website, then [add the domain](/docs/platform/manager/dns-manager/#add-a-domain) to the Linode server on which you plan to install the LEMP stack. If you do not have a registered domain name, then replace `example.com` with the IP address of the Linode server in the following instructions._
fix for: https://github.com/linode/docs/issues/3374
> [Update] LEMP and LAMP guides

- docs/security/firewalls/control-network-traffic-with-iptables/index.md
updated based on a comment in DisQus:
"iptables-save > /etc/iptables/rules.v6 commands as any IPv6 changes will be overwritten by the IPv4 rules"
Sure it does if you use wrong command. The right one is ip6tables-save > /etc/iptables/rules.v6
> [Update] Control Network Traffic with iptables

- docs/platform/longview/what-is-longview/index.md
Longview installation should now work on CentOS 8
> Remove note regarding CentOS 8 compatibility

- docs/kubernetes/how-to-setup-a-private-docker-registry-with-lke-and-object-storage/index.md
1. `hosts` is not a subkey of `secretName`.
2. `secretName` should be the name of the associated certificate, not the name of the issuer secret
> Fix bad ingress.tls docs / values

- docs/game-servers/how-to-set-up-minecraft-server-on-ubuntu-or-debian/index.md
dead link
https://minecraft.net/en/download/server
changed to
https://minecraft.net/en-us/download/server
> Fixed minecraft server page link

- docs/platform/block-storage/how-to-use-block-storage-with-your-linode/index.md
When doing capacity planning, it is common to ask: what is the maximum number of volumes I can have per Linode?
I have edited the text slightly to include the words "volumes per linode" so that finding this article via a Google search becomes easier. I also think this information should be on the main page about block storage here: https://www.linode.com/products/block-storage/
> Make "volumes per linode" stand out more.

- docs/applications/cloud-storage/tahoe-lafs-on-debian-9/index.md
- docs/platform/api/_index.md
- docs/platform/api/api-key/index.md
- docs/platform/create-limited-developer-account/index.md
- docs/platform/disk-images/disk-images-and-configuration-profiles/index.md
- docs/platform/disk-images/migrating-a-server-to-your-linode/index.md
- docs/platform/longview/longview-app-for-mysql-classic/index.md
- docs/platform/longview/longview-app-for-nginx-classic/index.md
- docs/platform/manager/using-the-linode-shell-lish/index.md
- docs/quick-answers/linode-platform/enable-backups-on-a-linode/index.md
- docs/security/recovering-from-a-system-compromise/index.md
- docs/tools-reference/custom-kernels-distros/install-alpine-linux-on-your-linode/index.md
- docs/tools-reference/custom-kernels-distros/install-nixos-on-linode/index.md
- docs/tools-reference/introduction-to-linux-concepts/index.md
- docs/tools-reference/linux-system-administration-basics/index.md
- docs/troubleshooting/disaster-recovery-guide/index.md
- docs/troubleshooting/troubleshooting-basic-connection-issues/index.md
- docs/troubleshooting/troubleshooting/index.md
- docs/uptime/monitoring-and-maintaining-your-server/index.md
I didn't look at the full context, just searched through the repo and for all of the non-deprecated docs, I updated the links from manager.linode.com to cloud.linode.com. May still need a bit of copy-editing.
> Update links for Cloud Manager

- docs/websites/host-a-website-with-high-availability/index.md
In the [linode high availability guide](https://www.linode.com/docs/websites/host-a-website-with-high-availability/#galera-with-xtradb), a change to Percona causes the user to not be able to install the percona packages due to a GPG error. 
Percona had a gpg key change on 15 Jan 2019, and all packages of Percona >= 0.1-6 and beyond (Current version is 0.1-7) use the new PERCONA-PACKAGING KEY. I've changed the instructions on how to install the new key.
Source: https://jira.percona.com/browse/ENG-37  (found while trying to install)
> Change PerconaDB GPG Key to install Percona-XtraDB

- docs/platform/disk-images/linode-images/index.md
Clarify that you can have 5, not 3, images per account.
> [Update] Linode Images

- docs/platform/object-storage/how-to-use-object-storage/index.md
Currently buckets are created in us-east-1 by default, regardless of your CLI configuration. If you want to make or interact with buckets in other clusters, the --cluster option is needed.
> Added information under the Linode CLI section of how-to-use-object-storage' about the --cluster option.

- docs/security/firewalls/configure-firewall-with-ufw/index.md
The UFW guide currently says "do not follow the Configure a Firewall section in How to Secure Your Server guide", presumably because the "How to Secure Your Server" guide used to include only instructions for using `iptables`. However, that guide now includes links to guides that provide different options for firewall configuration (including this UFW guide), so this "warning" in the UFW guide no longer makes sense. This commit removes it.
> Remove outdated reference in UFW guide

- docs/kubernetes/getting-started-with-load-balancing-on-a-lke-cluster/index.md
- docs/kubernetes/how-to-configure-load-balancing-with-tls-encryption-on-a-kubernetes-cluster/index.md
- docs/platform/nodebalancer/getting-started-with-nodebalancers/index.md
- docs/platform/nodebalancer/nodebalancer-ssl-configuration/index.md
- docs/platform/nodebalancer/what-are-nodebalancers/index.md
removed notes about ProxyProtocol not available and changed notes to say CCM does not have support for ProxyProtocol on LKE guides
> [Update] NodeBalancer Guides for ProxyProtocol

- docs/email/postfix/configure-spf-and-dkim-in-postfix-on-debian-9/index.md
Following the guide steps do not place the user in the directory in which to run the commands in step 8. Adding absolute paths to the commands removes the need for changing directory.
> Add Absolute Paths to Key MV Commands

- docs/tools-reference/custom-kernels-distros/install-a-custom-distribution-on-a-linode/index.md
Adding some documentation around unsupported ext4 features in custom distributions, specifically Meta-Data Checksums and that they don’t currently work with Linode Cloud Manager features.
> Some ext4 features (e.g. metadata_csum) not supported.

- docs/email/iredmail/install-iredmail-on-ubuntu/index.md
Original iRedMail download link was dead, updated to latest stable release and [here](https://www.linode.com/docs/email/iredmail/install-iredmail-on-ubuntu/#install-iredmail).
> updated iRedMail install guide DOCS-358

- docs/kubernetes/how-to-deploy-a-static-site-on-linode-kubernetes-engine/index.md
The container image in this guide uses an older version of Hugo, v0.54.0, while the latest is v0.74.3. When building the container image, hugo exits with the following error:
```
Error: Error building site: Failed to load translations in file “bg.toml”: unsupported file extension .toml
```
Updating Hugo to a more recent package resolves this issue. The Debian Buster(stable) repo has `0.54.0` as the latest available, while Debian Sid (unstable) has the more recent `0.74.3-1`.
This PR updates the base image to `alpine:3.12.0`, which has the more recent hugo `v0.71.1` package. Alpine is also a smaller base image, which should reduce the build time a bit.
> Update LKE static site guide to use alpine base image

- config.toml
- scripts/deploy_to_object_storage.sh
- scripts/generate_permanent_redirects.sh
- Fix generate_permanent_redirects.sh for new baseURL in last hotfix
- Also includes a deploy_to_production.sh fix that was meant to be included in last hotfix
> Hotfix v1.0.3

- _vendor/github.com/bep/linodedocs/layouts/_default/baseof.html
- _vendor/modules.txt
- config.toml
- go.mod
- go.sum
Example:
Before:
```
<title>Linode Guides &amp; Tutorials | What is iptables</title>
```
After:
```
<title>What is iptables | Linode</title>
```
This aligns with what we did on the old site, and it makes sure more of the page's actual title is visible in search results.
The appended text (e.g. "Linode") can be changed by setting `page_title_suffix` in the site params in config.toml
---
This does not changed the titles for section pages--I haven't figured that out yet. Nor does it change the titles and other <head> attributes for wordpress content pages. We have an open issue for that.
> Fix page titles for static pages (guides, product docs)

- scripts/update_linode_docs_search_indices/main.go
This change supports keeping several namespaced sets of indices on the same Algolia account. These would be used to maintain several staging servers, each of which has its own Algolia index collection.
If no `indexsuffix` is passed to the script, then these changes have no effect.
> Update Algolia upload script to optionally apply an index suffix

- .gitignore
- scripts/generate_permanent_redirects_for_nginx.sh
This script creates a set of 301 redirects that can then be copied over to an NGINX web server that hosts the docs site. The 301s that are generated correspond to the frontmatter `aliases` set within the guides.
> Script: generate NGINX 301 redirects from Hugo aliases

- _vendor/github.com/linode/linode-api-docs/v4/openapi.yaml
- _vendor/modules.txt
- go.mod
- go.sum
- Added the [Object Storage Object ACL View](/docs/api/object-storage/#object-storage-object-acl-config-view) (GET /object-storage/buckets/{clusterId}/{bucket}/object-acl) endpoint. This endpoint returns an Object's currently configured Access Control List (ACL) within a specific bucket. ACLs define who can access your buckets and objects and specify the level of access granted to those users.
- Added the [Object Storage Object ACL Update](/docs/api/object-storage/#object-storage-object-acl-config-update) (PUT /object-storage/buckets/{clusterId}/{bucket}/object-acl) endpoint. This endpoint update's an Object's currently configured Access Control List (ACL) within a specific bucket. ACLs define who can access your buckets and objects and specify the level of access granted to those users. …
> API Docs Release 1.4.0

- _vendor/github.com/bep/linodedocs/assets/js/main/navigation/breadcrumbs.js
- _vendor/github.com/bep/linodedocs/assets/js/main/navigation/create-href.js
- _vendor/github.com/bep/linodedocs/assets/js/main/navigation/explorer.js
- _vendor/github.com/bep/linodedocs/assets/js/main/navigation/init.js
- _vendor/github.com/bep/linodedocs/assets/js/main/search/dispatcher.js
- _vendor/github.com/bep/linodedocs/assets/js/main/search/search.js
- _vendor/github.com/bep/linodedocs/assets/js/main/sections/home/home.js
- _vendor/github.com/bep/linodedocs/assets/js/main/sections/sections/blog-article.js
- _vendor/github.com/bep/linodedocs/assets/js/main/sections/sections/list.js
- _vendor/github.com/bep/linodedocs/layouts/content/list.html
- _vendor/github.com/bep/linodedocs/layouts/data/metadata_sections.json
- _vendor/github.com/bep/linodedocs/layouts/partials/sections/after-body-start.html
- _vendor/github.com/bep/linodedocs/layouts/partials/sections/navigation/breadcrumbs.html
- _vendor/github.com/linode/linode-website-partials/footer.css
- _vendor/modules.txt
- go.mod
- go.sum
- scripts/generate_permanent_redirects_for_nginx.sh
Theme updates:
- Breadcrumb fixes (breadcrumbs now appear fully correct after a 'hard page refresh' for product docs/guides/api/blogs)
- SEO head information for blogs/resources/apps (rel canonical link, meta descriptions, og:descriptions, etc)
- Update linode-website-partials (full-width footer style change)
Update generate_permanent_redirects_for_nginx.sh to fix HTTPS 301 issue
---
For any reviewers, a couple known issues that will be fixed separately:
- Blogs have full breadcrumbs, but not resources or apps
- There's some funny URL encoding happening inside the breadcrumb string for some characters; see the dash in the title of this blog post for example:
> [Hotfix] v1.6.1

- _vendor/github.com/bep/linodedocs/layouts/partials/sections/head.html
- _vendor/modules.txt
- ci/yaml_rules.json
- docs/guides/databases/mariadb/mariadb-setup-debian/index.md
- docs/guides/platform/disk-images/tokyo2-migration/index.md
- docs/guides/platform/manager/manually-enable-elastic-ip-on-your-linode/index.md
- docs/guides/quick-answers/linode-platform/enable-backups-on-a-linode/index.md
- go.mod
- go.sum
* Add frontmatter `noindex` to theme (adds `<meta name="robots" content="noindex" />`) to a page's `head` when present
* Add noindex to Elastic IP guide
* Add noindex to ci yaml rules
* Rebuild theme reference
> Hotfix v1.6.3

- config.toml
This change makes the .Lastmod Hugo variable reflect the last commit date in Git. This was being used in the old docs site, but was lost in the migration to the new docs UI.
This should be merged alongside https://github.com/bep/linodedocs/pull/30. If we wanted to wait to merge that other PR, we could still merge this PR more immediately.
> Set enableGitInfo = true in config.toml

- docs/guides/applications/configuration-management/ansible/deploy-linodes-using-ansible/index.md
- As per the comment in disqus: I think there's a minor typo in the Ansible debug message -
<code>- name: Print info about my Linode instance
debug:
msg: "ID is {{ my_linode.instance.id }} IP is {{ my_linode.instance.ipv4 }}"</code>
debug should be unindented two spaces, as should msg.
> [update] fixed the indentation for the message

- docs/guides/platform/billing-and-support/manage-billing-in-cloud-manager/index.md
- docs/guides/platform/disk-images/linode-backup-service/index.md
Removing a Linode's backups or the Linode itself will delete all
backups generated by the Linode Backup Service, including snapshots.
There is also a small formatting change in this commit on the Backup
Service guide to correct monospaced text that was appearing on a note.
> Include caution messages for Backup deletion when removing services

- docs/guides/all-linodes-kvm-shortguide/index.md
- docs/guides/platform/disk-images/kvm-reference/index.md
- docs/guides/security/encryption/full-disk-encryption-xen/index.md
- docs/guides/security/upgrading/how-to-upgrade-to-ubuntu-10-04-lts-lucid/index.md
- docs/guides/security/upgrading/how-to-upgrade-to-ubuntu-10-10-maverick/index.md
- docs/guides/tools-reference/custom-kernels-distros/custom-compiled-kernel-with-pvgrub-centos-7/index.md
- docs/guides/tools-reference/custom-kernels-distros/custom-compiled-kernel-with-pvgrub-debian-ubuntu/index.md
- docs/guides/tools-reference/custom-kernels-distros/custom-compiled-kernel-with-pvgrub-on-arch/index.md
- docs/guides/tools-reference/custom-kernels-distros/install-a-custom-distribution-on-a-linode/index.md
- docs/guides/tools-reference/custom-kernels-distros/install-a-custom-distribution-on-a-xen-linode/index.md
- docs/guides/tools-reference/custom-kernels-distros/install-coreos-on-your-linode/index.md
- docs/guides/tools-reference/custom-kernels-distros/run-a-custom-compiled-kernel-with-pvgrub/index.md
- docs/guides/tools-reference/custom-kernels-distros/run-a-distributionsupplied-kernel-with-pvgrub/index.md
- docs/guides/tools-reference/custom-kernels-distros/use-the-distribution-supplied-kernel-on-centos-6-with-grub-legacy/index.md
I left these guides alone but added a short guide note:
- kvm-reference (this one should probably be left alone for "history")
- full-disk-encryption-xen (this one should probably be re-written for non-xen. The title of the guide doesn't say Xen, just the slug/folder)
These all didn't say Xen outright but used the xvda file system base examples instead of sda. They could be updated but they are deprecated, except for that last one that oddly has a front matter deprecated: false.
- run-a-custom-compiled-kernel-with-pvgrub (deprecated)
- run-a-distributionsupplied-kernel-with-pvgrub (deprecated)
- custom-compiled-kernel-with-pvgrub-centos-7 (deprecated)
- how-to-upgrade-to-ubuntu-10-10-maverick (deprecated)
- how-to-upgrade-to-ubuntu-10-04-lts-lucid (deprecated)
- …
> [Update] Xen Guides

- ci/vale/dictionary.txt
- docs/guides/security/basics/using-fail2ban-to-secure-your-server-a-tutorial/index.md
* SEO optimization updates and edits.
* OG PR: https://github.com/linode/docs/pull/3869/
> [Update] Using Fail2ban to Secure Your Server - A Tutorial

- docs/guides/platform/marketplace/deploying-docker-with-marketplace-apps/index.md
Added info on additional configuration options
> [Update] How to Deploy Docker with Marketplace Apps

- docs/guides/uptime/monitoring/monitoring-servers-with-monit/index.md
Monit is not available in Debian 10's standard repositories, but is available in its backports. I've included some special instructions for installing Monit on this distribution.
> Include instructions to install Monit on Debian 10

- algolia_settings.json
These settings were accidentally not included in release v1.19.1.
They have been set correctly on the production Algolia index,
so this commit gets algolia_settings.json aligned with the
production settings.
> Update Algolia ranking configs

- _vendor/github.com/linode/linode-docs-theme/layouts/partials/sections/before-body-end.html
- _vendor/modules.txt
- go.mod
- go.sum
* Update theme: add content grouping
* This will have no visible effect. If a guide includes the following front matter, this triggers special behavior that does not affect the UI:
```
gtags:
- key: external-contributors
value: est-ext
```
> [Hotfix] 1.25.1

- docs/guides/security/self-hosted-password-management-with-bitwarden-rs/index.md
Fixed an inconsistency with installing an older (incompatible) version of bitwarden later in the guide. This breaks bitwarden and will not allow new things to be added to the vault.
https://www.linode.com/community/questions/21147/how-do-i-notify-linode-that-a-guide-has-an-error-in-it#answer-75749
> [Update] bitwarden version inconsistency

- docs/guides/kubernetes/deploy-volumes-with-the-linode-block-storage-csi-driver/index.md
- docs/guides/kubernetes/how-to-install-the-linode-block-storage-csi-driver/index.md
- Repositions explanation on when manual installation of the CSI driver is needed for Kubernetes support
> [Update] Block Storage CSI driver guides

- docs/guides/platform/vlan/getting-started-with-vlans/index.md
Remove header for empty "Viewing VLANs attached to a Linode" section in Getting Started with VLANs guide.
> Hotfix to remove header for empty section

- docs/guides/platform/manager/cloud-stackscripts-shortguide/index.md
Updated the **cloud-stackscripts-shortguide** to fix the URL to the StackScripts Guides page. This shortguide is referenced within [/docs/products/tools/cloud-manager/guides/cloud-stackscripts/](https://www.linode.com/docs/products/tools/cloud-manager/guides/cloud-stackscripts/).
> [Update] cloud-stackscripts-shortguide (Fixed URL)

- docs/guides/kubernetes/how-to-configure-load-balancing-with-tls-encryption-on-a-kubernetes-cluster/index.md
- Updated `cert-manager` from `v0.15.1` to `v1.3.1` (the latest non alpha/beta release)
- Updated ClusterIssuer resource `apiVersion` from `cert-manager.io/v1alpha2` to `cert-manager.io/v1`
- Updated Ingress resource `apiVersion` from `networking.k8s.io/v1beta1` to `networking.k8s.io/v1`
- Updated Ingress resource manifest file
- Fixed formatting issues with extra spaces in code blocks and extra lines in output/file.
> [Updated] How to Configure Load Balancing with TLS Encryption on a Kubernetes Cluster

- docs/guides/kubernetes/how-to-deploy-nginx-ingress-on-linode-kubernetes-engine/index.md
Related to changes made in PR #4320 
- Updated Ingress resource `apiVersion` from `networking.k8s.io/v1beta1` to `networking.k8s.io/v1`
- Updated Ingress resource manifest file
> [Updated] How to Deploy NGINX Ingress on Linode Kubernetes Engine

- .github/workflows/test.yaml
This PR does two things:
- Integrate a workaround for the "head commit not ahead of base commit" error. Workaround proposed here:
https://github.com/jitterbit/get-changed-files/issues/11#issuecomment-718254652
- Filter out files that are not in the docs/ directory
This helps us avoid running Vale on non-content files, like our typography test page at _vendor/github.com/linode/linode-docs-theme/content/typografy-test.md
> Vale GHA improvements

- docs/guides/applications/configuration-management/terraform/beginners-guide-to-terraform/index.md
> I have submitted two accompanying pull requests to parent project terraform to also reflect these changes, https://github.com/hashicorp/terraform/pull/28578 and https://github.com/hashicorp/terraform/pull/28579 these may provide more context if needed.
In this article, the [Provisioners](https://www.linode.com/docs/guides/beginners-guide-to-terraform/#provisioners) section advises to use the following block of code:
```hcl
resource "linode_instance" "example_instance" {
provisioner "file" {
source      = "setup_script.sh"
destination = "/tmp/setup_script.sh"
}
provisioner "remote-exec" {
inline = [
"chmod +x /tmp/setup_script.sh",
"/tmp/setup_script.sh",
]
}
}
```
This results in the following error:
> Error: missing connection configuration for provisioner
According to the [Terraform …
> Update provisioners section for Terraform >= 0.12

- ci/vale/dictionary.txt
- docs/guides/applications/configuration-management/packer/how-to-use-linode-packer-builder/index.md
Significant reworking of this guide, including the following changes:
- New installation instructions for Packer
- Uses the HCL2 template syntax instead of the old JSON syntax
- Explains the components of a Packet template and the parameter for the Linode Packer builder
- Separates all Ansible content into its own section
- Outlines all image deployment methods, including the Cloud Manager and CLI in addition to the API
> [Updated] How to Use the Linode Packer Builder

- docs/guides/networking/linode-network/an-overview-of-ipv6-on-linode/index.md
- Updated terminology of IPv6 blocks to differentiate between routed ranges and pools.
> [Updated] An Overview of IPv6 on Linode

- docs/guides/kubernetes/how-to-migrate-from-k8s-alpha-to-terraform/index.md
Command was "terrform workspace new mynewcluster" but should have been "terraform workspace new mynewcluster". Fixed typo
> fixed typo in new workspace command when creating a cluster

- docs/guides/platform/marketplace/deploying-minecraft-with-marketplace-apps/index.md
This is a simple PR to update the Minecraft link in the Minecraft Marketplace App guide. The existing link appears to not resolve, but this one is tested and working.
> Update Minecraft download link to use working URL

- docs/guides/platform/billing-and-support/support/index.md
Removed the India Toll Free number to match the rest of our contact pages. We removed it because of reliability issues we were seeing when customers used that number.
> [Update] Linode Support

- docs/guides/tools-reference/tools/how-to-use-dnf/index.md
- docs/guides/tools-reference/tools/how-to-use-yum/index.md
- [Updated] Using the DNF Package Manager
- [Updated] Using the YUM Package Manager
This PR clarifies that DNF replaces YUM on Fedora *and* RHEL 8 and its derivatives (like CentOS 8 and AlmaLinux). It also discusses the benefits of DNF and addresses how the `yum` command can still be used on these newer distros.
> Updated YUM and DNF guides

- docs/guides/kubernetes/beginners-guide-to-kubernetes-part-4-controllers/index.md
The current command results in `error: the server doesn't have a resource type "logs"`.
> fix `kubectl logs` command

- docs/guides/quick-answers/websites/how-to-install-certbot-on-ubuntu-18-04/index.md
- fixes https://github.com/linode/docs/issues/3952
- the certbot PPA has been deprecated, see https://launchpad.net/~certbot/+archive/ubuntu/certbot
> updated the certbot install command

- docs/guides/networking/linode-network/linux-static-ip-configuration/index.md
Adds note referencing the requirement of an IPv6 SLAAC address as the primary IPv6 address
> [Update] Linux Static IP Configuration

- docs/guides/kubernetes/how-to-configure-load-balancing-with-tls-encryption-on-a-kubernetes-cluster/index.md
- docs/guides/kubernetes/how-to-deploy-nginx-ingress-on-linode-kubernetes-engine/index.md
- [Updated] Deploying NGINX Ingress on Linode Kubernetes Engine
- [Updated] Configuring Load Balancing with TLS Encryption on a Kubernetes Cluster
Updated helm repo for NGINX, enabled h1, added a section for creating a cluster, aligned some sections on both guides.
> Updates to both nginx ingress LKE guides

- docs/guides/security/ssl/enabling-https-using-certbot-with-apache-on-ubuntu/index.md
This came by way of an email to feedback@linode.com, where a customer pointed out the incorrect link in the guide.
> Wrong link for guide on installing Apache

- docs/guides/platform/marketplace/how-to-deploy-jitsi-with-marketplace-apps/index.md
Cloud Manager is pointing to an old URL for the Jitsi Marketplace App guide. Added that URL as an alias so users are redirected to the correct page.
> Added alias to Jitsi Marketplace doc

- docs/guides/email/postfix/configure-spf-and-dkim-in-postfix-on-debian-9/index.md
- Tech/copy edit for Debian 9 
- Replaces https://github.com/linode/docs/pull/4432/ because Debian 8 is deprecated.
> [Update] Configure SPF and DKIM With Postfix on Debian 9

- docs/guides/platform/disk-images/linode-images/index.md
- docs/products/tools/images/_index.md
- docs/products/tools/images/_shortguides/images-ga-pricing-update-shortguide/index.md
- docs/products/tools/images/_shortguides/upload-image-requirements-shortguide/index.md
Custom Images transitioned to a paid service on September 1st, 2021. This PR covers updating our documentation to reflect the new pricing.
- [Updated] Images > Overview
- [Updated] Images Tutorial
- [Updated] `images-ga-pricing-update-shortguide`
> Change to Custom Images pricing

- ci/vale/dictionary.txt
- docs/guides/web-servers/caddy/compile-caddy-from-source/index.md
- docs/guides/web-servers/caddy/how-to-install-and-configure-caddy-on-centos-8/index.md
- docs/guides/web-servers/caddy/how-to-install-and-configure-caddy-on-debian-10/index.md
- docs/guides/web-servers/caddy/how-to-install-and-configure-caddy-on-ubuntu-18-04/index.md
- docs/guides/web-servers/caddy/install-and-configure-caddy-on-centos-7/index.md
Updated the following caddy guides:
- https://www.linode.com/docs/guides/how-to-install-and-configure-caddy-on-ubuntu-18-04/
- https://www.linode.com/docs/guides/how-to-install-and-configure-caddy-on-debian-10/
- https://www.linode.com/docs/guides/how-to-install-and-configure-caddy-on-centos-8/
- https://www.linode.com/docs/guides/compile-caddy-from-source/
- https://www.linode.com/docs/guides/install-and-configure-caddy-on-centos-7/
Fixes: https://github.com/linode/docs/issues/4572
>  [Update] The caddy guides

- docs/guides/find-this-guide-on-github/index.md
- docs/guides/linode-writers-formatting-guide/index.md
- docs/guides/search/index.md
These guides were appearing in Explore Docs menu, but don’t need to:
- /docs/guides/find-this-guide-on-github/
- /docs/guides/linode-writers-formatting-guide/
- /docs/guides/search/
Note that these menu items do not appear when loading the docs home page, but they do on other pages (like https://www.linode.com/docs/guides/). They also appear after a delay, after the other items in the menu show up.
> Hide three guides from Explore Docs menu:

- docs/guides/development/python/how-to-install-python-on-ubuntu-20-04/index.md
Changed "CentOS 8" to "Ubuntu 20.04" in Python 3 Ubuntu 20.04 guide
> [Fixed] Install Python 3 on Ubuntu 20.04

- docs/guides/platform/vlan/getting-started-with-vlans/index.md
- docs/products/networking/vlans/get-started/index.md
- docs/products/networking/vlans/guides/detach-a-linode-from-your-vlan/index.md
A Cloud Manager release changed the button text on the Edit Configuration panel from **Edit Configuration** to **Save Changes**. This PR adds minor updates to three VLAN guides to correct that button text.
> Updated VLAN guides with correct button text

- ci/vale/dictionary.txt
- docs/guides/security/authentication/self-hosted-password-management-with-bitwarden-rs/index.md
The has been renamed to separate itself from the official Bitwarden server in the hopes of avoiding confusion and trademark/branding issues. Please see https://github.com/dani-garcia/vaultwarden/discussions/1642 for more explanation.
> Update bitwarden_rs to vaultwarden

- docs/products/networking/dns-manager/get-started/index.md
Cleaned up a few references to old terminology (master/slave to primary/secondary) and changed the name of the button, Add a Domain > Create Domain
> Updating doc language to match updated Cloud Manager language

- docs/guides/networking/linode-network/linux-static-ip-configuration/index.md
Updated the Linux Static IP Configuration guide to further specify that the first IPv6 assignment in most network configuration files should be the IPv6 SLAAC address for the Linode Compute Instance.
> [Updated] Linux Static IP Configuration

- docs/guides/tools-reference/tools/how-to-use-silver-searcher/index.md
This just fixes a broken link that we missed in the last release
> [Hotfix] v1.96.1

- docs/guides/quick-answers/linux/choosing-a-distribution/index.md
- Added Alpine 3.15 (just released)
- Marked Ubuntu 20.10, Fedora 32, and Alpine 3.10 as deprecated
> [Updated] Choosing a Linux Distribution

- _vendor/github.com/linode/linode-docs-theme/assets/js/main/navigation/explorer.js
- _vendor/github.com/linode/linode-docs-theme/assets/js/main/navigation/nav.js
- _vendor/github.com/linode/linode-docs-theme/assets/js/main/search/query.ts
- _vendor/github.com/linode/linode-docs-theme/assets/js/main/search/search-store.js
- _vendor/github.com/linode/linode-docs-theme/assets/js/main/sections/sections/list.js
- _vendor/github.com/linode/linode-docs-theme/assets/jsconfig.json
- _vendor/github.com/linode/linode-docs-theme/layouts/partials/sections/search/input.html
- _vendor/github.com/linode/linode-docs-theme/layouts/partials/sections/search/list.html
- _vendor/github.com/linode/linode-docs-theme/layouts/partials/sections/search/panel.html
- _vendor/modules.txt
- go.mod
- go.sum
- For search queries (e.g. the /docs/topresults/ page), use 'lndq'
instead of 'q' for the search term in the URL. This helps avoid
name collisions for marketing links that also use the 'q' param.
> Theme updates

- docs/guides/platform/marketplace/mistio-marketplace-app/index.md
Specifies that the Marketplace app installs the latest available version.
> [Updated] Deploying Mist.io through the Linode Marketplace

- docs/guides/applications/configuration-management/ansible/running-ansible-playbooks/index.md
Received this error regarding an old version of passlib:
```
<string>:1: DeprecationWarning: the method passlib.handlers.sha2_crypt.sha512_crypt.encrypt() is deprecated as of Passlib 1.7, and will be removed in Passlib 2.0, use .hash() instead.
```
So I swapped out .encrypt for .hash and I did not get a depreciation warning.
> updated passlib .encrypt funct to non-depreicated version

- docs/guides/platform/marketplace/plesk-marketplace-app/index.md
- docs/guides/platform/marketplace/plex-marketplace-app/index.md
The following link in the Cloud Manager for the Plex Marketplace App guide is redirecting to the *Plesk* Marketplace App guide:
```
https://linode.com/docs/platform/one-click/deploy-plex-with-one-click-apps/
->
https://www.linode.com/docs/guides/plesk-marketplace-app/
```
This PR fixes the aliases for both guides.
> [Fix] Updated aliases for Plesk and Plex Marketplace App guides

- docs/guides/platform/marketplace/flask-marketplace-app/index.md
- Provides guidance for deleting and overwriting the default configuration for new applications served over port 80
> [Update] Deploying Flask through the Linode Marketplace

- docs/guides/websites/hosting/host-a-website-with-high-availability/index.md
- Added command to install `wget`
- Replaced non-working URL to the percona rpm
- Added port 3306 to the Galera service firewall rules xml file
> [Fix] Host a Website with High Availability

- docs/guides/email/email-services/using-magicspam-email-authentication/index.md
- docs/guides/platform/billing-and-support/network-transfer/index.md
- docs/guides/security/monitoring/how-to-use-linode-api-with-twilio/index.md
- docs/guides/security/monitoring/twilio-api-monitor-network-transfer/index.md
- docs/guides/security/monitoring/twilio-api-monitor-network-transfer/transfer-pool-notification-twilio.py
- docs/guides/security/monitoring/twilio-api-monitor-network-transfer/transfer-pool-notification-with-overage-threshold-twilio.py
- docs/guides/security/monitoring/twilio-api-monitor-network-transfer/transfer-pool-notification-with-threshold-twilio.py
New:
- Monitor your Linode's Network Transfer Pool
The previous version of the guide had some problems that this edited version addresses:
- The code example incorrectly used the transfer data of the [Linode View endpoint](https://www.linode.com/docs/api/linode-instances/#linode-view) for a single Linode to represent the transfer usage of the Linode account. The code now uses the [Network Utilization View](https://www.linode.com/docs/api/account/#network-utilization-view) endpoint instead. 
- The guide referenced setting up a periodic notification system, but it never actually created this.  This guide sets up a cron job to run the code periodically. New code was also added that sets a transfer usage threshold for notifications.
Modified:
- Network Transfer Usage and Costs
I added a …
> [New] Monitor your Linode's Network Transfer Pool

- docs/guides/web-servers/apache/how-to-install-and-configure-fastcgi-and-php-fpm-on-centos-8/index.md
- docs/guides/web-servers/apache/how-to-install-and-configure-fastcgi-and-php-fpm-on-debian-10/index.md
- docs/guides/web-servers/apache/how-to-install-and-configure-fastcgi-and-php-fpm-on-ubuntu-18-04/index.md
- updated the steps for php-fpm on centos 8, debian 10, and ubuntu 18.04
- fixes [ 3380](https://github.com/linode/docs/issues/3380)
- fixes [ 3353](https://github.com/linode/docs/issues/3353)
- fixes [ 3543](https://github.com/linode/docs/issues/3543)
> [Update] How to Install and Configure FastCGI and PHP-FPM

- docs/guides/platform/marketplace/filecloud-marketplace-app/index.md
Removes the FileCloud Marketplace App guide from the site's index and adds a caution note to inform users that the app has been disabled due to breaking issues.
> [Release Candidate] v1.120.1

- ci/vale/dictionary.txt
- docs/guides/applications/cloud-storage/install-and-configure-owncloud-on-debian-7/index.md
- docs/guides/databases/mongodb/creating-a-mongodb-replication-set-on-debian-7-wheezy/index.md
- docs/guides/databases/mysql/how-to-install-mysql-on-centos-6/index.md
- docs/guides/databases/mysql/how-to-install-mysql-on-debian-7/index.md
- docs/guides/databases/mysql/install-mysql-on-ubuntu-14-04/index.md
- docs/guides/databases/mysql/install-mysql-phpmyadmin-debian-7/index.md
- docs/guides/databases/mysql/install-mysql-phpmyadmin-ubuntu-14-04/index.md
- docs/guides/databases/mysql/managing-mysql-with-phpmyadmin-on-centos-6-4/index.md
- docs/guides/development/clojure/clojure-deployment-with-immutant-and-wildfly-on-ubuntu-14-04/index.md
- docs/guides/development/frameworks/yesod/yesod-nginx-mysql-on-debian-7-wheezy/index.md
- docs/guides/development/ror/ruby-on-rails-with-nginx-on-debian-7-wheezy/index.md
- docs/guides/email/citadel/email-with-citadel-on-ubuntu-14-04/index.md
- docs/guides/email/postfix/email-with-postfix-dovecot-and-mysql-on-centos-6/index.md
- docs/guides/email/zimbra/zimbra-on-ubuntu-14-04/index.md
- docs/guides/security/upgrading/how-to-upgrade-to-debian-7-wheezy/index.md
- docs/guides/tools-reference/file-transfer/transfer-files-with-cyberduck-on-mac-os-x/index.md
- docs/guides/tools-reference/file-transfer/transfer-files-with-filezilla-on-ubuntu-9-10-desktop/index.md
- docs/guides/tools-reference/file-transfer/transfer-files-with-winscp-on-windows/index.md
- docs/guides/web-servers/apache/apache-and-modwsgi-on-ubuntu-14-04-precise-pangolin/index.md
- docs/guides/web-servers/apache/apache-web-server-on-centos-6/index.md
- docs/guides/web-servers/apache/apache-web-server-on-ubuntu-14-04/index.md
- docs/guides/web-servers/apache/running-fastcgi-php-fpm-on-debian-7-with-apache/index.md
- docs/guides/web-servers/lamp/lamp-on-centos-6/index.md
- docs/guides/web-servers/lamp/lamp-on-ubuntu-14-04/index.md
- docs/guides/web-servers/lamp/lamp-server-on-debian-7-wheezy/index.md
- docs/guides/web-servers/squid/squid-http-proxy-centos-6-4/index.md
- docs/guides/websites/cms/wordpress/install-wordpress-using-wp-cli-on-ubuntu-14-04/index.md
Some guides that target the following distributions were not marked as deprecated. This PR fixes that.
- CentOS 6 (no longer available on Linode's platform)
- Debian 7 (no longer available on Linode's platform)
- Ubuntu 14.04 (no longer available on Linode's platform)
> Deprecated Debian 7, Ubuntu 14.04, and CentOS 6 guides

- docs/guides/tools-reference/linux-package-management/apt-package-manager/index.md
Fixes restore command when using apt-clone
> [Fixed] Using APT to Manage Packages in Debian and Ubuntu

- docs/guides/databases/mysql/securing-mysql/index.md
This page used a mix of straight and right angled single-quotes to escape values in mysql CLI commands.
> Patch: standardize quote mark in Securing MySQL 

- docs/guides/web-servers/caddy/how-to-install-and-configure-caddy-on-ubuntu-18-04/index.md
the formatting was off, but also I was running as it without success. After some testing, I was able to get Caddy to install with the command I added.
> [Update] Install and Configure the Caddy Web Server on Ubuntu 18.04

- docs/guides/development/python/use-paramiko-python-to-ssh-server/index.md
- updated the example 1 for python 3 based on the comment in feedback: "python 3 complained on example 1 that stdin is not defined, renamed it to _stdin and it worked"
> [Update] How to Use Paramiko and Python to SSH into a Server

- scripts/generate_permanent_redirects_for_nginx.sh
Instead of grepping for a large portion of the header, the script now just looks for pages that contain a URL in the title tag, which only occurs for pages generated based on aliases.
> Fixes the script that generates NGINX redirects

- docs/guides/applications/remote-desktop/installing-apache-guacamole-natively/index.md
the cd command is wrong here. cp is the correct one.
> [Fix] Installing Apache Guacamole on Ubuntu and Debian

- docs/guides/platform/api/uninstall-linode-api-cli-v3/index.md
- Guides users towards upgrading to the newest version of the Linode CLI if they have not yet already upgraded
> [New] Uninstall Deprecated Linode CLI using API v3

- docs/products/storage/object-storage/guides/manage-buckets/index.md
Fixed the note under **Delete a Bucket** so that it mentions buckets must be empty before deleting them. Also provided the S3cmd command to delete a bucket along with its objects.
> [Update] Create and Manage Buckets

- docs/guides/websites/cms/wordpress/how-to-install-wordpress-ubuntu-2004/index.md
Updated based on a comment in the feedback for documents:
Need to reference https://www.linode.com/docs/guides/how-to-install-a-lamp-stack-on-ubuntu-20-04/ instead of what is currently referenced which is https://www.linode.com/docs/guides/how-to-install-a-lamp-stack-on-ubuntu-18-04/
The newer lamp stack instructions have different steps for mysql which are needed to successfully deploy a database for 20 04
> [Update] Install WordPress on Ubuntu 20.04

- docs/guides/networking/linode-network/ip-failover-bgp-frr/index.md
Adds IPv6 sharing support to FRR guide.
> [Update] Configuring IP Failover over BGP using FRR (Advanced)

- .github/workflows/test.yaml
This PR introduces a loop into the docs404 GHA that waits for Hugo to finish building before running the 404 scraping script. This is useful because we previously waited a static amount of time after starting Hugo (20 seconds); however, Hugo sometimes needed longer than this set time, and the docs404 test would fail in this situation.
- The script sleeps 1 second on each interval
- On each interval, it checks if the server is responding on port 1313 and exits the loop if it gets a response. 
- If there is no server response, but the Hugo process isn't running anymore, then we can infer that Hugo failed to build because of some fatal error. The loop exits and we set exit code 1 for the GHA so that it doesn't proceed to the 404 scraping script. https://github.com/linode/docs/pull/5277 tests …
> Dynamically wait for Hugo to start in docs404 job

- ci/vale/dictionary.txt
- docs/guides/networking/linode-network/ip-failover/index.md
The lelastic utility will soon support CentOS/RHEL. The pre-release of this new version has been tested and this PR updates all relevant documentation.
**Update:** lelastic has been updated and version incremented to `v0.0.4`
> [Update] Configuring Failover on a Compute Instance

- docs/products/storage/object-storage/guides/s3cmd/index.md
This PR updates the `sync` command usage instructions. While the original instructions were not incorrect, there was room for clarity and to bring this section in line with formatting conventions in other sections.
> [Update] Using S3cmd with Object Storage

- docs/guides/platform/cloud-firewall/getting-started-with-cloud-firewall/index.md
- docs/guides/platform/manager/an-overview-of-the-linode-cloud-manager/index.md
Addresses the current inability to create Personal Access tokens with limited cloud firewall permissions in the Linode Manager, and guides users towards completing this with the API
> [Update] Getting Started With Cloud Firewall

- ci/vale/dictionary.txt
- docs/guides/quick-answers/linux/how-to-use-fsck-to-fix-disk-problems/index.md
- docs/guides/quick-answers/linux/using-e2fsck-to-check-ext-rescue-mode/index.md
- docs/guides/troubleshooting/rescue-and-rebuild/index.md
- Additional fixes for fsck guides and "Rescue and Rebuild" to address the switch to e2fsck as the default filsystem repair utility.
> [New] Using e2fsck to Find and Repair Disk Errors on ext File Systems

- docs/guides/security/authentication/how-to-self-host-the-vaultwarden-password-manager/index.md
Fixes: [5309](https://github.com/linode/docs/issues/5309)
Validated and tested the steps with the new port numbers and it works.
```
rajie@caddy:~$ sudo docker run -d -p 80:80 -p 443:443 --name caddy -v /etc/Caddyfile:/etc/caddy/Caddyfile -v /etc/caddy:/root/.local/share/caddy --restart on-failure caddy:2
ac4aaf5d08068fee9606b0ec36bb2986561b0b670ad971809631ed13cd7afa27
rajie@caddy:~$ sudo docker logs caddy
{"level":"info","ts":1649243173.3180423,"msg":"using provided configuration","config_file":"/etc/caddy/Caddyfile","config_adapter":"caddyfile"}
{"level":"warn","ts":1649243173.3193927,"msg":"input is not formatted with 'caddy fmt'","adapter":"caddyfile","file":"/etc/caddy/Caddyfile","line":2}
{"level":"info","ts":1649243173.3204315,"logger":"admin","msg":"admin endpoint …
```
> updated the port numbers

- docs/products/databases/managed-databases/guides/updates-and-maintenance/index.md
Reverted change related to DBMS version upgrades. This now clarifies that *minor version releases* are not included in the automatic updates that occur during maintenance windows.
> [Update] Managed Databases > Automatic Updates and Maintenance Windows

- docs/products/networking/cloud-firewall/_shortguides/cloud-firewall-limits-shortguide/index.md
Added information about the type of traffic to which Cloud Firewall rules are applied. Specifically, they are applied to traffic over both the public and private networks, but not over VLANs.
> [Update] Cloud Firewall Limits

- docs/products/storage/object-storage/get-started/index.md
noticed that docs say to click "Add a Bucket" but the verbiage for the button on the cloud site is actually "Create Bucket." updating for accuracy
> [Update] Object Storage > Get Started

- docs/guides/networking/linode-network/ip-failover/index.md
- docs/guides/networking/linode-network/network-infrastructure-upgrades/index.md
Updated the following docs to reflect that Mumbai is now undergoing the planned network infrastructure upgrades.
- [Updated] Configuring Failover on a Compute Instance
- [Updated] Upcoming Changes Related to Network Infrastructure Upgrades
> Updated Mumbai's Network Upgrade status

- docs/products/tools/marketplace/guides/pihole/index.md
This PR removes Debian 11 from list of available distros in the Pi-hole guide.
> [Update] Deploying Pi-hole through the Linode Marketplace

- docs/guides/kubernetes/deploy-prometheus-operator-with-grafana-on-linode-kubernetes-engine/index.md
- rewrite the guide because the prometheus-operator helm chart was deprecated
> [update]How to Deploy Prometheus Operator and Grafana on LKE

- docs/guides/applications/remote-desktop/install-vnc-on-ubuntu-20-04/index.md
* Add missing alias. This should fix [the current 404](https://www.linode.com/docs/guides/install-vnc-on-ubuntu-21-04/).
> [Update] Install VNC on Ubuntu 20.04

- .gitignore
- CONTRIBUTING.md
This modifies the Hugo installation instructions. Instead of using a package manager like Homebrew, which installs the latest version of Hugo, the docs now outline how to use the precompiled binaries for the 0.83.1 release. This prevents issues that could arise when someone uses a newer version of Hugo to develop or test changes on the docs site.
Preview: https://github.com/linode/docs/blob/4802aff140acabfd1dbd9f6296d99022d2c014f1/CONTRIBUTING.md#install-hugo
> [Update] CONTRIBUTING.md

- docs/guides/websites/cms/basics/best-open-source-content-management-systems/index.md
- docs/guides/websites/cms/basics/cms-overview/index.md
- Moved "The Top Open Source Content Management Systems" guide from WordPress category to CMS Basics category
- Updated title capitalization for two CMS guides
> Recategorized a CMS guide and updated title capitalization

- docs/guides/networking/linode-network/systemd-networkd/index.md
This PR replaces the command used to reload network configuration changes after making modifications. Ubuntu 18.04 (and possibly other distributions) does not have the command `networkctl reload` so using a command to restart the service instead.
> [Update] Network Configuration Using systemd-networkd

- docs/guides/kubernetes/lke-continuous-deployment-part-11/index.md
```
➜  ~ helm upgrade --install kube-prometheus-stack kube-prometheus-stack \ --namespace prometheus --create-namespace \ --repo https://prometheus-community.github.io/helm-charts
Error: "helm upgrade" requires 2 arguments
Usage:  helm upgrade [RELEASE] [CHART] [flags]
```
Moving `--install` after `kube-prometheus-stack kube-prometheus-stack` allows the command to run as expected.
> [Fix] Continuous Deployment Using LKE: Prometheus and Grafana

- .github/workflows/test.yaml
- .vale.ini
In a recent change, the minimum alert level in Vale was set to only show errors (`MinAlertLevel = error`). This change was done in the .vale.ini file and affected the GitHub Action, running Vale locally in Docker, and using the VS Code extension. The intended purpose was to only show errors in the GitHub Action, though it was acceptable that the other methods of running Vale were also impacted (considering that you can explicitly set the preferred level in VS Code settings).
A better way to implement this without impacting any other Vale usage or needing to change any local settings is to use the `--minAlertLevel` flag within the GitHub Action itself. This PR makes that change and then reverts the main Vale configuration file back to showing both warning and errors.
> Adjustments to Vale's minimum alert level

- docs/products/databases/managed-databases/guides/postgresql-connect/index.md
- docs/products/databases/managed-databases/guides/postgresql-extensions/index.md
As part of a recent change, the default `linpostgres` user for PostgreSQL Managed Databases no longer has superuser access. This PR updates the PostgreSQL product docs as needed due to this change.
> Updated PostgreSQL Managed Database guides

- docs/guides/kubernetes/how-to-configure-load-balancing-with-tls-encryption-on-a-kubernetes-cluster/index.md
We recently moved cert-manager from the sponsoring org.
This PR fixes a dead link that was a result from that
> Fix a dead link to cert-manager helm chart page

- docs/guides/applications/containers/use-coreos-container-linux-on-linode/index.md
added deprecation to this guide because Linode no longer supports CoreOS
> [update] Use CoreOS Container Linux on Linode

- docs/guides/platform/billing-and-support/understanding-billing-and-payments/index.md
- docs/guides/quick-answers/linode-platform/an-overview-of-common-cloud-manager-errors/index.md
This PR clears up ambiguity regarding how we bill for services, specifically when they are powered down. We previously used the word "active", which caused some confusion. This changes the wording to "present on an account".
> [Update] Understanding Billing and Payments

- docs/products/databases/managed-databases/guides/postgresql-extensions/index.md
This PR adds an additional notice to inform users that some extensions may not be supported. It also marks extensions that are known to be incompatible as such. Lastly, it adds instructions for viewing a list of just installed extensions.
> [Update] PostgreSQL Extensions

- docs/products/networking/cloud-firewall/_index.md
- docs/products/networking/cloud-firewall/guides/manage-firewall-rules/index.md
This PR updates some of the content regarding using IP ranges in Cloud Firewalls, including adding an example for /24 IPv4 ranges. It also updates the date the Cloud Firewall docs were published, which was inaccurate a few months.
> [Update] Manage Firewall Rules

- docs/products/compute/gpu/_index.md
- docs/products/compute/gpu/_shortguides/gpu-deposit-shortguide/index.md
- docs/products/compute/gpu/get-started/index.md
This PR adds a shortguide that explains a deposit may be needed to deploy GPU Compute Instances. The shortguide is referenced on the main Overview page as well on the the Get Started page.
> Notice regarding deposits for GPU Instances

- docs/guides/kubernetes/how-to-setup-a-private-docker-registry-with-lke-and-object-storage/index.md
- Updates the helm command to install ingress-nginx (previous command would fail)
- Adds a step in the "Before you begin" section to mention configuring kubectl with the new LKE cluster , which is needed in order to perform the steps in this guide
- Updates the cert-manager documentation link
- Fixes formatting issues
- Enables the h1 header
> [Update] Setting Up a Private Docker Registry with LKE and Object Storage

- docs/products/databases/managed-databases/guides/create-database/index.md
- docs/products/databases/managed-databases/guides/database-engines/index.md
This PR adds a note to several guides to notify users that Managed Databases can't be resized once created.
- [Update] Managed Databases > Create a Managed Database
- [Update] Managed Databases > Database Engines and Plans
> Updates to Managed Database guides (note about resize)

- docs/products/tools/marketplace/guides/hashicorp-vault/index.md
Added supported distributions to the Vault Marketplace App guide.
> [Update] Deploying HashiCorp Vault through the Linode Marketplace

- docs/products/databases/managed-databases/guides/postgresql-extensions/index.md
Clarified that not all extensions can be installed by the user as some are either incompatible or need to be manually enabled per database.
> [Update] Managed Databases > PostgreSQL Extensions

- docs/guides/applications/configuration-management/puppet/getting-started-with-puppet-6-1-basic-installation-and-setup/index.md
added a reference link to configure java_args to the canonical documentation
> [update] Getting Started with Puppet - Basic Installation and Setup

- docs/guides/email/best-practices/running-a-mail-server/index.md
The current text makes it seem as if using a self-signed certificate was a reasonable choice. With the proliferation of free, easy-to-renew certificates such as Let's Encrypt, it really seems that we can more strongly encourage good security practice instead of training people to deploy self-signed certs and click through certificate warnings, so this PR nudges users a bit more strongly to use a trusted CA.
> [Update] Running a Mail Server

- docs/products/databases/managed-databases/_index.md
This PR adds a bullet point under "Limits and Considerations" to let customers know they are not able to host their own replicas.
> Live replicas or standby nodes for a high availability Managed Database cluster cannot be created or hosted outside of Linode's Managed Database service.
> [Update] Managed Databases > Overview

- docs/guides/platform/disk-images/managing-the-kernel-on-a-linode/index.md
Since new current releases are rolled out over a short time frame, this PR clarifies that selecting the latest 64-bit (or 32-bit) kernel in Cloud/CLI/API may still cause your system to use a version or two behind the latest.
> [Update] Managing the Kernel on a Linode

- .gitignore
The linode algolia admin tool generates a directory named algolia_out/ with some data it needs to run, but we don’t need to save it in version control, and this PR puts it in our gitignore.
> Ignore directory generated by linalgadm tool

- docs/products/tools/marketplace/guides/unifi-network-application/index.md
This PR updates the URL used for accessing the UniFi application after deployment. It can no longer be accessed by the IPv4 address and instead needs to use the rDNS domain or any custom domain entered during deployment.
> [Update] Deploying the UniFi Network Application through the Linode Marketplace

- docs/guides/email/postfix/email-with-postfix-dovecot-and-mysql/index.md
This PR notifies the reader that the SHA2() function in MySQL 5.8 and above should not be used when generating passwords. It also cleans up the `doveadmin pw` command and fixes some formatting issues.
> [Update] Configure an Email Server with Postfix, Dovecot, and MySQL on Debian and Ubuntu

- .github/workflows/cache-images.yaml
- .github/workflows/test.yaml
- New workflow for pushes to develop branch (e.g. triggered after a pull request merge into develop):
- Attempt to restore an existing image cache, if it exists
- Build Hugo with garbage collection turned on
- Delete existing image caches. The resources/_gen/images directory is large, so this helps us avoid hitting the 10GB cap on GHA caches. If we were to hit the cap, other caches start getting evicted, and this could possibly include things we want to keep like our GHAs' node/python package caches.
- Post-cache step will run after workflow and save the new image cache
- Update existing docs404 test:
- Before starting Hugo server, attempt to restore an image cache, if it exists. Image caches from the develop branch will be found, according to the cache lookup rules for GHA caches
- Do …
> Cache images for GitHub Actions

- docs/guides/security/vulnerabilities/install-openvas-on-ubuntu-16-04/index.md
_ added deprecated notice because openvas is now GVM and install instructions are different.
> [update]Install OpenVAS 8 on Ubuntu 16.04

- docs/products/storage/object-storage/guides/bucket-policies/index.md
Fix an errant comma prevent the policy from executing in the "[Allow or Deny Access from a Specific IP Address](https://www.linode.com/docs/products/storage/object-storage/guides/bucket-policies/#allow-or-deny-access-from-a-specific-ip-address)" section.
> [Update] Products > Object Storage > Guides - Define Access and Permissions using Bucket Policies

- docs/guides/databases/mongodb/creating-a-mongodb-replication-set-on-centos-6-4/index.md
- docs/guides/databases/mongodb/creating-a-mongodb-replication-set-on-debian-7-wheezy/index.md
- docs/guides/databases/mongodb/creating-a-mongodb-replication-set-on-ubuntu-12-04-precise/index.md
- docs/guides/development/react/deploy-a-react-app-on-linode/index.md
- docs/guides/development/ror/use-unicorn-and-nginx-on-ubuntu-14-04/index.md
- docs/guides/security/ssl/how-to-make-a-selfsigned-ssl-certificate/index.md
- docs/guides/security/ssl/install-lets-encrypt-to-create-ssl-certificates/index.md
- docs/guides/security/ssl/secure-http-traffic-certbot/index.md
- docs/guides/web-servers/lamp/install-lamp-stack-on-ubuntu-16-04/index.md
- docs/guides/websites/wikis/install-mediawiki-on-ubuntu-1604/index.md
This PR fixes deprecated links that 404. We identified these links by finding all `deprecated_link` parameters that have a value starting with `/` or `'/`.
> Fixes deprecated links that 404

- docs/guides/networking/linode-network/ip-failover/index.md
- docs/guides/networking/linode-network/network-infrastructure-upgrades/index.md
This PR updates the relevant guides related to the network infrastructure upgrades to mark Singapore as complete. It also updates the front matter for the network infrastructure guide so that it is searchable on the docs site.
> Singapore network upgrades are completed

- docs/guides/networking/linode-network/an-overview-of-ipv6-on-linode/index.md
- docs/guides/networking/linode-network/network-infrastructure-upgrades/index.md
- docs/guides/platform/manager/managing-ip-addresses/index.md
This PR adds a deprecation notice to pages that reference /116 pools. Users are no longer able to add them within any data centers.
> Mark /116 pools as deprecated

- ci/vale/dictionary.txt
- docs/guides/applications/cloud-storage/install-and-configure-owncloud-on-centos-stream-8/index.md
- docs/guides/applications/cloud-storage/install-and-configure-owncloud-on-ubuntu-20-04/index.md
- docs/guides/email/postfix/email-with-postfix-dovecot-and-mariadb-on-centos-7/index.md
- docs/guides/email/postfix/email-with-postfix-dovecot-and-mysql/index.md
- docs/guides/web-servers/lamp/how-to-install-a-lamp-stack-on-ubuntu-18-04/index.md
- docs/guides/web-servers/lamp/how-to-install-a-lamp-stack-on-ubuntu-20-04/index.md
- docs/guides/web-servers/lemp/how-to-install-the-lemp-stack-on-centos-8/index.md
- docs/guides/web-servers/lemp/how-to-install-the-lemp-stack-on-debian-10/index.md
- docs/guides/web-servers/lemp/how-to-install-the-lemp-stack-on-ubuntu-18-04/index.md
When you run mysql_secure_installation tool the system prompts you to change the root password. Added information to create a root password.
Fixes: https://github.com/linode/docs/issues/5528
> [update] remove information about you can skip setting root password

- docs/guides/platform/billing-and-support/tax-information/index.md
This PR adds the following notice at the top of the tax guide. The notice outlines the new regions that are taxable starting December 15th, 2022.
> As a result of Akamai’s acquisition of Linode, businesses or individuals residing in the following regions may be charged tax for some or all services starting December 15th, 2022:
> 
> - **Countries:** Cambodia, Chile, Malaysia, Russian Federation, Switzerland, United Arab Emirates
> - **U.S. States:** Colorado, Connecticut, Massachusetts, Mississippi, New Mexico, New York, South Carolina, Tennessee, Utah, West Virginia
> [Update] Tax Information

- docs/products/storage/block-storage/guides/nvme-upgrade/index.md
The timeline for launching NVMe Block Storage was updated from Q2 2022 to a later date. This PR updates the language to designate NVMe in Fremont as "Not yet available".
> [Update] NVMe Block Storage Upgrade

- package-lock.json
Fixes this [vulnerability](https://github.com/linode/docs/security/dependabot/11).
> [Security] Update minimatch from 3.0.4 to 3.1.2

- docs/products/networking/dns-manager/guides/incoming-dns-zone-transfers/index.md
- docs/products/networking/dns-manager/guides/outgoing-dns-zone-transfers/index.md
This PR updates content related to AXFR transfers.
- **Incoming DNS Zone Transfers**: Removes IP address list from the Before You Begin section. The correct list of Linode AXFR server IP addresses then appears within each of the individual sections, as this list of IPs is different for each task.
- **Outgoing DNS Zone Transfers**: Refresh of the entire page, which was mostly untouched in the previous releases. As part of this, the Linode AXFR server IPs are added to this guide.
> Updates to incoming and outgoing DNS zone transfers

- docs/guides/applications/messaging/install-mastodon-on-debian-10/index.md
- docs/guides/applications/messaging/install-mastodon-on-ubuntu-2004/index.md
- docs/guides/applications/messaging/install-mastodon-server-on-centos-stream/index.md
Added a note about using PostgreSQL server as backend.
I did not add a note for the Mastadon guide for Ubuntu 16.04 because that guide uses MySQL.
Fixes: [5872 ](https://github.com/linode/docs/issues/5872)
> [update] Installing a Mastodon Server on CentOS 8, Debian 10, Ubuntu 20.04

- docs/guides/kubernetes/lke-network-firewall-information-shortguide/index.md
This PR updates the `lke-network-firewall-information-shortguide` shortguide, which appears in 3 LKE guides. The updates include adding suggested firewall rules for LKE.
> [Update] LKE networking information and suggested firewall rules

- docs/products/tools/images/guides/capture-an-image/index.md
This PR adds information regarding the internal storage utilization when caturing an image. Specifically, the internal storage utilization must be 10% less than the account's image size limit (6 GB by default).
> [Update] Capture an Image

- docs/guides/applications/cloud-storage/install-and-configure-owncloud-on-centos-stream-8/index.md
This PR updates the owncloud CentOS 8 Stream doc, including the following changes:
- Fixes the download URL and now always downloads the latest stable version
- Uses the command code fence syntax (no regression, but a related theme PR will provide enhanced functionality). This has the benefit of fixing formatting (extra spaces in code blocks).
- Uses the file code fence syntax.
- Fixes issue where one of the note shortcodes wasn't indented correctly. Also replaced added a title for that note.
- Replaces bold styling with `<kbd>` element for keyboard shortcuts. Proper styling depends on the related theme PR.
> [Update] Installing and Configuring ownCloud on CentOS Stream 8

- docs/guides/platform/api/create-block-storage-volumes-with-the-linode-api/index.md
This PR adds a note to the resize section of the guide on managing Block Storage volumes in the API. The note informs readers they will need to resize the file system on the volume after resizing the volume itself.
> After resizing the Volume, you also need to resize the file system to accommodate the additional space. For instructions, see the last few steps on the [Resize a Volume](/docs/products/storage/block-storage/guides/resize-volume/) guide.
> [Update] Manage Block Storage Volumes with the Linode API

- docs/products/tools/marketplace/guides/mastodon/index.md
- Adds an alias to the Mastodon guide to fix a broken link that is used in the Cloud Manager
> [Release Candidate] v1.202.1

- docs/guides/security/backups/using-rdiff-backup-with-sshfs/index.md
- Added deprecation tag because SSHFS is no longer maintained. More details here:https://github.com/libfuse/sshfs
> [update] Using rdiff-backup with SSHFS

- docs/guides/kubernetes/how-to-install-rooknfs-on-lke/index.md
- Added deprecation notice.
May be we can write a new guide as recommended here: We recommend that users consider Rook-Ceph's CephNFS which is under active development. Alternatively, there is a classical, non-CSI NFS server provisioner if users don't wish to run a CephCluster and CephFilesystem to host NFS storage.
Fixes https://github.com/linode/docs/issues/6019
> [update] Setting Up Rook NFS for Persistent Storage on LKE

- docs/guides/linode-writers-formatting-guide/index.md
This PR adds information about the revised `note` shortcode to the Linode Writer's Formatting Guide.
> [Update] Linode Writer's Formatting Guide

- docs/guides/websites/lms/install-canvas-lms-on-ubuntu-2004/index.md
Fixes: https://github.com/linode/docs/issues/6006 
Validated the guide and updated the commands.
> [Update] Installing Canvas on Ubuntu 20.04

- ci/yaml_rules.json
- docs/guides/platform/_index.md
- docs/products/_index.md
- docs/reference-architecture/_index.md
- Set weightAge: 0 on product docs and linode platform guides
- Set weightSearchBoost: true on product docs and linode platform guides
- Add weightAge and weightSearchBoost to blueberry yaml rules
- Set "reference architecture" in keywordsAlgolia frontmatter of reference arch docs
Additional changes are being made to the linode-algolia-admin tool to support these frontmatter updates, so there will be no visible ranking changes until that happens (either in testing or in prod)
> Algolia ranking changes

- docs/guides/kubernetes/deploy-prometheus-operator-with-grafana-on-linode-kubernetes-engine/index.md
- Updated the version number and the apiVersion
Feedback Details:
```The documentation for Cert-Manager is outdated as the api version no longer is in alpha. Deployment failed due to this as the version in the guide is deprecated and don't support the current k8s version.
Should be apiVersion: [cert-manager.io/v1](http://cert-manager.io/v1) instead of apiVersion: [cert-manager.io/v1alpha2](http://cert-manager.io/v1alpha2)
Also the version should be 1.11.0 as of 10.02.2023. :)
Otherwise good docs. Will keep you updated if I find more stuff.```
> [update]Deploying Prometheus Operator and Grafana on LKE

- docs/products/storage/object-storage/guides/s3cmd/index.md
- Removes `https://` from the endpoint value in s3cmd. The protocol (https/http) is set in another configuration parameter so including it here is redundant.
- Updates the formatting
> [Update] Object Storage > Using S3cmd with Object Storage

- docs/products/tools/marketplace/guides/cpanel/index.md
- docs/products/tools/marketplace/guides/mastodon/index.md
This PR updates the recommended plan for Mastodon Marketplace App from any Compute Instance to a minimum recommendation of a 2 GB instance. It also updates the meta description and fixes an issue with the cPanel plan guidance.
> [Update] Deploy Mastodon through the Linode Marketplace

- docs/guides/applications/containers/install-docker-compose/index.md
- fixed the docker compose download command . See the official docs here: https://docs.docker.com/compose/install/other/
- fixes https://github.com/linode/docs/issues/6044
> Install a Mastodon Server on Ubuntu 20.04

- docs/release-notes/lke/v1.11.0.md
- docs/release-notes/lke/v1.12.1.md
- docs/release-notes/lke/v1.14.0.md
- docs/release-notes/lke/v1.15.1.md
- docs/release-notes/lke/v1.16.0.md
- docs/release-notes/lke/v1.17.0.md
- docs/release-notes/lke/v1.20.0.md
- docs/release-notes/lke/v1.21.0.md
- docs/release-notes/lke/v1.22.0.md
- docs/release-notes/lke/v1.23.0.md
- docs/release-notes/lke/v1.27.0.md
- docs/release-notes/lke/v1.29.0.md
- docs/release-notes/lke/v1.3.0.md
- docs/release-notes/lke/v1.30.0.md
- docs/release-notes/lke/v1.32.0.md
- docs/release-notes/lke/v1.34.0.md
- docs/release-notes/lke/v1.36.0.md
- docs/release-notes/lke/v1.42.0.md
- docs/release-notes/lke/v1.44.0.md
- docs/release-notes/lke/v1.45.0.md
- docs/release-notes/lke/v1.46.0.md
- docs/release-notes/lke/v1.5.1.md
- docs/release-notes/lke/v1.7.2.md
- docs/release-notes/lke/v1.8.0.md
This PR adds release notes for LKE v1.46.0. It also updates language for Kubernetes upgrades in previous release notes.
> [Release Notes] LKE v1.46.0

- config/development/server.toml
Note that this is just for local development (to silence the errors in the Chrome console).
> Add *.adobedtm.com to local server config

- docs/products/compute/compute-instances/guides/upcoming-pricing-changes-april-2023/index.md
Corrected network transfer unit of measurement from GB to TB.
> [Update] Upcoming Pricing Changes (Effective 4/1/2023)

- docs/products/compute/compute-instances/_index.md
- docs/products/platform/get-started/guides/network-transfer/index.md
This PR adds a technical specification for Compute Instances that outlines the egress / network transfer range with a note regarding prorating the amount based on the number of hours a service is active.
> [Update] Compute Instances > Overview

- docs/guides/applications/configuration-management/ansible/deploy-linodes-using-ansible/index.md
- docs/guides/websites/cms/wordpress/how-to-use-nginx-fastcgi-page-cache-with-wordpress/index.md
- docs/products/compute/compute-instances/guides/manage-the-kernel/index.md
* With older Hugo versions, these malformed attributes is just dropped.
* With the latest Hugo version, you will get a validation error.
> Fix some quote issues with code block attributes

- docs/guides/applications/cloud-storage/how-to-install-nextcloud-on-ubuntu-22-04/index.md
- docs/guides/applications/cloud-storage/store-and-share-your-files-with-nextcloud-centos-7/index.md
- docs/guides/databases/mongodb/install-mongodb-on-ubuntu-20-04/index.md
- docs/guides/databases/postgresql/how-to-install-use-postgresql-ubuntu-20-04/index.md
- docs/guides/databases/postgresql/ubuntu-10-04-lucid/index.md
- docs/guides/databases/postgresql/ubuntu-10-10-maverick/index.md
- docs/guides/databases/postgresql/ubuntu-8-04-hardy/index.md
- docs/guides/databases/postgresql/ubuntu-9-04-jaunty/index.md
- docs/guides/databases/postgresql/ubuntu-9-10-karmic/index.md
- docs/guides/databases/postgresql/use-postgresql-relational-databases-on-ubuntu-12-04/index.md
- docs/guides/web-servers/lamp/how-to-install-a-lamp-stack-on-ubuntu-22-04/index.md
- docs/guides/web-servers/lamp/install-lamp-stack-on-ubuntu-16-04/index.md
Added missing key values to some newer guides, which allows the distribution drop down box to function properly and link to other distributions.
> Added missing `relations: platform: key` parameter 

- docs/products/networking/nodebalancers/guides/ssl-termination/index.md
Let's Encrypt Certbot default key type is changed to ECDSA with the latest version 2.0.0.
> update certbot command for v2

- docs/products/platform/billing/guides/tax-information/index.md
- Added Kenya to list of countries that are taxable (starting June 1st 2023)
- Updated copy in the Canada section
> [Updated] Tax Information

- docs/products/compute/compute-instances/guides/failover/index.md
- docs/products/compute/compute-instances/guides/manage-ip-addresses/index.md
When IP Sharing is enabled for an IP address, all connectivity is lost to that IP address until the appropriate routing software is properly configured. This PR notes that in the following guide:
- [Update] Configure Failover on a Compute Instance
- [Update] Managing IP Addresses on a Compute Instance
> Adds a note regarding lost connectivity when enabling IP Sharing

- docs/guides/databases/mongodb/_shortguides/mongodb-deployment-methods-shortguide/index.md
- docs/guides/databases/mongodb/mongodb-community-shell-installation/index.md
- docs/products/tools/marketplace/guides/_index.md
- docs/products/tools/marketplace/guides/mongodb-cluster/index.md
- docs/products/tools/marketplace/guides/mongodb/index.md
- docs/products/tools/marketplace/guides/percona-monitoring-management/index.md
This PR marks the MongoDB marketplace app guides as expired so they no longer are rendered. It also removes links to those guides.
> Remove MongoDB Marketplace deployment guides

- docs/products/databases/managed-databases/_index.md
- docs/products/databases/managed-databases/get-started/index.md
- docs/products/databases/managed-databases/guides/_index.md
- docs/products/databases/managed-databases/guides/database-engines/index.md
- docs/products/databases/managed-databases/guides/manage-backups/index.md
- docs/products/databases/managed-databases/guides/mongodb-connect/index.md
- docs/products/databases/managed-databases/guides/mongodb-migrate/index.md
- docs/products/databases/managed-databases/resources/index.md
This PR removes MongoDB from Managed Databases. All MongoDB-specific product guides are hidden and references to MongoDB as a database engine for Managed Database have been removed.
> Remove MongoDB Managed Database

- CONTRIBUTING.md
This PR updates the cloning instructions in the Contributing guide to include steps for both HTTPS and SSH URLs. This is in response to some folks reporting issues with the cloning step after GitHub stopped supporting password authentication on August 13, 2021.
> [Updated] Contributing.md

- docs/guides/web-servers/apache-tips-and-tricks/redirect-urls-with-the-apache-web-server/index.md
This PR updates the formatting in the Apache Redirect guide. As part of this, it replaces the deprecated `code` shortcode with the newer `command` shortcode.
> [Update] Redirect URLs with the Apache Web Server

- docs/release-notes/cloud-manager/v1.93.2.md
- docs/release-notes/cloud-manager/v1.93.3.md
This PR fixes the order of Cloud Manager v1.93.2 and v1.93.3 release notes.
> Fixed order of two Cloud Manager release notes

- docs/guides/tools-reference/basics/using-the-terminal/index.md
> Add missing word to terminal guide

- docs/guides/applications/configuration-management/ansible/running-ansible-playbooks/index.md
- docs/guides/applications/messaging/install-openfire-on-ubuntu-12-04-for-instant-messaging/index.md
- docs/guides/databases/mysql/manage-mysql-with-phpmyadmin-on-ubuntu-10-10-maverick/index.md
- docs/guides/databases/redis/install-redis-ubuntu/index.md
- docs/guides/development/ror/ruby-on-rails-apache-debian/index.md
- docs/guides/email/exim/_index.md
- docs/guides/email/postfix/email-with-postfix-dovecot-and-mysql/index.md
- docs/guides/email/zimbra/_index.md
- docs/guides/networking/diagnostics/diagnosing-network-issues-with-mtr/index.md
- docs/guides/security/ssh/use-public-key-authentication-with-ssh/index.md
- docs/guides/security/ssl/ssl-apache2-debian-ubuntu/index.md
- docs/guides/security/ssl/using-openssls-subjectaltname-with-multiple-site-domains/index.md
- docs/guides/security/upgrading/how-to-upgrade-to-ubuntu-22-04/index.md
- docs/guides/tools-reference/basics/linux-users-and-groups/index.md
- docs/guides/tools-reference/custom-kernels-distros/_index.md
- docs/guides/web-servers/apache/_index.md
- docs/guides/web-servers/apache/apache-access-control/index.md
- docs/guides/web-servers/apache/how-to-install-apache-web-server-ubuntu-18-04/index.md
- docs/guides/web-servers/lamp/how-to-install-a-lamp-stack-on-centos-8/index.md
- docs/guides/web-servers/lamp/how-to-install-a-lamp-stack-on-ubuntu-22-04/index.md
- docs/guides/web-servers/lemp/how-to-install-a-lemp-stack-on-ubuntu-22-04/index.md
- docs/guides/web-servers/nginx/_index.md
- docs/guides/web-servers/nginx/how-to-install-and-use-nginx-on-ubuntu-20-04/index.md
- docs/guides/web-servers/squid/squid-http-proxy-ubuntu-18-04/index.md
The following links are used by external sources and result in 404s:
https://www.linode.com/docs/communications/xmpp/openfire/ubuntu-12.04-precise-pangolin
https://www.linode.com/docs/advanced/pv-grub-howto
https://www.linode.com/docs/web-servers/nginx/installation
https://www.linode.com/docs/websites/authbased-access-control-with-apache
https://www.linode.com/docs/databases/mysql/phpmyadmin-ubuntu-10.10-maverick
https://www.linode.com/docs/databases/redis/ubuntu-12.04-precise-pangolin
https://www.linode.com/docs/email/postfix/dovecot-mysql-ubuntu-10.04-lucid
https://www.linode.com/docs/email/zimbra/install-zimbra-ubuntu-10.04-lucid
https://www.linode.com/docs/lamp-guides/centos-5.3/index-print
https://www.linode.com/docs/lamp-guides/ubuntu-11.04-natty …
> Fix 404s from external sources

- docs/guides/security/basics/using-fail2ban-to-secure-your-server-a-tutorial/index.md
Some edits I found while using the guide myself. Namely:
- reduce commands by using `enable --now` with systemd.
- typo correction
- indent file example to nest under numbered step.
> Small edits to Fail2Ban guide

- docs/products/storage/object-storage/guides/linode-cli/index.md
- docs/products/tools/cli/guides/install/index.md
This PR updates the CLI installation instructions to use boto3, which is now a requirement of the Object Storage plugin.
- [Update] Install and Configure the Linode CLI
- [Update] Using the Linode CLI with Object Storage
> Update CLI instructions for boto3

- docs/products/platform/get-started/guides/beta-for-new-data-centers/index.md
This PR updates the beta document to outline that services deployed in the new DCs will start accruing charges on July 1st. It also updates the pricing tables to add hourly cost and improve formatting.
> [Update] Closed Beta for Akamai's New Data Centers

- docs/products/compute/compute-instances/guides/troubleshooting-connection-issues/index.md
- docs/products/compute/compute-instances/guides/troubleshooting-firewall-issues/index.md
- docs/products/compute/compute-instances/guides/troubleshooting-general-issues/index.md
- docs/products/compute/compute-instances/guides/troubleshooting-memory-issues/index.md
- docs/products/compute/compute-instances/guides/troubleshooting-services/index.md
- docs/products/compute/compute-instances/guides/troubleshooting-ssh-issues/index.md
This PR adds a few keywords to some troubleshooting guides. The key one here is "troubleshoot" as these guides aren't surfacing in the search results when a user types in "troubleshoot ___".
> Add additional keywords to troubleshooting guides

- docs/guides/websites/lms/install-canvas-lms-on-ubuntu-2204/index.md
Updated the version of ruby and the install instructions based on https://github.com/instructure/canvas-lms/wiki/Quick-Start#dependency-installation
Fixes : https://github.com/linode/docs/issues/6446
> [Update] How to Install Canvas on Ubuntu 22.04

- docs/products/tools/marketplace/get-started/index.md
This updates the installation verification command to work across all Marketplace Apps
Currently, the command can't be used to verify certain Apps including the LAMP stack.
> [Update] Marketplace Apps - Get Started

- docs/products/tools/marketplace/guides/_index.md
- docs/products/tools/marketplace/guides/wazuh/index.md
This PR hides the Wazuh marketplace deployment guide and adds a warning message to anyone accessing the url directly.
> Hides the Deploy Wazuh through the Linode Marketplace guide

- docs/products/platform/get-started/guides/beta-for-new-data-centers/index.md
This PR adds the Stockholm, Sweden data center to the document supporting the new core site beta releases.
[Preview](https://deploy-preview-6507--nostalgic-ptolemy-b01ab8.netlify.app/docs/products/platform/get-started/guides/beta-for-new-data-centers/)
> [Update] Limited Beta for Akamai's New Data Centers

- docs/products/compute/compute-instances/guides/lish/index.md
The proposed changes here update Lish and Glish gateway information, specifically SSH key fingerprints and Weblish/Glish names to match what is actually used by the API.
> Update Lish gateway information

- docs/products/compute/compute-instances/guides/rescue-and-rebuild/index.md
_ clarify that the additional disks are not mounted by default.
> [update] Rescue and Rebuild

- docs/guides/development/version-control/backing-up-gitlab-on-linode-object-storage/index.md
- docs/guides/platform/object-storage/working-with-cors-linode-object-storage/index.md
- docs/products/storage/object-storage/_index.md
- docs/products/storage/object-storage/get-started/index.md
- docs/products/storage/object-storage/guides/_index.md
- docs/products/storage/object-storage/guides/s4cmd/index.md
This PR updates some of the links to our Object Storage guides that _did not use_ a trailing slash.
> Added trailing slash to a few Object Storage links

- docs/guides/platform/object-storage/host-static-site-object-storage/index.md
- docs/guides/platform/object-storage/server-side-encryption/index.md
- docs/products/storage/object-storage/guides/lifecycle-policies/index.md
Removed notes specifying DC availability & pricing details from the following OBJ guides:
- Deploy a Static Site using Hugo and Object Storage
- Using Server-Side Encryption with Linode Object Storage
- Guides - Lifecycle Policies
> Removed header notes from various OBJ guides

- docs/products/tools/marketplace/guides/_index.md
- docs/products/tools/marketplace/guides/wazuh/index.md
The Wazuh Marketplace App is now available again. This PR un-hides the guide from search and removes the notice that said the app was removed.
> Re-enable Wazuh Marketplace App guide

- docs/products/compute/compute-instances/guides/metadata/index.md
Fixes the misspelling in the Metadata CLI example.
> [Update] Overview of the Metadata Service

- CONTRIBUTING.md
Using `npm ci` instead of `npm i` will not update package-lock.json
> Update npm install instructions in contributing guide

- docs/guides/web-servers/lamp/how-to-install-a-lamp-stack-on-debian-11/index.md
Added a new guide for Debian 11
> [new] How to Install a LAMP Stack on Debian 11

- docs/products/compute/compute-instances/guides/manual-network-configuration/index.md
- docs/products/compute/compute-instances/guides/netplan/index.md
- docs/products/compute/compute-instances/guides/systemd-networkd/index.md
This PR adds the "Network Configuration Using Netplan" guide, which is part of our Manual Network Configuration series. This guide walks readers through using Netplan on Ubuntu 18.04 (and newer) to modify their network configuration files manually instead of leaning on Network Helper.
> [New] Network Configuration Using Netplan

- docs/guides/web-servers/nginx/serve-php-php-fpm-and-nginx/index.md
Based on the comments in DisQus:
Instead of using an if statement for the /uploads path, you should define an additional location block that catches that path.
```
location ~^ /uploads/ {
try_files $uri =404;
}
location ~* \.php$ {
fastcgi_pass unix:/run/php/php7.0-fpm.sock;
include fastcgi_params;
fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
fastcgi_param SCRIPT_NAME $fastcgi_script_name;
}
```
> [update] Serve PHP with PHP-FPM and NGINX

- docs/guides/game-servers/how-to-set-up-minecraft-server-on-ubuntu-or-debian/index.md
- docs/guides/game-servers/minecraft-on-linode-with-ubuntu-12-04/index.md
- docs/guides/game-servers/minecraft-with-bungee-cord/index.md
- docs/guides/game-servers/minecraft-with-spigot-ubuntu/index.md
- docs/products/tools/marketplace/guides/minecraft/index.md
The Minecraft Fandom wiki has been forked to a new domain: minecraft.wiki. Learn more here: https://minecraft.wiki/w/Minecraft_Wiki:Moving_from_Fandom. This PR updates the previous outdated wiki links accordingly.
> Update Minecraft Wiki links to new domain

- docs/products/storage/object-storage/_index.md
As of right now, rate limits are still 750rps across all OBJ clusters (including ones in new regions). I believe a second line was accidentally added in https://github.com/linode/docs/pull/6550.
> fix: duplicate rate limit line

- docs/guides/applications/configuration-management/pulumi/deploy-in-code-with-pulumi/index.md
- docs/products/compute/kubernetes/guides/_index.md
- docs/products/compute/kubernetes/guides/deploy-cluster-using-pulumi/index.md
Here is a guide on how to set up an LKE cluster using Pulumi and Typescript. I kept the structure similar to the TF guide. I also updated some of the links in other articles pointing to resources on the Pulumi website.
> Guide "Deploy a Linode Kubernetes Engine Cluster Using Pulumi"

- docs/products/tools/marketplace/guides/focalboard/index.md
Updated supported distros
New focalboard script: https://github.com/akamai-compute-marketplace/marketplace-apps/blob/main/deployment_scripts/linode-marketplace-focalboard/focalboard-deploy.sh
> [update] Deploy Focalboard through the Linode Marketplace

- docs/guides/tools-reference/tools/how-to-use-glances-system-monitoring/index.md
Changed two instances of '61208' to '61209' in the 'Setting up Clients and Servers' section so to accurately reflect the port that is open by default
> [Update] Use Glances for System Monitoring

- docs/guides/linode-writers-formatting-guide/index.md
This PR adds the new placeholder shortcode to the Linode Writer's Formatting guide. It also clarifies preferred usage of example IP addresses, adds examples, and adds IPv6 documentation range.
> Adds placeholder shortcode to formatting guide

- docs/guides/game-servers/deploy-7-days-to-die-linux-game-server/index.md
_ updated the packages that need to be installed
- fixes: https://github.com/linode/docs/issues/6613
Tested and validated that netcat-traditional is required.
```Do you want to continue? [Y/n] y
Get:1 http://mirrors.linode.com/ubuntu jammy/universe amd64 netcat-traditional amd64 1.10-47 [63.3 kB]
Fetched 63.3 kB in 1s (48.8 kB/s)             
Selecting previously unselected package netcat-traditional.
(Reading database ... 75240 files and directories currently installed.)
Preparing to unpack .../netcat-traditional_1.10-47_amd64.deb ...
Unpacking netcat-traditional (1.10-47) ...
Setting up netcat-traditional (1.10-47) ...
Processing triggers for man-db (2.10.2-1) ...
Scanning processes...                                                           
Scanning candidates... …
```
> [update] Deploying a 7 Days to Die Server on Linux

- docs/products/tools/images/_index.md
Clarified that the Maximum image size should be 6 GB when uncompressed.
Fixes: https://github.com/linode/docs/issues/6637
> [update] Images > Overview

- docs/guides/development/python/pytorch-installation-ubuntu-2004/index.md
Fixes: https://github.com/linode/docs/issues/6265
Tested and validated the commands and updated the guide.
```
rajie@pytorch:~/anaconda$ python3
Python 3.8.10 (default, May 26 2023, 14:05:08) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> print (torch.cuda.is_available)
<function is_available at 0x7fcb6a241040>
>>> print (torch.cuda.is_available())
False
>>> print (torch.cuda.device_count)
<function device_count at 0x7fcb6a25f940>
>>> print (torch.cuda.device_count())
0
>>> 
```
> [update] Install PyTorch on Ubuntu 20.04

- docs/products/compute/compute-instances/guides/distributions/index.md
This PR makes the following changes to the distros page:
- Removes Alpine 3.14, Fedora 36, Ubuntu 18.04 and 16.04
- Adds Fedora 39, Ubuntu 23.10
- Marks Alpine 3.15 and Ubuntu 22.10 as deprecated
- Clarifies that AlmaLinux and Rocky Linux are not quite binary compatible derivatives of RHEL.
> [Update] Choosing a Linux Distribution

- docs/guides/applications/configuration-management/packer/how-to-use-linode-packer-builder/index.md
New URL is https://developer.hashicorp.com/packer/integrations/linode/linode
> Update Linode Packer Builder docs with new upstream link

- docs/products/compute/kubernetes/guides/high-availability-control-plane/index.md
Fixes naming nits:
- "cloud control manager" -> "cloud controller manager" ([CCM repo](https://github.com/linode/linode-cloud-controller-manager), [K8s docs](https://kubernetes.io/docs/concepts/architecture/cloud-controller/))
- `kube-api-server` -> `kube-apiserver` ([K8s docs](https://kubernetes.io/docs/reference/command-line-tools-reference/kube-apiserver/))
> [Fix] CCM and apiserver naming nits

- docs/products/databases/managed-databases/guides/postgresql-connect/index.md
_ added a link to the documentation that provides information about creating users and databases.
> [update] Connect to a PostgreSQL Database

- _vendor/github.com/linode/linode-api-docs/v4/openapi.yaml
- _vendor/modules.txt
- docs/release-notes/api/v4.170.2.md
- go.mod
- go.sum
-   **Linode Resize** ([POST /linode/instances/{linodeId}/resize](/docs/api/linode-instances/#linode-resize))
- Added `type` property with two values:
- `warm`: the Linode remains powered on until the migration is complete.
- `cold`: the Linode is powered down and migrated. When the migration is complete, the Linode is powered on.
-   **Linode Migrate** ([POST /linode/instances/{linodeId}/migrate](/docs/api/linode-instances/#dc-migrationpending-host-migration-initiate))
- Added `migration_type` property with two values:
- `warm`: the Linode remains powered on until the migration is complete.
- `cold`: the Linode is powered down and migrated. When the migration is complete, the Linode is powered on.
> [API] 4.170.2

- _vendor/github.com/linode/linode-api-docs/v4/openapi.yaml
- _vendor/modules.txt
- docs/release-notes/api/v4.170.2.md
- go.mod
- go.sum
API Updates (v4.170.2):
-   **Linode Resize** ([POST /linode/instances/{linodeId}/resize](/docs/api/linode-instances/#linode-resize))
- Added `type` property with two values:
- `warm`: the Linode remains powered on until the migration is complete.
- `cold`: the Linode is powered down and migrated. When the migration is complete, the Linode is powered on.
-   **Linode Migrate** ([POST /linode/instances/{linodeId}/migrate](/docs/api/linode-instances/#dc-migrationpending-host-migration-initiate))
- Added `migration_type` property with two values:
- `warm`: the Linode remains powered on until the migration is complete.
- `cold`: the Linode is powered down and migrated. When the migration is complete, the Linode is powered on.
> [Release] v1.296.0

- docs/products/platform/get-started/guides/beta-for-new-data-centers/index.md
For Madrid LA, added the following to **Limited Beta for Akamai's New Data Centers** doc:
- data center ID (for IP Sharing and Failover)
- region ID (for the List of New Data Centers)
- cluster ID and cluster URL (for Object Storage)
- Lish gateway info (for Lish Gateways): Lish SSH Gateway, Lish SSH Gateway Fingerprints, Weblish/Glish Gateway
> Updated Limited Beta doc with Madrid LA details

- docs/guides/email/email-services/using-magicspam-email-authentication/index.md
- docs/guides/game-servers/create-an-ark-server-on-ubuntu/index.md
- docs/products/compute/compute-instances/plans/dedicated-cpu/index.md
- docs/products/tools/marketplace/guides/_index.md
- docs/products/tools/marketplace/guides/ark-survival-evolved/index.md
- docs/products/tools/marketplace/guides/bitninja/index.md
- docs/products/tools/marketplace/guides/magicspam/index.md
- docs/products/tools/marketplace/guides/mistio/index.md
- docs/products/tools/marketplace/guides/percona-monitoring-management/index.md
- docs/products/tools/marketplace/guides/team-fortress-2/index.md
- docs/products/tools/marketplace/guides/terraria/index.md
Updated the following guides for Marketplace App deprecation:
- Deploy Terraria through the Linode Marketplace (deprecated)
- Deploy a Team Fortress 2 Server through the Linode Marketplace (deprecated)
- Deploy an ARK Survival Evolved Server through the Linode Marketplace (deprecated)
- Creating a Dedicated ARK Server on Ubuntu: Removed note pointing to Marketplace deployment guide; updated cross-play note
- Deploy MagicSpam through the Linode Marketplace (deprecated)
- Using MagicSpam to Secure your Email Server: Removed text pointing to Marketplace deployment guide
- Deploy BitNinja through the Linode Marketplace (deprecated)
- Deploy Percona Monitoring and Management (PMM) through the Linode Marketplace (deprecated)
- Deploy Mist.io through the Linode Marketplace (deprecated)
> Updated guides for multiple deprecated Marketplace Apps

- docs/products/tools/cli/guides/install/index.md
If a user installs the Linode CLI through pip3 on a fresh macOS instance (and perhaps other operating systems), they may receive a warning that their system's Python bin directory isn't in their PATH environment variable. If the user takes no action and proceeds to run a `linode-cli` command, the command won't be found. To overcome this, they'll need to update PATH. Instructions for doing this vary, so none are provided at this time.
> [Update] Install and Configure the Linode CLI

- _vendor/github.com/linode/linode-docs-theme/layouts/_default/alternative-guides-parent.html
- _vendor/github.com/linode/linode-docs-theme/layouts/_default/single.html
- _vendor/github.com/linode/linode-docs-theme/layouts/_default/tabbed-section-layout.html
- _vendor/github.com/linode/linode-docs-theme/layouts/partials/sections/navigation/recommendations-cards.html
- _vendor/github.com/linode/linode-docs-theme/layouts/products/single.html
- _vendor/modules.txt
- go.mod
- go.sum
This PR fixes an issue where the "Related Content" heading is displayed on all guides, even if the guide does not have related content.
> Update theme (2024-02-20)

- _vendor/github.com/linode/linode-api-docs/v4/openapi.yaml
- _vendor/modules.txt
- docs/release-notes/api/v4.173.0.md
- go.mod
- go.sum
- Added API v4.173.0 Release Notes
- Updated API Docs to v4.173.0
> API Docs v4.173.0

- docs/release-notes/lke/v1.63.0.md
* Upgraded kernel version to 6.1 for new LKE nodes.
* Fix added to address CVE-2024-21626.
> Updated LKE 1.63.0 rel notes with new fix

- docs/release-notes/lke/v1.67.0.md
1.67.0 was initially retracted from [this PR](https://github.com/linode/docs/pull/6868/commits/f2c534581a0ce4359837bdc82e22b5f306b12db6#diff-a91fcead1ade05ef0cc1304aaedccbe37dd2ed90fca6546a817c96136a1ba2b0). Re-adding it here.
> Add LKE 1.67.0 changelog

- CONTRIBUTING.md
- _vendor/github.com/linode/linode-docs-theme/layouts/partials/components/render-svg.html
- _vendor/github.com/linode/linode-docs-theme/layouts/partials/sections/search/get-sections-meta.html
- _vendor/modules.txt
- docs/products/_index.md
- docs/reference-architecture/_index.md
- go.mod
- go.sum
- netlify.toml
Theme updates:
- Revert theme update for Hugo 0.125.3 upgrade
- Revert contributing.md, netlify.toml, and section page configurations for Hugo 0.125.3 upgrade
- Fix for double-click recognizer interacting with pan/zoom buttons on SVG diagrams
> [Release] v1.320.0

- docs/release-notes/api/v4.174.0.md
- docs/release-notes/api/v4.175.0.md
Missed including release notes entries for these two releases.
> Release notes for API v4.174.0 and v4.175.0

- _vendor/github.com/linode/linode-api-docs/v4/openapi.yaml
- _vendor/modules.txt
- go.mod
- go.sum
Updated account availability-related endpoints, to apply new functionality and bring them from beta to GA:
-  **Account Availability** (GET /account/availability)
-  **Region Service Availability** (GET /account/availability/{id})
- **Service Transfer Create** (POST /account/service-transfers]). Included VPC in list of services that a Linode can't use.
- **VPC-related fixes**:
- Corrections to `nat_1_1` objects for proper support.
- Proper IP address formatting for VPC IP addresses.
- **IP Addresses List** (GET /linode/instances/{linodeId}/ips). Corrected response example to show VPC's displayed as objects in an array and added ipv4.vpc attribute to x-linode-cli-subtables.
- **Domain Clone** (POST /domains/{domainId}/clone). Updated regex examples to proper format.
- **IP Addresses List** …
> Update API reference to api spec v4.176.0

- docs/guides/databases/mariadb/how-to-install-mariadb-on-debian-10/index.md
- To align with the usage of `mariadb` client as it used by the official MariaDB website.
- This change helps remove confusion by using consistent terminology throughout the documentation.
Please [`check this article`](https://mariadb.com/docs/server/connect/clients/mariadb-client/#Client_10.3_and_Older) as it said:
```
Modern versions of MariaDB Client use client binary filename of mariadb
For MariaDB Client 10.3 and older, the client binary filename was mysql rather than mariadb.
```
Note that the LTS version of MariaDB is `10.11`!
- I checked the page manually and confirmed it looks great
> Use `mariadb` client instead of `mysql` in `docs/guides/how-to-install-mariadb-on-debian-10`

- docs/products/tools/longview/get-started/index.md
- docs/products/tools/longview/guides/apache/index.md
- docs/products/tools/longview/guides/manage/index.md
This PR fixes an display issue introduced in the latest Hugo upgrade (based on looking at recent Netlify previews). The issue only affected some Longview pages as they were one of the first to introduce tab functionality and used an older syntax.
- [Live site](https://www.linode.com/docs/products/tools/longview/get-started/#start-agent) (broken formatting)
- [Netlify preview](https://deploy-preview-6967--nostalgic-ptolemy-b01ab8.netlify.app/docs/products/tools/longview/get-started/#start-agent) (fixed formatting)
> Fix tab formatting in Longview guides

- docs/products/networking/vpc/_index.md
Modified limitation pertaining to Metadata service support (supported, but cloud-init is not).
> [Update] VPC Overview

- docs/guides/applications/containers/build-a-cloud-native-private-registry-with-quay/index.md
- docs/guides/applications/containers/create-a-dagger-pipeline/index.md
- docs/guides/applications/containers/remove-docker-resources/index.md
- docs/guides/applications/media-servers/live-streaming-with-livekit-and-obs/index.md
- docs/guides/applications/project-management/how-to-use-n8n-to-automate-workflows/index.md
- docs/guides/databases/general/how-to-install-and-use-replibyte/index.md
- docs/guides/databases/harperdb/create-a-harperdb-cluster/index.md
- docs/guides/databases/mariadb/how-to-set-up-mariadb-galera-clusters-on-ubuntu-2204/index.md
- docs/guides/databases/neo4j/installing-and-configuring-neo4j-on-ubuntu-2204/index.md
- docs/guides/databases/postgresql/manage-replication-failover-on-postgresql-cluster-using-repmgr/index.md
- docs/guides/databases/surrealdb/getting-started-with-surrealdb/index.md
- docs/guides/development/javascript/build-mern-stack-chat-application/index.md
- docs/guides/development/javascript/deploy-a-mern-stack-application/index.md
- docs/guides/development/version-control/speed-up-your-development-process-with-turborepo/index.md
- docs/guides/email/email-services/how-to-install-and-use-postal/index.md
- docs/guides/email/iredmail/how-to-install-and-configure-iredmail/index.md
- docs/guides/security/vulnerabilities/emulate-syn-flood-attack-with-kali-linux/index.md
- docs/guides/tools-reference/tools/load-testing-with-jmeter/index.md
- docs/guides/uptime/logs/how-to-use-fluentd-for-data-logging/index.md
- docs/guides/web-servers/apache/how-to-install-apache-ubuntu-2004/index.md
- docs/guides/web-servers/lamp/how-to-install-lamp-stack-on-fedora-alma-rocky-linux/index.md
- docs/guides/web-servers/nginx/deploying-nginx-docker-container/index.md
- docs/guides/websites/cms/strapi/using-strapi-cms/index.md
- docs/products/compute/compute-instances/guides/monitor-and-maintain/index.md
This PR uses the `scripts/update-internal-links.py` script to find outdated internal links and update them to the latest URL of the destination guide.
> Fix internal links

- ci/vale/styles/Linode/SubstitutionWarning.yml
- docs/guides/applications/configuration-management/puppet/getting-started-with-puppet-6-1-basic-installation-and-setup/index.md
- docs/products/compute/compute-instances/faqs/_index.md
- docs/products/compute/compute-instances/guides/rescue-and-rebuild/index.md
- docs/products/compute/compute-instances/guides/set-up-and-secure/index.md
- docs/products/compute/compute-instances/guides/troubleshooting-firewall-issues/index.md
- docs/products/compute/kubernetes/get-started/index.md
- docs/products/compute/kubernetes/guides/kubectl/index.md
- docs/products/compute/kubernetes/guides/kubernetes-dashboard/index.md
- docs/products/platform/accounts/guides/parent-child-accounts/index.md
- docs/products/platform/accounts/guides/user-security-controls/index.md
- docs/products/platform/accounts/resources/index.md
- docs/products/storage/object-storage/get-started/index.md
- docs/products/storage/object-storage/guides/acls/index.md
- docs/products/tools/marketplace/guides/antmediaenterpriseserver/index.md
- docs/products/tools/marketplace/guides/antmediaserver/index.md
- docs/products/tools/marketplace/guides/chevereto/index.md
- docs/products/tools/marketplace/guides/cyberpanel/index.md
- docs/products/tools/marketplace/guides/gopaddle/index.md
- docs/products/tools/marketplace/guides/hashicorp-nomad-clients-cluster/index.md
- docs/products/tools/marketplace/guides/mainconcept-ffmpeg-plugins-demo/index.md
- docs/products/tools/marketplace/guides/mainconcept-live-encoder-demo/index.md
- docs/products/tools/marketplace/guides/peppermint/index.md
- docs/products/tools/marketplace/guides/rust/index.md
- docs/products/tools/marketplace/guides/simplex/index.md
- docs/products/tools/marketplace/guides/vscode/index.md
- docs/products/tools/marketplace/guides/warpspeed/index.md
- docs/products/tools/marketplace/guides/zabbix/index.md
This PR adds the following Vale substitution warnings:
- "[Ll]ogin to": log in to
- "[Ll]og into": log in to
- "[Ll]ogged into": logged in to
- "[Ll]ogging into": logging in to
Incorrect instances of these terms were fixed in the /docs/products/ section.
> Added vale substitution warning for variations of "log into" -> "log in to" 

- docs/guides/applications/containers/remove-docker-resources/index.md
- docs/guides/databases/concepts/what-is-database-sharding/index.md
- docs/guides/development/javascript/how-to-use-filter-method-javascript/index.md
- docs/guides/development/javascript/how-to-use-javascript-fetch-api/index.md
- docs/guides/tools-reference/tools/how-to-use-ack-command/index.md
- docs/guides/web-servers/nginx/using-openresty/index.md
In 5 guides, removed links from external resources:
- How to Remove Docker Images, Containers, and Volumes
- What Is Database Sharding?
- How to Use the JavaScript Fetch API
- How to Use the ack Command on Linux
- How to Use the OpenResty Web Server
Also removes parenthesis in title for: How to Use the filter Method for Arrays in JavaScript
> Remove links from various external resources sections

- docs/products/platform/accounts/guides/user-security-controls/index.md
Changed 2FA timeout from 90 to 30 days.
(Platform>Accounts>Guides)
> [UPDATE] Security Controls for User Accounts

- docs/guides/development/python/installing-and-importing-modules-in-python-3/index.md
- docs/guides/kubernetes/how-to-setup-a-private-docker-registry-with-lke-and-object-storage/index.md
- docs/guides/platform/migrate-to-linode/migrating-a-server-to-your-linode/index.md
- docs/guides/tools-reference/linux-package-management/linux-package-management-overview/index.md
- docs/guides/websites/hosting/host-a-website-with-high-availability/index.md
- docs/products/compute/compute-instances/guides/manage-ip-addresses/index.md
- docs/products/compute/compute-instances/guides/resize/index.md
This change does a pass through the documentation for misuse of "manger" instead of "manager".
> Fix mistyped "manager" in various documentation.

- docs/products/compute/kubernetes/guides/deploy-and-manage-cluster-with-the-linode-api/index.md
This PR fixes several issues reported within the new [Add Labels and Taints to your LKE Node Pools](https://www.linode.com/docs/products/compute/kubernetes/guides/deploy-and-manage-cluster-with-the-linode-api/#add-labels-and-taints-to-your-lke-node-pools) section.
> [Update] Deploy and Manage a Linode Kubernetes Engine (LKE) Cluster with the Linode API

- docs/products/tools/marketplace/guides/wazuh/index.md
Update the Wazuh docs to address customer feedback regarding setting up a Wazuh Agent
> [update] Deploy Wazuh Cluster through the Linode Marketplace

- docs/products/compute/kubernetes/_index.md
This PR updates the technical specs for LKE. Specifically, it removes compute resource ranges and instead links out to the pricing page. It also lets readers know that the 512 GB plan size is not available.
Preview: [LKE > Overview](https://deploy-preview-7031--nostalgic-ptolemy-b01ab8.netlify.app/docs/products/compute/kubernetes/#technical-specifications)
> [Update] LKE > Overview

- docs/products/compute/compute-instances/_index.md
- docs/products/compute/compute-instances/developers/index.md
- docs/products/compute/compute-instances/get-started/index.md
- docs/products/compute/compute-instances/guides/_index.md
- docs/products/compute/compute-instances/guides/placement-groups/index.md
- docs/products/compute/compute-instances/resources/index.md
"Work with Placement Groups" topic fixes:
* Topic was inheriting 1/18/2023 as the last modified date from the parent _index.md file.
* Changes based on feedback during a team call, to help clarify "Affinity Type."
> Fix to modified date and concept clarification

- docs/products/tools/marketplace/guides/openlitespeed-django/index.md
This PR fixes a small issue with the output shortcode syntax in the OpenLiteSpeed Django guide.
> [Fix] Deploy OpenLiteSpeed Django through the Linode Marketplace

- docs/products/networking/dns-manager/guides/common-dns-configurations/index.md
- docs/products/storage/object-storage/get-started/index.md
- docs/products/tools/marketplace/guides/counter-strike-go/index.md
- docs/products/tools/marketplace/guides/wireguard/index.md
This PR removes embedded youtube videos from all guides (4) within product documentation.
> Remove embedded YouTube videos within product docs

- ci/vale/dictionary.txt
- docs/guides/applications/containers/installing-docker-shortguide/index.md
- docs/guides/kubernetes/how-to-deploy-a-static-site-on-linode-kubernetes-engine/index.md
Updates the static site LKE guide:
- New Alpine version in Docker Image
- New timestamps
- Adds note re: Hugo version .toml file naming conventions
- Misc. copy edits
Updates to installing-docker-shortguide:
- Copy edit with instructions for installing Docker on Mac and Windows
Entry added to dictionary.txt
> [Updated] Deploy a Static Site on Linode Kubernetes Engine

- docs/products/compute/compute-instances/guides/manage-ip-addresses/index.md
This information adds a small section to the **Managing IP Addresses on a Compute Instance** guide to help readers understand how to confirm that their network settings are correctly configured on their instance. Primarily, it serves to link out to our other guides that cover these topics in more detail.
> [Update] Managing IP Addresses on a Compute Instance

- docs/guides/kubernetes/deploy-volumes-with-the-linode-block-storage-csi-driver/index.md
- docs/guides/kubernetes/install-the-linode-block-storage-csi-driver-on-unmanaged-kubernetes/index.md
- Deploying Persistent Volume Claims with the Linode Block Storage CSI Driver
- Install the Linode Block Storage CSI Driver on Kubernetes
> Deprecate Linode Block Storage CSI driver guides

- docs/guides/applications/configuration-management/terraform/how-to-build-your-infrastructure-using-terraform-and-linode/index.md
- docs/guides/applications/configuration-management/terraform/how-to-use-terraform-with-linode-object-storage/index.md
Updated two guides with steps on how to configure Terraform to use Linode OBJ as a backend to write state:
- Use Terraform to Provision Infrastructure on Linode
- Use Terraform With Linode Object Storage (points to Terraform Provision guide)
> [Updated] Terraform guides with steps for storing state on OBJ

- docs/products/compute/compute-instances/guides/lassie-shutdown-watchdog/index.md
- docs/products/platform/accounts/guides/manage-api-tokens/index.md
These will fail the build in the next Hugo version, but should be fixed even if you never plan to upgrade.
> Fix some invalid front matter dates

- ci/vale/dictionary.txt
- docs/contributors/leon-yen/_index.md
- docs/guides/tools-reference/file-transfer/comparing-data-transfer-utilities/index.md
New guide written by Leon Yen (contributor) comparing various data transfer utilities.
Also updated:
- dictionary.txt
- added contributor page for Leon Yen
> [New] Comparing Data Transfer Utilities

- docs/guides/security/firewalls/control-network-traffic-with-iptables/index.md
* the text below the commands are now in a sequence
* fixes: https://github.com/linode/docs/issues/3727
> [update] A Tutorial for Controlling Network Traffic with iptables

- .github/workflows/update-algolia-on-schedule.yaml
- CONTRIBUTING.md
- _vendor/github.com/linode/linode-docs-theme/config.toml
- _vendor/github.com/linode/linode-docs-theme/layouts/partials/sections/head-src.html
- _vendor/github.com/linode/linode-docs-theme/layouts/shortcodes/content.html
- _vendor/modules.txt
- ci/vale/dictionary.txt
- config.toml
- docs/guides/databases/general/database-solutions/index.md
- docs/guides/databases/mysql/install-mysql/index.md
- docs/guides/databases/mysql/mysql-command-line-client/index.md
- docs/guides/databases/mysql/mysqldump-backups/index.md
- docs/guides/databases/sql-syntax/sharded-database/index.md
- docs/guides/security/ssl/_shortguides/installing-snapd-certbot-dnf-rhel-shortguide/index.md
- docs/guides/security/ssl/enabling-https-using-certbot-with-apache-on-fedora/index.md
- docs/guides/security/ssl/enabling-https-using-certbot-with-nginx-on-fedora/index.md
- docs/guides/uptime/loadbalancing/how-to-use-haproxy-for-load-balancing/index.md
- docs/marketplace-docs/guides/jenkins/index.md
- docs/marketplace-docs/guides/plesk/index.md
- docs/marketplace-docs/guides/secure-your-server/index.md
- docs/marketplace-docs/guides/wireguard/index.md
- docs/marketplace-docs/guides/zabbix/index.md
- docs/products/databases/managed-databases/_shortguides/dbass-eos/index.md
- go.mod
- go.sum
- netlify.toml
Updated for DBaaS product relaunch:
- Installing MySQL: A Definitive Guide
- Backing Up MySQL Databases Using mysqldump
- Determine the Best Database and Cloud Hosting Solution for Your Next Application
- Database Sharding: Concepts, Examples, and Strategies
- Connect to a MySQL Database Using the mysql Command
- dbass-eos shortguide
Other:
- Using HAProxy for Load Balancing; grammar and copy edits
- Refactor content shortcode
- Update to Hugo 0.138.0
> [Release Candidate] v1.355.0

- docs/guides/networking/dns/advanced-troubleshooting-dns-problems/index.md
Proposing just a quick correction: this should reference `/etc/resolv.conf`.
> The correct file name is resolv.conf

- docs/guides/kubernetes/install-the-linode-ccm-on-unmanaged-kubernetes/index.md
This PR updates instructions for manual install of CCM on a k8s cluster. Since terraform k8s provider for linode is deprecated, this PR also removes reference to it and instead suggests to use CAPL as an alternative.
> [update] : update ccm install docs

- docs/guides/quick-answers/linux/linux-mount-smb-share/index.md
fixed the command after validating
fixes: https://github.com/linode/docs/issues/7155
> [update] Mount an SMB Share in Linux

- docs/guides/web-servers/caddy/how-to-install-and-configure-caddy-on-debian-10/index.md
- Updated the installation command after validating on Debian 10
- fixes https://github.com/linode/docs/issues/7154
> [update] Installing and Configuring the Caddy Web Server on Debian 10

- docs/guides/security/firewalls/what-is-iptables/index.md
Fixes: https://github.com/linode/docs/issues/7131
Updated the tables and the chains supported after validating:
```
root@localhost:~# sudo iptables -t nat -L
Chain PREROUTING (policy ACCEPT)
target     prot opt source               destination         
Chain INPUT (policy ACCEPT)
target     prot opt source               destination         
Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination         
Chain POSTROUTING (policy ACCEPT)
target     prot opt source               destination     
```
> [Update]Understanding iptables

- docs/guides/security/basics/securing-nginx-with-modsecurity/index.md
Fixes: https://github.com/linode/docs/issues/6803
Tested, validated, and updated the guide.
```
rajie@nginx:/opt/nginx-1.18.0$ sudo make modules
make -f objs/Makefile modules
make[1]: Entering directory '/opt/nginx-1.18.0'
cc -c -fPIC -pipe  -O -W -Wall -Wpointer-arith -Wno-unused-parameter -Werror -g -g -O2 -fdebug-prefix-map=/build/nginx-09OHwu/nginx-1.18.0=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -Wdate-time -D_FORTIFY_SOURCE=2 -I src/core -I src/event -I src/event/modules -I src/os/unix -I /usr/local/modsecurity/include -I /usr/include/libxml2 -I objs -I src/http -I src/http/modules -I src/http/v2 -I src/mail -I src/stream \
-o objs/src/http/modules/ngx_http_xslt_filter_module.o \
src/http/modules/ngx_http_xslt_filter_module.c
cc -c -fPIC -pipe  -O -W -Wall …
```
> [update] Securing Nginx With ModSecurity

- docs/guides/applications/remote-desktop/troubleshooting-virtual-network-computing/index.md
New title: Troubleshooting Virtual Network Computing
This guide is in reference to applications like RealVNC, and the VNC acronym actually stands for virtual network computing, not connections:
https://en.wikipedia.org/wiki/VNC
> Rename and move Troubleshooting Virtual Network Connections guide

- docs/marketplace-docs/guides/owncast/index.md
Updates MERN OCA guide for new deployment distribution
> [Update] Owncast OCA

- docs/guides/networking/vpn/strongswan-vpn-server-install/index.md
Tested and validated the guide and then updated the commands.
Fixes: https://github.com/linode/docs/issues/6062
```
rajie@ss:~$ sudo apt-get update && sudo apt-get upgrade
[sudo] password for rajie: 
Hit:1 http://mirrors.linode.com/ubuntu focal InRelease
Hit:2 http://mirrors.linode.com/ubuntu focal-updates InRelease
Hit:3 http://mirrors.linode.com/ubuntu focal-backports InRelease
Hit:4 http://security.ubuntu.com/ubuntu focal-security InRelease
Reading package lists... Done         
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
rajie@ss:~$ sudo apt install strongswan strongswan-pki libcharon-extra-plugins libcharon-extauth-plugins …
```
> [update] Install and Configure a StrongSwan Gateway VPN Server

- ci/vale/dictionary.txt
- docs/contributors/michael-archer/_index.md
- docs/guides/game-servers/set-up-a-xonotic-game-server-with-k3s-and-agones/index.md
- docs/guides/networking/vpn/strongswan-vpn-server-install/index.md
- docs/marketplace-docs/guides/aapanel/index.md
- docs/marketplace-docs/guides/gitlab/index.md
- docs/marketplace-docs/guides/mern-stack/index.md
- docs/marketplace-docs/guides/mysql/index.md
- docs/marketplace-docs/guides/owncast/index.md
- docs/marketplace-docs/guides/plex/index.md
New:
- Set Up a Xonotic Game Server with K3s and Agones
Updated:
- Deploy a MERN Stack through the Linode Marketplace
- Deploy Owncast through the Linode Marketplace
- Deploy MySQL/MariaDB through the Linode Marketplace
- Deploy Plex Media Server through the Linode Marketplace
- Install and Configure a StrongSwan Gateway VPN Server on Ubuntu 20.04
> [Release] v1.368.0

- docs/marketplace-docs/guides/apache-spark-cluster/index.md
Updated the Apache Spark Marketplace documentation to reflect Ubuntu 24.04 instead of Ubuntu 22.04. Verified compatibility and made necessary adjustments to commands and references.
Tested the guide locally using Hugo.
> Update Apache Spark Marketplace guide to use Ubuntu 24.04

- docs/marketplace-docs/guides/moodle/index.md
- docs/marketplace-docs/guides/pihole/index.md
[update] Deploy Moodle through the Linode Marketplace
[update] Deploy Pihole through the Linode Marketplace
> [update] Pihole & Moodle Marketplace app doc update

- docs/guides/kubernetes/deploy-llm-for-ai-inferencing-on-apl/index.md
- docs/guides/kubernetes/deploy-rag-pipeline-and-chatbot-on-apl/index.md
- docs/guides/kubernetes/inter-service-communication-with-rabbitmq-and-apl/index.md
Updated App Platform guides for platform updates during beta period:
- Deploy an LLM for AI Inferencing with App Platform for LKE
- Deploy a RAG Pipeline and Chatbot with App Platform for LKE
- Set Up Inter-Microservice Communication Using RabbitMQ On App Platform For LKE
> [Updated] APL guides and platform changes

- _vendor/github.com/linode/linode-docs-theme/layouts/partials/sections/body-structured-data.html
- _vendor/modules.txt
- docs/guides/databases/postgresql/managed-postgresql-databases-on-akamai-cloud-with-terraform/index.md
- go.mod
- go.sum
Updates:
- Managed PostgreSQL Databases on Akamai Cloud with Terraform
Theme updates:
- Schema.org metadata updates
> [Release] v1.376.0

- docs/guides/kubernetes/use-app-platform-to-deploy-wordpress/index.md
- docs/guides/security/secrets-management/deploy-openbao-on-linode-kubernetes-engine/index.md
- docs/guides/security/secrets-management/deploying-openbao-on-a-linode-instance/index.md
Updated the following guides:
- **Deploying OpenBao on a Linode Instance**: added link to Deploy OpenBao on Linode Kubernetes Engine guide, copy edit
- **Deploy OpenBao on Linode Kubernetes Engine**: added link to Deploying OpenBao on a Linode Instance guide
- **Use App Platform to Deploy WordPress with Persistent Volumes on LKE**: updated publish date, added link to App Platform documentation
> [Updated] Multiple guide edits

- docs/guides/kubernetes/deploy-llm-for-ai-inferencing-on-apl/index.md
- docs/guides/kubernetes/deploy-rag-pipeline-and-chatbot-on-apl/index.md
- docs/guides/kubernetes/inter-service-communication-with-rabbitmq-and-apl/index.md
- docs/guides/kubernetes/use-app-platform-to-deploy-wordpress/index.md
Updated App Platform product documentation URLs in the following guides:
- Use App Platform to Deploy WordPress with Persistent Volumes on LKE
- Deploy an LLM for AI Inferencing with App Platform for LKE
- Deploy a RAG Pipeline and Chatbot with App Platform for LKE
- Set Up Inter-Microservice Communication Using RabbitMQ On App Platform For LKE
> [Updated] App Platform Guides

- docs/guides/databases/surrealdb/surrealdb-for-web-applications/index.md
`DEFINE LOGIN` is incorrect. It should be `DEFINE USER`
> fix: Corrected surrealql statement.

- docs/guides/applications/configuration-management/terraform/create-a-multicloud-infrastructure-using-terraform/index.md
- docs/guides/applications/configuration-management/terraform/create-a-nodebalancer-with-terraform/index.md
- docs/guides/applications/configuration-management/terraform/create-terraform-module/index.md
- docs/guides/applications/configuration-management/terraform/deploy-a-wordpress-site-using-terraform-and-linode-stackscripts/index.md
- docs/guides/applications/configuration-management/terraform/how-to-build-your-infrastructure-using-terraform-and-linode/index.md
- docs/guides/applications/configuration-management/terraform/how-to-deploy-secure-linodes-using-cloud-firewalls-and-terraform/index.md
- docs/guides/applications/configuration-management/terraform/how-to-use-terraform-with-linode-object-storage/index.md
- docs/guides/applications/configuration-management/terraform/import-existing-infrastructure-to-terraform/index.md
- docs/guides/applications/configuration-management/terraform/secrets-management-with-terraform/index.md
Updated multiple guides for newest Linode Terraform Provider and Terraform versions:
- Use Terraform With Linode Object Storage
- Creating a Multicloud Infrastructure Using Terraform
- Deploy Secure Linodes using Cloud Firewalls and Terraform
- Import Existing Infrastructure to Terraform
- Create a Terraform Module
- Managing Secrets with Terraform
- Deploy a WordPress Site Using Terraform and Linode StackScripts
- Create a NodeBalancer with Terraform
- Use Terraform to Provision Infrastructure on Linode
> [Updated] Terraform Provider Version

- docs/guides/kubernetes/deploy-rag-pipeline-and-chatbot-on-apl/index.md
Added temporary note re: guide functionality related to platform updates
> [Updated] Deploy a RAG Pipeline and Chatbot with App Platform for LKE

- ci/vale/dictionary.txt
- docs/marketplace-docs/guides/jaeger/index.md
Adds documentation for a new Marketplace app: Jaeger "All-in-one"
The app was merged into the `main` branch of the akamai-compute-marketplace repo this week.
https://github.com/akamai-compute-marketplace/marketplace-apps/pull/259
> [Add] Jaeger All-In-One Marketplace OCA Documentation

- docs/marketplace-docs/guides/kali-linux/index.md
* Updates instructions to include the three different Kali packages that can be installed with this updated Marketplace app: Core, Default, and Everything.
* Updates VNC section to reflect app update - VNC is now optional
The new app has already been merged to to the main branch of the akamai-compute-marketplace repo, so this PR can be merged whenever is convenient for your team. 
I also tested it with `hugo server`
> [Update] Kali Linux Marketplace OCA Documentation
