linode/docs

- docs/products/tools/cloud-manager/guides/cloud-email-notifications/index.md
- Updated the link to the latest guide https://www.linode.com/docs/products/tools/monitoring/guides/monitoring-email-alerts
> [Update] Guides - Linode Email Notifications

- docs/guides/platform/marketplace/deploy-shadowsocks-with-marketplace-apps/index.md
- docs/guides/platform/marketplace/deploying-minecraft-with-marketplace-apps/index.md
Minecraft distrobution update & Shadowsocks encryption type update.
> Marketplace update: Minecraft & Shadowsocks

- docs/guides/troubleshooting/rescue-and-rebuild/index.md
Deleted missing space from the note box linking to our Update your fstab guide
> Fixing Update your fstab link

- docs/guides/applications/configuration-management/basics/introduction-to-hcl/index.md
- docs/guides/applications/configuration-management/terraform/create-terraform-module/index.md
- docs/guides/applications/configuration-management/terraform/deploy-a-wordpress-site-using-terraform-and-linode-stackscripts/index.md
- docs/guides/applications/configuration-management/terraform/how-to-build-your-infrastructure-using-terraform-and-linode/index.md
- docs/guides/applications/configuration-management/terraform/how-to-deploy-secure-linodes-using-cloud-firewalls-and-terraform/index.md
- docs/guides/applications/configuration-management/terraform/how-to-provision-an-unmanaged-kubernetes-cluster-using-terraform/index.md
- docs/guides/kubernetes/how-to-deploy-an-lke-cluster-using-terraform/index.md
- Updated the terraform guides with the provider details in the main.tf
- PS: @rsyracuse  There was no need to create a provide.tf and add it as modules in the guide. However, I may be wrong please take a look.
> [Update] Terraform provider details in the main.tf

- _vendor/github.com/linode/linode-api-docs/v4/openapi.yaml
- _vendor/modules.txt
- go.mod
- go.sum
Update API reference to API spec v4.89.0
> Release v1.35.0

- docs/guides/websites/cms/wordpress/install-wordpress-ubuntu-18-04/index.md
Updated with SEO recommendations
> Adding update for WordPress on Ubuntu 18.04 article.

- docs/guides/kubernetes/getting-started-with-load-balancing-on-a-lke-cluster/index.md
Also fixed some typos (serivce.yaml -> service.yaml)
> Include note on TLS termination/intra-cluster endpoints

- docs/products/networking/cloud-firewall/_index.md
> [Update] Cloud Firewall Product Docs

- docs/guides/platform/vlan/getting-started-with-vlans/index.md
- docs/products/networking/vlans/guides/_index.md
- docs/products/networking/vlans/guides/manually-configuring-a-vlan/index.md
- docs/products/networking/vlans/guides/vlans-limitations-shortguide/index.md
Added the **Manually configuring a VLAN on a Linode** guide and adjusted links within other pages as needed.
> [New] Manually configuring a VLAN on a Linode

- docs/guides/platform/managed/linode-managed/index.md
- docs/products/services/managed/guides/_index.md
- docs/products/services/managed/resources/index.md
- added links to community site for cpanel in resources
- added additional note about cpanel installation, and license
- updated the sentence in the guides for more information
> Update [Linode Managed]

- ci/vale/dictionary.txt
- docs/guides/quick-answers/linux/how-to-install-selinux-on-ubuntu-18-04/index.md
Pulling out  the SELinux info  from https://github.com/linode/docs/pull/3971 into its own PR
> How to install selinux on ubuntu 18 04 (Without  nano)

- _vendor/github.com/linode/linode-api-docs/v4/openapi.yaml
- _vendor/modules.txt
- go.mod
- go.sum
Update API reference to API spec v4.90.0
> Release Candidate v1.40.0

- docs/guides/quick-answers/linux/how-to-install-selinux-on-ubuntu-18-04/index.md
-fixed the link to the msql guide
> [Update] How to Install SELinux on Ubuntu 18.04

- _vendor/github.com/linode/linode-api-docs/v4/openapi.yaml
- _vendor/modules.txt
- go.mod
- go.sum
> Release v1.42.1

- ci/vale/dictionary.txt
- docs/guides/platform/marketplace/deploy-cyberpanel-with-marketplace-apps/index.md
- Temporary deprecation of Cyberpanel Marketplace App guide
> [Release Candidate] v1.43.2

- docs/guides/platform/marketplace/deploy-cyberpanel-with-marketplace-apps/index.md
> [Release Candidate] Hotfix v1.43.2 Patch

- docs/guides/websites/wikis/install-mediawiki-on-ubuntu-2004/index.md
Composed a guide for installing MediaWiki on Ubuntu 20.04.
> Guide for installing MediaWiki on Ubuntu 20.04.

- docs/guides/websites/wikis/install-mediawiki-on-centos-8/index.md
Composed a guide for installing MediaWiki on CentOS 8.
> Guide for installing MediaWiki on Centos 8

- docs/guides/applications/configuration-management/basics/introduction-to-hcl/index.md
updated with SEO recommendations
> An update to the HCL introduction.

- docs/guides/platform/disk-images/disk-images-and-configuration-profiles/index.md
- docs/guides/quick-answers/linode-platform/resize-a-linode-disk/index.md
- Add additional information on caveats
> [Update] Disk Images and Configuration Profiles & Resize a Linode Disk

- docs/guides/platform/monitoring/what-is-longview/index.md
Re-organizing, mentioning fedora updates
> [Update] What is Longview

- docs/guides/tools-reference/basics/how-to-use-linux-environment-variables/index.md
Submitting a guide on using environment variables.
> Guide on Environment Variables

- docs/guides/web-servers/nginx/loadbalancer-sticky-session/index.md
> New loadbalancer sticky session

- docs/guides/game-servers/install-steamcmd-for-a-steam-game-server/index.md
Ported in and updated changes to the SteamCMD guide (See [PR 4175](https://github.com/linode/docs/pull/4175))
> Ported in and updated Northcutt changes to the SteamCMD guide

- docs/guides/web-servers/comparison-apache-nginx/index.md
> New comparison apache nginx

- _vendor/github.com/linode/linode-api-docs/v4/openapi.yaml
- _vendor/modules.txt
- go.mod
- go.sum
- Update API reference to API spec v4.93.0
> [Release Candidate] 1.50.0

- ci/vale/dictionary.txt
- docs/guides/development/python/pylint-intro/index.md
> New pdce pylint

- ci/vale/dictionary.txt
- docs/guides/databases/sqlite/nodejs-sqlite/index.md
> New pdce nodejs sqlite

- docs/guides/tools-reference/basics/linux-system-administration-basics/index.md
> [Update] Linux Systems Administration Basics

- docs/guides/kubernetes/getting-started-with-load-balancing-on-a-lke-cluster/index.md
Added note on concurrent connection limit for NodeBalancers
> [Update] Getting Started with Load Balancing on an LKE Cluster

- docs/guides/applications/cloud-storage/dropbox/index.md
- Added info on new required dependencies
> [Update] Installing and Configuring Dropbox

- docs/guides/databases/postgresql/how-to-install-postgresql-on-ubuntu-16-04/index.md
Cherry-pick commits from https://github.com/linode/docs/pull/4179 into a new PR
> [Update] How to Install PostgreSQL on Ubuntu 16.04

- docs/guides/platform/stackscripts/stackscripts-create-linode-shortguide/index.md
- docs/guides/platform/stackscripts/writing-scripts-for-use-with-linode-stackscripts-a-tutorial/index.md
- Further clarification/examples for python and the use of other scripting languages
> [Update] Writing Scripts for Use With Linode Stackscripts

- _vendor/github.com/linode/linode-api-docs/v4/openapi.yaml
- _vendor/modules.txt
- go.mod
- go.sum
Update API reference to API spec v4.94.0
> [Release Candidate] 1.54.0

- docs/products/storage/object-storage/guides/cyberduck/index.md
- docs/products/storage/object-storage/guides/linode-cli/index.md
- docs/products/storage/object-storage/guides/s3cmd/index.md
- docs/products/storage/object-storage/guides/s4cmd/index.md
- [Updated] Using s3cmd with Object Storage
- Fixed front matter in the new Object Storage guides from a recent release
> Updates to Object Storage front matter and s3cmd guide

- ci/vale/dictionary.txt
- docs/guides/development/frameworks/angular/getting-started-angular/index.md
Submitting the guide for getting started with Angular.
> Guide for Getting Started with Angular

- docs/guides/development/frameworks/express/getting-started-express-js/index.md
Submitting the guide for getting started with Express JS.
> Guide for Getting Started with Express JS

- docs/guides/kubernetes/securing-an-lke-cluster-with-rbac/index.md
- Fixes incorrectly closed output block
> [Hotfix] v1.56.1

- _vendor/github.com/linode/linode-api-docs/v4/openapi.yaml
- _vendor/modules.txt
- go.mod
- go.sum
Update API reference to API spec v4.95.0
> [Release Candidate] 1.57.0

- docs/products/compute/dedicated-cpu/_index.md
- docs/products/compute/gpu/_index.md
- docs/products/compute/high-memory/_index.md
- docs/products/compute/kubernetes/_index.md
- docs/products/compute/shared-linodes/_index.md
- docs/products/networking/cloud-firewall/_index.md
- docs/products/networking/ddos-protection/_index.md
- docs/products/networking/dns-manager/_index.md
- docs/products/networking/nodebalancers/_index.md
- docs/products/networking/vlans/_index.md
- docs/products/services/managed/_index.md
- docs/products/services/professional-services/_index.md
- docs/products/storage/backups/_index.md
- docs/products/storage/block-storage/_index.md
- docs/products/tools/billing/_index.md
- docs/products/tools/cli/_index.md
- docs/products/tools/cloud-manager/_index.md
- docs/products/tools/images/get-started/index.md
- docs/products/tools/linode-api/_index.md
- docs/products/tools/marketplace-one-click-apps/_index.md
- docs/products/tools/monitoring/_index.md
- docs/products/tools/stackscripts/_index.md
- Added regions for GPU and Cloud Firewall
- For products with full availability, replaced long list of regions with "available across all regions" message.
> Updated product availability

- docs/guides/platform/manager/dns-manager-add-dns-records-shortguide/index.md
- docs/guides/platform/manager/dns-manager-edit-dns-records-shortguide/index.md
- docs/guides/platform/manager/dns-manager/index.md
clarified propagation time in DNS manager guide
> [Updated] DNS Manager

- docs/guides/platform/get-started/how-to-resell-linode-services/index.md
- Removes discount explanation discrepancy
> [Update] How to Resell Linode Services

- _vendor/github.com/linode/linode-api-docs/v4/openapi.yaml
- _vendor/modules.txt
- go.mod
- go.sum
Update API reference to API spec v4.96.0
> [Release Candidate] 1.59.0

- docs/guides/quick-answers/linux/choosing-a-distribution/index.md
[Updated] Choosing a Linux Distribution: Added AlmaLinux, Rocky Linux, removed CoreOS, added releases/versions, added advice for selecting LTS for production
> [Release Candidate] v1.59.1

- docs/guides/quick-answers/linode-platform/cancel-your-account-shortguide/index.md
- docs/guides/quick-answers/linode-platform/how-to-cancel-your-account/index.md
- Enabled h1 header
- Clarified that any past due balances will be charged when account is cancelled.
> [Updated] Cancelling Your Account

- _vendor/github.com/linode/linode-api-docs/v4/openapi.yaml
- _vendor/modules.txt
- go.mod
- go.sum
> [Release] v1.60.1

- _vendor/github.com/linode/linode-api-docs/v4/openapi.yaml
- _vendor/modules.txt
- go.mod
- go.sum
Update API reference to API spec v4.97.2
> [Release Candidate] v1.61.0

- ci/vale/dictionary.txt
- docs/guides/game-servers/minecraft-with-bungee-cord/index.md
> [Update] Setting up BungeeCord to Link Spigot Servers

- docs/guides/applications/configuration-management/basics/yaml-anchors-aliases-overrides-extensions/index.md
> [New] YAML Anchors, Aliases, and Overrides

- docs/guides/development/frameworks/asp-net/how-to-host-asp-core-on-linux/index.md
Submitting the guide for hosting ASP.NET Core on Linux.
> Guide for Hosting ASP.NET Core on Linux

- ci/vale/dictionary.txt
- docs/guides/applications/messaging/how-to-install-inspircd-on-debian-10-ubuntu-2004/index.md
Submitting the guide for installing InspIRCd on Debian 10 and Ubuntu 20.04.
> Guide for Installing InspIRCd on Debian 10 and Ubuntu 20.04

- docs/guides/platform/nodebalancer/nodebalancer-reference-guide/index.md
- docs/guides/platform/nodebalancer/nodebalancer-ssl-configuration/index.md
- Notes unsupported TLS versions
> [Update] NodeBalancer Reference Guide && NodeBalancer SSL Config

- ci/vale/dictionary.txt
- docs/guides/security/firewalls/how-to-use-nftables/index.md
Submitting the guide on using nftables.
> Guide on nftables

- docs/guides/networking/dns/dns-records-an-introduction/index.md
Added Null MX info to "MX" section.
> [Updated]  DNS Records: An Introduction 

- docs/guides/platform/cloud-firewall/add-new-cloud-firewall-rules-shortguide/index.md
- Added port limitations to *add-new-cloud-firewall-rules-shortguide*, which updates the Add Cloud Firewall Rules page (and associated guide). 
- Minor table formatting changes.
> [Updated] Add Cloud Firewall Rules

- _vendor/github.com/linode/linode-api-docs/v4/openapi.yaml
- _vendor/modules.txt
- go.mod
- go.sum
Update API reference to API spec v4.99.0
> [Release Candidate] v1.66.0

- ci/vale/dictionary.txt
- docs/guides/development/data-visualization/visualize-history/index.md
- docs/guides/kubernetes/getting-started-with-kubernetes/index.md
Fixed ToC issue on two guides.
> [Release Candidate] v1.66.1

- docs/guides/applications/configuration-management/ansible/getting-started-with-ansible/index.md
- docs/guides/applications/media-servers/how-to-install-shoutcast-dnas-server-on-linux/index.md
- docs/guides/databases/mariadb/backup-mariadb-mysql-to-object-storage-with-restic/index.md
- docs/guides/development/version-control/manage-source-code-versions-with-subversion/index.md
- small spelling edits and a few adjustements to docs
Resolves: fix/small_spelling_edits
> Small Spelling Edits To Docs

- docs/guides/tools-reference/basics/how-to-use-usermod-command/index.md
Submitting the guide on what the usermod command is and how to use it.
> Guide on usermod

- _vendor/github.com/linode/linode-api-docs/v4/openapi.yaml
- _vendor/modules.txt
- go.mod
- go.sum
Update API reference to API spec v4.100.1
> [Release Candidate] v1.69.0

- _vendor/github.com/linode/linode-docs-theme/assets/js/main/sections/sections/list.js
- _vendor/modules.txt
- go.mod
- go.sum
- Fix for a bug in the "All guides" view of a section, where
subsections were being rendered like regular guides
---
> Theme update

- docs/guides/platform/get-started/how-to-resell-linode-services/index.md
It should be partnerships@linode.com (with an "s" at the end)
> Fix partnership email

- ci/vale/dictionary.txt
- docs/guides/development/nodejs/how-to-install-nodejs/index.md
I updated some links and fixed some small grammar/syntax issues.
> Small fixes on Node.js install guide

- docs/guides/kubernetes/how-to-configure-load-balancing-with-tls-encryption-on-a-kubernetes-cluster/index.md
Add the text and the link for "What is Kubernetes cert-manager?"
> Fix broken link

- docs/guides/networking/dns/configure-your-linode-for-reverse-dns/index.md
Minor change to Cloud Manager reference (Networking -> Network)
> [Updated] Configure Your Linode for Reverse DNS (rDNS)

- docs/guides/platform/managed/linode-managed/index.md
- docs/guides/platform/managed/managed-add-service-shortguide/index.md
Added a "Configuring Firewall Rules" section (and linked to it from various other sections)
> [Updated] Getting Started with Linode Managed

- docs/guides/tools-reference/basics/restart-linux-server/index.md
Submitting the guide on how to restart a Linux server from the command line.
> Guide on Restarting a Linux Server

- docs/guides/platform/object-storage/server-side-encryption/index.md
- removed the python version 2.7 because it is EOL
- fixes https://github.com/linode/docs/issues/4382
> [update] How to Use Server-Side Encryption with Linode Object Storage

- docs/guides/web-servers/lamp/hosting-a-website-ubuntu-18-04/index.md
> [Update] How a Website on Ubuntu 18.04

- docs/guides/websites/cms/cpanel/set-up-dns-services-on-cpanel/index.md
- docs/guides/websites/hosting/set-up-web-server-host-website/index.md
- docs/products/networking/dns-manager/get-started/index.md
- [Updated] Set Up DNS Services on cPanel
- [Updated] Set up a Web Server and Host a Website on Linode
- [Updated] DNS Manager > Get Started
> Updated AXFR3 IPv4 address

- docs/products/services/professional-services/_index.md
PR removes phone number from guide
> Update Professional Services Doc

- docs/products/storage/object-storage/_shortguides/object-storage-ga-shortguide/index.md
- Fixed incorrect links and updated copy in the `object-storage-ga-shortguide` shortguide.
> [Updated] Object Storage availability shortguide

- _vendor/github.com/linode/linode-api-docs/v4/openapi.yaml
- _vendor/modules.txt
- go.mod
- go.sum
* Update API reference to api spec v4.101.0
> [Hotfix] v4.101.0

- docs/guides/platform/billing-and-support/tax-information/index.md
Revamped "Tax Information" guide. This guide now includes a table showing tax rates by country and an overhauled FAQ section.
> [Updated] Tax Information

- docs/guides/databases/postgresql/how-to-back-up-your-postgresql-database/index.md
> [Update] How to Back Up Your PostgreSQL Database

- docs/guides/platform/marketplace/how-to-deploy-woocommerce-with-marketplace-apps/index.md
Long overdue WooCommerce update. Stackscript hasn't been updated yet but once we're ready to merge this PR I will ensure we coordinate the update with this PR.
> Marketplace update: WooCommerce 

- ci/vale/dictionary.txt
- docs/guides/tools-reference/basics/how-to-check-clean-linux-disk-space/index.md
Submitting the guide for checking and cleaning Linux disk space.
> Guide on Linux Disk Space

- ci/vale/dictionary.txt
- docs/guides/tools-reference/basics/how-to-write-files-from-shell/index.md
Submitting the guide on writing to files from the shell.
> Guide on Writing to Files from the Shell

- docs/guides/platform/marketplace/deploy-moodle-with-marketplace-apps/index.md
- docs/guides/platform/marketplace/deploying-moodle-marketplace-app/index.md
Part of Q3 Marketplace release
> Marketplace add: Moodle

- docs/guides/platform/marketplace/deploy-jetbackup-with-marketplace-apps/index.md
- docs/guides/platform/marketplace/deploying-jetbackup-marketplace-app/index.md
Part of Q3 Marketplace release
> Marketplace add: JetBackup 

- ci/vale/dictionary.txt
- docs/guides/platform/marketplace/deploy-splunk-with-marketplace-apps/index.md
- docs/guides/platform/marketplace/deploying-splunk-marketplace-app/index.md
Part of Q3 Marketplace release
> Marketplace add: Splunk 

- docs/guides/platform/marketplace/deploy-magicspam-with-marketplace-apps/index.md
- docs/guides/platform/marketplace/deploying-magicspam-marketplace-app/index.md
Part of Q3 Marketplace release
> Marketplace add: MagicSpam

- docs/guides/applications/configuration-management/terraform/secrets-management-with-terraform/index.md
> [Update] Secrets Management with Terraform

- _vendor/github.com/linode/linode-api-docs/v4/openapi.yaml
- _vendor/modules.txt
- docs/guides/platform/marketplace/deploy-mysql-with-marketplace-apps/index.md
- docs/guides/quick-answers/linux/choosing-a-distribution/index.md
- go.mod
- go.sum
- [Updated] Deploying MySQL/MariaDB with Marketplace Apps
- [Updated] Choosing a Linux Distribution
- Update API reference to API spec v4.101.1
> [Release Candidate] v1.72.1

- _vendor/github.com/linode/linode-api-docs/v4/openapi.yaml
- _vendor/modules.txt
- docs/guides/platform/marketplace/deploy-mysql-with-marketplace-apps/index.md
- docs/guides/quick-answers/linux/choosing-a-distribution/index.md
- go.mod
- go.sum
* update MySQL/MariaDB guide for ubuntu 20 (#4616)
* Updates to Choosing a Linux Distribution guide
* Update API reference to API spec v4.101.1
Co-authored-by: hmorris3293 <morrisholdenx@gmail.com>
Co-authored-by: bbiggerr <bxbigg@gmail.com>
> [Release Candidate] v1.72.1 (merge into develop)

- docs/guides/platform/marketplace/deploying-nirvashare-marketplace-app/index.md
> Marketplace Update: Nirvashare port update

- docs/guides/networking/linode-network/an-overview-of-ipv6-on-linode/index.md
Fixes reported issues: #4583 and #3509
> Fixed broken link in IPv6 Overview guide

- docs/guides/web-servers/lamp/hosting-a-website-ubuntu-18-04/index.md
- Fixes issue #4605.
- Numbers the steps within the "Hosting Multiple Websites on Ubuntu 18.04" section, with small copy edits as needed.
> [Updated] Hosting a Website on Ubuntu 18.04

- docs/guides/platform/billing-and-support/how-linode-billing-works/index.md
- docs/guides/platform/billing-and-support/manage-billing-in-cloud-manager/index.md
- [Updated] Billing and Payments: Updated Google Pay and PayPal payment method details, including how to use PayPal through Google Pay.
- [Updated] Managing Billing in the Cloud Manager: Added "Deleting Google Pay" section.
> Updated Google Pay and PayPal details within billing guides

- docs/guides/kubernetes/kubernetes-cron-job/index.md
Includes organizational edits, technical edits, and copy edits
> [New] How to Create Kubernetes CronJobs

- docs/guides/development/python/using-python-lists/index.md
Submitting the guide on using Python lists.
> Guide on Using Python Lists

- docs/guides/platform/object-storage/how-to-use-object-storage/index.md
- Fixed an incorrect shortguide reference.
> [Fix] How to Use Linode Object Storage

- docs/guides/platform/dedicated-cpu/when-to-upgrade-to-a-dedicated-cpu/index.md
Change level headings, h1_title, and add link to resize guide
> [Update] Upgrading from Shared to Dedicated CPU Instances

- docs/guides/platform/billing-and-support/manage-billing-in-cloud-manager/index.md
Changed maximum payment method limit to 6.
> [Updated] Managing Billing in the Cloud Manager

- docs/guides/platform/disk-images/managing-the-kernel-on-a-linode/index.md
One Debian command was missing a required sudo.
> Add missing sudo

- docs/products/storage/block-storage/_index.md
- docs/products/storage/block-storage/_shortguides/block-storage-limitations-shortguide/index.md
This PR adds performance limits to the main Block Storage Overview page. With the recommended theme changes in a separate PR, the table included within this PR will look a bit better:
> [Updated] Block Storage Overview

- docs/guides/web-servers/nginx/how-to-configure-nginx/index.md
- It has SEO updates for NGINX from https://github.com/linode/docs/pull/3865
> [Update] How to confugure  NGINX

- docs/products/tools/images/_shortguides/upload-image-requirements-shortguide/index.md
Calrify compressed/uncompressed
> [Update] Upload Image Requirements

- ci/vale/dictionary.txt
- docs/guides/tools-reference/basics/navigate-linux/index.md
- Original PR: https://github.com/linode/docs/pull/4696 drafted by @JeffreyNovotny 
- Recreated pull request to remove 600+ checked in generated images.
> [New] Linux Navigation Commands

- docs/guides/quick-answers/linode-platform/an-overview-of-common-cloud-manager-errors/index.md
- Add section for error retrieving network info
> [Update] An Overview of Common Cloud Manager Errors

- docs/guides/development/version-control/git-rebase/index.md
Small spelling fix. Off -> of.
> [Update] Using the Git Rebase Command

- docs/guides/platform/marketplace/beef-marketplace-app/index.md
Projected Launch date: November 16th
> BeEF Marketplace Doc

- docs/guides/platform/marketplace/bitninja-marketplace-app/index.md
Projected Launch date: November 16th
> BitNinja Marketplace Doc

- docs/guides/platform/marketplace/wirespeed-marketplace-app/index.md
Projected Launch date: November 16th
> Wirespeed Marketplace Doc

- docs/guides/quick-answers/linux/choosing-a-distribution/index.md
Added Fedora 35 to the Choosing a Distribution guide
> [Update] Choosing a Linux Distribution

- _vendor/github.com/linode/linode-docs-theme/assets/js/main/search/search-store.js
- _vendor/github.com/linode/linode-docs-theme/layouts/_default/tabbed-section-layout.html
- _vendor/github.com/linode/linode-docs-theme/layouts/products/single.html
- _vendor/modules.txt
- go.mod
- go.sum
This reverts commit 93905492332d7b0b34b88622214710e2f2b03c8f.
> Revert "[Theme] Updates for 11-9-21 (#4870)"

- _vendor/github.com/linode/linode-docs-theme/assets/js/main/search/search-store.js
- _vendor/github.com/linode/linode-docs-theme/layouts/_default/tabbed-section-layout.html
- _vendor/github.com/linode/linode-docs-theme/layouts/products/single.html
- _vendor/github.com/linode/linode-website-partials/footer.css
- _vendor/github.com/linode/linode-website-partials/header.css
- _vendor/github.com/linode/linode-website-partials/header.html
- _vendor/modules.txt
- go.mod
- go.sum
- Header and Footer changes
- Add promo code and Delighted score to product pages
- Fix broken anchor tags
> [Theme] Updates for 11-9-21 (Actual)

- _vendor/github.com/linode/linode-docs-theme/layouts/_default/single.html
- _vendor/github.com/linode/linode-docs-theme/layouts/_default/tabbed-section-layout.html
- _vendor/github.com/linode/linode-docs-theme/layouts/partials/components/delighted/form.html
- _vendor/github.com/linode/linode-docs-theme/layouts/partials/sections/content/promo_code.html
- _vendor/github.com/linode/linode-docs-theme/layouts/products/single.html
- _vendor/modules.txt
- go.mod
- go.sum
Theme updates:
- Fix for error where Delighted "Provide Feedback" button does not
open the feedback form
- Fix for error where promo code banner "Sign Up" button does not
take users to Cloud Manager login page
- Moved promo code banner to the top of guides and product pages
> [Hotfix] v1.97.1

- _vendor/github.com/linode/linode-docs-theme/assets/css/sections/content.css
- _vendor/github.com/linode/linode-docs-theme/assets/js/main/navigation/explorer.js
- _vendor/github.com/linode/linode-docs-theme/assets/js/main/search/filters.js
- _vendor/github.com/linode/linode-docs-theme/content/typografy-test.md
- _vendor/github.com/linode/linode-docs-theme/layouts/_default/whatsnew.html
- _vendor/github.com/linode/linode-docs-theme/layouts/partials/sections/search/filters.html
- _vendor/github.com/linode/linode-docs-theme/layouts/partials/sections/search/filters__tags.html
- _vendor/github.com/linode/linode-docs-theme/layouts/partials/sections/search/panel.html
- _vendor/github.com/linode/linode-docs-theme/layouts/shortcodes/file.html
- _vendor/modules.txt
- go.mod
- go.sum
- Filter out deprecated pages in whatsnew
- 2 search filter fixes
- Fix file shortcode when no title
- explorer: Sort blog posts chronologically
> Theme update 11-12-21:

- docs/guides/platform/marketplace/beef-marketplace-app/index.md
- docs/guides/platform/marketplace/bitninja-marketplace-app/index.md
- docs/guides/platform/marketplace/harbor-marketplace-app/index.md
- docs/guides/platform/marketplace/litespeed-cpanel-marketplace-app/index.md
- docs/guides/platform/marketplace/openlitespeed-django-marketplace-app/index.md
- docs/guides/platform/marketplace/openlitespeed-nodejs-marketplace-app/index.md
- docs/guides/platform/marketplace/openlitespeed-rails-marketplace-app/index.md
- docs/guides/platform/marketplace/pritunl-marketplace-app/index.md
- docs/guides/platform/marketplace/rocketchat-marketplace-app/index.md
- docs/guides/platform/marketplace/utunnel-marketplace-app/index.md
- docs/guides/platform/marketplace/warpspeed-marketplace-app/index.md
- docs/guides/platform/marketplace/wazuh-marketplace-app/index.md
[Fix] Added redirects to new marketplace app guides
> [Release Candidate] v1.100.1

- _vendor/github.com/linode/linode-api-docs/v4/openapi.yaml
- _vendor/modules.txt
- go.mod
- go.sum
Update API reference to API spec v4.109.1
> [Release Candidate] v1.102.0

- docs/guides/networking/vpn/set-up-wireguard-vpn-on-ubuntu/index.md
- docs/guides/platform/marketplace/wireguard-marketplace-app/index.md
- Update the format of the ip to 10.0.0.1/24
- Update the steps for Ubuntu installation
> [Update] Wire Guard market place app and Ubuntu Guide

- docs/guides/platform/object-storage/how-to-manage-objects-with-lifecycle-policies/index.md
- docs/guides/platform/object-storage/how-to-use-object-storage-acls-and-bucket-policies/index.md
- [Updated] Enacting Access Control Lists (ACLs) and Bucket Policies on Object Storage
Clarified information on the canonical ID and how to retrieve it
- [Updated] How To Manage Objects with Lifecycle Policies
Clarified examples commands.
> Updated several Object Storage guides

- docs/guides/platform/block-storage/how-to-use-block-storage-with-your-linode/index.md
- docs/products/storage/block-storage/_index.md
- [Updated] How to Use Block Storage with Your Linode
Removed pricing details.
- [Updated] Block Storage Overview
Added hourly rate.
> Updated Block Storage pricing with hourly rate

- ci/vale/dictionary.txt
- docs/guides/development/python/web-programming-languages/index.md
- docs/guides/networking/vpn/set-up-wireguard-vpn-on-ubuntu/index.md
- docs/guides/platform/block-storage/how-to-use-block-storage-with-your-linode/index.md
- docs/guides/platform/marketplace/wireguard-marketplace-app/index.md
- docs/guides/platform/object-storage/how-to-manage-objects-with-lifecycle-policies/index.md
- docs/guides/platform/object-storage/how-to-use-object-storage-acls-and-bucket-policies/index.md
- docs/guides/quick-answers/linux/open-source-software-benefits/index.md
- docs/products/storage/block-storage/_index.md
- Open Source Software: Benefits Explained
- Programming Languages for Web Development
- Enacting Access Control Lists (ACLs) and Bucket Policies on Object Storage
- How To Manage Objects with Lifecycle Policies
- How to Use Block Storage with Your Linode
- Block Storage Overview
- Wire Guard market place app and Ubuntu Guide
> [Release Candidate] v1.104.0

- docs/guides/quick-answers/linux-essentials/introduction-to-backups/index.md
> [Update] Introduction to Backups

- ci/vale/dictionary.txt
- docs/guides/development/go/golang-unit-testing/index.md
* Created new branch to fix merge conflicts and 404.
> [New] Golang Testing: Unit Testing Your Go Applications

- docs/guides/platform/managed/linode-managed/index.md
- docs/products/services/managed/_index.md
Updates managed documentation to clearly state the LKE nodes are exempt from Managed billing
> [Update] Linode Managed Documentation

- docs/guides/kubernetes/how-to-deploy-nginx-ingress-on-linode-kubernetes-engine/index.md
Removes redundant/unnecessary link
> [Update] How to Deploy NGINX Ingress on LKE

- docs/guides/databases/mysql/how-to-install-mysql-on-ubuntu-20-04/index.md
- Fixed CREATE USER command based on user feedback
- Minor formatting fixes
> [Updated] Installing and Configuring MySQL on Ubuntu 20.04

- docs/guides/platform/marketplace/utunnel-marketplace-app/index.md
- Updated name to "UTunnel VPN" (from just "UTunnel") as per request
- Minor copy edits
> [Updated] Deploying UTunnel VPN through the Linode Marketplace

- ci/vale/dictionary.txt
- docs/guides/databases/mongodb/mongodb-community-shell/index.md
> [New] Install the MongoDB Community Shell

- docs/guides/applications/configuration-management/ansible/deploy-linodes-using-ansible/index.md
Addresses potentially breaking issues as part of installation
> [Update] How to use the Linode Ansible Module to Deploy Linodes

- docs/guides/platform/marketplace/openvpn-marketplace-app/index.md
Openvpn has made some changes to their app structure so we had to make adjustments to the script. Included instructions on how to find the random generated password and the addition UDFs to align with our current style of apps
> Marketplace OpenVPN Distro & Password update

- docs/guides/tools-reference/tools/how-to-use-sd-command/index.md
Submitting the guide on installing and using the `sd` command for find and replace on LInux.
> Guide on the sd Command

- docs/guides/platform/nodebalancer/nodebalancer-proxypass-configuration/index.md
Add note to address configuration concerns for unique services
> [Update] Using Proxy Protocol with NodeBalancers

- docs/products/networking/cloud-firewall/_shortguides/add-new-cloud-firewall-rules-shortguide/index.md
- docs/products/networking/cloud-firewall/_shortguides/cloud-firewall-limits-shortguide/index.md
- Informs users of lack of errors when IP addresses or ranges are entered incorrectly, as well as providing an additional example of IP ranges.
> [Update] Cloud Firewall Shortguides

- docs/guides/tools-reference/tools/how-to-use-cheat-command/index.md
Submitting the guide on how to install and use the `cheat` command.
> Guide on the cheat Command

- docs/guides/quick-answers/linux/how-to-install-selinux-on-debian-10/index.md
- fixed a typo based on the feedback in DisQus
> [update]How to Install SELinux on Debian 10

- docs/guides/platform/linode-gpu/gpu-install-driver-with-cuda-shortguide/index.md
- Update the guide with the links to update and change the kernel
- Added  the gcc install step
- Fixeshttps://github.com/linode/docs/issues/4344
> [Update] NVIDIA Driver CUDA Installation

- docs/guides/platform/marketplace/plex-marketplace-app/index.md
Someone pointed out that the 2GB Dedicated plan doesn't exist. https://twitter.com/thibaultmol/status/1475552225778929669
> Update the minimum plan size

- docs/products/storage/object-storage/_index.md
Include disclaimer re: temporary Object Storage cluster limits.
> 5TB limit update

- docs/guides/tools-reference/tools/how-to-use-choose-command/index.md
Submitting the guide on installing and using the `choose` command for text processing.
> Guide on the choose Command

- docs/guides/platform/api/linode-cli-object-storage-shortguide/index.md
> [Update] Linode CLI Object Storage

- docs/guides/email/email-services/using-magicspam-email-authentication/index.md
> [Update] Using MagicSpam to Secure your Email Server

- docs/guides/platform/object-storage/how-to-use-object-storage-acls-and-bucket-policies/index.md
replacing *ther-users-bucket* with : replacing *other-users-bucket*
> [Fix] How to Use ACLs and Bucket Policies on Linode Object Storage

- docs/guides/tools-reference/tools/how-to-find-files-with-fd-command/index.md
Fixes [issue ](https://github.com/linode/docs/issues/4958)
> [Update] How to Find Files With the fd Command

- docs/guides/web-servers/lamp/how-to-install-a-lamp-stack-on-ubuntu-20-04/index.md
Address syntax issues with mysql 8 and above
> [Update] How to Install a LAMP Stack on Ubuntu 20.04

- docs/guides/platform/disk-images/copying-a-disk-image-over-ssh/index.md
- docs/guides/platform/disk-images/copying-a-disk-image-to-a-different-account/index.md
Update dd commands to use the "status=progress" parameter to monitor progress of the disk while it is being copied
> [Update] Copying a Disk over SSH

- docs/guides/kubernetes/lke-continuous-deployment-part-1/index.md
- docs/guides/kubernetes/lke-continuous-deployment-part-10/index.md
- docs/guides/kubernetes/lke-continuous-deployment-part-11/index.md
- docs/guides/kubernetes/lke-continuous-deployment-part-12/index.md
- docs/guides/kubernetes/lke-continuous-deployment-part-13/index.md
- docs/guides/kubernetes/lke-continuous-deployment-part-2/index.md
- docs/guides/kubernetes/lke-continuous-deployment-part-3/index.md
- docs/guides/kubernetes/lke-continuous-deployment-part-4/index.md
- docs/guides/kubernetes/lke-continuous-deployment-part-5/index.md
- docs/guides/kubernetes/lke-continuous-deployment-part-6/index.md
- docs/guides/kubernetes/lke-continuous-deployment-part-7/index.md
- docs/guides/kubernetes/lke-continuous-deployment-part-8/index.md
- docs/guides/kubernetes/lke-continuous-deployment-part-9/index.md
- docs/guides/kubernetes/lke-continuous-deployment-series/index.md
This replaces northcutt's PR #4650
> Added SEO optimizations to LKE CD series

- docs/products/storage/block-storage/guides/nvme-upgrade/index.md
Updated NVMe launch table with more specific date estimates
> [Updated] NVMe Block Storage Upgrade

- docs/guides/databases/redis/getting-started-redis/index.md
Submitting the guide on connecting to Redis and using Redis databases.
Note that the guide is intended to be part of a series on Redis. The upcoming guides in the series are generally referenced in the "Working with Keys in Redis", "Setting and Getting Keys", and "Conclusion" sections
> Guide on Getting Started with Redis

- docs/products/storage/block-storage/guides/nvme-upgrade/index.md
Updated Block Storage NVMe guide to reflect launch in Tokyo
> [Updated] NVMe Block Storage Upgrade (Tokyo launch)

- docs/guides/web-servers/apache-tips-and-tricks/modevasive-on-apache/index.md
> [Update] mod_evasive on Apache

- ci/vale/dictionary.txt
- docs/guides/game-servers/install-steamcmd-for-a-steam-game-server/index.md
Updates broken installation on Ubuntu, adds clarification to apt install process
> [Update] Install SteamCMD for a Steam Game Server

- ci/vale/dictionary.txt
- docs/guides/platform/marketplace/akaunting-marketplace-app/index.md
add Akaunting doc for January 25 Marketplace launch
> [New] Deploying Akaunting through the Linode Marketplace

- ci/vale/dictionary.txt
- docs/guides/platform/marketplace/restyaboard-marketplace-app/index.md
Add Restyaboard for January 25th Marketplace launch
> [New] Deploying Restyaboard through the Linode Marketplace

- docs/guides/kubernetes/deploy-and-manage-a-cluster-with-linode-kubernetes-engine-a-tutorial/index.md
- docs/guides/kubernetes/enable-lke-high-availability/index.md
Indexes currently hidden guide
> [Hotfix] v1.118.1

- docs/guides/development/python/how-to-slice-strings-using-python/index.md
The two tables do not look like they are properly using center alignment, but the md code looks right. I'm not sure if it's an issue with my browser or with Hugo. I'll leave it to the editor to verify.
> Initial draft of guide to Python string indexing and slicing

- docs/guides/tools-reference/linux-package-management/apt-package-manager/index.md
- docs/guides/tools-reference/linux-package-management/dnf-package-manager/index.md
- docs/guides/tools-reference/linux-package-management/yum-package-manager/index.md
Updated list/code formatting in several package manager docs
> [Fixed] Corrected formatting in package manager guides

- docs/products/storage/block-storage/_index.md
- docs/products/storage/block-storage/_shortguides/nvme-block-storage-notice-shortguide/index.md
- docs/products/storage/block-storage/guides/nvme-upgrade/index.md
- [Updated] Block Storage > Guides > NVMe Block Storage Upgrade
- [Updated] Block Storage > Overview
- Updated language in the NVMe shortguide
> Updated Block Storage guides to reflect NVMe launch in London and Mumbai

- docs/products/compute/kubernetes/_index.md
Update LKE availability to reflect LKE release in Atlanta, GA
> Hotfix v1.120.2

- docs/products/storage/block-storage/guides/nvme-upgrade/index.md
Updated the NVMe Block Storage Upgrade for the Sydney launch
> [Release Candidate] v1.120.3

- _vendor/github.com/linode/linode-docs-theme/assets/js/main/components/cm-api-v2.js
- _vendor/github.com/linode/linode-docs-theme/assets/js/main/components/disqus.js
- _vendor/github.com/linode/linode-docs-theme/assets/js/main/index.js
- _vendor/github.com/linode/linode-docs-theme/assets/js/main/navigation/nav-store.js
- _vendor/github.com/linode/linode-docs-theme/config.toml
- _vendor/github.com/linode/linode-docs-theme/layouts/partials/components/disqus.html
- _vendor/github.com/linode/linode-docs-theme/layouts/partials/sections/before-body-end.html
- _vendor/github.com/linode/linode-docs-theme/layouts/partials/sections/head-linode-common.html
- _vendor/github.com/linode/linode-website-partials/attribution-inline.js
- _vendor/github.com/linode/linode-website-partials/footer-inline.js
- _vendor/github.com/linode/linode-website-partials/footer.html
- _vendor/github.com/linode/linode-website-partials/header.html
- _vendor/modules.txt
- config/_default/module.toml
- go.mod
- go.sum
Theme updates:
- Enable vendorClosest in the top-level module config. Official docs: https://gohugo.io/hugo-modules/configuration/
- Attribution/promo code scripts from marketing site now incorporated
on page load for docs site
> Hotfix v1.120.4

- ci/yaml_rules.json
To support the frontmatter for this new theme feature:
https://github.com/linode/linode-docs-theme/pull/230
> Add toc and notoc options to ci/yaml_rules.json

- docs/guides/quick-answers/linux/choosing-a-distribution/index.md
Updated the distros guide to reflect deprecated and removed distro images.
> [Updated] Choosing a Linux Distribution

- docs/guides/applications/configuration-management/puppet/use-puppet-modules-to-create-a-lamp-stack-ubuntu-18-04-master/index.md
- docs/guides/email/postfix/troubleshooting-problems-with-postfix-dovecot-and-mysql/index.md
- docs/guides/kubernetes/kubernetes-use-cases/index.md
- docs/guides/networking/diagnostics/lsof/index.md
- docs/guides/networking/diagnostics/ss/index.md
- docs/guides/networking/dns/configure-your-linode-for-reverse-dns/index.md
- docs/guides/networking/linode-network/linux-static-ip-configuration/index.md
- docs/guides/platform/marketplace/clustercontrol-marketplace-app/index.md
- docs/guides/platform/marketplace/gitlab-marketplace-app/index.md
- docs/guides/platform/marketplace/harbor-marketplace-app/index.md
- docs/guides/platform/marketplace/jetbackup-marketplace-app/index.md
- docs/guides/platform/marketplace/moodle-marketplace-app/index.md
- docs/guides/platform/marketplace/rocketchat-marketplace-app/index.md
- docs/guides/platform/marketplace/vscode-marketplace-app/index.md
- docs/guides/platform/marketplace/wazuh-marketplace-app/index.md
- docs/guides/platform/migrate-to-linode/migrate-cpanel-to-linode/index.md
- docs/guides/platform/monitoring/what-is-longview/index.md
- docs/guides/tools-reference/custom-kernels-distros/use-the-distribution-supplied-kernel-on-centos-6-with-grub-legacy/index.md
- Removes outdated references to members.linode.com address
- Fixes an issue where LKE is still described as upcoming in the [Kubernetes Use Cases](https://www.linode.com/docs/guides/kubernetes-use-cases/) guide
> [Update] Remove outdated references to members.linode.com

- docs/products/storage/backups/guides/take-a-snapshot/index.md
- Adds a note to clarify that the Backups service needs to be enabled
- Updated description
- Other misc copy changes
> [Update] Backups > Guides > Take a Manual Snapshot

- docs/guides/quick-answers/linux-essentials/introduction-to-systemctl/index.md
- clarified about the symlink for the unit files
> [Update] systemctl Commands: Restart, Reload, Stop Service and More

- docs/guides/platform/billing-and-support/tax-information/index.md
> Hotfix v1.122.1

- _vendor/github.com/linode/linode-docs-theme/assets/jsconfig.json
- _vendor/github.com/linode/linode-website-partials/header.css
- _vendor/github.com/linode/linode-website-partials/header.html
- _vendor/github.com/linode/linode-website-partials/header.js
- _vendor/modules.txt
- go.mod
- go.sum
Theme updates:
- Update header to support dynamic notification messages on left
side of top nav bar
> Hotfix v1.123.1

- docs/guides/databases/mysql/an-introduction-to-mysql/index.md
> [Update] What Is Mysql: An Overview

- docs/guides/platform/marketplace/bitninja-marketplace-app/index.md
The url to Bitninja's main website changed so this PR updates the links. The docs website is the same, but the link to the docs page was broken so updated that one as well.
> [Updated] Deploying BitNinja through the Linode Marketplace

- docs/guides/development/react/deploy-a-react-app-on-linode/index.md
- docs/guides/development/react/how-to-deploy-a-react-app-on-centos-8/index.md
- docs/guides/development/react/how-to-deploy-a-react-app-on-debian-10/index.md
- docs/guides/development/react/how-to-deploy-a-react-app-on-ubuntu-18-04/index.md
Fixing a broken link. Pointing it to wayback machine due to the link being offline.
> [Update] Deploy React Guides

- docs/guides/platform/marketplace/webuzo-marketplace-app/index.md
Updated the post-provisioning time frame to account for longer times within some data centers. Also noted that a restart may be required if the initial setup screen doesn't appear.
> [Update] Deploying Webuzo through the Linode Marketplace

- docs/guides/game-servers/multicraft-on-ubuntu/index.md
Fix command typo and add sudo before install command
> fix: tasksel install command on multicraft installation doc

- docs/guides/platform/billing-and-support/how-linode-billing-works/index.md
Removed the hanging parenthesis in the last sentence of line 58. It was just after the relative hyperlink for the "remove the service".
> Removed hanging parenthesis on line 58

- docs/guides/networking/vpn/strong-swan-vpn-server-ubuntu/index.md
Fixes the 404 in the StrongSwan guide.
> [Fix] Install and Configure a StrongSwan Gateway VPN Server on Ubuntu 20.04

- docs/guides/platform/marketplace/openvpn-marketplace-app/index.md
- Added note that the app no longer uses a user-provided password and instead automatically generates one
- Added caution note about the HTTPS browser warning when accessing admin and client dashboards
- Updated IP address references
> [Update] Deploying OpenVPN through the Linode Marketplace

- docs/products/databases/managed-databases/_index.md
- docs/products/databases/managed-databases/guides/connect-to-mysql/index.md
- docs/products/databases/managed-databases/guides/migrate-mysql/index.md
- [Update] Managed Databases > Overview
*Added a limitation to inform users that there is currently no way to update the software*
- [Update] Managed Databases > Guides > Connecting to a MySQL Database
*Added details regarding the private network host string*
- [Update] Managed Databases > Guides > Migrate a MySQL or MariaDB Database to a Managed Database
*Added a Before You Begin section to address required MySQL user grants. Updated mysqldump command to export a single database and add addition optional arguments.*
> Updated Managed Databases product documentation

- ci/vale/dictionary.txt
- docs/guides/development/concepts/solid-principles-programming/index.md
Please note that code examples are pseudo-code and do not require code validation.
> Initial draft of guide to the SOLID programming principles

- docs/guides/databases/redis/using-redis-hashes/index.md
Submitting the guide on using Redis hashes.
Note that this guide makes general references to other guides meant to be in the same series. Currently, these other guides consist of the "Connecting to Redis and Using Redis Databases" guide, submitted in PR #4975, and the "How to Use Lists and Sets in Redis Databases" and "How to Use Sorted Sets in Redis Databases" guides submitted in PR #4995.
> Guide on Redis Hashes

- docs/guides/platform/manager/an-overview-of-the-linode-cloud-manager/index.md
Very minor update to this page. Replaced reference to `feedback@linode.com` with a link to the new feedback form.
> [Update] An Overview of the Linode Cloud Manager

- docs/products/databases/managed-databases/_index.md
- docs/products/databases/managed-databases/_shortguides/managed-databases-beta-notice-shortguide/index.md
- Updated guides to reflect Managed Databases open beta launch.
> [Release Candidate] v1.132.1

- docs/guides/databases/mysql/sql-data-types/index.md
New PR for SQL Data Type guide.
> tech edits

- docs/guides/game-servers/how-to-set-up-minecraft-server-on-ubuntu-or-debian/index.md
* tested and validated the steps on Ubuntu/Debian
* Updated the before you begin so that the new `mincecraft` sudo user can proceed with the installation.
```
*** System restart required ***
Last login: Sat Mar  5 21:26:02 2022 from 49.207.217.45
rajie@minecraft:~$ rm ~/.ssh/authorized_keys
rajie@minecraft:~$ exit
logout
Connection to 194.195.112.49 closed.
rkodhandapani@rkodhandapani-C02XG0X6JG5H ~ % ssh minecraft@194.195.112.49
minecraft@194.195.112.49: Permission denied (publickey).
rkodhandapani@rkodhandapani-C02XG0X6JG5H ~ % ssh minecraft@194.195.112.49
minecraft@194.195.112.49's password: 
Welcome to Ubuntu 20.04.4 LTS (GNU/Linux 5.4.0-100-generic x86_64)
* Documentation:  https://help.ubuntu.com
* Management:     https://landscape.canonical.com
* Support: …
```
> [Update] Setting up Minecraft Server on Ubuntu or Debian

- docs/products/storage/object-storage/guides/lifecycle-policies/index.md
Added alias for previous URL (/docs/guides/how-to-manage-objects-with-lifecycle-policies/)
> [Fix] Object Storage > Guides > Lifecycle Policies

- docs/products/storage/block-storage/guides/nvme-upgrade/index.md
- Added Singapore to NVME DCs
- Updated timeline for remaining DCs
> [Update] NVMe Block Storage Upgrade

- docs/guides/platform/cloud-firewall/getting-started-with-cloud-firewall/index.md
I noticed a missing space while reading through this guide. This PR adds the missing space. Cheers!
> Add missing space

- docs/products/databases/managed-databases/_index.md
fixes: https://github.com/linode/docs/issues/5285
> [Update] Managed Databases > Overview

- docs/guides/websites/cms/wordpress/best-open-source-content-management-systems/index.md
- Replace Bitrix with Grav
- Add links to relevant Marketplace App guides
> [Update] The Top Open Source Content Management Systems

- docs/guides/development/concepts/types-of-api/index.md
Submitting the guide on types of APIs.
Note that this guide references another guide which has not, at the time of this writing, been published. That guide is "REST API Best Practices for Design", submitted in PR #5268.
> Guide on types of APIs

- docs/products/tools/marketplace/guides/docker/index.md
- docs/products/tools/marketplace/guides/grafana/index.md
- docs/products/tools/marketplace/guides/ruby-on-rails/index.md
- docs/products/tools/marketplace/guides/wireguard/index.md
Ruby on Rails: Ubuntu 20.04
Grafana: Debian 11
Wireguard: Debian 11
Docker: Debian 11 & Ubuntu 20.04LTS
> Supported Distro Update: Linode Marketplace 

- docs/guides/applications/configuration-management/terraform/deploy-a-wordpress-site-using-terraform-and-linode-stackscripts/index.md
- Fixes incorrectly formatted terraform configuration files, uses updated stackscript, upgrades to Ubuntu 20.04 in the example config
> [Update] Deploy a Wordpress Site Using Terraform and Linode Stackscripts

- docs/guides/kubernetes/how-to-setup-a-private-docker-registry-with-lke-and-object-storage/index.md
- Validated and tested that the given steps work even though the chart is deprecated.
- Updated the link to the official helm registry document.
> [update] How to Set Up a Docker Registry with LKE and Object Storage

- docs/guides/development/javascript/introduction-to-dom/example-page.html
- docs/guides/development/javascript/introduction-to-dom/index.md
- docs/guides/development/javascript/javascript-objects-tutorial/index.md
Submitting two guides:
- JavaScript Objects Tutorial
- Introduction to the DOM
> Guides on JavaScript Objects and the DOM

- docs/products/databases/managed-databases/_index.md
- docs/products/databases/managed-databases/_shortguides/managed-databases-beta-notice-shortguide/index.md
Updated beta notice and pricing details in advance of GA. This should be released on 4/18 to coincide with planned communication.
> [Update] Managed Databases beta notice

- docs/guides/websites/cms/wordpress/how-to-install-wordpress-using-wp-cli-on-ubuntu-18-04/index.md
- docs/guides/websites/cms/wordpress/install-wordpress-using-wp-cli-on-ubuntu-18-04/index.md
Addresses near identical guide for the purposes of consolidation
> [Update] Install Wordpress using wp-cli on Ubuntu 18.04

- docs/products/storage/block-storage/guides/nvme-upgrade/index.md
NVMe Block Storage is tentatively scheduled to launch in Dallas next week. This PR updates the availability table to reflect this launch.
> [Update] NVMe Block Storage Upgrade (Dallas NVMe launch)

- docs/products/tools/marketplace/guides/nextcloud/index.md
Update distro and remove old UDF
> [Update] Deploying Nextcloud through the Linode Marketplace 

- docs/guides/troubleshooting/rescue-and-rebuild/index.md
Fix broken image link and some markdown code snippets syntax #5396
> [Update] Rescue and Rebuild

- docs/products/databases/managed-databases/_index.md
- docs/products/databases/managed-databases/_shortguides/managed-databases-beta-notice-shortguide/index.md
Updated the pricing details and beta notice for Managed Database.
> MySQL Managed Database GA

- docs/guides/development/javascript/how-to-link-javascript-to-html/example.html
- docs/guides/development/javascript/how-to-link-javascript-to-html/index.md
- docs/guides/development/javascript/how-to-link-javascript-to-html/js_files/example.js
Submitting the guide on linking JavaScript to HTML.
Note that this guide's **Conclusion** section references three other Linode guides that have not yet been published:
- JavaScript Objects Tutorial (PR #4887)
- Introduction to the DOM (PR #4887)
- JavaScript Events: A Tutorial (PR #4947)
> Guide on Linking JavaScript to HTML

- docs/products/tools/marketplace/developers/index.md
- Added information about how to create and submit a marketplace app.
> [Update] Marketplace Apps > Developers

- docs/products/databases/managed-databases/guides/connect-to-mysql/index.md
- Updated `mysql` install instructions
- Added changes to make to the connection string when the local system is using MariaDB instead of MySQL
> [Update] Managed Databases > Guides > Connect to a MySQL Database

- docs/products/tools/images/_index.md
Updated the **Limitations** sections of the Images product documentation to clarify image size limits.
> [Update] Images > Overview

- docs/guides/networking/ssh/verifying-the-authenticity-of-remote-host/index.md
Updated details regarding the various algorithms involved in a host key fingerprint.
> [Update] Verifying the Authenticity of a Remote Server through Its SSH Key Fingerprint

- docs/guides/development/python/how-to-reverse-a-string-in-python/index.md
- docs/guides/development/python/how-to-slice-strings-using-python/index.md
- docs/guides/development/python/string-manipulation-python-3/index.md
Submitting the guide on reversing strings in Python.
> Guide on Reversing Strings in Python

- docs/guides/development/version-control/how-to-configure-git/index.md
- docs/guides/development/version-control/subversion-svn-tutorial/index.md
- docs/guides/development/version-control/svn-vs-git/index.md
Submitting the guide on SVN vs Git.
> Guide on SVN vs Git

- _vendor/github.com/linode/linode-docs-theme/layouts/shortcodes/file.html
- _vendor/modules.txt
- go.mod
- go.sum
Revert problematic Prettier changes to file shortcode
> Hotfix v1.152.1

- _vendor/github.com/linode/linode-docs-theme/assets/js/main/navigation/lang.js
- _vendor/modules.txt
- go.mod
- go.sum
Update to Spanish language switcher
> Theme update 5/20/22

- docs/products/tools/marketplace/_shortguides/marketplace-custom-domain-fields-shortguide/index.md
- docs/products/tools/marketplace/guides/wordpress/index.md
- Added a note about SSL certificates being automatically generated.
> [update] Deploying WordPress through the Linode Marketplace

- docs/products/networking/vlans/get-started/index.md
Fixed link to Cloud Manager in VLAN Get Started guide
> [Fix] VLANs > Get Started

- ci/vale/dictionary.txt
- docs/guides/networking/linode-network/ifupdown/index.md
- docs/guides/networking/linode-network/ip-failover/index.md
- docs/guides/networking/linode-network/linux-static-ip-configuration/index.md
- docs/guides/networking/linode-network/manual-network-configuration/index.md
- docs/guides/networking/linode-network/network-infrastructure-upgrades/index.md
- docs/guides/networking/linode-network/networkmanager/index.md
- docs/guides/networking/linode-network/systemd-networkd/index.md
- docs/guides/quick-answers/linux/choosing-a-distribution/index.md
- Manual Network Configuration on a Compute Instance
- Network Configuration Using NetworkManager
- Network Configuration Using systemd-networkd
- Network Configuration Using ifupdown
- Choosing a Linux Distribution
- Upcoming Changes Related to Network Infrastructure Upgrades
- Configuring Failover on a Compute Instance
> [Release Candidate] v1.154.0

- docs/products/tools/marketplace/guides/yacht/index.md
> [Update] Deploying Yacht through the Linode Marketplace 

- docs/products/tools/marketplace/guides/counter-strike-go/index.md
> [Update] Deploying CS:GO through the Linode Marketplace 

- docs/products/tools/marketplace/guides/serverwand/index.md
> [Update] Deploying Serverwand through the Linode Marketplace

- docs/products/tools/marketplace/guides/jitsi/index.md
Updated distro & removed SSL UDF
> [Update] Deploying Jitsi through the Linode Marketplace

- docs/products/networking/vlans/get-started/index.md
Missing parentheses on the Markdown link.
> chore: fix VLAN link

- docs/guides/networking/linode-network/networkmanager/index.md
- docs/guides/networking/linode-network/systemd-networkd/index.md
Clarified how to disable IPv6 SLAAC assignment in several guides
- Network Configuration Using NetworkManager
- Network Configuration Using systemd-networkd
> Minor update to manual network configuration guides

- config.toml
> Update docs promo code June 2022

- docs/products/tools/marketplace/guides/ark-survival-evolved/index.md
- docs/products/tools/marketplace/guides/bitninja/index.md
- docs/products/tools/marketplace/guides/cloudron/index.md
- docs/products/tools/marketplace/guides/cyberpanel/index.md
- docs/products/tools/marketplace/guides/jetbackup/index.md
- docs/products/tools/marketplace/guides/litespeed-cpanel/index.md
- docs/products/tools/marketplace/guides/mistio/index.md
- docs/products/tools/marketplace/guides/openlitespeed-django/index.md
- docs/products/tools/marketplace/guides/openlitespeed-nodejs/index.md
- docs/products/tools/marketplace/guides/openlitespeed-rails/index.md
- docs/products/tools/marketplace/guides/openlitespeed-wordpress/index.md
- docs/products/tools/marketplace/guides/phpmyadmin/index.md
- docs/products/tools/marketplace/guides/prometheus/index.md
- docs/products/tools/marketplace/guides/rust/index.md
- docs/products/tools/marketplace/guides/shadowsocks/index.md
- docs/products/tools/marketplace/guides/team-fortress-2/index.md
- docs/products/tools/marketplace/guides/utunnel/index.md
Noticed a few docs had outdated distros, went through each app and all should will be up to date once this PR is merged.
> [Update] Linode Marketplace Distro Updates

- docs/guides/platform/get-started/getting-started/index.md
Removes references to the Linode Support Bot.
> [Update] Getting Started on the Linode Platform

- _vendor/github.com/linode/linode-website-partials/attribution-inline.js
- _vendor/github.com/linode/linode-website-partials/footer-inline.js
- _vendor/github.com/linode/linode-website-partials/footer.html
- _vendor/github.com/linode/linode-website-partials/header.html
- _vendor/modules.txt
- ci/vale/dictionary.txt
- docs/guides/platform/billing-and-support/tax-information/index.md
- go.mod
- go.sum
Updates:
- Tax Information
Theme updates:
- Update header and footer navigation
> [Release] v1.159.1

- docs/guides/development/concepts/oop-principles/index.md
Submitting the guide on object-oriented programming principles.
> Guide on OOP principles

- ci/vale/dictionary.txt
- docs/guides/networking/linode-network/ip-failover/index.md
- docs/guides/networking/linode-network/network-infrastructure-upgrades/index.md
- Upcoming Changes Related to Network Infrastructure Upgrades
- Configuring Failover on a Compute Instance
> [Release Candidate] v1.161.1

- ci/vale/dictionary.txt
- docs/guides/development/python/python-arrays/index.md
Submitting the guide on Python arrays.
> Guide on Python arrays

- docs/guides/security/authentication/use-public-key-authentication-with-ssh/index.md
> [Update] How to Use SSH Public Key Authentication

- docs/products/tools/marketplace/guides/kali-linux/index.md
- Added an alias to the Kali Linux Marketplace App
> [Release Candidate] 1.166.1

- docs/guides/development/version-control/how-to-configure-git/index.md
- docs/guides/development/version-control/how-to-undo-git-commit/index.md
Because Git terms are often non-intuitive, it is easy to use an incorrect term. Please double check I haven't mixed up reset and revert anywhere.
> Initial draft of guide on undoing a git commit

- docs/guides/applications/cloud-storage/install-and-configure-owncloud-on-centos-stream-8/index.md
based on a comment in disqus updated the command
> [update] fixed a typo

- _vendor/github.com/linode/linode-api-docs/v4/openapi.yaml
- _vendor/modules.txt
- go.mod
- go.sum
Update API docs to version 4.130.0
> [Release Candidate] v1.168.0

- docs/guides/email/postfix/configure-spf-and-dkim-in-postfix-on-debian-9/index.md
Fixes the pass comments that were incorrect.
> [update] Configure SPF and DKIM With Postfix on Debian 9

- docs/guides/kubernetes/kubernetes-security/index.md
Updating the Kubernetes guide link provided at the start of the article so that it is more clear that this article is intended for general Kubernetes administration and not LKE specifically.
> [Update] Kubernetes Security Best Practices Overview

- docs/guides/networking/linode-network/manual-network-configuration/index.md
- docs/guides/quick-answers/linux/choosing-a-distribution/index.md
Adds Rocky Linux 9 to list of supported distributions.
> [Update] Choosing a Distribution

- _vendor/github.com/linode/linode-docs-theme/assets/js/main/helpers/helpers.js
- _vendor/github.com/linode/linode-docs-theme/assets/js/main/helpers/index.js
- _vendor/github.com/linode/linode-docs-theme/assets/js/main/helpers/smartqueue.js
- _vendor/github.com/linode/linode-docs-theme/assets/js/main/index.js
- _vendor/github.com/linode/linode-docs-theme/assets/js/main/navigation/explorer.js
- _vendor/github.com/linode/linode-docs-theme/assets/js/main/navigation/nav-analytics.js
- _vendor/github.com/linode/linode-docs-theme/assets/js/main/navigation/nav-store.js
- _vendor/github.com/linode/linode-docs-theme/assets/js/main/navigation/nav.js
- _vendor/github.com/linode/linode-docs-theme/assets/js/main/search/search-store.js
- _vendor/github.com/linode/linode-docs-theme/config.toml
- _vendor/github.com/linode/linode-docs-theme/layouts/_default/baseof.html
- _vendor/github.com/linode/linode-docs-theme/layouts/index.json
- _vendor/github.com/linode/linode-docs-theme/layouts/partials/funcs/get-objectid.html
- _vendor/github.com/linode/linode-docs-theme/layouts/partials/sections/content/navbar__dropdown-github.html
- _vendor/github.com/linode/linode-docs-theme/layouts/partials/sections/content/navbar__dropdown-share.html
- _vendor/github.com/linode/linode-docs-theme/layouts/partials/sections/content/navbar__dropdown__link.html
- _vendor/github.com/linode/linode-docs-theme/layouts/partials/sections/content/promo_code.html
- _vendor/github.com/linode/linode-docs-theme/layouts/partials/sections/search/list.html
- _vendor/modules.txt
- go.mod
- go.sum
Theme updates:
- Introduce Algolia Insights API/events functionality
> [Release] v1.169.1

- docs/guides/platform/billing-and-support/tax-information/index.md
Alphabetized tax ID list and added Japan.
> Tax update for Japanese tax ID

- docs/guides/networking/linode-network/ip-failover/index.md
- docs/guides/networking/linode-network/network-infrastructure-upgrades/index.md
- [Update] Configuring Failover on a Compute Instance
- [Update] Upcoming Changes Related to Network Infrastructure Upgrades
> Updates related to London's network upgrades

- _vendor/github.com/linode/linode-api-docs/v4/openapi.yaml
- _vendor/modules.txt
- go.mod
- go.sum
- Update API reference to API spec v4.132.0
> [Release Candidate] v1.171.0

- docs/products/networking/vlans/_index.md
Added London to the list of available data centers, updated formatting of availability list.
> [Update] VLANs > Overview

- docs/products/storage/object-storage/guides/s3cmd/index.md
updated the description of S3 endpoint
> [update]Using S3cmd with Object Storage

- docs/guides/platform/stackscripts/stackscripts-create-linode-shortguide/index.md
* updated the stack scripts apt-get commands.
> [update] Writing Scripts for Linode StackScripts

- docs/guides/kubernetes/deploy-tobs-on-linode-kubernetes-engine/index.md
Just updated the title to make the guide more discoverable.
> [update] How to deploy TOBS on LKE

- docs/guides/databases/mongodb/build-database-clusters-with-mongodb/index.md
fixed a typo
fixes https://github.com/linode/docs/issues/5603
> [update] How To Build Database Clusters with MongoDB

- docs/guides/websites/hosting/host-a-website-with-high-availability/index.md
- Updated the guide with instructions to use the new cloud manager.
> [Update] Host a Website with High Availability

- docs/products/storage/block-storage/_shortguides/attach-block-storage-volume-shortguide/index.md
- docs/products/storage/block-storage/_shortguides/configuring-and-mounting-a-volume-shortguide/index.md
Updated the instructions for configuring and mounting a Block Storage Volume. This also makes the data loss warning (when creating a file system on a volume) a bit clearer.
> [Update] Configure and Mount a Block Storage Volume

- ci/vale/dictionary.txt
- docs/guides/databases/mongodb/build-database-clusters-with-mongodb/index.md
- docs/guides/kubernetes/deploy-tobs-on-linode-kubernetes-engine/index.md
- docs/guides/kubernetes/how-to-configure-load-balancing-with-tls-encryption-on-a-kubernetes-cluster/index.md
- docs/guides/platform/stackscripts/stackscripts-create-linode-shortguide/index.md
- docs/guides/tools-reference/file-transfer/vsftp-on-ubuntu-installation/index.md
- docs/guides/websites/hosting/host-a-website-with-high-availability/index.md
- docs/products/storage/block-storage/_shortguides/attach-block-storage-volume-shortguide/index.md
- docs/products/storage/block-storage/_shortguides/configuring-and-mounting-a-volume-shortguide/index.md
- docs/products/storage/object-storage/guides/s3cmd/index.md
New:
- VSFTPD on Ubuntu 20.04: Installation and Configuration
Updated:
- Products > Object Storage > Guides > Using S3cmd with Object Storage
- Products > Block Storage > Guides > Configure and Mount a Block Storage Volume
- Products > Block Storage > Guides > Attach an Existing Block Storage Volume to a Linode
- How to Use Block Storage with Your Linodz
- Deploy a Linode Instance with a StackScript
- How to Deploy TOBS (The Observability Stack) on LKE
- How To Build Database Clusters with MongoDB
- Host a Website with High Availability
- Configure Load Balancing with TLS Encryption on Kubernetes
> [Release] v1.173.0

- _vendor/github.com/linode/linode-api-docs/v4/openapi.yaml
- _vendor/modules.txt
- go.mod
- go.sum
- Update API reference to API spec v4.133.0
> [Release Candidate] v1.174.0

- docs/products/tools/linode-api/developers/index.md
Fixes bad link in API Developers page
> [Update] API > Developers

- docs/guides/networking/ssh/connect-to-server-over-ssh-on-windows/index.md
Ending double-quote was missing. Added
> [Fix] Connecting to a Remote Server Over SSH on Windows

- docs/products/storage/object-storage/guides/urls/index.md
Minor copy edit to add a missing character and fix title capitalization.
> [Fix] Access Buckets and Files through URLs

- config.toml
From DOCSR4RDING to docs1000822
> Change promo code

- docs/guides/platform/billing-and-support/tax-information/index.md
Add BC, Saskatchewan, and Manitoba tax info
> Canadian Provincial Tax updates

- docs/guides/networking/dns/configure-your-linode-for-reverse-dns/index.md
Refactored the "Before You Begin" section by expanding the content into several other new sections. Added details on creating a AAAA Record for use with IPv6.
> [Update] Configure Your Linode for Reverse DNS (rDNS)

- docs/guides/networking/linode-network/ip-failover/index.md
- docs/guides/networking/linode-network/network-infrastructure-upgrades/index.md
- [Update] Configuring Failover on a Compute Instance
- [Update] Upcoming Changes Related to Network Infrastructure Upgrades
> Updated Mumbai's status on guides related to the network infrastructure upgrades

- docs/guides/applications/configuration-management/basics/yaml-anchors-aliases-overrides-extensions/index.md
- Fixed the indents
- Fixes [5679](https://github.com/linode/docs/issues/5679)
> [update]YAML Anchors, Aliases, and Overrides

- docs/products/networking/cloud-firewall/_index.md
Fixed typo within Cloud Firewall Overview guide
> [Fix] Cloud Firewall > Overview

- _vendor/github.com/hotwired/turbo/src/core/drive/visit.ts
- _vendor/github.com/linode/linode-api-docs/v4/openapi.yaml
- _vendor/modules.txt
- go.mod
- go.sum
Update API reference to API spec v4.136.0
> [Release Candidate] v1.183.0

- docs/guides/kubernetes/how-to-setup-a-private-docker-registry-with-lke-and-object-storage/index.md
Added a note to get around the deprecation notice for docker registry.
> [update] Setting Up a Private Docker Registry with LKE and Object Storage

- docs/products/storage/block-storage/_index.md
Block Storage data is erasure coded for resiliency and durability and so no longer necessarily 3x duplicated.
> [Update] Block Storage Resiliency

- docs/guides/platform/object-storage/working-with-cors-linode-object-storage/index.md
Submitting the guide on working with CORS for Linode Object Storage instances.
> Guide on working with CORS and Linode Object Storage

- config.toml
- Updated feedback survey link url and re-enabled the feedback survey button
> [Release Candidate] v1.186.1

- docs/guides/platform/disk-images/managing-the-kernel-on-a-linode/index.md
-added the GRUB_ENABLE_BLSCFG=false a new type of configuration system for GRUB
> [update]Managing the Kernel on a Linode

- docs/products/tools/marketplace/guides/cloudron/index.md
> [Update] Deploying Cloudron through the Linode Marketplace 

- docs/guides/networking/linode-network/linux-static-ip-configuration/index.md
update broken link for updated static network guide
> [Update] Fix deprecated link on  Linux Static IP Configuration

- _vendor/github.com/linode/linode-website-partials/header.css
- _vendor/github.com/linode/linode-website-partials/header.html
- _vendor/modules.txt
- go.mod
- go.sum
Theme update
- Update header/footer (typo fix)
> Hotfix v1.187.1

- docs/products/tools/cli/guides/install/index.md
Add reminder to add Pip and Python to PATH
> [Update] CLI instructions

- docs/products/tools/marketplace/guides/wazuh/index.md
Add recommended specs per Wazuh guidance.
> [Update] Wazuh Marketplace Guide

- docs/guides/databases/mariadb/set-up-mariadb-clusters-with-galera-debian-and-ubuntu/index.md
Updated the repo for Debian 10 and Debian 11.
> [Update]Set Up MariaDB Clusters with Galera Debian and Ubuntu

- _vendor/github.com/linode/linode-docs-theme/assets/css/components/chroma.css
- _vendor/github.com/linode/linode-docs-theme/assets/css/components/chroma_dark.css
- _vendor/github.com/linode/linode-docs-theme/assets/css/sections/all.css
- _vendor/github.com/linode/linode-docs-theme/assets/css/sections/content.css
- _vendor/github.com/linode/linode-docs-theme/content/typografy-test.md
- _vendor/github.com/linode/linode-docs-theme/layouts/_default/_markup/render-codeblock-code.html
- _vendor/github.com/linode/linode-docs-theme/layouts/_default/_markup/render-codeblock-file.html
- _vendor/modules.txt
- ci/vale/dictionary.txt
- docs/guides/linode-writers-formatting-guide/index.md
- go.mod
- go.sum
Theme updates
-   Add support for markdown code fence syntax for file and code shortcodes
-   Add support for line highlighting for file shortcodes
Updated:
-   Linode Writer's Formatting Guide
Update File and Command sections to reflect new code fence syntax and line highlighting features. Add section for output shotcode.
> Theme updates, Writer's Guide updates

- docs/guides/development/version-control/install-apache-subversion-ubuntu-2004/index.md
Updated the commands
Fixes: [5829 ](https://github.com/linode/docs/issues/5829)
> [update] How to Install Apache Subversion on Ubuntu 20.04

- docs/guides/applications/configuration-management/salt/configure-and-use-salt-cloud-and-cloud-maps-to-provision-systems/index.md
- tested and validated the guide
- updated the guide to use v4 because v3 is deprecated
- updated the command to test the API key
- updated the confirmation files with the details required in v4
> [update] Using Salt Cloud and Cloud Maps to Provision Systems

- ci/vale/dictionary.txt
- docs/guides/tools-reference/tools/linux-cat-command/index.md
Submitting the guide on the Linux *cat* command.
> Guide on the Linux cat command

- docs/guides/tools-reference/basics/introduction-to-linux-concepts/index.md
* updated the sentence to latest version of Ubuntu so that we don't have to update for every new release of Ubuntu.
* tried and tested all the commands in the guide on Ubuntu
> [Update] Introduction to Linux Concepts

- docs/guides/kubernetes/how-to-deploy-jenkins-x-in-linode-kubernetes-engine/index.md
Added a deprecation notice and a note about V3.
Fixes: [5756](https://github.com/linode/docs/issues/5756)
> [update]How to Deploy Jenkins X in Linode Kubernetes Engine

- docs/products/tools/marketplace/guides/openlitespeed-wordpress/index.md
> [Update] Deploying OpenLiteSpeed WordPress through the Linode Marketplace

- _vendor/github.com/linode/linode-api-docs/v4/openapi.yaml
- _vendor/modules.txt
- go.mod
- go.sum
Update API reference to API spec v4.139.0
> [Release Candidate] v1.193.0

- docs/guides/development/rust/how-to-build-website-using-rust-rocket/index.md
Update the guide to use Rust syntax highlighting.
> [Update] Build a Website Using Rust and the Rocket Web Framework

- docs/guides/platform/get-started/set-up-and-secure/index.md
- fixed a typo
- fixes [5856](https://github.com/linode/docs/issues/5856)
> [update] Setting Up and Securing a Compute Instance

- docs/guides/security/encryption/use-luks-for-full-disk-encryption/index.md
- added the prerequisites to delete the disks because you cannot created the raw disks in the new cloud manager without deleting.
> [update] How to Use LUKS for Full Disk Encryption on Linux

- .github/workflows/cache-images.yaml
- .github/workflows/test.yaml
- CONTRIBUTING.md
- README.md
- docs/products/networking/dns-manager/guides/incoming-dns-zone-transfers/index.md
- docs/products/networking/dns-manager/guides/outgoing-dns-zone-transfers/index.md
- netlify.toml
Updated:
- Incoming DNS Zone Transfers
- Outgoing DNS Zone Transfers
> [Release] v1.195.0

- _vendor/github.com/linode/linode-api-docs/v4/openapi.yaml
- _vendor/modules.txt
- go.mod
- go.sum
Update API reference to API spec v4.140.0
> [Release Candidate] v1.196.0

- docs/products/storage/object-storage/_index.md
Clarified per region limits for object storage.
> [Update] Object Storage > Overview

- docs/guides/tools-reference/tools/using-ssh-agent/index.md
Submitting the guide on how to use ssh-agent.
> Guide on ssh-agent

- docs/products/platform/billing/faqs/_index.md
- docs/products/platform/billing/guides/_index.md
- Adds necessary aliases to several billing guides.
> [Release Candidate] v1.199.1

- _vendor/github.com/linode/linode-docs-theme/assets/js/main/navigation/nav.js
- _vendor/github.com/linode/linode-docs-theme/content/typografy-test.md
- _vendor/github.com/linode/linode-docs-theme/layouts/_default/_markup/render-codeblock-command.html
- _vendor/github.com/linode/linode-docs-theme/layouts/_default/_markup/render-codeblock-output.html
- _vendor/github.com/linode/linode-docs-theme/layouts/index.json
- _vendor/github.com/linode/linode-docs-theme/layouts/partials/sections/search/input.html
- _vendor/github.com/linode/linode-docs-theme/layouts/shortcodes/command.html
- _vendor/github.com/linode/linode-docs-theme/layouts/shortcodes/output.html
- _vendor/modules.txt
- docs/products/platform/accounts/_index.md
- go.mod
- go.sum
Theme updates
- Show the clear search "X" button when viewing individual search results
- Enable code fence syntax for output and command shortcodes
- Add h1_title, title_meta, and title_social to search records
- Add keywordsAlgolia, weightAge, weightAgeMonths, and weightAgeYears to search records
> Hotfix v1.199.2

- ci/yaml_rules.json
- docs/guides/security/authentication/free-ipa-for-identity-management/index.md
- docs/guides/security/authentication/secure-ssh-access-with-2fa/index.md
- docs/products/platform/accounts/_index.md
- **Use 2FA (Two-Factor Authentication) with SSH:** Updated front matter 
- **Set Up a FreeIPA Server and Client:** Fixed formatting issues and updated front matter
> Misc Updates

- docs/guides/applications/containers/install-docker-compose/index.md
- docs/guides/applications/messaging/install-mastodon-on-debian-10/index.md
- docs/guides/applications/messaging/install-mastodon-on-ubuntu-2004/index.md
- docs/guides/applications/messaging/install-mastodon-server-on-centos-stream/index.md
- Validated and updated the Mastodon guides for Debian and Ubuntu.
> [update] Mastodon guides

- docs/products/storage/backups/_index.md
- added a sentence about unformatted disks
> [update] Storage - Backups

- docs/products/platform/billing/guides/tax-information/index.md
This PR adds tax information for the upcoming December 15th changes, as well as adds Akamai's Tax IDs.
> [Update] Billing > Tax Information

- docs/guides/platform/manager/managing-ip-addresses/index.md
- updated the links to new guide
> [update] Managing IP Addresses on a Compute Instance

- docs/guides/platform/get-started/monitor-and-maintain-compute-instance/index.md
- docs/guides/security/basics/security-automation-business/index.md
- docs/products/networking/dns-manager/guides/manage-domains/index.md
- docs/products/networking/nodebalancers/guides/configure/index.md
- docs/products/tools/marketplace/guides/docker/index.md
This PR searches for any empty Markdown links (using the search`]()`) in our guides and updates them accordingly.
> Updates empty Markdown links in our docs

- docs/guides/kubernetes/lke-continuous-deployment-part-8/index.md
- updated information about CoreDNS and the TTL option.
> [update] Building a Continuous Deployment Pipeline Using LKE (Part 8)

- docs/products/storage/backups/guides/restore-to-an-existing-linode/index.md
fix typo in text about existing datacenter requirement
> [Update] Restore a Backup to an Existing Linode

- docs/guides/linode-writers-formatting-guide/index.md
Another small PR, this one updates the `lang` parameter on two file shortcodes to improve syntax highlighting.
> [Update] Linode Writer's Formatting Guide

- _vendor/github.com/linode/linode-docs-theme/assets/css/components/chroma.css
- _vendor/github.com/linode/linode-docs-theme/assets/css/components/highlight.css
- _vendor/github.com/linode/linode-docs-theme/assets/css/sections/content.css
- _vendor/github.com/linode/linode-docs-theme/layouts/_default/_markup/render-codeblock-file.html
- _vendor/github.com/linode/linode-docs-theme/layouts/_default/_markup/render-link.html
- _vendor/github.com/linode/linode-docs-theme/layouts/index.html
- _vendor/github.com/linode/linode-docs-theme/layouts/shortcodes/file.html
- _vendor/modules.txt
- go.mod
- go.sum
- Fixes the Developers > API Guides link on the docs home page
- Renders links inline with surrounding content
- Improvements to the file shortcode
> Update theme (2022-12-13)

- docs/products/tools/marketplace/guides/unifi-network-application/index.md
update deployment doc for correct debian version
> [Update] Deploy the UniFi Network Application through the Linode Marketplace

- docs/products/platform/accounts/guides/third-party-authentication/index.md
- docs/products/platform/accounts/guides/user-security-controls/index.md
- docs/products/platform/billing/guides/tax-information/index.md
- docs/products/tools/cli/guides/manage-multiple-accounts/index.md
- docs/products/tools/marketplace/guides/unifi-network-application/index.md
- docs/release-notes/api/2017-10-23.md
- docs/release-notes/api/2018-01-08.md
- docs/release-notes/api/2018-01-24.md
- docs/release-notes/api/v4.7.0.md
- docs/release-notes/cloud-manager/v0.45.0.md
- docs/release-notes/cloud-manager/v0.57.0.md
- docs/release-notes/cloud-manager/v1.9.1.md
- Tax Information
- Deploy the UniFi Network Application through the Linode Marketplace
> [Release Candidate] v1.204.0

- docs/products/platform/billing/guides/make-a-payment/index.md
The hyper link text had a typo in it, just proposing a fix.
> [Fix] Billing > Make a Payment

- docs/products/tools/marketplace/guides/drupal/index.md
Update distro and deployment details
> [Update] Deploy Drupal through the Linode Marketplace

- docs/guides/applications/big-data/install-a-jupyter-notebook-server-on-a-linode-behind-an-apache-reverse-proxy/index.md
* Remove redundant requirement in Before You Begin
* Fix cert command
* Fix file path
> [Update] Installing a Jupyter Notebook on a Linode Behind an Apache Reverse Proxy

- docs/products/compute/gpu/_index.md
Switching "maching" to "machine".
> fix: quick spelling error

- _vendor/github.com/linode/linode-api-docs/v4/openapi.yaml
- _vendor/modules.txt
- docs/release-notes/api/v4.142.1.md
- go.mod
- go.sum
- package-lock.json
- API v4.142.1 [Release Notes](https://www.linode.com/docs/products/tools/api/release-notes/)
- Updated [API docs](https://www.linode.com/docs/api) spec to [v4.142.1](https://github.com/linode/linode-api-docs/releases/tag/v4.142.1)
> [Release Candidate] v1.208.0

- ci/vale/dictionary.txt
- docs/release-notes/cloud-manager/v1.83.0.md
- docs/release-notes/lke/v1.45.0.md
- LKE v1.45.0 release notes
- Cloud  Manager v1.83.0 release notes
> [Hotfix] v1.208.1

- _vendor/github.com/linode/linode-api-docs/v4/openapi.yaml
- _vendor/modules.txt
- docs/release-notes/api/v4.142.2.md
- go.mod
- go.sum
> [Hotfix] v1.208.2

- _vendor/github.com/linode/linode-api-docs/v4/openapi.yaml
- _vendor/modules.txt
- docs/release-notes/api/v4.142.2.md
- go.mod
- go.sum
* Added API v4.142.2 release notes
* Bump API spec to v4.142.2
> [Hotfix] v1.208.2 (merge main into develop)

- _vendor/github.com/linode/linode-api-docs/v4/openapi.yaml
- _vendor/modules.txt
- docs/release-notes/cloud-manager/v1.83.1.md
- go.mod
- go.sum
- Cloud Manager v1.83.1 [release notes](https://www.linode.com/docs/release-notes)
- API Docs spec updated to [v4.142.3-patch1](https://github.com/linode/linode-api-docs/releases/tag/v4.142.3-patch1)
> [Hotfix] v1.208.3

- docs/guides/applications/configuration-management/terraform/beginners-guide-to-terraform/index.md
the repo maintained by hashicorp is now archived. linode's repo is active one
> [Fix] A Beginner's Guide to Terraform

- docs/guides/networking/linode-network/ip-failover/index.md
- docs/guides/networking/linode-network/network-infrastructure-upgrades/index.md
This PR updates the IP Sharing and network upgrade status for the Dallas data center.
> Changes related to network infrastructure upgrades in Dallas

- docs/products/tools/marketplace/guides/mean-stack/index.md
- Added information about PM2
- Fixes: https://github.com/linode/docs/issues/5906
- Validated that pm2 is indeed installed:
> [Update] Deploy a MEAN Stack through the Linode Marketplace

- docs/guides/websites/cms/cpanel/use-cpanel-to-manage-domains-and-databases/index.md
- Updated port number after checking on https://docs.cpanel.net/knowledge-base/general-systems-administration/how-to-configure-your-firewall-for-cpanel-services/
> [update] Use cPanel to Manage Domains and Databases

- docs/guides/_shortguides/email-warning-shortguide/index.md
- docs/products/tools/marketplace/guides/_index.md
- docs/products/tools/marketplace/guides/pritunl/index.md
- docs/products/tools/marketplace/guides/secure-your-server/index.md
This PR adds a guide for the existing Secure Your Server marketplace app.
> [New] Secure Your Server through the Linode Marketplace

- _vendor/github.com/linode/linode-api-docs/v4/openapi.yaml
- _vendor/modules.txt
- go.mod
- go.sum
* Update API reference to API spec v4.143.2
> [Release Candidate] v1.213.0

- _vendor/github.com/linode/linode-docs-theme/assets/css/components/buttons.css
- _vendor/github.com/linode/linode-docs-theme/assets/css/styles.css
- _vendor/github.com/linode/linode-docs-theme/assets/js/main/index.js
- _vendor/github.com/linode/linode-docs-theme/assets/js/main/navigation/index.js
- _vendor/github.com/linode/linode-docs-theme/assets/js/main/navigation/paginator.js
- _vendor/github.com/linode/linode-docs-theme/assets/js/main/search/search-store.js
- _vendor/github.com/linode/linode-docs-theme/assets/js/main/sections/sections/list.js
- _vendor/github.com/linode/linode-docs-theme/config.toml
- _vendor/github.com/linode/linode-docs-theme/content/testpages/_index.md
- _vendor/github.com/linode/linode-docs-theme/content/testpages/links.md
- _vendor/github.com/linode/linode-docs-theme/content/testpages/toc.md
- _vendor/github.com/linode/linode-docs-theme/content/testpages/typography.md
- _vendor/github.com/linode/linode-docs-theme/layouts/_default/content-only.html
- _vendor/github.com/linode/linode-docs-theme/layouts/index.json
- _vendor/github.com/linode/linode-docs-theme/layouts/partials/sections/navigation/explorer.html
- _vendor/github.com/linode/linode-docs-theme/layouts/release-notes/list.html
- _vendor/github.com/linode/linode-docs-theme/layouts/shortcodes/releasenotes/list.html
- _vendor/github.com/linode/linode-website-partials/attribution-inline.js
- _vendor/github.com/linode/linode-website-partials/footer-inline.js
- _vendor/github.com/linode/linode-website-partials/footer.css
- _vendor/github.com/linode/linode-website-partials/footer.html
- _vendor/github.com/linode/linode-website-partials/header.css
- _vendor/github.com/linode/linode-website-partials/header.html
- _vendor/github.com/linode/linode-website-partials/header.js
- _vendor/modules.txt
- go.mod
- go.sum
- Added pagination for Release Notes
- Updated header and footer
> Update theme (2023-02-01)

- _vendor/github.com/linode/linode-docs-theme/content/testpages/links.md
- _vendor/github.com/linode/linode-docs-theme/layouts/index.html
- _vendor/modules.txt
- go.mod
- go.sum
This PR updates a few of the docs links that are hard-coded into the theme, including the home page links to the Get Started and API guides.
> Update theme 2023-02-07

- docs/products/networking/dns-manager/guides/a-record/index.md
Wrong title, expected "AAAA" instead of "AAA"
> [Fix] DNS Manager > A and AAAA Records

- _vendor/github.com/linode/linode-docs-theme/assets/css/grids/grid--base.css
- _vendor/github.com/linode/linode-docs-theme/assets/js/main/components/index.js
- _vendor/github.com/linode/linode-docs-theme/assets/js/main/components/tabs.js
- _vendor/github.com/linode/linode-docs-theme/assets/js/main/helpers/helpers.js
- _vendor/github.com/linode/linode-docs-theme/assets/js/main/index.js
- _vendor/github.com/linode/linode-docs-theme/assets/js/main/navigation/nav-store.js
- _vendor/github.com/linode/linode-docs-theme/content/testpages/_index.md
- _vendor/github.com/linode/linode-docs-theme/content/testpages/tabs-page-1.md
- _vendor/github.com/linode/linode-docs-theme/content/testpages/tabs-page-2.md
- _vendor/github.com/linode/linode-docs-theme/content/testpages/tabs-page-3.md
- _vendor/github.com/linode/linode-docs-theme/layouts/shortcodes/note.html
- _vendor/github.com/linode/linode-docs-theme/layouts/shortcodes/tab.html
- _vendor/github.com/linode/linode-docs-theme/layouts/shortcodes/tabs.html
- _vendor/github.com/linode/linode-website-partials/footer.html
- _vendor/github.com/linode/linode-website-partials/header.css
- _vendor/github.com/linode/linode-website-partials/header.html
- _vendor/modules.txt
- go.mod
- go.sum
Theme updates:
- New shortcode for tabbed content
- Header/footer updates
> [Hotfix] v1.216.1

- docs/products/databases/managed-databases/guides/updates-and-maintenance/index.md
This PR updates the downtime notice related to Managed Database maintenance updates. Specifically, it clarifies that a high availability plan doesn't always eliminate downtime during updates and the cluster may experience a momentary loss of connectivity when failover occurs.
> [Update] Managed Database > Automatic Updates and Maintenance Windows

- docs/products/platform/accounts/guides/cancel-account/index.md
This PR updates the Cancel Your Account guide to include a note about refunds, specifically our policy on refunds within the first 7 days and instructions for requesting a refund.
> [Update] Accounts > Cancel Your Account

- docs/products/networking/dns-manager/get-started/index.md
- docs/products/networking/dns-manager/guides/_index.md
- docs/products/networking/dns-manager/guides/manage-dns-records/index.md
Modified some error descriptions
> [Fix] DNS Manager > Get started & Guides & Manage DNS Records 

- _vendor/github.com/linode/linode-docs-theme/assets/css/grids/grid--base.css
- _vendor/github.com/linode/linode-docs-theme/layouts/_default/baseof.html
- _vendor/github.com/linode/linode-website-partials/header.css
- _vendor/github.com/linode/linode-website-partials/header.html
- _vendor/modules.txt
- go.mod
- go.sum
Theme updates
- Fix top banner grid spacing issues
- Remove Linode logo from Explore Docs menu
> [Hotfix] v1.217.1

- docs/products/tools/marketplace/guides/gopaddle/index.md
> [Update] Deploy gopaddle through the Linode Marketplace

- docs/products/platform/accounts/_index.md
- docs/products/platform/accounts/developers/index.md
- docs/products/platform/accounts/guides/change-user-email/index.md
- docs/products/platform/accounts/guides/reset-user-password/index.md
- docs/products/platform/accounts/resources/index.md
- docs/products/platform/billing/developers/index.md
- docs/products/platform/billing/guides/_index.md
- docs/products/platform/billing/guides/access-billing/index.md
- docs/products/platform/billing/guides/make-a-payment/index.md
- docs/products/platform/billing/guides/payment-methods/index.md
- docs/products/platform/billing/guides/promo-code/index.md
- docs/products/platform/billing/guides/referral-program/index.md
- docs/products/platform/billing/guides/stop-billing/index.md
- docs/products/platform/billing/guides/update-billing-contact-info/index.md
- docs/products/platform/billing/guides/view-history/index.md
- docs/products/platform/billing/resources/index.md
This PR updates the frontmatter parameter for product docs without a `published` date.
> Update to published front matter in Platform > Billing and Platform > Account

- _vendor/github.com/linode/linode-docs-theme/content/testpages/links.md
- _vendor/github.com/linode/linode-docs-theme/layouts/alias.html
- _vendor/modules.txt
- go.mod
- go.sum
This theme PR fixes the `/null` issue that may occur when navigating to an alias URL.
> Update theme 2023-02-24

- docs/guides/game-servers/create-an-ark-server-on-ubuntu/index.md
updated the links that linked to the old wiki which was abandoned in April 2022 to move to the new platform as you see in this article from the official forums https://survivetheark.com/index.php?/forums/topic/657902-official-ark-wiki-feedback/&
> [Update] Creating a Dedicated ARK Server on Ubuntu

- docs/guides/platform/get-started/support/index.md
As specified in: https://docs.google.com/document/d/17P5qAro6HCybsaff1oGFtLSjx3pGKSC2-DZvBb2cnlg
Related to launch of new support contact form.
> Replace support email CTA with link to new form

- docs/guides/platform/get-started/network-transfer/index.md
- docs/products/compute/_shortguides/april-price-update-shortguide/index.md
- docs/products/compute/compute-instances/_index.md
- docs/products/compute/compute-instances/plans/_index.md
- docs/products/compute/compute-instances/plans/choosing-a-plan/index.md
- docs/reference-architecture/cloud-based-document-management-system/guides/implementing-cloud-based-document-management-system/index.md
- Adds a notice at the top of some product docs that outlines the April 1st pricing changes.
> [Release Candidate] v1.220.1

- docs/guides/platform/get-started/network-transfer/index.md
- docs/products/compute/_shortguides/april-price-update-shortguide/index.md
- docs/products/compute/compute-instances/guides/upcoming-pricing-changes-april-2023/index.md
Preview: [Upcoming Pricing Changes (Effective 4/1/2023)](https://deploy-preview-6124--nostalgic-ptolemy-b01ab8.netlify.app/docs/products/compute/compute-instances/guides/upcoming-pricing-changes-april-2023/)
> [New] Upcoming Pricing Changes (Effective 4/1/2023)

- _vendor/github.com/linode/linode-website-partials/footer.html
- _vendor/github.com/linode/linode-website-partials/header.html
- _vendor/modules.txt
- docs/guides/platform/get-started/network-transfer/index.md
- docs/products/compute/_shortguides/april-price-update-shortguide/index.md
- docs/products/compute/compute-instances/guides/upcoming-pricing-changes-april-2023/index.md
- go.mod
- go.sum
- Upcoming Pricing Changes (Effective 4/1/2023)
- Updates to the header and footer
> [Release Candidate] v1.220.2

- docs/products/compute/compute-instances/guides/upcoming-pricing-changes-april-2023/index.md
- Upcoming Pricing Changes (Effective 4/1/2023)
> [Release Candidate] v1.220.3

- docs/products/compute/compute-instances/guides/manage-the-kernel/index.md
_ incorporated the feedback from a users about appending the option and not deleting other lines.
> [update] Manage the Kernel on a Compute Instance

- docs/guides/websites/cms/wordpress/how-to-install-and-configure-wordpress/index.md
- docs/products/compute/compute-instances/guides/migrate-to-different-dc/index.md
The nex Hugo version will throw an error for these.
> Fix 2 unclosed notes shortcodes

- docs/products/compute/compute-instances/guides/multiqueue-nic/index.md
This PR updates multiqueue NICs instructions to remove 8 queue maximum.
> [Update] Compute Instances > Configuring Multi-Queue NICs

- docs/guides/applications/configuration-management/salt/use-salt-states-to-configure-a-lamp-stack-on-a-minion/index.md
- docs/guides/linode-writers-formatting-guide/index.md
- docs/products/compute/compute-instances/guides/manual-network-configuration/index.md
- docs/products/platform/accounts/guides/cancel-account/index.md
- docs/products/platform/billing/_index.md
- Fixed a spelling error
- Corrected "Indentation" heading placement within the Writer's Formatting Guide
- Linked to refund section from Cancel Account guide.
> Misc fixes (2023-03-02)

- docs/authors/rajakavitha-kodhandapani/_index.md
- docs/guides/databases/mongodb/create-a-mongodb-replica-set/index.md
- tested and validated the instructions on Ubuntu 22.04 and it works as expected.
- tried to recreate the issues and addressed them in the instructions.
> [Update] Creating a MongoDB Replica Set

- docs/release-notes/cloud-manager/v1.88.0.md
- docs/release-notes/cloud-manager/v1.89.0.md
This PR adds release notes for Cloud Manager v1.88.0 and v1.89.0
> [Release Notes] Cloud Manager v1.88.0, v1.89.0

- docs/guides/tools-reference/basics/restart-linux-server-from-the-command-line/index.md
_ added a note about enabling Lassie.
> [update] Restart a Linux Server from the Command Line

- docs/guides/kubernetes/deploy-kubernetes-cluster-using-kubeadm/index.md
_ updated, tested, and validated the steps in the guide.
> [update] Deploy a Kubernetes Cluster Using kubeadm

- docs/products/platform/billing/guides/tax-information/index.md
> [Release Candidate] v1.226.2

- docs/products/tools/marketplace/guides/cpanel/index.md
- docs/products/tools/marketplace/guides/virtualmin/index.md
Remove CentOS 7, add AlmaLinux 8
> cPanel distro update

- docs/guides/databases/mysql/install-and-configure-mysql-on-ubuntu-22-04/index.md
- docs/guides/development/javascript/javascript-base-64-decode/index.md
Effects:
- Install and Configure MySQL on Ubuntu 22.04
- JavaScript Base 64 Decoding and Encoding
> [Update] Add new formatting to recently merged guides

- docs/guides/kubernetes/how-to-deploy-kubernetes-on-linode-with-rancher-2-x/index.md
This reverts commit a486c539a6c479c402c4779f7d385e5fbd93cf32.
> Revert "[update] Deploying Kubernetes on Linode with Rancher (#6214)"

- docs/release-notes/cloud-manager/v1.89.1.md
- docs/release-notes/cloud-manager/v1.90.0.md
This PR adds release notes for Cloud Manager v1.89.1 and v1.90.0.
> [Release Notes] Cloud Manager v1.89.1, v1.90.0

- docs/products/tools/marketplace/guides/beef/index.md
> [Update] Deploy BeEF through the Linode Marketplace

- docs/guides/databases/mysql/configure-master-master-mysql-database-replication/index.md
- docs/guides/development/concepts/logic-programming-languages/index.md
- docs/guides/development/javascript/getting-started-ember/index.md
- docs/guides/development/python/how-to-write-and-run-python-script/index.md
- docs/guides/development/python/python-data-types/index.md
- docs/guides/development/python/python-stacks/index.md
- docs/guides/development/python/python-variables/index.md
- docs/guides/websites/static-sites/generating-static-sites-with-gatsby/index.md
- Fixes outdated internal links
- Minor changes to new guides
> Misc fixes

- docs/guides/security/authentication/use-public-key-authentication-with-ssh/index.md
This PR clarifies some incorrect aspects of public/private keypair authentication. It also updates the formatting.
> [Fix] Using SSH Public Key Authentication on Linux, macOS, and Windows

- docs/guides/quick-answers/linux/wordpress-with-docker-compose/index.md
- added the missing environment variable for compose
> [update] Install WordPress with Docker Compose

- docs/products/tools/marketplace/guides/moodle/index.md
_ included the software that are installed and additional details such as ports and password setting
- did not include the version number because none of the OCA guide have the exact version of the software installed
>  [Update] Deploy Moodle through the Linode Marketplace

- docs/guides/email/postfix/configure-spf-and-dkim-in-postfix-on-debian-8/index.md
- docs/guides/email/postfix/configure-spf-and-dkim-in-postfix-on-debian-9/index.md
removed references to http://www.openspf.org/
> [update] Configure SPF and DKIM With Postfix on Debian 8

- docs/products/tools/marketplace/guides/harbor/index.md
_ added a sentence about not being able to install Harbor on LKE
> [update] Deploy Harbor through the Linode Marketplace

- docs/products/tools/marketplace/guides/liveswitch/index.md
update contact link & description per partner recommendation
> [Update] Deploy LiveSwitch through the Linode Marketplace

- docs/products/_index.md
- docs/products/compute/_index.md
- docs/products/compute/kubernetes/guides/_index.md
- docs/products/compute/kubernetes/release-notes/_index.md
- docs/products/databases/_index.md
- docs/products/databases/managed-databases/developers/index.md
- docs/products/databases/managed-databases/resources/index.md
- docs/products/networking/_index.md
- docs/products/networking/vlans/guides/_index.md
- docs/products/platform/_index.md
- docs/products/services/managed/guides/_index.md
- docs/products/storage/_index.md
- docs/products/storage/backups/_index.md
- docs/products/storage/backups/guides/_index.md
- docs/products/storage/block-storage/guides/_index.md
- docs/products/tools/_index.md
- docs/products/tools/api/release-notes/_index.md
- docs/products/tools/cli/get-started/index.md
- docs/products/tools/cli/guides/_index.md
- docs/products/tools/cloud-manager/developers/index.md
- docs/products/tools/cloud-manager/release-notes/_index.md
- docs/products/tools/marketplace/guides/_index.md
- docs/release-notes/_index.md
- docs/release-notes/api/_index.md
- docs/release-notes/cloud-manager/_index.md
- docs/release-notes/lke/_index.md
This PR introduces some additional meta tag improvements (`title_meta` and `description` parameters) to product docs.
> Additional meta tag improvements for product docs

- docs/release-notes/lke/v1.47.0.md
Added release notes for LKE v1.47
> [Release Notes] LKE v1.47

- docs/guides/networking/ssh/connect-to-server-over-ssh-on-linux/index.md
- docs/guides/networking/ssh/connect-to-server-over-ssh-on-mac/index.md
- docs/guides/networking/ssh/connect-to-server-over-ssh-on-windows/index.md
- docs/guides/networking/ssh/connect-to-server-over-ssh-using-putty/index.md
- docs/guides/networking/ssh/connect-to-server-over-ssh/index.md
- docs/guides/security/authentication/use-public-key-authentication-with-ssh/index.md
- docs/products/compute/compute-instances/guides/create/index.md
- docs/products/compute/compute-instances/guides/set-up-and-secure/index.md
- docs/products/platform/accounts/guides/2fa/index.md
- docs/release-notes/lke/v1.47.0.md
> [Release Candidate] v1.330.2

- ci/vale/dictionary.txt
- docs/guides/websites/lms/install-canvas-lms-on-ubuntu-2204/index.md
- Formatted texts and style as per Linode style guide
- Tech edited
> Install Canvas on Ubuntu 22.04 - copy content from word to md

- docs/guides/security/basics/secure-web-server/index.md
> [update] How to Secure Web Servers

- _vendor/github.com/linode/linode-api-docs/v4/openapi.yaml
- _vendor/modules.txt
- docs/guides/security/basics/secure-web-server/index.md
- docs/release-notes/api/v4.152.0.md
- go.mod
- go.sum
* API v4.152.0 release notes
* API reference to API spec v4.152.0
* How to Secure Web Servers
> [Release Candidate] v1.332.0

- ci/vale/dictionary.txt
- docs/guides/quick-answers/linux/linux-dump-and-restore-commands/index.md
- Copy content from [Word](https://docs.google.com/document/d/1vn_ykVNabk4dmEjFyWleFrN7bYn944mgP6sfQYs8UuU/edit#) to MD
- Tech edits for "Quick Guide to the Linux Dump and Restore Commands"
> Quick Guide to the Linux Dump and Restore Commands

- docs/products/platform/get-started/_index.md
_ removed the mention of bare metal in the guide.
> [update] Platform - Getting Started on the Linode Platform

- docs/guides/quick-answers/linux/how-to-use-cd/index.md
- docs/products/storage/block-storage/guides/attach-and-detach/index.md
- docs/products/storage/block-storage/resources/index.md
- docs/products/tools/images/resources/index.md
_ incorporate victorious suggestions
> [update] block storage, images, cd command, attach volume

- _vendor/github.com/linode/linode-api-docs/v4/openapi.yaml
- _vendor/modules.txt
- go.mod
- go.sum
- Updated API reference to API spec v4.152.3
> [Release Candidate] v1.334.0

- docs/products/platform/billing/_index.md
> [Update] Billing

- docs/products/tools/images/guides/upload-an-image/index.md
- Updated the command after testing and confirming with the guide https://www.linode.com/docs/guides/archiving-and-compressing-files-with-gnu-tar-and-gnu-zip/#the-gzip-command
> [Update] Custom Images > Upload an Image

- docs/products/platform/accounts/guides/service-transfers/index.md
Added a note about the default generic label.
> [update] Transfer Services to a Different Account

- _vendor/github.com/linode/linode-api-docs/v4/openapi.yaml
- _vendor/modules.txt
- docs/release-notes/api/v4.153.2.md
- go.mod
- go.sum
* Added API v4.153.2 release notes
> [Release Candidate] v1.238.0

- _vendor/github.com/linode/linode-api-docs/v4/openapi.yaml
- _vendor/modules.txt
- go.mod
- go.sum
- Updated API spec to v4.153.3-patch.1
> [Hotfix] v1.238.1

- docs/guides/email/best-practices/running-a-mail-server/index.md
Announcement by Microsoft: [Office is now Microsoft 365](https://support.microsoft.com/en-us/office/office-is-now-microsoft-365-22eac811-08d6-4df3-92dd-77f193e354a5)
> Update Office 365 to be Microsoft 365

- docs/products/platform/accounts/guides/manage-ssh-keys/index.md
Adds a list of SSH key types supported by the Linode Platform.
> [Update] Manage SSH Keys

- docs/guides/databases/mysql/install-mysql/index.md
- docs/products/compute/compute-instances/guides/distributions/index.md
- [Updated] Choosing a Linux Distribution: Removed and deprecated some distributions.
- [Updated] Installing MySQL: A Definitive Guide: Updated references to Fedora distros we no longer support.
> Updated list of distros 

- docs/products/tools/marketplace/guides/harbor/index.md
> [Update] Deploy the Harbor through the Linode Marketplace

- docs/guides/databases/hadoop/how-to-install-and-set-up-hadoop-cluster/index.md
- added a link to securing the containers at the end of the guide.
> [update] How to Install and Set Up a 3-Node Hadoop Cluster

- docs/products/tools/images/guides/capture-an-image/index.md
This PR clarifies the max disk usage when attempting to capture an image.
> [Update] Capture an Image

- docs/guides/applications/remote-desktop/install-vnc-on-ubuntu-20-04/index.md
_ added the links to the steps that details how to secure and connect.
> [update] Install VNC on Ubuntu 20.04

- docs/products/platform/get-started/guides/beta-for-new-data-centers/index.md
This PR adds Chicago to the new data center beta doc.
> [Update] Closed Beta for Akamai's New Data Centers

- ci/vale/dictionary.txt
- docs/guides/quick-answers/linux/customization-tricks-for-ssh/index.md
> SSH Customization Tricks- tech edits

- docs/guides/development/python/python-get-current-directory/index.md
> How to Get the Current Directory in Python

- _vendor/github.com/linode/linode-api-docs/v4/openapi.yaml
- _vendor/modules.txt
- docs/release-notes/api/v4.155.0.md
- go.mod
- go.sum
* Added API v4.155.0 release notes
* Updated API reference to API spec v4.155.0
> API Docs v4.155.0

- _vendor/github.com/linode/linode-docs-theme/assets/css/styles.css
- _vendor/github.com/linode/linode-docs-theme/content/api/testing/spec.yaml
- _vendor/github.com/linode/linode-docs-theme/layouts/api/__common.html
- _vendor/github.com/linode/linode-docs-theme/layouts/partials/sections/navigation/language-switcher.html
- _vendor/github.com/linode/linode-docs-theme/layouts/partials/sections/navigation/toc.html
- _vendor/github.com/linode/linode-docs-theme/tailwind.config.js
- _vendor/modules.txt
- go.mod
- go.sum
- Fixed duplicate `id` tags in language selector
- Fixed `aria-label` tags in the Table of Contents show/hide icons
- Fixed an API docs display bug where a boolean property for an endpoint's Request Body Schema would not be displayed if the default value was `false`.
> Update theme (2023-06-21)

- ci/vale/dictionary.txt
- docs/guides/tools-reference/tools/command-line-tools/index.md
This pull request converts the "**Command Line Tools: A Beginner’s Guide**" guide from a Word document to Markdown format. Additionally, it includes technical edits to enhance clarity and accuracy.
Please review the changes.
> Command Line Tools: A Beginner’s Guide - Tech edits

- docs/products/platform/billing/_index.md
This PR updates the billing examples to use a different product with updating pricing.
> [Update] Understanding How Billing Works on the Linode Platform

- docs/guides/applications/remote-desktop/install-vnc-on-ubuntu-18-04/index.md
- Added deprecation notice for 18.04 version. tested and validated the instructions for 20.04
> [update] Install VNC on Ubuntu 18.04

- docs/guides/kubernetes/how-to-migrate-from-k8s-alpha-to-terraform/index.md
Updated the front matter with building false.
> [update] Migrating from k8s-alpha CLI to Terraform

- docs/guides/platform/disk-images/kvm-reference/index.md
- docs/products/compute/compute-instances/guides/upcoming-pricing-changes-april-2023/index.md
- docs/products/compute/compute-instances/plans/comparing-shared-and-dedicated-cpus/index.md
- docs/products/compute/compute-instances/plans/gpu/index.md
- docs/products/storage/block-storage/_index.md
- docs/products/storage/block-storage/guides/nvme-upgrade/index.md
This PR adds any missing column headers to various tables in our documentation to address accessibilities issues.
> Add missing column headers on tables

- _vendor/github.com/linode/linode-api-docs/v4/openapi.yaml
- _vendor/modules.txt
- go.mod
- go.sum
* Updated API reference to API spec v4.157.1
> API Docs v4.157.1

- docs/products/compute/compute-instances/guides/failover/index.md
- docs/products/compute/compute-instances/guides/network-infrastructure-upgrades/index.md
This PR updates the failover status for Tokyo to *undergoing network upgrades* and marks Dallas as complete.
> [Update] Configure Failover on a Compute Instance

- docs/products/compute/compute-instances/plans/choosing-a-plan/index.md
- docs/products/compute/compute-instances/plans/premium/index.md
- [Update] Premium Compute Instances
- [Update] Choosing a Compute Instance Type and Plan
This PR updates the language used for Premium Plan availability.
> Copy edit for Premium instance availability

- .github/workflows/cache-images.yaml
- .github/workflows/test.yaml
- _vendor/github.com/linode/linode-docs-theme/layouts/_default/alternative-guides-parent.html
- _vendor/github.com/linode/linode-docs-theme/layouts/_default/list.html
- _vendor/github.com/linode/linode-docs-theme/layouts/index.html
- _vendor/github.com/linode/linode-docs-theme/layouts/partials/components/alternative-guides__dropdown.html
- _vendor/github.com/linode/linode-docs-theme/layouts/partials/components/image-modal.html
- _vendor/github.com/linode/linode-docs-theme/layouts/partials/helpers/leak-checker.html
- _vendor/github.com/linode/linode-docs-theme/layouts/release-notes/list.html
- _vendor/github.com/linode/linode-docs-theme/package.hugo.json
- _vendor/github.com/linode/linode-docs-theme/package.json
- _vendor/github.com/linode/linode-docs-theme/tailwind.config.js
- _vendor/github.com/linode/linode-website-partials/footer.css
- _vendor/github.com/linode/linode-website-partials/footer.html
- _vendor/github.com/linode/linode-website-partials/header.css
- _vendor/github.com/linode/linode-website-partials/header.html
- _vendor/github.com/linode/linode-website-partials/header.js
- _vendor/modules.txt
- config/_default/build.toml
- config/_default/module.toml
- docs/products/compute/compute-instances/plans/choosing-a-plan/index.md
- docs/products/compute/compute-instances/plans/premium/index.md
- go.mod
- go.sum
- package-lock.json
- package.json
Updates:
- Choosing a Compute Instance Type and Plan
Theme updates:
- Tailwind 3 upgrade
- Header/footer updates
- Fix for ampersand rendering in blog/content resource section pages
> [Release] v1.252.0

- docs/guides/tools-reference/custom-kernels-distros/install-nixos-on-linode/index.md
_ updated the option for the latest version of NixOS.
_ fixes https://github.com/linode/docs/issues/6464
> [Update] Install and Configure NixOS on a Linode

- ci/vale/dictionary.txt
- docs/guides/databases/general/database-solutions/index.md
- docs/guides/databases/general/list-of-databases/index.md
This PR includes a new guide that provides information on the various database management systems and how to host these databases on Akamai. 
Preview: [Determine the Best Database and Cloud Hosting Solution for Your Next Application](https://deploy-preview-6478--nostalgic-ptolemy-b01ab8.netlify.app/docs/guides/database-solutions/)
> [New] Determine the Best Database and Cloud Hosting Solution for Your Next Application

- _vendor/github.com/linode/linode-api-docs/v4/openapi.yaml
- _vendor/modules.txt
- docs/release-notes/api/v4.158.0.md
- docs/release-notes/api/v4.158.1.md
- go.mod
- go.sum
* Added API v4.158.0 and v4.158.1 release notes
* Updated API Docs spec to v4.158.1
> [Release Candidate] v1.254.0 (API Docs v4.158.0 v4.158.1)

- docs/products/platform/get-started/guides/beta-for-new-data-centers/index.md
This PR adds Chennai to the beta doc for the new data centers.
> [Update] Limited Beta for Akamai's New Data Centers

- _vendor/github.com/linode/linode-api-docs/v4/openapi.yaml
- _vendor/modules.txt
- docs/release-notes/api/v4.159.0.md
- go.mod
- go.sum
* Added API v4.159.0 release notes
* Update API reference to API spec v4.159.0
> API Docs v4.159.0

- docs/guides/databases/mongodb/install-mongodb-on-centos-7/index.md
- docs/guides/platform/migrate-to-linode/migrate-cpanel-to-linode/index.md
- docs/guides/websites/cms/cpanel/install-cpanel-on-centos/index.md
- Added the option to deploy cpanel using marketplace
- Updated the other distros that cn be used.
> [Update] How to Migrate a CPanel Server to Linode

- docs/products/networking/vlans/get-started/index.md
This PR fixes a typo on the VLANs > Get Started guide.
> [Update] VLANs > Get Started

- docs/products/platform/get-started/guides/resell-services/index.md
This PR updates the first paragraph of our reseller guide to correct the partner email address, add a link to the partner form, and provide additional copy improvements.
> [Update] Resell Linode Services

- docs/products/tools/marketplace/guides/wordpress/index.md
> [update] Guides - Deploy WordPress through the Linode Marketplace

- docs/guides/applications/configuration-management/terraform/how-to-build-your-infrastructure-using-terraform-and-linode/index.md
This fixes an issue with the commit history of PR #6493
> [Update] Use Terraform to Provision Infrastructure on Linode

- docs/guides/applications/configuration-management/terraform/how-to-build-your-infrastructure-using-terraform-and-linode/index.md
- docs/guides/databases/mongodb/install-mongodb-on-centos-7/index.md
- docs/guides/kubernetes/how-to-setup-a-private-docker-registry-with-lke-and-object-storage/index.md
- docs/guides/kubernetes/terraform-vs-helm/index.md
- docs/guides/platform/migrate-to-linode/migrate-cpanel-to-linode/index.md
- docs/guides/websites/cms/cpanel/install-cpanel-on-centos/index.md
- docs/products/networking/vlans/get-started/index.md
- docs/products/platform/billing/guides/tax-information/index.md
- docs/products/platform/get-started/guides/resell-services/index.md
- docs/products/tools/marketplace/guides/_index.md
- docs/products/tools/marketplace/guides/wazuh/index.md
- docs/products/tools/marketplace/guides/wordpress/index.md
- Comparing Terraform and Helm: When to Use Each Tool
- Billing > Tax Information
- Get Started > Resell Linode Services
- How to Migrate a cPanel Server to Linode
- Install cPanel on CentOS
- Use Terraform to Provision Infrastructure on Linode
- Setting Up a Private Docker Registry with LKE and Object Storage
- Deploy Wazuh through the Linode Marketplace
> [Release Candidate] v1.257.0

- docs/guides/tools-reference/tools/rclone-object-storage-file-sync/index.md
- docs/products/platform/get-started/guides/beta-for-new-data-centers/index.md
- Limited Beta for Akamai's New Data Centers
- Use Rclone to Sync Files to Linode Object Storage
> [Release Candidate] v1.258.0

- _vendor/github.com/gohugoio/hugo-mod-jslibs/instantpage/layouts/partials/jslibs/instantpage/script-src.html
- _vendor/github.com/gohugoio/hugo-mod-jslibs/turbo/v7/layouts/partials/jslibs/turbo/script-src.html
- _vendor/github.com/linode/linode-website-partials/footer.css
- _vendor/github.com/linode/linode-website-partials/footer.html
- _vendor/github.com/linode/linode-website-partials/header.js
- _vendor/modules.txt
- go.mod
- go.sum
- netlify.toml
Theme updates:
- Update linode-website-partials
Site updates:
- Update Netlify to Hugo 0.116.1
> Update theme, update Netlify to Hugo 0.116.1

- docs/guides/uptime/monitoring-configure-email-alerts-shortguide/index.md
Clarify the CPU usage wordings.
> [update] Configure Email Alerts for Resource Usage on Compute Instances

- docs/release-notes/lke/v1.46.0.md
- docs/release-notes/lke/v1.52.0.md
- LKE v1.46 grammar edit
- Added LKE v1.52 release notes
> Release notes for LKE v1.52.0

- docs/guides/tools-reference/tools/rclone-object-storage-file-sync/index.md
- removed the references to numbers in the options
- added the daemon option to the amount command
- added the links to the official docs for mount, sync, and copy
> [update] Use Rclone to Sync Files to Linode Object Storage

- docs/products/platform/get-started/guides/beta-for-new-data-centers/index.md
Consolidated Weblish and Glish gateways using a single API endpoint
> Update weblish/glish gateways in Limited Beta for new DCs doc

- docs/products/compute/compute-instances/guides/install-nvidia-cuda/index.md
_ add a link to the section where you can choose a distribution for your GPU. instance.
> [update] Guides - Install the NVIDIA CUDA Toolkit

- _vendor/github.com/linode/linode-docs-theme/assets/css/sections/content.css
- _vendor/github.com/linode/linode-docs-theme/assets/css/sections/nav/toc.css
- _vendor/github.com/linode/linode-docs-theme/content/testpages/typography.md
- _vendor/github.com/linode/linode-docs-theme/layouts/_default/list.html
- _vendor/github.com/linode/linode-docs-theme/layouts/_default/whatsnew.html
- _vendor/github.com/linode/linode-docs-theme/layouts/api/list.html
- _vendor/github.com/linode/linode-docs-theme/layouts/api/single.html
- _vendor/github.com/linode/linode-docs-theme/layouts/authors/taxonomy.html
- _vendor/github.com/linode/linode-docs-theme/layouts/authors/term.html
- _vendor/github.com/linode/linode-docs-theme/layouts/bundles/taxonomy.html
- _vendor/github.com/linode/linode-docs-theme/layouts/index.html
- _vendor/github.com/linode/linode-docs-theme/layouts/partials/components/alternative-guides__dropdown.html
- _vendor/github.com/linode/linode-docs-theme/layouts/partials/components/disqus.html
- _vendor/github.com/linode/linode-docs-theme/layouts/partials/components/error.html
- _vendor/github.com/linode/linode-docs-theme/layouts/partials/sections/404.html
- _vendor/github.com/linode/linode-docs-theme/layouts/partials/sections/content/products/title-byline.html
- _vendor/github.com/linode/linode-docs-theme/layouts/partials/sections/content/title-byline.html
- _vendor/github.com/linode/linode-docs-theme/layouts/partials/sections/navigation/explorer-toggle.html
- _vendor/github.com/linode/linode-docs-theme/layouts/partials/sections/navigation/toc-main.html
- _vendor/github.com/linode/linode-docs-theme/layouts/partials/sections/search/panel.html
- _vendor/github.com/linode/linode-docs-theme/layouts/release-notes/list.html
- _vendor/github.com/linode/linode-docs-theme/layouts/shortcodes/note.html
- _vendor/github.com/linode/linode-docs-theme/layouts/shortcodes/releasenotes/list.html
- _vendor/modules.txt
- go.mod
- go.sum
- Fixes a scrollbar artifact on scrollable tables
- Fixes the weight of the titles within guides
- Fixes the caret position within the mobile Table of Contents
- Fixes spacing issue within release notes
> Update theme (2023-08-16)

- _vendor/github.com/linode/linode-docs-theme/assets/css/sections/content.css
- _vendor/github.com/linode/linode-docs-theme/assets/css/sections/nav/toc.css
- _vendor/github.com/linode/linode-docs-theme/content/testpages/typography.md
- _vendor/github.com/linode/linode-docs-theme/layouts/_default/list.html
- _vendor/github.com/linode/linode-docs-theme/layouts/_default/whatsnew.html
- _vendor/github.com/linode/linode-docs-theme/layouts/api/list.html
- _vendor/github.com/linode/linode-docs-theme/layouts/api/single.html
- _vendor/github.com/linode/linode-docs-theme/layouts/authors/taxonomy.html
- _vendor/github.com/linode/linode-docs-theme/layouts/authors/term.html
- _vendor/github.com/linode/linode-docs-theme/layouts/bundles/taxonomy.html
- _vendor/github.com/linode/linode-docs-theme/layouts/index.html
- _vendor/github.com/linode/linode-docs-theme/layouts/partials/components/alternative-guides__dropdown.html
- _vendor/github.com/linode/linode-docs-theme/layouts/partials/components/disqus.html
- _vendor/github.com/linode/linode-docs-theme/layouts/partials/components/error.html
- _vendor/github.com/linode/linode-docs-theme/layouts/partials/sections/404.html
- _vendor/github.com/linode/linode-docs-theme/layouts/partials/sections/content/products/title-byline.html
- _vendor/github.com/linode/linode-docs-theme/layouts/partials/sections/content/title-byline.html
- _vendor/github.com/linode/linode-docs-theme/layouts/partials/sections/navigation/explorer-toggle.html
- _vendor/github.com/linode/linode-docs-theme/layouts/partials/sections/navigation/toc-main.html
- _vendor/github.com/linode/linode-docs-theme/layouts/partials/sections/search/panel.html
- _vendor/github.com/linode/linode-docs-theme/layouts/release-notes/list.html
- _vendor/github.com/linode/linode-docs-theme/layouts/shortcodes/note.html
- _vendor/github.com/linode/linode-docs-theme/layouts/shortcodes/releasenotes/list.html
- _vendor/modules.txt
- docs/products/tools/marketplace/guides/_index.md
- docs/products/tools/marketplace/guides/wazuh/index.md
- go.mod
- go.sum
Adds to PR #6543 
- Deploy Wazuh through the Linode Marketplace
- Fixes a scrollbar artifact on scrollable tables
- Fixes the weight of the titles within guides
- Fixes the caret position within the mobile Table of Contents
- Fixes spacing issue within release notes
> [Release Candidate] v1.261.0 (Part 2 of 2)

- docs/products/platform/get-started/guides/beta-for-new-data-centers/index.md
**Updated**:
- Added Seattle DC to Beta DC doc
> [Release Candidate] v1.262.0

- docs/products/storage/object-storage/guides/custom-domain/index.md
This PR removes mention of CNAME flattening and explicitly notes that apex/root domains are not supported.
> [Update] Object Storage > Configure a Custom Domain (with a TLS/SSL Certificate)

- docs/products/platform/get-started/guides/beta-for-new-data-centers/index.md
Added Milan data center details to the Beta DC doc.
> Add Milan to beta DC doc

- _vendor/github.com/linode/linode-docs-theme/assets/css/grids/grid--base.css
- _vendor/github.com/linode/linode-docs-theme/assets/css/sections/content.css
- _vendor/github.com/linode/linode-docs-theme/assets/css/sections/main.css
- _vendor/github.com/linode/linode-docs-theme/assets/css/styles.css
- _vendor/github.com/linode/linode-docs-theme/content/testpages/typography.md
- _vendor/github.com/linode/linode-docs-theme/layouts/_default/_markup/render-image.html
- _vendor/github.com/linode/linode-docs-theme/layouts/_default/baseof.html
- _vendor/github.com/linode/linode-docs-theme/layouts/_default/single.html
- _vendor/github.com/linode/linode-docs-theme/layouts/partials/sections/content/deprecated.html
- _vendor/github.com/linode/linode-docs-theme/layouts/shortcodes/table.html
- _vendor/modules.txt
- go.mod
- go.sum
- Added sticky column and added colors for alternating rows in newer table shortcode.
- Fixed issue where images did not correctly display when the page's URL was missing a trailing slash
- Fixed right margin issue present on certain display sizes when system or browser was set to not display scrollbars.
- Fixed content width and alignment issues introduced with new Table of Contents (for larger screen sizes)
- Other formatting fixes and improvements
> Update theme (2023-08-23)

- docs/guides/applications/configuration-management/salt/automate-a-static-site-deployment-with-salt/index.md
- docs/guides/applications/configuration-management/terraform/create-a-nodebalancer-with-terraform/index.md
- docs/guides/databases/cassandra/install-cassandra-across-multiple-data-centers/index.md
- docs/guides/development/version-control/backing-up-gitlab-on-linode-object-storage/index.md
- docs/guides/quick-answers/linode-platform/dhcp-ip-address-reference/index.md
- docs/guides/quick-answers/linux-essentials/multi-cloud-vs-hybrid-cloud/index.md
- docs/products/networking/dns-manager/guides/incoming-dns-zone-transfers/index.md
Fixed data center spelling and fixed apt- command
> Misc fixes (2023-08-22)

- docs/products/compute/_shortguides/metadata-beta-notice/index.md
Updated the metadata beta notice to include links to the soon to be published blog post and feedback survey.
> Updated Metadata beta notice

- docs/products/compute/_shortguides/metadata-beta-notice/index.md
- Added links to the Metadata block post and feedback form to the Metadata beta notice.
> [Release Candidate] v1.265.0

- docs/products/platform/billing/guides/tax-information/index.md
Added New Zealand tax info to our Tax Information guide
> Tax Information - add New Zealand tax info

- docs/products/compute/compute-instances/guides/failover/index.md
- docs/products/compute/compute-instances/guides/lish/index.md
- docs/products/compute/compute-instances/plans/premium/index.md
- docs/products/networking/vlans/_index.md
- docs/products/platform/get-started/guides/choose-a-data-center/index.md
- docs/products/storage/object-storage/_index.md
- docs/products/storage/object-storage/guides/urls/index.md
Updated the following guides for Stockholm GA:
- Premium CPU Instances
- OBJ Overview
- Access Your System Console Using Lish
> Stockholm GA docs updates

- docs/products/platform/get-started/guides/beta-for-new-data-centers/index.md
Updated Beta DC doc with new sites in beta:
- Amsterdam
- Jakarta
- Osaka
- São Paulo
Updated following DC for GA:
- Stockholm
> Beta DC doc updates with new beta sites

- docs/guides/tools-reference/tools/rclone-object-storage-file-sync/index.md
> [update] fix the indentation

- docs/products/networking/cloud-firewall/guides/manage-firewall-rules/index.md
- docs/release-notes/api/v4.161.1.md
- package-lock.json
* Added API v4.161.1 release notes
* Updated Manage Firewall Rules product docs
> API Docs v4.161.1

- docs/products/platform/get-started/guides/beta-for-new-data-centers/index.md
Added to Beta DC document:
- Los Angeles (lax) beta info
- Miami (mia) beta info
> Beta DC Doc Update

- docs/products/compute/compute-instances/guides/rescue-and-rebuild/index.md
Fixed incorrect info about disk mounting in Rescue Mode Overview section.
> Rescue and Rebuild - disk mounting error fix

- docs/products/storage/object-storage/_index.md
Added in Stockholm DC details to the OBJ storage table in the OBJ Overview guide.
> OBJ Overview - added Stockholm to storage table

- docs/products/tools/marketplace/guides/wireguard/index.md
> [update]Deploy Wireguard through the Linode Marketplace

- docs/products/compute/kubernetes/guides/deploy-cluster-using-terraform/index.md
- Updated the version of k8s to 1.26 and that of Linode to 2.7.1
> [Update] Deploy a Linode Kubernetes Engine Cluster Using Terraform

- docs/products/compute/compute-instances/guides/failover/index.md
- docs/products/compute/compute-instances/guides/lish/index.md
- docs/products/compute/compute-instances/plans/premium/index.md
- docs/products/networking/vlans/_index.md
- docs/products/platform/get-started/guides/beta-for-new-data-centers/index.md
- docs/products/platform/get-started/guides/choose-a-data-center/index.md
- docs/products/storage/object-storage/_index.md
- docs/products/storage/object-storage/guides/urls/index.md
Docs updated:
- Limited beta for Akamai's new DCs
- How to choose a DC
- VLANs overview
- Premium compute instances
- OBJ overview
- Access buckets and files through URLs
- Access your system console using LISH
- Configure failover on a compute instance
> Updated - docs for Seattle and Milan GA

- docs/release-notes/lke/v1.53.0.md
Added release notes for LKE v.1.53.0
> Release notes for LKE v1.53.0

- docs/guides/security/basics/securing-apache2-with-modsecurity/index.md
Updated the instructions for 20.04 
PS: tested and validated the guide on Ubuntu 20.04 . The terminal output is attached in the Jira Ticket
> [Update] Securing Apache 2 With ModSecurity

- docs/guides/databases/sqlite/getting-started-with-nodejs-sqlite/index.md
- docs/guides/development/deno/how-to-install-and-use-deno/index.md
- docs/guides/development/javascript/build-react-video-streaming-app/index.md
- docs/guides/development/javascript/how-to-create-a-mern-stack-application/index.md
- docs/guides/development/nodejs/install-nodejs-on-ubuntu-22-04/index.md
- docs/guides/development/python/task-queue-celery-rabbitmq/index.md
- docs/guides/security/monitoring/visualize-server-security-on-centos-7-with-an-elastic-stack-and-wazuh/index.md
Fix the styling for Node.js across the documentation
> [update] Doc set

- _vendor/github.com/linode/linode-docs-theme/content/testpages/typography.md
- _vendor/github.com/linode/linode-docs-theme/layouts/_default/baseof.html
- _vendor/github.com/linode/linode-docs-theme/layouts/partials/funcs/get-author-link.html
- _vendor/github.com/linode/linode-docs-theme/layouts/partials/sections/navigation/toc-main.html
- _vendor/github.com/linode/linode-docs-theme/layouts/partials/sections/navigation/toc.html
- _vendor/github.com/linode/linode-docs-theme/layouts/partials/sections/search/filters.html
- _vendor/github.com/linode/linode-docs-theme/layouts/partials/sections/search/filters__tags.html
- _vendor/github.com/linode/linode-docs-theme/layouts/shortcodes/command.html
- _vendor/modules.txt
- go.mod
- go.sum
- Adds support to display multiple authors on a single guide
- Adds scrolling support for long Table of Contents section within desktop viewports.
- Improves color formatting on search filters
- Fixes Table of Contents section highlighting
- Fixes issue where copy icon overlaps text within code blocks
> Theme updates (2023-09-26)

- docs/products/compute/compute-instances/guides/metadata/index.md
This PR updates Metadata availability to remove Chennai and add Osaka.
> [Update] Overview of the Metadata Service

- _vendor/github.com/linode/linode-docs-theme/assets/js/main/helpers/helpers.js
- _vendor/github.com/linode/linode-docs-theme/assets/js/main/navigation/paginator.js
- _vendor/github.com/linode/linode-docs-theme/assets/js/main/sections/sections/list.js
- _vendor/github.com/linode/linode-docs-theme/layouts/_default/list.html
- _vendor/github.com/linode/linode-docs-theme/layouts/shortcodes/releasenotes/list.html
- _vendor/github.com/linode/linode-docs-theme/package.hugo.json
- _vendor/github.com/linode/linode-docs-theme/package.json
- _vendor/github.com/linode/linode-website-partials/footer.html
- _vendor/github.com/linode/linode-website-partials/header.html
- _vendor/modules.txt
- docs/guides/applications/configuration-management/crossplane/getting-started-with-crossplane/index.md
- docs/guides/applications/containers/using-nomad-for-orchestration/index.md
- docs/guides/applications/social-networking/how-to-install-pixelfed/index.md
- docs/guides/databases/mysql/delete-record-sql/index.md
- docs/reference-architecture/jenkins-ci-cd-on-linode-to-any-hyperscaler/guides/implement-jenkins-ci-cd/index.md
- go.mod
- go.sum
- Adds pagination to section pages (which fixes an issue in which only the first 20 guides were visible on a section page)
- Changes "Cloud Pricing Calculator" to "Cloud Computing Calculator" in header and footer
- Replaces instances of the "caution" shortcode with the "note" shortcode.
> Theme updates (2023-09-27)

- docs/products/compute/compute-instances/guides/failover/index.md
- docs/products/compute/compute-instances/guides/lish/index.md
- docs/products/compute/compute-instances/guides/metadata/index.md
- docs/products/compute/compute-instances/plans/premium/index.md
- docs/products/networking/vlans/_index.md
- docs/products/platform/get-started/guides/beta-for-new-data-centers/index.md
- docs/products/platform/get-started/guides/choose-a-data-center/index.md
- docs/products/storage/object-storage/_index.md
- docs/products/storage/object-storage/guides/urls/index.md
> [Updated] Chennai GA and regional messaging

- docs/products/compute/compute-instances/guides/failover/index.md
- docs/products/compute/compute-instances/guides/lish/index.md
- docs/products/compute/compute-instances/guides/metadata/index.md
- docs/products/compute/compute-instances/plans/premium/index.md
- docs/products/networking/vlans/_index.md
- docs/products/platform/get-started/guides/beta-for-new-data-centers/index.md
- docs/products/platform/get-started/guides/choose-a-data-center/index.md
- docs/products/storage/object-storage/_index.md
- docs/products/storage/object-storage/guides/urls/index.md
Multiple docs for Chennai data center GA:
> [Release Candidate] v1.271.0

- .github/workflows/deploy-to-feature-testing-server.yaml
- .github/workflows/deploy-to-main-staging-server.yaml
- .github/workflows/deploy-to-production.yaml
Supports static Explore Docs menu
> Build Hugo twice in GitHub Actions deployment workflows

- docs/products/compute/compute-instances/guides/failover/index.md
- docs/products/compute/compute-instances/guides/lish/index.md
- docs/products/compute/compute-instances/guides/metadata/index.md
- docs/products/compute/compute-instances/plans/premium/index.md
- docs/products/networking/vlans/_index.md
- docs/products/platform/get-started/guides/beta-for-new-data-centers/index.md
- docs/products/platform/get-started/guides/choose-a-data-center/index.md
- docs/products/storage/object-storage/_index.md
- docs/products/storage/object-storage/guides/urls/index.md
> [Updated] Docs for Jakarta GA

- docs/products/compute/compute-instances/guides/failover/index.md
- docs/products/compute/compute-instances/guides/lish/index.md
- docs/products/compute/compute-instances/guides/metadata/index.md
- docs/products/compute/compute-instances/plans/premium/index.md
- docs/products/networking/vlans/_index.md
- docs/products/platform/get-started/guides/beta-for-new-data-centers/index.md
- docs/products/platform/get-started/guides/choose-a-data-center/index.md
- docs/products/storage/object-storage/_index.md
- docs/products/storage/object-storage/guides/urls/index.md
Docs updated for São Paulo GA:
> [Updated] Docs for São Paulo GA

- docs/products/compute/compute-instances/guides/failover/index.md
- docs/products/compute/compute-instances/guides/lish/index.md
- docs/products/compute/compute-instances/guides/metadata/index.md
- docs/products/compute/compute-instances/plans/premium/index.md
- docs/products/networking/vlans/_index.md
- docs/products/platform/get-started/guides/beta-for-new-data-centers/index.md
- docs/products/platform/get-started/guides/choose-a-data-center/index.md
- docs/products/storage/object-storage/_index.md
- docs/products/storage/object-storage/guides/urls/index.md
Updated for São Paulo GA:
- Object Storage Overview: removed duplicate line in table
> [Release Candidate] v1.275.0

- docs/guides/development/frameworks/laravel/how-to-create-website-using-laravel/index.md
tested and validated the steps in the guide
> [update] Build a Website Using the Laravel Framework

- _vendor/github.com/linode/linode-docs-theme/assets/css/components/large-diagram.css
- _vendor/github.com/linode/linode-docs-theme/assets/css/sections/content.css
- _vendor/github.com/linode/linode-docs-theme/content/testpages/_index.md
- _vendor/github.com/linode/linode-docs-theme/content/testpages/placeholder.md
- _vendor/github.com/linode/linode-docs-theme/layouts/shortcodes/placeholder.html
- _vendor/modules.txt
- go.mod
- go.sum
- Added placeholder functionality to code samples
- Changed scale and opacity of ping animation for diagram bullets
> Update theme (2023-10-12)

- docs/products/compute/compute-instances/guides/failover/index.md
- docs/products/compute/compute-instances/guides/lish/index.md
- docs/products/compute/compute-instances/guides/metadata/index.md
- docs/products/compute/compute-instances/plans/premium/index.md
- docs/products/networking/vlans/_index.md
- docs/products/platform/get-started/guides/beta-for-new-data-centers/index.md
- docs/products/platform/get-started/guides/choose-a-data-center/index.md
- docs/products/storage/object-storage/_index.md
- docs/products/storage/object-storage/guides/urls/index.md
Docs updated for Amsterdam GA:
> [Updated] Docs for Amsterdam GA

- _vendor/github.com/linode/linode-docs-theme/assets/css/components/large-diagram.css
- _vendor/github.com/linode/linode-docs-theme/assets/css/sections/content.css
- _vendor/github.com/linode/linode-docs-theme/content/testpages/_index.md
- _vendor/github.com/linode/linode-docs-theme/content/testpages/placeholder.md
- _vendor/github.com/linode/linode-docs-theme/layouts/shortcodes/placeholder.html
- _vendor/modules.txt
- docs/guides/development/frameworks/laravel/how-to-create-website-using-laravel/index.md
- docs/products/compute/compute-instances/guides/failover/index.md
- docs/products/compute/compute-instances/guides/lish/index.md
- docs/products/compute/compute-instances/guides/metadata/index.md
- docs/products/compute/compute-instances/plans/premium/index.md
- docs/products/networking/vlans/_index.md
- docs/products/platform/get-started/guides/beta-for-new-data-centers/index.md
- docs/products/platform/get-started/guides/choose-a-data-center/index.md
- docs/products/storage/object-storage/_index.md
- docs/products/storage/object-storage/guides/urls/index.md
- go.mod
- go.sum
Build a Website Using the Laravel Framework guide
Docs for Amsterdam GA:
- Added placeholder functionality to code samples
- Changed scale and opacity of ping animation for diagram bullets
> [Release Candidate] v1.276.0

- docs/products/compute/compute-instances/guides/failover/index.md
- docs/products/compute/compute-instances/guides/lish/index.md
- docs/products/compute/compute-instances/guides/metadata/index.md
- docs/products/compute/compute-instances/plans/premium/index.md
- docs/products/networking/vlans/_index.md
- docs/products/platform/get-started/guides/beta-for-new-data-centers/index.md
- docs/products/platform/get-started/guides/choose-a-data-center/index.md
- docs/products/storage/object-storage/_index.md
- docs/products/storage/object-storage/guides/urls/index.md
Updates to support the Miami data center launch.
> Miami data center launch

- _vendor/github.com/linode/linode-api-docs/v4/openapi.yaml
- _vendor/modules.txt
- docs/release-notes/api/v4.166.0.md
- go.mod
- go.sum
* Add API v4.166.0 release notes
* Update API spec to v4.166.0
> API Docs v4.166.0

- docs/products/storage/object-storage/_index.md
Updated Object Storage Overview doc to include new OBJ limits
> [Updated] Object Storage limits

- .gitignore
- docs/products/storage/object-storage/_index.md
Edited default limits and exceptions language.
> [Updated] Object Storage Overview edits

- .gitignore
- docs/products/storage/object-storage/_index.md
- Object Storage Overview: Updated Object Storage defaults and limits
> [Release Candidate] v1.278.0

- docs/guides/applications/messaging/linode-object-storage-with-mastodon/index.md
> [updat] How to Use Linode Object Storage with Mastodon

- docs/products/compute/compute-instances/guides/failover/index.md
- docs/products/compute/compute-instances/guides/lish/index.md
- docs/products/compute/compute-instances/guides/metadata/index.md
- docs/products/compute/compute-instances/plans/premium/index.md
- docs/products/networking/vlans/_index.md
- docs/products/platform/get-started/guides/beta-for-new-data-centers/index.md
- docs/products/platform/get-started/guides/choose-a-data-center/index.md
- docs/products/storage/object-storage/_index.md
- docs/products/storage/object-storage/guides/urls/index.md
Docs updated for Los Angeles GA:
> [Updated] Docs for Los Angeles GA

- docs/products/tools/marketplace/guides/peppermint/index.md
Update UDFs and supported distros
New peppermint script: https://github.com/akamai-compute-marketplace/marketplace-apps/blob/main/deployment_scripts/linode-marketplace-peppermint/peppermint-deploy.sh
> [update] Deploy Peppermint through the Linode Marketplace

- docs/products/tools/marketplace/guides/odoo/index.md
Update UDFs and supported distros
New odoo script: https://github.com/akamai-compute-marketplace/marketplace-apps/blob/main/deployment_scripts/linode-marketplace-odoo/odoo-deploy.sh
> [update] Deploy Odoo through the Linode Marketplace

- docs/products/tools/marketplace/guides/nirvashare/index.md
Update UDFs and supported distros
New nirvashare script: https://github.com/akamai-compute-marketplace/marketplace-apps/blob/main/deployment_scripts/linode-marketplace-nirvashare/nirvashare-deploy.sh
> [update] Deploy NirvaShare through the Linode Marketplace

- docs/products/tools/marketplace/guides/docker/index.md
Update UDFs and supported distros 
New docker script: https://github.com/akamai-compute-marketplace/marketplace-apps/blob/main/deployment_scripts/linode-marketplace-docker/docker-deploy.sh
> [update] Deploy Docker through the Linode Marketplace

- docs/products/platform/get-started/guides/beta-for-new-data-centers/index.md
- docs/products/platform/get-started/guides/network-transfer/index.md
- docs/products/storage/object-storage/_index.md
Updated docs for Object Storage pricing changes for new regions:
- Network Transfer Usage and Costs guide
> [Updated] Object Storage pricing per region

- docs/products/platform/billing/guides/tax-information/index.md
- docs/products/tools/marketplace/guides/wordpress/index.md
Changed:
- Wordpress Marketplace App
- Tax guide
> RC v1.285.0

- docs/products/platform/billing/guides/tax-information/index.md
Updated the Tax Information guide:
- Copy edits for clarity
- Added tax exemption guidance for customers in non-US/Canada geolocations
> Updated: Tax Info doc

- docs/guides/applications/configuration-management/ansible/deploy-linodes-using-linode-ansible-collection/index.md
- updated the ansible.cfg file after validating that the file in indeed hidden.
- fixes: https://github.com/linode/docs/issues/6674
> [update] Use the Linode Ansible Collection to Deploy a Linode

- docs/guides/networking/diagnostics/inspecting-network-information-with-netstat/index.md
Updated the note in the IPv6 section
Fixes: https://github.com/linode/docs/issues/6712
> [update] Inspecting Network Information with netstat

- docs/products/compute/compute-instances/guides/network-infrastructure-upgrades/index.md
- docs/products/networking/vlans/_index.md
- docs/products/platform/get-started/guides/choose-a-data-center/index.md
VLANs has been released in Dallas. This PR updates a few pages in support of that.
> VLAN launch in Dallas

- docs/release-notes/lke/v1.57.0.md
> [RC] v1.292.0

- archetypes/api-endpoint-collection.md
To be used like:
```
hugo new -k api-endpoint-collection docs/api/new-api-collection.md
```
> Hugo archetype for API endpoint collection placeholder files

- _vendor/github.com/linode/linode-api-docs/v4/openapi.yaml
- _vendor/modules.txt
- go.mod
- go.sum
- Update API reference to api spec v4.169.1
> [Release Candidate] v1.293.1

- docs/products/storage/object-storage/guides/custom-domain/index.md
- added links to the tools to access object storage.
- added link to the guide that provides information to move objects between buckets.
> [update] Configure a Custom Domain (with a TLS/SSL Certificate)

- docs/guides/applications/configuration-management/cloud-init/using-metadata-service-api/index.md
- docs/products/compute/compute-instances/guides/_index.md
- docs/products/compute/compute-instances/guides/metadata-api/index.md
- docs/products/compute/compute-instances/guides/metadata/index.md
Submitting the guide on using the Metadata service API directly.
Preview: [How to Use the Metadata Service API](https://deploy-preview-6785--nostalgic-ptolemy-b01ab8.netlify.app/docs/guides/using-metadata-service-api/)
> [New] How to Use the Metadata Service API

- docs/products/storage/block-storage/_index.md
> [update] Storage - Block Storage

- docs/products/tools/api/guides/create-an-oauth-app-with-the-python-api-library/index.md
_ updated the list of scopes and the permissions.
> [update] Create an OAuth App with the Linode Python API Library

- ci/vale/dictionary.txt
- docs/guides/security/firewalls/network-firewalls-vs-application-firewalls/index.md
Preview: [Network Firewalls vs. Application Firewalls](https://deploy-preview-6758--nostalgic-ptolemy-b01ab8.netlify.app/docs/guides/network-firewalls-vs-application-firewalls/)
> [NEW] Network Firewalls vs. Application Firewalls

- docs/guides/security/firewalls/comparing-network-firewall-solutions/index.md
Submitting the guide comparing software firewalls on Linux.
Preview: [Comparing Linux-Based Network Firewall Software](https://deploy-preview-6695--nostalgic-ptolemy-b01ab8.netlify.app/docs/guides/comparing-network-firewall-solutions/)
> [New] Comparing Linux-Based Network Firewall Software

- docs/products/compute/compute-instances/guides/failover/index.md
- docs/products/compute/compute-instances/guides/network-infrastructure-upgrades/index.md
- docs/products/networking/vlans/_index.md
- docs/products/platform/get-started/guides/choose-a-data-center/index.md
- Updated VLAN availability to reflect launch in Tokyo.
- Updated IP sharing / failover capabilities to reflect feature availability in Tokyo, Atlanta, and Toronto.
> Updated VLAN availability and IP failover capabilities

- docs/products/tools/marketplace/guides/wordpress/index.md
Clarified instructions on file path for password reset.
> [Update] Deploy WordPress through the Linode Marketplace

- _vendor/github.com/linode/linode-api-docs/v4/openapi.yaml
- _vendor/modules.txt
- docs/api/vpcs.md
- docs/release-notes/api/v4.170.0.md
- go.mod
- go.sum
This API spec bump includes all updates related to the VPC beta launch
> Update API reference to api spec v4.170.0

- ci/vale/dictionary.txt
- docs/products/networking/vpc/_index.md
- docs/products/networking/vpc/developers/index.md
- docs/products/networking/vpc/get-started/index.md
- docs/products/networking/vpc/guides/_index.md
- docs/products/networking/vpc/guides/assign-services/index.md
- docs/products/networking/vpc/guides/create/index.md
- docs/products/networking/vpc/guides/subnets/index.md
This PR adds a VPC product documentation section to support the VPC beta launch.
> VPC beta product documentation

- docs/guides/applications/configuration-management/cloud-init/using-metadata-cloud-init-on-any-distribution/index.md
- docs/products/compute/compute-instances/guides/metadata-api/index.md
- docs/products/networking/cloud-firewall/guides/_index.md
This PR runs the script to automatically replace outdated internal links with updated urls.
> Update internal links

- docs/guides/security/upgrading/upgrade-to-ubuntu-20-04/index.md
_ updated the link to : https://www.linode.com/docs/products/storage/backups/guides/take-a-snapshot/
> [Update] Inline Upgrade to Ubuntu 20.04 LTS (Focal Fossa)

- docs/products/compute/compute-instances/guides/set-up-and-secure/index.md
Added a note about the additional command that need sto be run to start the sshd service.
> [update] Guides - Setting Up and Securing a Compute Instance

- docs/products/tools/marketplace/_shortguides/marketplace-required-limited-user-fields-shortguide/index.md
- docs/products/tools/marketplace/guides/secure-your-server/index.md
Fixing some identation issues in last release PR
> [Hotfix] v1.298.1

- docs/guides/email/email-services/using-magicspam-email-authentication/index.md
- docs/guides/game-servers/create-an-ark-server-on-ubuntu/index.md
- docs/guides/linode-writers-formatting-guide/index.md
- docs/products/compute/compute-instances/plans/dedicated-cpu/index.md
- docs/products/tools/marketplace/guides/_index.md
- docs/products/tools/marketplace/guides/ark-survival-evolved/index.md
- docs/products/tools/marketplace/guides/bitninja/index.md
- docs/products/tools/marketplace/guides/magicspam/index.md
- docs/products/tools/marketplace/guides/mistio/index.md
- docs/products/tools/marketplace/guides/percona-monitoring-management/index.md
- docs/products/tools/marketplace/guides/team-fortress-2/index.md
- docs/products/tools/marketplace/guides/terraria/index.md
Updated for Marketplace App deprecation:
- Marketplace Apps - Guides: *Removed deprecated app links*
- Deploy Terraria through the Linode Marketplace (deprecated)
- Deploy a Team Fortress 2 Server through the Linode Marketplace (deprecated)
- Deploy an ARK Survival Evolved Server through the Linode Marketplace (deprecated)
- Creating a Dedicated ARK Server on Ubuntu: *Removed note pointing to Marketplace deployment guide; updated cross-play note*
- Deploy MagicSpam through the Linode Marketplace (deprecated)
- Using MagicSpam to Secure your Email Server: *Removed text pointing to Marketplace deployment guide*
- Deploy BitNinja through the Linode Marketplace (deprecated)
- Deploy Percona Monitoring and Management (PMM) through the Linode Marketplace (deprecated)
- Deploy Mist.io through …
> [Release Candidate] v1.299.0

- docs/products/storage/block-storage/guides/resize-volume/index.md
There are no instructions shown after clicking the Resize button.
> Correction to Resize Volume Instructions

- _vendor/github.com/linode/linode-website-partials/footer-inline.js
- _vendor/github.com/linode/linode-website-partials/footer.css
- _vendor/github.com/linode/linode-website-partials/footer.html
- _vendor/github.com/linode/linode-website-partials/header.css
- _vendor/github.com/linode/linode-website-partials/header.html
- _vendor/modules.txt
- go.mod
- go.sum
> [Release Candidate] v1.301.1

- docs/guides/applications/media-servers/live-streaming-with-livekit-and-obs/index.md
Updated Live Streaming With LiveKit and OBS Studio guide:
- Added URL pointing to LiveKit benchmarking documentation
> [Updated] Live Streaming With LiveKit and OBS Studio

- docs/products/networking/vpc/_index.md
Fixed typo in cascading product description
> Fixed typo in front matter

- docs/release-notes/lke/v1.59.0.md
- docs/release-notes/lke/v1.60.0.md
- docs/release-notes/lke/v1.63.0.md
Two new changelog entries for past releases in January, and a new one for February.
> New changelog entries for LKE

- docs/guides/applications/media-servers/live-streaming-with-livekit-and-obs/index.md
- docs/products/networking/vpc/_index.md
- docs/release-notes/lke/v1.59.0.md
- docs/release-notes/lke/v1.60.0.md
- docs/release-notes/lke/v1.63.0.md
- Release notes for LKE v1.59.0, v1.60.0, and v1.63.0
- Live Streaming With LiveKit and OBS Studio: _Added URL pointing to LiveKit benchmarking documentation_
- VPC Product Documentation pages: _Fixed typo in product description_
> [Release Candidate] v1.302.0

- .github/workflows/deploy-to-feature-testing-server.yaml
- .github/workflows/deploy-to-main-staging-server.yaml
- .github/workflows/deploy-to-production.yaml
- Updates .github/workflows/deploy-to-production.yaml workflow to use SFTP to upload site to web servers
- Small tweaks to deploy-to-main-staging-server.yaml and deploy-to-feature-testing-server.yaml workflows
The new production web servers are not in use yet, but this release prepares them to be used.
> [Release] v1.305.0

- docs/products/compute/compute-instances/guides/manage-the-kernel/index.md
`apt upgrade` upgrades all packages. `apt install` would upgrade a single package.
> manage-the-kernel: correct `apt` commands

- docs/products/compute/kubernetes/guides/_index.md
- docs/products/compute/kubernetes/guides/coredns-custom-config/index.md
Adds a new LKE guide covering the newly added (v1.66.0) CoreDNS configuration customization features.
> LKE Guides: CoreDNS custom configuration

- _vendor/github.com/linode/linode-docs-theme/assets/js/main/navigation/create-href.js
- _vendor/github.com/linode/linode-docs-theme/assets/js/main/search/search-store.js
- _vendor/github.com/linode/linode-docs-theme/assets/js/main/sections/home/home.js
- _vendor/github.com/linode/linode-docs-theme/config.toml
- _vendor/github.com/linode/linode-docs-theme/layouts/index.html
- _vendor/modules.txt
- go.mod
- go.sum
- Removes breadcrumbs from the home page.
- Removes "Q&A" section from Explore docs menu and home page.
- Removes "Q&A" search filter.
> Update theme (2024-03-19)

- docs/products/tools/marketplace/_shortguides/marketplace-required-limited-user-fields-shortguide/index.md
- docs/products/tools/marketplace/guides/harbor/index.md
- docs/products/tools/marketplace/guides/jupyterlab/index.md
- docs/products/tools/marketplace/guides/kepler/index.md
- docs/products/tools/marketplace/guides/lamp-stack/index.md
- docs/products/tools/marketplace/guides/lemp-stack/index.md
- docs/products/tools/marketplace/guides/nats-single-node/index.md
- docs/products/tools/marketplace/guides/secure-your-server/index.md
- docs/products/tools/marketplace/guides/splunk/index.md
- docs/products/tools/marketplace/guides/woocommerce/index.md
- docs/products/tools/marketplace/guides/wordpress/index.md
Updates required limited user shortcode to match changes in password and ssh key handling. 
Updates limited user credential locations where required.
Should be synced with March 18th Cloud Manager release.
> Marketplace Limited User Updates

- ci/vale/dictionary.txt
- docs/products/tools/marketplace/guides/linuxgsm/index.md
- docs/products/tools/marketplace/guides/passbolt/index.md
- Deploy Passbolt through the Linode Marketplace
- Deploy LinuxGSM through the Linode Marketplace
> [Update] Passbolt and LinuxGSM marketplace guides

- docs/products/storage/block-storage/_index.md
[update] Block Storage - Update to the Limits and Considerations
> [Update] Block storage

- _vendor/github.com/linode/linode-api-docs/v4/openapi.yaml
- _vendor/modules.txt
- go.mod
- go.sum
- Update API reference to api spec v4.174.0
> [Release Candidate] v1.314.0

- CONTRIBUTING.md
- _vendor/github.com/linode/linode-docs-theme/content/testpages/_index.md
- _vendor/github.com/linode/linode-docs-theme/layouts/partials/sections/search/get-sections-meta.html
- _vendor/github.com/linode/linode-website-partials/footer.html
- _vendor/github.com/linode/linode-website-partials/header.html
- _vendor/modules.txt
- go.mod
- go.sum
- netlify.toml
This reverts commit 5a4ad19ce1e7fbec6e6e60eaac0fddcbc094198c.
> Revert "Theme updates (#6920)"

- docs/products/_index.md
- docs/reference-architecture/_index.md
Fix for product and reference architecture layouts
> [Hotfix] v1.322.1

- docs/guides/security/ssh/enable-ssh-ubuntu/index.md
on How to Enable SSH on Ubuntu 20.04 LTS
> Fix ssh status code snippet

- docs/products/compute/compute-instances/plans/premium/index.md
Update spelling.
from peformance -> performance
> Updated spelling

- docs/guides/akamai/get-started/observability-with-datastream-and-multiplexing/index.md
Updated terminology from "Datastream 2" to "DataStream"
> [Updated] DataStream With Multiplexing for Observability

- docs/guides/email/postfix/pflogsumm-for-postfix-monitoring-on-centos-6/index.md
Fixed a Markdown syntax error causing page rendering issues
> [Fixed] Pflogsumm for Postfix Monitoring on CentOS 6 - Markdown error

- archetypes/content.md
- docs/guides/linode-writers-formatting-guide/index.md
Updated:
- "Before You Begin" section in the [Linode Writer's Formatting Guide](https://www.linode.com/docs/guides/linode-writers-formatting-guide/#before-you-begin) with new guidelines
- "Before You Begin" section in the **content.md** archetype; replaced example content with general guidelines and link to the writer's guide
> [Updated] Before You Begin section

- docs/products/compute/compute-instances/guides/manual-network-configuration/index.md
Updated "Static vs Dynamic Addressing" and "Networking Terms" sections to reflect VPC support for DHCP.
> [UPDATE] Manual Network Configuration on a Compute Instance

- docs/guides/akamai/get-started/observability-with-datastream-and-trafficpeak/index.md
Branding edits to TrafficPeak guide
> [Updated] Large Data Observability With DataStream and TrafficPeak

- docs/products/networking/vlans/_index.md
> [UPDATE] VLANs

- docs/products/platform/billing/guides/tax-information/index.md
This PR updates tax details for Estonia.
> [Updated] Billing > Tax Information

- docs/products/tools/marketplace/guides/passbolt/index.md
updates Passbolt Community Edition language re: OCA-1411
> [Updated] Deploy Passbolt Community Edition through the Linode Marketplace

- docs/marketplace-docs/guides/secure-your-server/index.md
- Edited supported distros
- Removed some deployment options
> [Updated] Secure Your Server through the Linode Marketplace

- ci/blueberry.py
- docs/guides/applications/configuration-management/terraform/how-to-build-your-infrastructure-using-terraform-and-linode/index.md
- docs/guides/applications/configuration-management/terraform/how-to-use-terraform-with-linode-object-storage/index.md
- docs/guides/uptime/monitoring/how-to-install-prometheus-and-grafana-on-ubuntu/index.md
Updated two guides with steps on how to configure Terraform to use Linode OBJ as a backend to write state:
- Use Terraform to Provision Infrastructure on Linode
- Use Terraform With Linode Object Storage (points to Terraform Provision guide)
- How to Install and Configure Prometheus and Grafana on Ubuntu; fixes bad link
- Ignore marketplace docs for blueberry test
> [Release Candidate] v1.346.0

- docs/contributors/alex-fornuto/_index.md
@alexfornuto hey alex, I changed the contributor page description for you here. we had previously run a batch script with a shared description to set up these pages, so my apologies that yours was not accurate
> Fix description for Alex Fornuto contributor page

- docs/guides/applications/project-management/how-to-create-a-private-python-package-repository/index.md
Updated:
- How to Create a Private Python Package Repository
> [Release] v1.348.0

- ci/vale/dictionary.txt
- docs/guides/databases/general/database-solutions/index.md
- docs/guides/databases/mysql/install-mysql/index.md
- docs/guides/databases/mysql/mysql-command-line-client/index.md
- docs/guides/databases/mysql/mysqldump-backups/index.md
- docs/guides/databases/sql-syntax/sharded-database/index.md
- docs/products/databases/managed-databases/_shortguides/dbass-eos/index.md
Updated dbass-eos shortguide with new product launch availability information.
Copy edits and link updates to the following guides for DBaaS relaunch:
- [Installing MySQL: A Definitive Guide](https://deploy-preview-7143--nostalgic-ptolemy-b01ab8.netlify.app/docs/guides/install-mysql/)
- [Backing Up MySQL Databases Using mysqldump](https://deploy-preview-7143--nostalgic-ptolemy-b01ab8.netlify.app/docs/guides/mysqldump-backups/)
- [Determine the Best Database and Cloud Hosting Solution for Your Next Application](https://deploy-preview-7143--nostalgic-ptolemy-b01ab8.netlify.app/docs/guides/database-solutions/)
- [Database Sharding: Concepts, Examples, and Strategies](https://deploy-preview-7143--nostalgic-ptolemy-b01ab8.netlify.app/docs/guides/sharded-database/)
Copy edit and added dbaas-eos …
> [Updated] DBaaS avail notes and links

- docs/guides/uptime/loadbalancing/how-to-use-haproxy-for-load-balancing/index.md
Made grammatical and clarity fixes.
> [Update] Using HAProxy for Load Balancing

- docs/guides/applications/big-data/manually-deploy-kafka-cluster/index.md
Added author credits to manual apache cluster guide
> [Updated] Manually Deploy an Apache Cluster on Akamai

- _vendor/github.com/linode/linode-docs-theme/content/headless/home/data_v2.toml
- _vendor/github.com/linode/linode-website-partials/footer.html
- _vendor/github.com/linode/linode-website-partials/header.html
- _vendor/modules.txt
- go.mod
- go.sum
This reverts commit 8b3f03d0ac5736bb700e214addda74eb5bfe8484.
> Revert "Theme updates (#7169)"

- _vendor/github.com/linode/linode-docs-theme/content/headless/home/data_v2.toml
- _vendor/github.com/linode/linode-website-partials/footer.html
- _vendor/github.com/linode/linode-website-partials/header.html
- _vendor/modules.txt
- go.mod
- go.sum
This reverts commit 0e491632f35ed805ac43a00d483a510e90220deb.
> Revert "Revert "Theme updates (#7169)" (#7171)"

- docs/marketplace-docs/guides/drupal/index.md
- docs/marketplace-docs/guides/lamp-stack/index.md
- docs/marketplace-docs/guides/lemp-stack/index.md
- docs/marketplace-docs/guides/rabbitmq/index.md
- docs/marketplace-docs/guides/uptime-kuma/index.md
- docs/marketplace-docs/guides/vscode/index.md
Minor Distro and instructions update:
Apps:
Drupal
code-server
RabbitMQ
Django
LAMP
LEMP
Wordpress
Uptime Kuma
> [update] January Marketplace doc updates

- docs/guides/development/iot/install-thingsboard-iot-dashboard/index.md
> [update] Viewing IoT Data with ThingsBoard

- docs/marketplace-docs/guides/aapanel/index.md
- docs/marketplace-docs/guides/gitlab/index.md
[Update] Deploy aaPanel through the Linode Marketplace
[Update] Deploy Gitlab through the Linode Marketplace
> [Update]  aaPanel & Gitlab Marketplace doc updates

- _vendor/github.com/linode/linode-docs-theme/config.toml
- _vendor/github.com/linode/linode-docs-theme/config/development/config.toml
- _vendor/github.com/linode/linode-docs-theme/config/staging/config.toml
- _vendor/github.com/linode/linode-docs-theme/config/testing/config.toml
- _vendor/github.com/linode/linode-website-partials/footer.css
- _vendor/github.com/linode/linode-website-partials/footer.html
- _vendor/github.com/linode/linode-website-partials/header.css
- _vendor/github.com/linode/linode-website-partials/header.html
- _vendor/github.com/linode/linode-website-partials/header.js
- _vendor/modules.txt
- go.mod
- go.sum
Theme updates
- Update OneTrust scripts
- Update header and footer
> [Release] v1.369.0

- docs/marketplace-docs/guides/mean-stack/index.md
Update MEAN OCA guide with new distro and instructions for deployment.
Note: This app was merged into the main branch of the Akamai marketplace repo on Monday 3/17, so it's ready to go on our end for your next release, if everything looks good with my PR. Thanks!
> [Update] MEAN OCA

- docs/marketplace-docs/guides/redis/index.md
Updates distro and deployment details for Redis 7.2.7 Marketplace deployment
> [Update] Marketplace App for Redis updates

- docs/guides/applications/big-data/manually-deploy-kafka-cluster/index.md
The requirements.txt file includes Ansible 10.4 which only works with Python 3.11 or higher, so this PR updates the required python version to 3.11.
> Update required python version

- docs/guides/applications/configuration-management/packer/how-to-use-linode-packer-builder/index.md
fixes: https://github.com/linode/docs/issues/7220
After reading
> [Update] Using the Linode Packer Builder to Create Custom Images

- docs/guides/kubernetes/deploy-llm-for-ai-inferencing-on-apl/index.md
- docs/guides/kubernetes/deploy-rag-pipeline-and-chatbot-on-apl/index.md
Two guides updated with new hardware prerequisites:
- Deploy an LLM for AI Inferencing with App Platform for LKE
- Deploy a RAG Pipeline and Chatbot with App Platform for LKE
> [Updated] App Platform LLM and RAG Pipeline guides

- docs/guides/security/encryption/post-quantum-encryption-nginx-debian11/index.md
- docs/guides/security/encryption/post-quantum-encryption-nginx-ubuntu2404/index.md
Updates provided by Seweryn Krajczok
> [Update] Post Quantum Encryption with NGINX

- docs/guides/databases/postgresql/dbaas-postgres-terraform/index.md
- docs/guides/databases/postgresql/managed-postgresql-databases-on-akamai-cloud-with-terraform/index.md
Preview: https://deploy-preview-7260--nostalgic-ptolemy-b01ab8.netlify.app/docs/guides/managed-postgresql-databases-on-akamai-cloud-with-terraform/
> [New] Managed PostgreSQL Databases on Akamai Cloud with Terraform

- docs/guides/akamai/solutions/complete-observability-for-live-stream-events-with-trafficpeak/index.md
- docs/guides/akamai/solutions/high-performance-kv-store-fintech-akamai/index.md
- docs/guides/akamai/solutions/iot-firmware-upgrades-with-obj-and-cdn/index.md
- docs/guides/akamai/solutions/preparing-infrastructure-for-high-impact-ad-traffic/index.md
- docs/guides/platform/object-storage/optimizing-obj-bucket-architecture-for-akamai-cdn/index.md
- docs/guides/platform/object-storage/using-object-storage-with-akamai-cdn/index.md
- docs/marketplace-docs/_index.md
- docs/marketplace-docs/developers/index.md
- docs/marketplace-docs/guides/_index.md
- docs/marketplace-docs/guides/couchbase-cluster/index.md
- docs/marketplace-docs/guides/openlitespeed-django/index.md
- docs/marketplace-docs/guides/openlitespeed-wordpress/index.md
- docs/marketplace-docs/guides/passbolt/index.md
- docs/marketplace-docs/guides/prometheus-grafana/index.md
- docs/marketplace-docs/guides/splunk/index.md
- docs/marketplace-docs/guides/valkey/index.md
- docs/reference-architecture/video-transcoding/_index.md
- docs/reference-architecture/video-transcoding/diagrams/index.md
Akamai Connected Cloud > Akamai Cloud
> Branding changes

- docs/guides/applications/containers/using-podman/index.md
> Install Podman for Running Containers

- docs/guides/applications/configuration-management/terraform/create-a-multicloud-infrastructure-using-terraform/index.md
- docs/guides/applications/configuration-management/terraform/create-a-nodebalancer-with-terraform/index.md
- docs/guides/applications/configuration-management/terraform/create-terraform-module/index.md
- docs/guides/applications/configuration-management/terraform/deploy-a-wordpress-site-using-terraform-and-linode-stackscripts/index.md
- docs/guides/applications/configuration-management/terraform/how-to-build-your-infrastructure-using-terraform-and-linode/index.md
- docs/guides/applications/configuration-management/terraform/how-to-deploy-secure-linodes-using-cloud-firewalls-and-terraform/index.md
- docs/guides/applications/configuration-management/terraform/how-to-use-terraform-with-linode-object-storage/index.md
- docs/guides/applications/configuration-management/terraform/import-existing-infrastructure-to-terraform/index.md
- docs/guides/applications/configuration-management/terraform/secrets-management-with-terraform/index.md
- docs/guides/applications/containers/using-podman/index.md
- docs/guides/databases/surrealdb/surrealdb-for-web-applications/index.md
- docs/guides/kubernetes/deploy-llm-for-ai-inferencing-on-apl/index.md
- docs/guides/kubernetes/deploy-rag-pipeline-and-chatbot-on-apl/index.md
- docs/guides/kubernetes/inter-service-communication-with-rabbitmq-and-apl/index.md
- docs/guides/kubernetes/use-app-platform-to-deploy-wordpress/index.md
Updated the following guides for the end of the App Platform beta period:
- Deploy an LLM for AI Inferencing with App Platform for LKE
- Deploy a RAG Pipeline and Chatbot with App Platform for LKE
- Set Up Inter-Microservice Communication Using RabbitMQ On App Platform For LKE
- Use App Platform to Deploy WordPress with Persistent Volumes on LKE
Updated multiple guides for newest Linode Terraform Provider and Terraform versions:
- Use Terraform With Linode Object Storage
- Creating a Multicloud Infrastructure Using Terraform
- Deploy Secure Linodes using Cloud Firewalls and Terraform
- Import Existing Infrastructure to Terraform
- Create a Terraform Module
- Managing Secrets with Terraform
- Deploy a WordPress Site Using Terraform and Linode StackScripts
- Create a NodeBalancer with …
> [Release Candidate] v1.383.0

- docs/marketplace-docs/guides/docker/index.md
- docs/marketplace-docs/guides/secure-your-server/index.md
- Update to ubuntu 24 for Docker
- Update to ubuntu 24 for Secure your Server
> [update] Docker & Secure your Server Marketplace app guide
